### ISSUE TITLE
LinkedState array of objects

### ISSUE THREAD

**Issue by rafbgarcia** [developit/preact#1001]
Not sure if this is the right channel.

I'm trying to do the following, is it possible?

```js
linkState(this, `user.addresses[${index}].street`)
```

Thanks!

**Comment by Kanaye** [comment]
Hi @rafbgarcia.
The [linkstate replository](https://github.com/developit/linkstate) would 've probably been a better place for this question.

You can't use the syntax you tried above. Linkstate parses dots `.` as the seperators of identifiers.
So your example would look like this:
```javascript
linkState(this, `user.addresses.${index}.street`)
```

An example of this working: https://codesandbox.io/s/kol0rzo2j7
