### ISSUE TITLE
Wait for code to complete on componentWillUnmount before removing DOM elements

### ISSUE THREAD

**Issue by fedemar** [developit/preact#1002]
**Do you want to request a feature or report a bug?**

feature/question

**What is the current behavior?**

DOM elements are already removed when componentWillUnmount is called

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Being able to access DOM elements on componentWillUnmount

**If this is a feature request, what is motivation or use case for changing the behavior?**

Access object element to release adobe flash camera on ie11 when navigating away, clicking on back/forward button. Without access to the object element I cannot release the camera, ending up with the camera light turned on.

Please mention other relevant information.

node version
npm version
Operating system

**Comment by yaodingyd** [comment]
Component's DOM is removed after `componentWillUnmount` is called, so not sure what your question is. Maybe you can create a sandbox to showcase your issue.

**Comment by developit** [comment]
@fedemar You can access the DOM tree of your component within `componentWillUnmount()` as `this.base`.  Do not rely on `querySelector()` or `getElementById()`.
