### ISSUE TITLE
Component's prevState not tracked properly

### ISSUE THREAD

**Issue by natevw** [developit/preact#1012]
I was having trouble understanding [some code in Component.prototype.setState](https://github.com/developit/preact/blob/80ad4367e5352cbf6720f973a4488f6504498eb9/src/component.js#L53-L59) when I came across it:

```
let s = this.state;
if (!this.prevState) this.prevState = extend({}, s);
extend(s, typeof state==='function' ? state(s, this.props) : state);
```

It reads like `prevState` is only ever initialized once, and indeed this seems to be the case. If I add a method to a Component:

```
  componentDidUpdate(_, prevState) {
    console.log("componentDidUpdate:", prevState.ctr)
    
    setInterval(_ => {
      this.setState(s => (s.ctr || 0) + 1)
    }, 3e3)
  }
```

After it is triggered the first time, it keeps logging "componentDidUpdate: undefined" every three seconds, rather than an increasing counter.

I suspect there should be some code in vdom/component.js that deletes the prevState once [it is used](https://github.com/developit/preact/blob/0a88752e4890d391b5e23809d9432f625a833ae8/src/vdom/component.js#L67)?

**Comment by yaodingyd** [comment]
You need to return a object literal in `setState` function:

```
this.setState(s => ({ctr: (s.ctr || 0) + 1}) )
```

**Comment by developit** [comment]
There is code in that file that deletes the value once used:
https://github.com/developit/preact/blob/0a88752e4890d391b5e23809d9432f625a833ae8/src/vdom/component.js#L94

**Comment by natevw** [comment]
D'oh! Yep, definitely working fine…sorry for not checking *my* "test" code more thoroughly!
