### ISSUE TITLE
No warn when nodeName is undefined

### ISSUE THREAD

**Issue by ptbrowne** [developit/preact#1029]
There are no checks to check if `nodeName` is undefined.

It makes for some hard to debug code : 

Example 1 (bad import)

```jsx
import Component from 'src/Components`

...
  render () {
    return <Component>{ children }</Component>
    // Whoopsie, I should have written `import { Component } from 'src/Components'
    // Here what is rendered <undefined>{ children }</undefined>
  }
...
```

Example 2 (typo)

```jsx
  render ({ children }) {
    return <div>{{ children }}</div>
    // renders <div><undefined>{ children }</undefined></div>
  }
```

It looks like it should be easy to fix by throwing an Error here : https://github.com/developit/preact/blob/master/src/dom/index.js#L10 ? Is this a performance issue if the check is not done ?

Apologies if the issue has already been submitted with another name, I could not found any other similar issue (opened or closed) with "nodeName" and "undefined".

Thanks for Preact !

**Comment by marvinhagemeister** [comment]
@ptbrowne Thanks for the detailed analysis. We already have this feature as part of our debug tools: https://github.com/developit/preact/blob/master/debug/index.js#L11 . They are really helpful and warn you about such errors.

See more at the [Debug section in the Readme](https://github.com/developit/preact#debug-mode)

**Comment by ptbrowne** [comment]
Thanks for the quick response, seems like I missed this part of the doc :/ It works :)
