### ISSUE TITLE
Failing build on Travis

### ISSUE THREAD

**Issue by mkxml** [developit/preact#1038]
Hello everyone.

I noticed the failing build on IE. It's the empty node rendering test that is failing. As you can see on https://travis-ci.org/developit/preact/builds/354352816#L1021

Couldn't reproduce it on my local IE 11. All tests OK when using `COVERAGE=false FLAKEY=false PERFORMANCE=false`

Any thoughts on why it broke on Travis/Sauce Labs?

**Comment by developit** [comment]
Hmm - might be a browser extension they have running/

**Comment by marvinhagemeister** [comment]
We should probably remove the `IE9 + IE10` tests. Mocha [dropped support for those](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#500--2018-01-17) in January.

**Comment by valotas** [comment]
@marvinhagemeister how can you claim that preact works on IE9 if there are no tests for IE9? Unless it is ok to just support IE10+

**Comment by mkxml** [comment]
Working on some stuff in `sauce-test` branch. Will update here if I find something interesting.

Focus is fixing Sauce Labs and IE11 test first.

Maybe add Android and iOS testing back later on, because mobile testing is important. Need to check if remote testing of mobile platforms is stable first.

**Comment by valotas** [comment]
@marvinhagemeister I do not have any problem with the supported browsers. My problem is dropping support without any announcement and doing it in a minor release.

**Comment by marvinhagemeister** [comment]
@valotas I don't know what you mean. We dropped IE 9 + 10 from our test suite only  **after** we released 8.2.9. We haven't done our next release yet 🤔

**Comment by valotas** [comment]
@marvinhagemeister I know. I would make it a major. That is all I am saying.

**Comment by valotas** [comment]
can someone help me on running the tests on saucelabs?

**Comment by valotas** [comment]
@mkxml is [looks like IE](https://travis-ci.org/developit/preact/builds/374997810) renders an additional empty text. Am I getting that right?

**Comment by developit** [comment]
@valotas @mkxml yup - looks like this line:
https://github.com/developit/preact/blob/ba7577477dac7f04134008ee14f4d7a238381efe/test/browser/render.js#L49

Maybe we need to clear via .innerHTML at the beginning of that test?

**Comment by mkxml** [comment]
@developit @valotas @marvinhagemeister I've just tested this on `sauce-test` branch. Managed to get Sauce Labs to work again but this single failing test on IE11 persists.

I can't manage to reproduce it on my local Windows machine. That's really odd, looks like a flakey test.

Added the `scratch.innerHTML = '';` line at the beginning of the test, but it didn't work.

The work there is experimental, I'm trying to fix it there before drafting a PR. Even enabled the `debug` flag on Sauce Labs to see what's going on.

Log of failing test is here: https://travis-ci.org/developit/preact/jobs/384881747#L1162

**Comment by marvinhagemeister** [comment]
@mkxml can confirm. Locally all tests pass fine (tested with a win7 vm). I have no idea what's going on and why it fails specifically on saucelabs :S

**Comment by mkxml** [comment]
@valotas Changed the code:

It looks like IE doesn't even clean scratch on Sauce Labs.

Look: https://travis-ci.org/developit/preact/jobs/384927442#L1227

I will check Sauce Labs docs to see if we can use another build/version of IE11 or something.

**Comment by mkxml** [comment]
Worked! https://travis-ci.org/developit/preact/builds/384940572

**Comment by mkxml** [comment]
Worked! https://travis-ci.org/developit/preact/builds/384943378

**Comment by mkxml** [comment]
That's really strange.

Need to run this build a couple times. If it's fine I can draft a PR with only the needed changes to green master.

**Comment by marvinhagemeister** [comment]
@mkxml did amazing work here and resolved the issue. Closing as #1126 is now in master 🎉
