### ISSUE TITLE
Worth copying orphaned childNodes into swapped element?

### ISSUE THREAD

**Issue by aimwhy** [developit/preact#104]
*context:* https://github.com/aimwhy/study-preact

Order disorder for trigger "componentWillMount / componentDidMount"
More entrance for trigger "componentWillMount / componentDidMount"

The above two points lead to difficult to understand

/**************************************************/

There is a bit of confusion about this code. ：

```js
if (!dom) {
    out = createNode(nodeName);
} else if (toLowerCase(dom.nodeName) !== nodeName) {
    out = createNode(nodeName);
    appendChildren(out, toArray(dom.childNodes)); //?dont understand! need this line?
    recollectNodeTree(dom);
}
```

in  function diff.

/**************************************************/
hope usefull

**Comment by developit** [comment]
Hi @aimwhy,

This codepath is used when a Node's type changes, because the type of an DOM Element cannot be changed after creation. 

I haven't looked at your repo yet, I will take a look tomorrow.

**Comment by aimwhy** [comment]
i think：     when a Node's type changes， Can be thought of as not a same type components
Should not handle the element appends


dom's childNodes is Empty
```
recollectNodeTree(dom);
```

only Recycle dom

**Comment by aimwhy** [comment]
how use compontent.ref ?   give me a demo

**Comment by developit** [comment]
Ah, I understand what you're saying. Right now, changing the type of an Element moves `childNodes` into the new element from the old one.  It's optimized for this type of a case:

```js
let root = render((
  <ul>
    <li>one</li>
    <li>two</li>
    <li>three</li>
  </ul>
), document.body);

render((
  <ol>
    <li>one</li>
    <li>two</li>
    <li>three</li>
  </ol>
), document.body, root);
```

... which might not be very common.  Perhaps the simpler solution would be to skip moving the `childNodes`, let the recycler reclaim them, and if they happen to be re-used, the recycled elements would end up being re-used anyway.

Here's a demo of how to use the `ref` prop: https://jsfiddle.net/developit/x8qpzjdf/

**Comment by aimwhy** [comment]
https://github.com/developit/preact/issues/104#issuecomment-200346195   
ok ,I think:  I understand your intentions， thanks
Can you give me an example on how to use compontent.ref ?

**Comment by developit** [comment]
@aimwhy I put an example at the bottom: https://jsfiddle.net/developit/x8qpzjdf/

**Comment by aimwhy** [comment]
Thank you so much @developit 
English is not good, understanding is best

**Comment by aimwhy** [comment]
I think I understand how ‘ref’ is used
It implementations in trouble than react a little bit
hope to improve!            
Automatically add a node or component instances to refs  
@developit

**Comment by developit** [comment]
@aimwhy - that behavior is being removed from React soon. It is fully supported in [preact-compat](https://github.com/developit/preact-compat). 

([Source Code](https://github.com/developit/preact-compat/blob/master/src/index.js#L126-L129), [Tests](https://github.com/developit/preact-compat/blob/master/test/component.js#L47-L99))

**Comment by aimwhy** [comment]
Oh, really? That's really fantastic
Used uniform

**Comment by developit** [comment]
Closing this out as I've done a bunch of performance testing and migrating childNodes ends up being advantageous in a few important cases (router routes).  Thanks so much for the discussion and insight though :)
