### ISSUE TITLE
Make new release?

### ISSUE THREAD

**Issue by alexeypetrushin** [developit/preact#1041]
Currently it's pretty much impossible to use it with TypeScript. 

Master contains couple of fixes, would be nice to release it.

**Comment by developit** [comment]
Release will go out this weekend.

**Comment by marvinhagemeister** [comment]
Hope that #1044 makes it into the next release. Apart from that I think we are ready to go 🎉

**Comment by alexeypetrushin** [comment]
3... 2... 1... GO! :)

P.S. Just joking, take your time, and thanks for the great library!

**Comment by aulneau** [comment]
+1

**Comment by developit** [comment]
We need to revert a PR.
