### ISSUE TITLE
getChildContext() undeclared

### ISSUE THREAD

**Issue by mindplay-dk** [developit/preact#1043]
The `getChildContext()` method appears to be missing in the `.d.ts` file?

**Comment by k1r0s** [comment]
Yup! nice catch, feel free to PR this!

**Comment by k1r0s** [comment]
That means this is a bug and can be easily solved :)

**Comment by marvinhagemeister** [comment]
@k1r0s Perhaps we should name this `Good first bug` or something like that to avoid confusion

**Comment by k1r0s** [comment]
Yup, agree. I didn't see any label here to properly inform about this
