### ISSUE TITLE
Prop method referring to wrong method

### ISSUE THREAD

**Issue by samundrak** [developit/preact#1045]
I have a component which takes one method as prop and on some action, I call it,
This component is used in two places but the prop method always refers to first one.
Component:
![image](https://user-images.githubusercontent.com/3079452/37828531-b9362ff0-2ec3-11e8-896e-7f34c0231566.png)

Used place 1:
```          <FileInput onFile={this.handleFileInput} /> ```

Used place 2:
```          <FileInput onFile={this.handleFileInput2} /> ```

Here if FileInput triggers from second used place it will still invoke method of used place 1

**Comment by yaodingyd** [comment]
Can you show your complete usage here? A repo or sandbox would be helpful.

**Comment by samundrak** [comment]
Hello, 
Thank you for your response,
The problem here was of the conflicting id, I don't know how it effect preact internally.

**Comment by samundrak** [comment]
I have reproduced the problem here please check the console.
https://codesandbox.io/s/p95njm2krm

**Comment by yaodingyd** [comment]
Your `FileInput` component set the same id for `input` and `label`, so your `ContainerTwo`'s label still points to `ContainerOne`'s input. 

Set a `id` prop for your `FileInput` [https://codesandbox.io/s/ykq1kooz89](https://codesandbox.io/s/ykq1kooz89)
