### ISSUE TITLE
Dot in floating point numbers in style attribute is replaced with comma

### ISSUE THREAD

**Issue by foreheadSniffer** [developit/preact#1056]
https://preactjs.com/repl?code=%0Aexport%20default%20class%20TodoList%20extends%20Component%20%7B%0A%20%20%20%20state%20%3D%20%7B%20todos%3A%20%5B%5D%2C%20text%3A%20%27%27%2C%20style%3A%20%7Bbackground%3A%20%27red%27%2C%20padding%3A%20%2720.9%25%27%20%7D%20%7D%3B%0A%20%20%20%20%0A%20%20%20%20render(%7B%20%7D%2C%20%7B%20todos%2C%20text%20%7D)%20%7B%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20style%3D%7Bthis.state.style%7D%20data-style%3D%7Bthis.state.style.padding%7D%20onSubmit%3D%7Bthis.addTodo%7D%20action%3D%22javascript%3A%22%3E%0A%20%20%20%20%20%09%09%09%09%09Lorem%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D%0A

**Comment by yaodingyd** [comment]
<img width="1436" alt="screen shot 2018-04-03 at 13 01 47" src="https://user-images.githubusercontent.com/11392695/38263889-57510826-373f-11e8-8a1f-43a04fc5f926.png">
Your example works for me in Chrome 65 on Mac. 

Can you give more details?

**Comment by foreheadSniffer** [comment]
![image](https://user-images.githubusercontent.com/9723255/38264576-18f24580-377c-11e8-97fe-b5afa354e5e7.png)

Chromium  65.0.3317.0

**Comment by yaodingyd** [comment]
It looks like the padding style is still correctly applied. Otherwise it would look like this

![capture](https://user-images.githubusercontent.com/11392695/38265643-7c81abf0-3744-11e8-9802-2db58398b657.PNG)

**Comment by foreheadSniffer** [comment]
@yaodingyd  I understand that, but value is incorrect even if chromium could parse it.

**Comment by foreheadSniffer** [comment]
Turned out to be a chromium bug. Closing this.
