### ISSUE TITLE
Problems with Preact and AnimateHeight component

### ISSUE THREAD

**Issue by mikeaustin** [developit/preact#1057]
We love Preact because of it's small size, but have also noticed a few issues. One that we're addressing currently is a component not displaying the second time it is mounted when using [AnimateHeight](https://www.npmjs.com/package/react-animate-height).

I believe Preact is re-using/re-cycling elements, and changing DOM elements directly doesn't work well. It works perfectly fine in React. Our temporary solution is to comment out a few lines in AnimateHeight. Setting display to 'none' is done to prevent tabbing into a hidden child.

There may be other workarounds / fixes, but it is a different behavior from React. What are our other options? It looked like recycling was taken out in version 8, but maybe not all aspects of it?

```
    ...
    // Hide content if height is 0 (to prevent tabbing into it)
    // Check for contentElement is added cause this would fail in tests (react-test-renderer)
    // Read more here: https://github.com/Stanko/react-animate-height/issues/17
    if (this.contentElement && this.contentElement.style) {
      this.hideContent(height);
    }

  hideContent(newHeight) {
    // Doesn't work well with Preact. Element recycling / re-use?.
    //
    // if (newHeight === 0) {
    //   this.contentElement.style.display = 'none';
    // }
  }
```

**Comment by developit** [comment]
Preact still recycles component roots when unmounted and remounted. Removing this has been discussed.

**Comment by marvinhagemeister** [comment]
The recycler is gone in Preact X :tada:
