### ISSUE TITLE
Render with multiple data sources -- suggestion

### ISSUE THREAD

**Issue by CoderJason123** [developit/preact#1059]
Hello.  I do not mean to indicate this is an issue, it's not.  It's more of a question for best practice on using preactjs in this situation.

Say i have a component which has 1 source of data, such as a list of customers.  Those customers have "lookup" fields, like customer type id, or address type id.  Those columns are typically displayed in selects.

I have to fetch from 3 different places.  Doing so starts to deviate from the pattern and lifecycle of preact, which i prefer to follow.  

I sort of want all the data to load, say on component did mount, but what i've ended up with is a series of nested fetches.  I think this is ugly.

Not to mention, one piece of state gets set, but not all of them.  This can cause issues, right, where I am looking at the contact list, but the contact type list is not loaded, so I can't match the values until all 3 data source are loaded.

I'm hoping someone has some expertise and guidance to get the multiple sources of data but not mess up render or state as I've indicated?  Thank you kindly.

**Comment by k1r0s** [comment]
IMO you should load these three resources on a component which contains the entire form, and you should prevent its children from rendering until these resources are fulfilled. You can chain all promises and, using a flag, prevent render content until u have all data.

**Comment by CoderJason123** [comment]
Interesting...the last sentence seems like a similar idea to what i'm doing now, without per say having to keep track of which one has finished.  the reason i think i am in this mess is that each fetch of course has error handling.  in reality, it's unlikely that 1 out of 3 would fail...if 1 failed, the others would too.  I would not mind, if you have time, to see a tiny example because in my mind it still looks sort of ugly.  

Now the flip side is a simple set of boolean flags in the state which i can check sort of like you indicated.  Curious on your thoughts, and i appreciate the idea.

**Comment by k1r0s** [comment]
glad it was helpful @CoderJason123 

Even though you may handle specific errors in each case on other layers, parent component (which contains the entire form) should only care about one/any failure. So you should provide a single async resolution for the entire set of calls.. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by CoderJason123** [comment]
sounds good. thanks.
