### ISSUE TITLE
SSR rehydrate

### ISSUE THREAD

**Issue by nlhkh** [developit/preact#1060]
This is a question.

In React 16, when using SSR, in the client-side code, we need to use `hydrate` instead of `render` so that React only registers event handler. I guess that React does this by comparing the checksum between server-side rendered html and supposed-to-be client-side rendered html.

While playing with Preact and attempting to perform SSR, I notice that at first my component was rendered twice.
The rendering code is

```javascript
// Server code
app.get("/", (req, res) => {
  const html = renderToString(<App />)
  res.render('index', { html })
})


// Client code
const root = document.getElementById("root")
render(<App />, root)
```
and the resulting html is

```html
...
<div id="root">
  <div>This is my app.</div>
  <div>This is my app.</div>
</div>
...
```

When I change the client code to be
```javascript
// Client code
const root = document.getElementById("root")
render(<App />, document.body, root)
```

The rendered html appears to be correct
```html
...
<div id="root">
  <div>This is my app.</div>
</div>
...
```
but I wonder if it was the original html with preact event all hooked up, or if the content was replaced with exactly the same content.

Please help me shed some light on this.

**Comment by developit** [comment]
Where are you injecting the script tag?

**Comment by Cinamonas** [comment]
@nlhkh, I was running into the same issue. Found a solution in #24.

**Comment by rattrayalex-stripe** [comment]
React 16 has `ReactDOM.hydrate` for this purpose: https://reactjs.org/docs/react-dom.html#hydrate perhaps preact should support an equivalent?

**Comment by developit** [comment]
There is no meaningful difference between hydrate() and render() within Preact, since we don't use checksums.

If you're seeing a flash of white or similar, check that you're not rendering something that is initially different from your server-rendered HTML.  Also make sure you're interpreting the meaning of "parent" and "root" correctly:

```
const App = () => <div id="app">foo</div>

// our "server-side render":
document.write('<html><body><div id="root">' + renderToString(<App />) + '</div></body></html>')

// how "hydrate" from that:
render(<App />, document.getElementById('#root'), document.getElementById('#app'))
```

If you'd like a hydrate method, here's a simple one:

```js
function hydrate(vnode, parent) {
  return preact.render(vnode, parent, parent.firstElementChild);
}
```

**Comment by mfbx9da4** [comment]
@developit Very helpful. Could that go in the docs somewhere?

**Comment by marconi1992** [comment]
> There is no meaningful difference between hydrate() and render() within Preact, since we don't use checksums.
> 
> If you're seeing a flash of white or similar, check that you're not rendering something that is initially different from your server-rendered HTML. Also make sure you're interpreting the meaning of "parent" and "root" correctly:
> 
> ```js
> const App = () => <div id="app">foo</div>
> 
> // our "server-side render":
> document.write('<html><body><div id="root">' + renderToString(<App />) + '</div></body></html>')
> 
> // how "hydrate" from that:
> render(<App />, document.getElementById('#root'), document.getElementById('#app'))
> ```
> 
> If you'd like a hydrate method, here's a simple one:
> 
> ```js
> function hydrate(vnode, parent) {
>   return preact.render(vnode, parent, parent.firstElementChild);
> }
> ```

It works when the component has a root element but It doesn't work using `Fragment`.

**Comment by marvinhagemeister** [comment]
For completeness: We do ship with a `hydrate` function in Preact X. It bypasses all diffing and only attaches event listeners. For it to work you must make sure that the SSR result matches the virtual tree on the client.

**Comment by bm-stschneider** [comment]
I have the same html tree as on the SSR but I also get flaky hydration results with some intermediate version where HTML is missing.

**Comment by marvinhagemeister** [comment]
@bm-stschneider That sounds suspicious. Can you file a new issue for that?

**Comment by bm-stschneider** [comment]
I think that was a fault on my part, loading async data and loading that while initializing component elements, now I fetch all data before mounting that seems to work
