### ISSUE TITLE
contentEditable value is getting wiped out (question)

### ISSUE THREAD

**Issue by paritoshmmmec** [developit/preact#1062]
I am not sure what I am doing wrong but certainly contentEditable value is getting reset on blur. Sorry for stupid question (I did search but did not find anything related to it.) also it is working in React set up but  not in this setup

To reproduce JSfiddle [https://jsfiddle.net/q4bbceg2/1/](https://jsfiddle.net/q4bbceg2/1/) 

problematic part of code is this 

```
class ChildComponent extends Component {
 constructor() {
    super();
    this.state = {
      inputActive: false,
    };
  }
	render() {
   
		return ( <div
          role="button" style="border:1px solid red;"
          tabIndex="0"
          onFocus={() => { this.setState({ inputActive: true }); }}
          onBlur={() => { this.setState({ inputActive: false }); }}
          ref={(e) => { this.userInput = e; }}
       
          contentEditable="true"
          placeholder="Write a reply..."
          className="sc-user-input--text"
        >AAA
        </div>)
	}
}
```
I just wondering what I am missing here, if someone can point  me in right direction it would be great.

Here is the same code in react 
https://jsfiddle.net/69z2wepo/173750/

**Comment by lukeed** [comment]
It's reset because onblur you are changing the state. Any state change will rerender the component (unless a `shouldComponentUpdate` is set) and in your case, you explicitly have "AAA" set as the value.

What you should do is either set a `sCU` to false or track the value oninput & put it into state. Then the value is placed into the component.

**Comment by paritoshmmmec** [comment]
Cool thanks lukeed 

one quick question then how come it is working in react?

**Comment by yaodingyd** [comment]
In react diffing is done with comparing two vnodes, so in react, state change triggers a rerender, but vnode has not changed, so no changes applies to DOM, thus your own change to DOM preserves.

But in preact diffing is done with DOM node reference and vnode. In rerender preact would think vnode has changed thus a update on DOM, which applies the original vnode to DOM.

**Comment by developit** [comment]
Yup! Just remove the `AAA` and the diff won't have anything to compare within your contentEditable, so it won't reset the contents.

**Comment by marvinhagemeister** [comment]
@paritoshmmmec The safest way to do it in both `react` and `preact` is to store the content inside the components `state`. Here is the fixed version of your fiddle: https://jsfiddle.net/q4bbceg2/4/

```jsx
class ChildComponent extends Component {
  this.state = {
    value: "AAA",
  };

  render() { 
    return (
      <div
        onBlur={() => this.setState({
          // update text value
          value: this.userInput.textContent
        })}
        ref={(e) => { this.userInput = e; }}
        contentEditable="true"
      >
        {/* Always renders the correct value, now diffing works as expected */}
        {this.state.value}
      </div>
    );
  }
}
```
