### ISSUE TITLE
NPM published TypeScript definition still has "linkState"

### ISSUE THREAD

**Issue by rdev** [developit/preact#1072]
Hi! I just encountered an issue with `linkState`. It was removed in cb6123d0, but it still remained in TypeScript definitions.
[This comment](https://github.com/developit/preact/issues/638#issuecomment-294393577) brought it up and it seems to have been removed in 33f86d40 ([here](https://github.com/developit/preact/commit/33f86d4021b4fd321abc42572be9ecb66cdd3d72#diff-1e7674e8d96415d80a9ca1c1cafd6e6fL66))

But when installing Preact, it still has that definition:

<img width="568" alt="screen shot 2018-04-22 at 9 01 19 pm" src="https://user-images.githubusercontent.com/8418866/39095328-3eaea062-4671-11e8-922a-f94b0e30778a.png">

**Comment by k1r0s** [comment]
Hey @rdev, thanks for figure out!

feel free to PR this

**Comment by rdev** [comment]
@k1r0s There's no need for a PR, currently on the master the typing is correct, but it's not published to npm. And I'm not entirely sure how Preact is published 🙈

**Comment by k1r0s** [comment]
sorry @rdev, dr

basically latest version https://github.com/developit/preact/releases/tag/8.2.7 still contains that code so we might need to wait until next release is published :\

**Comment by marvinhagemeister** [comment]
@rdev We just published 8.2.8 🎉
