### ISSUE TITLE
Latest release is completely broken

### ISSUE THREAD

**Issue by jescalan** [developit/preact#1075]
It looks like there was an update to the minification script which caused all variables to be renamed, which probably was to save some extra bytes in the package. However, it renamed all the exports, and it also renamed "exports" as well, so now the package exports an empty object, which causes anything using preact to fail completely. Here's how the main export looks, built from the latest release directly:

![](https://cl.ly/rDSE/Screen%20Shot%202018-04-26%20at%206.20.05%20PM.png)

For now, we are pinning to `8.2.7`, which fixes the problem. Probably something should be done about this quickly, as it's a fairly critical issue.

**Comment by developit** [comment]
Ack! We will fix this right away.

**Comment by developit** [comment]
Alright, we have rolled it back for now. Thanks for reporting @jescalan!

**Comment by marvinhagemeister** [comment]
FYI: Filed an issue at the uglify repo https://github.com/mishoo/UglifyJS2/issues/3107

**Comment by yaodingyd** [comment]
@marvinhagemeister is this the same issue with uglifyjs v3 handle inline function? #1065

**Comment by leeoniya** [comment]
might also want to consider switching to https://github.com/google/closure-compiler-js, it's much slower (several seconds vs dozens of ms) but the bundles end up smaller and with fewer regressions, in my experience.

**Comment by developit** [comment]
I'd be open to it - Sam did a bunch of experimentation and got things set up with GCC a while back in #564.

**Comment by developit** [comment]
@yaodingyd yup, the VNode constructor issue is that one. Thing is, I believe we are benefitting from function inlining elsewhere, so we can't turn it off wholesale

**Comment by marvinhagemeister** [comment]
Re-open, because we haven't made a new release yet.

**Comment by jescalan** [comment]
Very exciting, thanks for your great work! 🙇🙇🙇
