### ISSUE TITLE
Typescript JSX child type checking

### ISSUE THREAD

**Issue by Alexendoo** [developit/preact#1086]
Typescript allows type checking of element children if you tell it the property name to use, would be very useful for type inference of expressions passed to a component, for example preact-router's [Match](https://github.com/developit/preact-router#active-matching--links)

https://www.typescriptlang.org/docs/handbook/jsx.html#children-type-checking

**Comment by Alexendoo** [comment]
I tried to implement it however it's not as straightforward as just adding that interface, I believe some changes to how children are typed in components will be needed

**Comment by marvinhagemeister** [comment]
Related: #1008

**Comment by matthewmueller** [comment]
this is sweeeet! at first it was a little annoying because it actually breaks some existing typechecks, but i've been wanting this feature for awhile. thanks for figuring it out!
