### ISSUE TITLE
{ Silly question} VirtualDOM compability with Elmish

### ISSUE THREAD

**Issue by ShalokShalom** [developit/preact#1087]
Sorry for putting this probably obvious topic here in the issues:

Is it possible to see preact as a drop in replacement for react?
Since its API is the same?

Can I simply use Preact in Elmish, since its ported to React already?
Thanks :D

**Comment by marvinhagemeister** [comment]
In most projects `preact` can be used as a drop in replacement for `react`. In case some 3rd party library needs react-specific things we have a compat layer called `preact-compat` that can be used in conjunction. Note that the latest react has made some API changes in `16.3.` though, but most libraries haven't switched yet.

I'm not sure how Elmish works under the hood. It looks really interesting! I don't have any experience with F#, perhaps someone else can chime in here?

**Comment by MangelMaxime** [comment]
You can indeed use preact, inferno or any library compatible with react using Elmish and modifying only your webpack config.

See their migration guide: https://preactjs.com/guide/switching-to-preact

```js
{
  "resolve": {
    "alias": {
      "react": "preact-compat",
      "react-dom": "preact-compat"
    }
  }
}
```
