### ISSUE TITLE
Support for createContext

### ISSUE THREAD

**Issue by bignose-debian** [developit/preact#1092]
The React 16.3 API now has a way to add “context”, [the `createContext` function](https://reactjs.org/docs/context.html):

> Context provides a way to pass data through the component tree without having to pass props down manually at every level.

Please implement this same behaviour and API in Preact.

**Comment by yaodingyd** [comment]
There is a PR #963 to track this.

**Comment by bignose-debian** [comment]
On 05-May-2018, Yao Ding wrote:
> There is a PR #963 to track this.

Great, thank you.

So should we leave this issue open, until the feature is implemented
in a release?

-- 
 \     “I must say that I find television very educational. The minute |
  `\       somebody turns it on, I go to the library and read a book.” |
_o__)                                                    —Groucho Marx |
Ben Finney <ben@benfinney.id.au>

**Comment by yaodingyd** [comment]
I don't see leave this issue open any good. The PR has all the implementation info(which you can review as well) and discussions, also Jason said currently Preact prefer `context` as a dedicated module. Also one wonderful contributor already published a [module](https://github.com/valotas/preact-context). Keeping this issue open would only cause distraction.
