### ISSUE TITLE
Stateless components returning wrong .type (cl)

### ISSUE THREAD

**Issue by mikeaustin** [developit/preact#1096]
We converted some some components in our project to stateless functions, and now referencing .type is returning "cl" instead of something like "Button".

Is there a known workaround for this?

cl(props, context) {
		bindAll(this);
		Component$1.call(this, props, context, BYPASS_HOOK);
		newComponentHook.call(this, props, context);
	}

**Comment by marvinhagemeister** [comment]
I'm not sure what you mean with `.type`. A function object doesn't have a `type` property per se. If you meant `MyFunction.name`, then that property is usually mangled by minifiers to save bytes.

Looking at the sample code provided it seems like you got bitten by javascript's special `this` behaviour. A `this` keyword inside a function doesn't point to the function object, but to the object the function belongs to (likely `window/module` in this example).

**Comment by Kanaye** [comment]
The `cl`-function looks like it is returned by preact-compats `createClass()`:
https://github.com/developit/preact-compat/blob/b1fe0ad17847130340429a2fab11d3a9704c0d58/src/index.js#L405-L409
But I'm also not sure whet `.type` should be.

**Comment by developit** [comment]
Use `.displayName` instead of `.name`.

**Comment by marvinhagemeister** [comment]
Oh I completely forgot about `displayName`! That's definitely the right way to ask for a component type.

**Comment by mikeaustin** [comment]
Would displayName also be mangled? I'm using an optimized version of ```continueButton.type === <Button />.type``` to make sure it works everywhere.
