### ISSUE TITLE
Fix jsfiddles in readme

### ISSUE THREAD

**Issue by eventualbuddha** [developit/preact#11]
I think they're all broken due to something being weird with rawgit. Perhaps you could switch to npmcdn.com? It's just https://npmcdn.com/preact/dist/preact.js for the latest release.

**Comment by developit** [comment]
Will do, yup.  I have been switching stuff over to `npmcdn`, it's awesome!

**Comment by developit** [comment]
@eventualbuddha All fixed, thanks for catching that.
