### ISSUE TITLE
Update JSDoc

### ISSUE THREAD

**Issue by andrewiggins** [developit/preact#1106]
In trying to better understand how Preact works, I've noticed that the JSDocs of some of the internal methods [have become out of date](https://github.com/developit/preact/blob/4f57ba02bd4dee37d3278f2e75ce18073a36deac/src/vdom/component.js#L13). I'd like to take a stab at updating these in an effort to better understand Preact. But before I do, could I get other's opinions on what style they prefer? I see a couple different styles in the codebase today. Some options are outlined below.

**Comment start**
*Most common in Preact*
Comment starts on same line as `/**`. ([example in Preact](https://github.com/developit/preact/blob/4f57ba02bd4dee37d3278f2e75ce18073a36deac/src/vdom/component.js#L10)):
```js
/** Description
 *	@param {Object} props Description
 */
```

Comment starts on line after `/**` ([example in Preact](https://github.com/developit/preact/blob/4f57ba02bd4dee37d3278f2e75ce18073a36deac/src/util.js#L2)) (Note: this appears to be the style on [usejsdoc.org](http://usejsdoc.org/about-getting-started.html))
```js
/**
 * Description
 * @param {Object} props Description
 */
```

With both of these, the intention is that `@tag` aligns to the top `Description`.

**Parameter description alignment**
Tabs between `@tag {type} name` and `description` to align descriptions ([example in Preact](https://github.com/developit/preact/blob/4f57ba02bd4dee37d3278f2e75ce18073a36deac/src/vdom/component.js#L13)):
```js
/**
 * Description
 * @param {Object} props	Description
 * @param {Number} props2	Description2
 */
```

Single space between `@tag {type} name` (i.e. don't align descriptions) ([example in Preact](https://github.com/developit/preact/blob/4f57ba02bd4dee37d3278f2e75ce18073a36deac/src/vdom/index.js#L40))
```js
/**
 * Description
 * @param {Object} props Description
 * @param {Number} props2 Description2
 */
```

@developit @marvinhagemeister - let me know if you have an opinion or not - it doesn't matter to me. I just wanted to see if it matters to you.

**Comment by developit** [comment]
@andrewiggins oooh I would wholeheartedly love to see these changes.  I also use VSCode, and have finally given up on my crazy JSDoc preferences - now I just use the format it suggests, which happens to be the one everyone else used already.  

Feel free to dump stuff into Slack as you go too if its too transient for a GH issue. Excited to see these things.

**Comment by reznord** [comment]
This would be amazing :) Excited to see these changes 😄

**Comment by marvinhagemeister** [comment]
That's awesome. I'm a real fan of typings and jsdoc are great for intellisense. I did try to apply `@ts-check` to our code base a few weeks back, but ultimately failed because of the way we declare the vnode class.

I'm neutral on wether the description should be on the first line or on the second like jsdoc suggests.
