### ISSUE TITLE
Clock example from Preact site TypeScript errors

### ISSUE THREAD

**Issue by BlackHoleFox** [developit/preact#1107]
I've been trying tons of things and haven't managed to get this to not error on me. I'm getting:
 `Property 'time' does not exist on type 'Readonly<{}>`
 and
 `Property 'timer' doesn't exist on type 'Clock'`

I looked around the existing issues and I can't tell if this was looked into or not properly, or if any fixes have been come up with. When it's in a vanilla .jsx file nothing errors. Is there a workaround to this or another way to create a component that updates on a set timer?

URL: https://preactjs.com/guide/getting-started

Thanks.

**Comment by marvinhagemeister** [comment]
TypeScript expects all member variables to be declared upfront. Here is the clock example ported to TS:

```tsx
import { h, render, Component } from 'preact';

interface State {
  time: number;
}

export class Clock extends Component<any, State> {
    timer: number = 0;
    state: State = {
      // set initial time:
      time: Date.now(),
    };

    componentDidMount() {
        // update time every second
        this.timer = setInterval(() => {
            this.setState({ time: Date.now() });
        }, 1000);
    }

    componentWillUnmount() {
        // stop when not renderable
        clearInterval(this.timer);
    }

    render(props: any, state: State) {
        const time = new Date(state.time).toLocaleTimeString();
        return <span>{ time }</span>;
    }
}

// render an instance of Clock into <body>:
render(<Clock />, document.body);
```

**Comment by BlackHoleFox** [comment]
Sadly the issues still pertain with the read only and property stuff. I still think its something wonky with the TS definitions

**Comment by marvinhagemeister** [comment]
The code above compiles fine with TS 2.8 for me. No issues there. Seems like there is something else going on in your code. Can you make a reproducible snippet/repo?

**Comment by BlackHoleFox** [comment]
@marvinhagemeister With the exact code you sent above, the only error that I get is `[ts] Type 'Timer' is not assignable to type 'number'.` on this snippet: 
 ```typescript
 componentDidMount() {
        // update time every second
        this.timer = setInterval(() => {
            this.setState({ time: Date.now() });
        }, 1000);
    }

**Comment by marvinhagemeister** [comment]
@BlackHoleFox Looks like some package in your dependency tree pulls in `@types/node`. In that case the correct types are:

```ts
class Clock extends Component<{}, State> {
  timer: NodeJS.Timer;
  // ...
}
``

**Comment by BlackHoleFox** [comment]
@marvinhagemeister I didn't realize that a dependency would do that. Its compiling now with no troubles. Thank you tons for your help, even if this turned out to be more of a trivial issue.

**Comment by marvinhagemeister** [comment]
@BlackHoleFox Awesome, glad that everything is working fine now 🎉
