### ISSUE TITLE
<a> element with "text" property

### ISSUE THREAD

**Issue by phts** [developit/preact#1108]
Currently (v8.2.9) there is a strange behavior with `text` property on `<a>` element (seems to be undocumented):

```html
<a href="http://example.com" text="WTF???"/>
```

produces:

```html
<a href="http://example.com">WTF???</a>
```

I used latest version of [preact boilerplate](https://github.com/developit/preact-boilerplate) to test.

Is it normal behavior? What `text` property is for? Original `<a>` DOM element doesn't have `text` attribute. React [doesn't behave](https://codesandbox.io/s/oov542x505) like that.

**Comment by marvinhagemeister** [comment]
Nothing strange about it, that's the way HTML is specified. It is included in the w3c spec under [HTMLAnchorElement](http://w3c.github.io/html/single-page.html#htmlanchorelement).

Curiously the [whatwg spec](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) doesn't list `text` as a valid attribute. Seems like brothers followed the one of w3c in this case.

You can easily try this out in the browser console:

```js
var el = document.createElement("a");
el.text = "foo";
console.log(el);
```
