### ISSUE TITLE
Change base path

### ISSUE THREAD

**Issue by gmarcos87** [developit/preact#1109]
When I want to use a preact application in a subdirectory I get an error. I think the problem is in the base path of index.html 
I found this issue (https://github.com/developit/preact-router/issues/279) in preact-router, but I don't think it's a router problem, as the scripts never get loaded.

**Comment by marvinhagemeister** [comment]
Preact itself only cares about update DOM-Elements and has no knowledge about urls.

The issue you described sounds like a misconfiguration of webpack. The option you are looking for is [output.publicPath](https://webpack.js.org/configuration/output/#output-publicpath) which specifies from which url assets are loaded once bundled. If you are using `preact-cli` than we have a small section on [how to extend the internal webpack config](https://github.com/developit/preact-cli#webpack).

By setting `publicPath` to the correct location the assets will be generated to the right subfolder. If you encounter any further issues once the asset path is fixed, [preact-router](https://github.com/developit/preact-router/issues) is the right place to track them.

**Comment by developit** [comment]
You might also find it useful to set the path for your document:

```html
<head>
  <base href="/my/app">
</head>
```
