### ISSUE TITLE
componentDidCatch Life cycle method in preact

### ISSUE THREAD

**Issue by KowsalyaPK** [developit/preact#1118]
This is a feature request. Please add componentDidCatch life cycle method which exists in React. In case if this method already exists then help me out as it doesn't fire when there is a error in the component

**Comment by marvinhagemeister** [comment]
@KowsalyaPK That's awesome! There is already a [PR available](https://github.com/developit/preact/pull/819) that addresses this. I'm closing this issue because we are already tracking this in #1047 and more specifically #799 👍 

**Edit:**  @Kanaye beat me to it 🎉
