### ISSUE TITLE
How to handle mustache templates?

### ISSUE THREAD

**Issue by iivn** [developit/preact#1121]
I want to work with [mustache](https://github.com/janl/mustache.js/), but how can I use the mustache brackets in the created html version? 

My Component:

```javascript
const myLinkComponent = () => (<a href={{href}}>{{linkText}}</a>);
```

This should appear in the final HTML file:

```html
<a href={{href}}>{{text}}</a>

**Comment by PepsRyuu** [comment]
```
const MyLinkComponent = () => (
    <a href="{{href}}">{"{{linkText}}"}</a>
);
```

That will output: 

```
<a href="{{href}}">{{linkText}}</a>
```

Since curly braces are special characters in JSX, you have to escape them and output them in a string. For attributes, it's as simple as opening up quotes. For the text content (the link text), open up braces, and then put in quotes inside that so you're outputting a string.

**Comment by iivn** [comment]
@PepsRyuu @marvinhagemeister Alright, thank you for your help.
