### ISSUE TITLE
Add demos for performance comparisons

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact#1136]
We have more and more PRs where we need to do a performance review (example: #1135 ). Besides just measuring numbers I'd love to add some real world demos, where we can verify the responsiveness similar to react's triangle fiber demo. This would also be beneficial when playing around with async rendering when we'll make changes to our internals.

Possible candidates:

- https://codepen.io/developit/full/xGoagz
- https://claudiopro.github.io/react-fiber-vs-stack-demo/fiber.html
- https://preact-factals.surge.sh/

**Comment by developit** [comment]
I have a preact copy of that fiber demo somewhere

**Comment by mkxml** [comment]
In the first codepen demo, when selecting setImmediate or Promise timing options my Chrome tab just hangs.

**Comment by gaearon** [comment]
Crucially the point of the triangle demo isn't to demo "performance", it's to show that there's separate scheduling for high priority and low priority updates, and that we can "rebase" the low priority reconciliation on top of a high priority update. It's nothing Preact would be able to do anyway without implementing a double buffer like in Fiber (and then resuming — which we are still missing).
