### ISSUE TITLE
Preact logo?

### ISSUE THREAD

**Issue by katopz** [developit/preact#114]
Would be nice if we have logo. Here's a rip off [React logo](https://commons.wikimedia.org/wiki/File:React.js_logo.svg) and add "P" in side.

![preact_logo](https://cloud.githubusercontent.com/assets/97060/14226818/b1cee434-f917-11e5-85a4-22b930e8b6ef.png)

Just for an idea (or if you like this do ping me for svg version of this).

Cheers

**Comment by jsonmaur** [comment]
You could also go with a simplified version of the React logo, since Preact is a "simplified" version of React. Doubt you'd have to worry about any copyright issues, the React logo is just an outline of an atom, and it's used in a ton of different logos.

![preact](https://cloud.githubusercontent.com/assets/911274/14228263/35cc51fe-f8cd-11e5-97c7-0019783ca15a.png)

**Comment by developit** [comment]
Wow guys these are both awesome. @jsonmaur good point about their logo not really being trademarkable.

**Comment by developit** [comment]
@katopz @jsonmaur Do you guys have vector versions of these?

**Comment by jsonmaur** [comment]
Sure thing.
[preact-logo.zip](https://github.com/developit/preact/files/202994/preact-logo.zip)

**Comment by developit** [comment]
Awesome, thanks!

**Comment by katopz** [comment]
@developit here we go! https://github.com/katopz/temp/blob/master/preact_logo.svg

**Comment by developit** [comment]
Awesome, got it downloaded if you need to delete the temp repo haha.

**Comment by katopz** [comment]
Naaa, I decide to keep my random ideas there, It kinda fun to look at it many years later. heehee ;)

**Comment by developit** [comment]
Nice :)

**Comment by zaccolley** [comment]
fan of the simplified react logo idea, cool! :+1: 

inspired me with a few ideas: :bulb: 

1. to emphasize 'lightweight' using a lighter typeface, here [Dosis Light](https://www.google.com/fonts/specimen/Dosis)
2. tweaked rings
3. tweak the colour so there's more contrast 

here's some examples:

![preactlogoideas](https://cloud.githubusercontent.com/assets/2591901/14413666/cfe5ad9c-ff78-11e5-9970-d96a1b797bee.png)

**Comment by developit** [comment]
Big fan of the font (particularly the `E`), though I'm dreading going back and replacing it in Affinity Designer, haha.

**Comment by katopz** [comment]
@developit Before you can close this, please provide https://preactjs.com/favicon.ico ;)

**Comment by developit** [comment]
(though I need to tweak the meta tags, the larger icon isn't taking precedence)

**Comment by katopz** [comment]
it's [kinda vary factors](https://github.com/audreyr/favicon-cheat-sheet), usually I use [fav icon generator](http://www.favicomatic.com/) to do that for me.
