### ISSUE TITLE
text input gets confused?

### ISSUE THREAD

**Issue by aprilmintacpineda** [developit/preact#1140]
https://github.com/aprilmintacpineda/preact-test-app/tree/0.0.1

The project was created with `preact create default test-app`. On the `home page`, there's an `input` of `type=text` with `value={this.state.newTodo}`. Try to type as fast as you can, maybe just type `asd` over and over again and watch the console. You'll observe that it get's confused, you can say that because of the output, you'll see that some stuff get's on the console twice, which can't be because you are literally typing `asdasdasdasdasdasdas`.

<img width="1360" alt="screen shot 2018-06-12 at 3 36 50 pm" src="https://user-images.githubusercontent.com/21032419/41276355-95ee66e8-6e56-11e8-8604-d49f0fc335af.png">

**Comment by Kanaye** [comment]
Preact uses default browser events.
In your example you are listening on the `keyup` event.
The keyup event will in some cases not get fired before an other keystroke occurs and therefore the inputs `value` property is updated.
You can oberserve this behavior within your logs for example from log line 3 to log line 4 the value changes from `asd` to `asdas`.

**Comment by marvinhagemeister** [comment]
@aprilmintacpineda The repo that you linked doesn't print out the inputs content at all. Preact uses the standard browser event system. If you feel like they don't follow the spec, the browsers bug tracker are the right place to file an issue for that.

Looking at the other issue you just closed #1141 it looks like the term you are looking for is `controlled` vs `uncontrolled` form inputs. The react docs have [a great section about the differences](https://reactjs.org/docs/forms.html).
