### ISSUE TITLE
Value of the input should not changed if the state is unchanged

### ISSUE THREAD

**Issue by aprilmintacpineda** [developit/preact#1141]
https://github.com/aprilmintacpineda/preact-test-app/tree/0.0.2

The project was created with `preact create default test-app`.

On the `home page` there's an input text there, type in something. The value is changed but the state is not changed.

```jsx
<input className={style.input} type="text" value={this.state.newTodo} />
```

**Comment by Kanaye** [comment]
Preact (and other react like frameworks) do *not* have two-way-data-bindings frameworks like angular provide.
You have to synchronize the state yourself using events.
For more information see preact docs on forms: https://preactjs.com/guide/forms and reacts docs on forms: https://reactjs.org/docs/forms.html

**Comment by aprilmintacpineda** [comment]
The value in the text is updated even when the state does not update.
I don't handle the input vent as you can see above with the code, so I don't expect the text input's value to change, but If I type in the text input, the value of the text input is still updating. It shouldn't update because I'm not updating it.

**Comment by Kanaye** [comment]
Browser elements state changes because the user is typing something not because you are updating the state.
That 's the default behavior and preact won't change it.
You can prevent it yourself for example by attaching an event listener to the `keydown` event and calling `preventDefault()` on the passed event object.

**Comment by aprilmintacpineda** [comment]
Okay.
