### ISSUE TITLE
Electron, Preact and Preact-material-components

### ISSUE THREAD

**Issue by cjus** [developit/preact#1146]
I'm interested in using Preact and preact-material-components within an Electron application. In fact I wrote a blog post: [Desktop apps using Electron, Preact and Material Design](https://medium.com/@cjus/desktop-apps-using-electron-preact-and-material-design-8161938624c6)

I used the preact-cli to build a sample app: `preact create material epmd` 
Everything seems to work just find until I try to use the Electron ipcRenderer:

```
const electron = require('electron');
const ipcRenderer  = electron.ipcRenderer;
```

Doing so results in a `Module not found: Error: Can't resolve 'fs' in '/Users/cjustiniano/dev/myapp/node_modules/electron'

The issue and solution seems to be referenced in stackoverflow and other dev sites.  The solution seems to be to add `target: 'electron-renderer'` to the webpack.

How to I get access to webpack's config to inject a new target value?

**Comment by cjus** [comment]
I looked at this https://github.com/developit/preact-cli/wiki/Config-Recipes#customising-babel-options-using-loader-helpers . But it's still not clear how to get access to webpack.

**Comment by marvinhagemeister** [comment]
@cjus The config argument __IS__ the webpack config. Just edit that ;)

1. create `preact.config.js` at the same level as your `package.json``
2. paste this (taken from `preact-cli` docs)

```js
export default function (config, env, helpers) {
  // The config arg is the webpack configuration
}
```

P.S: The [preact-cli repo](https://github.com/developit/preact-cli/issues) is the proper place for issues with `preact-cli`. The `preact` repo is more about issues with the actual framework itself.
