### ISSUE TITLE
Material-UI 1.2.1 not working with Preact

### ISSUE THREAD

**Issue by vinaybedre** [developit/preact#1148]
Hi,

Just create a default template preact-cli project, add material-ui and just use Button at https://material-ui.com/getting-started/usage/

An error is thrown: Material-UI: react@16.3.0 or greater is required

Error comes from the file https://github.com/mui-org/material-ui/blob/3353f440053222b4eed36f575593b5bfcfa7a0f3/packages/material-ui/src/ButtonBase/ButtonBase.js  and line 48.

How can we make React.createContext?

Can you please help?

**Comment by vinaybedre** [comment]
Closing as I created a PR with a fix in preact-compat

**Comment by exebook** [comment]
Any news on this?
