### ISSUE TITLE
Example for Preact with PouchDB

### ISSUE THREAD

**Issue by katopz** [developit/preact#115]
Hi,

I'm just finish (super easy) integration [Preact with PouchDB](https://github.com/katopz/preact-todomvc-pouchdb)
Would be nice if it add to examples list so someone else can have fun with it. :)

Cheers

**Comment by developit** [comment]
Ack! I meant to reply to this right away and completely forgot, sorry! Totally agree, let's add it to [preact-www](https://github.com/developit/preact-www).

**Comment by katopz** [comment]
No worry! Nothing rush :) PR here https://github.com/developit/preact-www/pull/1

**Comment by developit** [comment]
Awesome, thanks. Let's move there :)
