### ISSUE TITLE
How to destroy root Preact node?

### ISSUE THREAD

**Issue by DanielApt** [developit/preact#1151]
I want to destroy the root Preact DOM node. I initially render my component as follows:

```js
import { h, render } from 'preact';
import App from "./components/App";

render(<App />, document.querySelector("#app");
```

How do I destroy `App`? Do I simply unmount the `#app` DOM node, or does Preact offer a method similar to React's [`unmountComponentAtNode()`](https://reactjs.org/docs/react-dom.html#unmountcomponentatnode) method?

**Comment by Kanaye** [comment]
To destory your app properly you can render `null`  or `''`(empty string) into your container and set the third parameter `merge` to your apps root element.
Preact will then clean up the dom (okay it will leave an empty `TextNode`).

Example:
```javascript
class App extends Component {
  render() {
    return (<h1> Some app </h1>);
  }

  componentWillUnmount() {
    window.alert('bye cruel world');
  }
}


const root = render(<App />, document.querySelector('#app'));

function destroy() {
  render(null, document.querySelector('#app'), root);
}

```
Here the example: https://jsfiddle.net/8pcfntvz/4/

**Comment by developit** [comment]
lol +1 for a funny example

**Comment by keichinger** [comment]
Just wondering, when you're doing something like

```js
root = render(...);
// ...

root.parentNode.removeChild(root);
```

is it intentional/correct/by-design that `componentWillUnmount` won't be triggered?

I've updated the previous example to include the above snippet: https://jsfiddle.net/8pcfntvz/9/

**Comment by Kanaye** [comment]
Preact can't know that the node got removed. Afaik there is no event when a specific node get's removed. So there is no way to call lifecycle hooks when a node get 's removed by `Node.removeChild()` or `Node.remove()` . The node *must* be removed by preact for the lifecycle hooks to be called.

**Comment by apfelbox** [comment]
This would be possible via [`MutationObserver`s](https://developer.mozilla.org/de/docs/Web/API/MutationObserver). Not sure whether this is something, that should be added to core, though.

**Comment by developit** [comment]
Correct all-around :)
One other really nice way to hook element removal is to define the element as a Custom Element:

```js
customElements.define('render-root', class extends HTMLElement {
  render(props) {
    return <MyComponent {...props} />
  }
  attributeChangedCallback() {
    let props = {};
    for (let a=this.attributes, i=0; i<a.length; i++) props[a[i].name] = a[i].value;
    render(h(this.render, props), this, this.firstChild);
  }
  connectedCallback() {
    this.attributeChangedCallback();
  }
  disconnectedCallback() {
    render(null, this, this.firstChild);
  }
})
```

**Comment by cattermo** [comment]
> To destory your app properly you can render `null` or `''`(empty string) into your container and set the third parameter `merge` to your apps root element.
> Preact will then clean up the dom (okay it will leave an empty `TextNode`).
> 
> Example:
> 
> ```js
> class App extends Component {
>   render() {
>     return (<h1> Some app </h1>);
>   }
> 
>   componentWillUnmount() {
>     window.alert('bye cruel world');
>   }
> }
> 
> 
> const root = render(<App />, document.querySelector('#app'));
> 
> function destroy() {
>   render(null, document.querySelector('#app'), root);
> }
> ```
> 
> Here the example: https://jsfiddle.net/8pcfntvz/4/

This example is really confusing. According to the typing `render` does not return anything. Is the typing wrong?

**Comment by marvinhagemeister** [comment]
@cattermo It's correct that render doesn't return anything, but it did in older Preact versions during the 8.x release line. In current Preact versions (>10.x) the third argument can and should be omitted. We're planning to drop it in the next major version.

To destroy a root node in current Preact versions calling

```js
render(null, document.querySelector('#app'))
```

does the job.

**Comment by aleclarson** [comment]
This should be documented 😄 

Also, any idea whether react-scan using a double call to `render(null, …)` is warranted? See the link below, which provides an explanation.

https://github.com/aidenybai/react-scan/blob/0dd040a73ea33d809fddc61441b62ebeae38682a/packages/scan/src/web/toolbar.tsx#L68-L72
