### ISSUE TITLE
How to add appcache manifest to my project?

### ISSUE THREAD

**Issue by exebook** [developit/preact#1152]
I just need help with this silly newbie question:

How to get appcache manifst working with preact? I have installed `appcache-webpack-plugin` and added it's object to `config.plugins` so my `manifest.appcache` is generated and saved into `build`, but it is not referenced from `index.html` i.e. `<html>` tag `manifest` property is not added. I went to webpack manual but their tutorial just suggest  you have a full control on `index.html` and create one by hand. Preact gives me prebuilt `index.html` which I have no idea how to control.

**Comment by zouhir** [comment]
I'm going to close the issue here, please move it to preact-cli if you have any questions!

Thank you and Good luck 😁
