### ISSUE TITLE
`this` value in event handlers should not be the internal `_listeners` map.

### ISSUE THREAD

**Issue by keeto** [developit/preact#1154]
Event handlers added via `on<EventName` are currently invoked with a `this` value pointing to the private `_listeners` map of the Element: https://github.com/developit/preact/blob/master/src/dom/index.js#L137.

Instead of setting the `this` value to an internal, implementation specific object, consider setting it to `null`  as in React (which would set `this` to `undefined` in Strict Mode or `global` in sloppy mode):

```js
return this._listeners[e.type].call(null, options.event && options.event(e) || e);
```

Or to be more in line with DOM Events, just set it to the element:

```js
return this._listeners[e.type].call(this, options.event && options.event(e) || e);
```

**Comment by developit** [comment]
It used to point to the element, but we removed that because people relying on it expected the same from React. I'd be curious to see the size difference for avoiding invoking listeners on `_listeners` - it's not really avoiding much of a footgun, so it's a difficult thing to justify unless its basically free.

**Comment by Kanaye** [comment]
Preacts code size is highly optimized. That 's meant by "size difference".

**Comment by keeto** [comment]
I see. I'm not familiar with the preact minification/compilation strategy, but `.call()` might indeed present an issue. If `.call(null)` semantics is required without call, it can also be achieved by calling the function as a value rather than as a method call:

```js
return (0, this._listeners[e.type])(options.event && options.event(e) || e);
```

**Comment by developit** [comment]
That's a fantastic suggestion - would you be willing to submit a Pull Request adding the `(0, ...)` wrap?

**Comment by marvinhagemeister** [comment]
Looks like the interest in adding this has faded ✨ closing for now.
