### ISSUE TITLE
react-slick / preact-compat in production mode: Cannot read property 'className' of undefined

### ISSUE THREAD

**Issue by mradke** [developit/preact#1157]
References: #785 

Used bundler: webpack v. 4.12.0
preact: v. ^8.2.0
preact-compat: v. ^3.17.0
react-slick: v. 0.23.1

Used [webpack config](https://gist.github.com/mradke/9baa4b5ec540c6af8e10373528e9fa2d)

**Prequel**

We are using [react-slick](https://github.com/akiran/react-slick) in one of our projects in conjunction with preact-compat. In development mode the slider is working flawlessly.

**Observed problem**

When minified, the slider is trying to access `elem.props.className`, which fails, because the element lacks the `props` key.

The structure of `elem`, when it fails, is:

```
{
  attributes : {key: 0, children: Array(1)},
  children : [{…}],
  key : 0,
  nodeName : "div",
  preactCompatNormalized : true,
  preactCompatUpgraded : true
}
```

**Questions / Further investigation**

- Why is the object above lacking the `props`? Is this even relevant?
- Are there options to fix this short of forking `react-slick`?
- Do you need more information to reproduce this error or to comment on this?

Thanks for reading 🙂

**Comment by marvinhagemeister** [comment]
Looks like this is not an issue with `preact` itself but with `preact-compat`. Internally we do have a different data structure than `react`.

The contributors over at the `preact-compat` repo have more experience with compatibility issues than us core devs. Some of us do work on both projects though. I'd recommend filing an issue over there.

In either case I'd rethink if using `react-slick` is the right choice. It is just a wrapper for the famous `slick` slider, meaning it is based on `jQuery`. And that's the first thing it does: load `jQuery`. If you are building a `(p)react` app it makes no sense to include another framework and nullifies all performance/load improvements gained by using `preact`.
