### ISSUE TITLE
setState raised error

### ISSUE THREAD

**Issue by engmagdy87** [developit/preact#1159]
After build the React 16  app  with preact-compat, I received this error when calling a function with setState for onClick event

![capture](https://user-images.githubusercontent.com/8473421/42091208-b793cbd4-7ba4-11e8-9e99-98c7e9f17a84.PNG)

**Comment by yaodingyd** [comment]
Preact doesn't support `createPortal` currently. It is on the to-do list of `preact-compat` though. This issue is more suitable to be in `preact-compat` repo.

**Comment by developit** [comment]
Closing in favor of developit/preact-compat#481. Cheers!
