### ISSUE TITLE
Provide ES2015 dist bundle, Part 2

### ISSUE THREAD

**Issue by backspaces** [developit/preact#1162]
@yaodingyd asked https://github.com/developit/preact/issues/927 Provide ES2015 dist bundle and was closed by @developit

It did include the comment: 
> FWIW, src/ contains only valid ES2015 and ES Modules code - if you're using Webpack 2 or Rollup, you can bundle it without any plugins.

This issue addresses two points: 
1 - Now more modern CDNs provide a way for npm packages to provide *both* a UMD and an ESM.
2 - Time has passed and ESMs are more important than ever. Thus if we can Rollup our own es6 bundle, so can you! :) But if you'd prefer not to do so, could you make this a documentation request? *Thanks!*

Re 1: A point missed in  https://github.com/developit/preact/issues/927 is the new dual-repo npm approach where the UMD is served as usual, but with a module: xxx field in package.json, the ESM version can be served. You can see this with D3 and unpkg.com. Here's the approach for d3-selection, for example.

Dashboard: http://unpkg.com/d3-selection/
UMD: http://unpkg.com/d3-selection (i.e. leave off the /)
ESM: http://unpkg.com/d3-selection?module (i.e. add the module query string)

Re 2: If you really find ESM a bad idea for your project, that's fine, I know you are a lot more familiar with the downsides than I am. But then simple documentation on the README for how we can do the Rollup should do the trick.

**Comment by developit** [comment]
@backspaces I might be missing the point here - we currently ship ESM using the module main:

http://unpkg.com/preact
http://unpkg.com/preact?module

**Comment by backspaces** [comment]
My bad! I misinterpreted the comment to mean we had to build our own Rollups.

Thanks so much for the es6 module support. I'm amazed how few projects take it seriously.

Example from one project which marked an Issue for es6 module support as "wontfix" even tho only a 2 line task:

> We'll change this eventually but right not only a fraction of packages support the new import syntax and the fix to use <script src="https://unpkg.com/vega-lite"></script> is easy. Luckily this turned out to not be a bug so there is no urgency. Having said that, if we see adoption of the new import syntax is other libraries, we will follow. Changing to es2015 imports only takes two lines of changes in our building scripts.

Thanks again.
