### ISSUE TITLE
Preact breaks Apollo when setting state

### ISSUE THREAD

**Issue by dandv** [developit/preact#1169]
I might have found a reproduction for #1168, unless this is an unrelated issue.

`setState` (or using `linkState`) with a number input interferes in really odd ways with other React components. Here's a reproduction for using Apollo Client with Preact:

https://github.com/dandv/preact-breaks-apollo-when-mutating-state

The third time the state is changed, ApolloClient returns an empty data object:

![preact-apollo bug when changing state 3 times](https://user-images.githubusercontent.com/33569/43044114-23a4aa52-8d55-11e8-92fa-e558db99ee38.gif)

The app was created by running `preact create default` and removing unnecessary files.

By comparison, the [exact same code run with CRA](https://github.com/dandv/react-vs-preact-apollo) works fine.

**Comment by developit** [comment]
This should be fixed in [8.3.0](https://github.com/developit/preact/releases/tag/8.3.0)!
Please feel free to re-open otherwise :)
