### ISSUE TITLE
rollup-plugin-memory deprecation warning

### ISSUE THREAD

**Issue by dandv** [developit/preact#1172]
Got this while running `npm install`:

> deprecated rollup-plugin-memory@3.0.0: Use https://github.com/rollup/rollup-plugin-virtual instead

rollup-plugin-memory is a [direct devDependency](https://github.com/developit/preact/blob/master/package.json#L118).

**Comment by developit** [comment]
Best solved by switching to microbundle.

**Comment by marvinhagemeister** [comment]
Closing, we switched to microbundle for Preact X. We'll merge the code back into this repo on March 4th.
