### ISSUE TITLE
this.props.children is always empty array

### ISSUE THREAD

**Issue by rblin081** [developit/preact#1173]
With a render method like below the props.children is always empty

`	render(props, state) {
		return (
			h(
                'section', 
                { 
                    class : 'audioLayout'                
                },
                h('div')
			)
		);
	}`

**Comment by developit** [comment]
This is by design. We don't ship all the Children helpers in core because children is always a flat array.

**Comment by rblin081** [comment]
I'm confused, whats the correct way to access the children components from
a parent ?
