### ISSUE TITLE
Preact Children Props Array is always empty

### ISSUE THREAD

**Issue by rblin081** [developit/preact#1174]
Preact doesn't count children returned from a component's render function as children for example

`	render(props, state) {
        return(<div><ComponentOne/><ComponentTwo/></div>);
	}`

will always have props.children = []

This is inconsistent behavior from React where the children props absolutely are counted.
Also before you close this issue as a non-bug, please give guidance on how to properly get props.children to show the correct information

**Comment by yaodingyd** [comment]
Are you sure your issue is legit? The "children" in component render function should not be counted as children in the first place, and that's what react is doing too: [link](https://codesandbox.io/s/n38v1p29o0).

React children means the stuff between the opening and closing tags when actually invoking a component, that means the following count as chidlren:

```javascript
<MyComponent>
	<ComponentOne/>
	<ComponentTwo/>
</MyComponent>
```

**Comment by rblin081** [comment]
In React the opening tag is counted as the component and everything thereafter is considered a child.
Please refer to the existing [React Docs](https://reactjs.org/docs/composition-vs-inheritance.html), specifically the part about the WelcomeDialog.


> Anything inside the <FancyBorder> JSX tag gets passed into the FancyBorder component as a children prop. Since FancyBorder renders {props.children} inside a div, the passed elements appear in the final output.

**Comment by yaodingyd** [comment]
Yes, that is correct. But in your example, you are rendering child component inside a `div`, not a component.

**Comment by pl12133** [comment]
Please don’t open duplicates: https://github.com/developit/preact/issues/1173

If you create a running code sample to demonstrate the differences between React and Preact it might be easier to understand your question.

**Comment by rblin081** [comment]
Peter I replied to 1173 and did not receive a response, leading me to
believe the issue would be ongoing

**Comment by developit** [comment]
> What is the correct way to access children from a component?

```js
class Foo extends Component {
  render(props) {
    props.children  // [<span />, "hello"]
    return h('div', { id: 'foo' }, props.children);
  }
}

render(<Foo><span />hello</Foo>);
```

`props.children` is always an Array containing the JSX elements and text values passed as children to a given component.  It's normalized: `h('div', { children: 'one' }).children === ['one']`
