### ISSUE TITLE
Rendering JSX in readme

### ISSUE THREAD

**Issue by angelochen960** [developit/preact#1182]
Hi, I might get it wrong, my understanding of that paragraph is, just  import the 'h' and 'render', it should work, so here is the jsfiddle， but not working,  anything wrong here?

http://jsfiddle.net/jfeub89L/

**Comment by Kanaye** [comment]
Hi @angelochen960.
JSX is a superset of js and therefore must be compiled to js with a compiler like babel or buble.
In jsfiddle you have to change the language setting to `Babel + JSX`:
![grafik](https://user-images.githubusercontent.com/5108989/43991855-6e12eda8-9d75-11e8-8537-82220844aee8.png)
Babel by default assumes you are using react and will try to call `React.createElement`
you can configure Babel to use preacts `h` function instead with `//@jsx h`.

You can find the updated example here: http://jsfiddle.net/jfeub89L/6/

**Comment by marvinhagemeister** [comment]
@Kanaye is right on the money 👍

**Comment by angelochen960** [comment]
thanks, could you suggest a book or a tutorial on preact for people without previous React experience?

**Comment by developit** [comment]
@angelochen960 yup, this one just came out a few months ago and it's great!
https://bleedingedgepress.com/progressive-web-apps-with-preact/
