### ISSUE TITLE
Anonymous text nodes are missing after changing innerHTML of a node with a ref

### ISSUE THREAD

**Issue by Panya** [developit/preact#1185]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
I'm trying to manually change innerHTML of a node with ref. The new html contains anonymous text nodes. And after rerender, the nodes are missing in the new DOM tree.

**If the current behaviour is a bug, please provide the steps to reproduce.**
See an example https://jsfiddle.net/7v9nr23q/6 (click on the button).
The example works fine in React.

**What is the expected behaviour?**
The nodes should be in the new DOM tree.

**Please mention other relevant information.**
- Preact version: 8.3.0
- Operating system: Mac OS 11
- Browser: any

**Comment by Panya** [comment]
Seems like the bug is caused by the lines https://github.com/developit/preact/blob/master/src/vdom/diff.js#L263-L266
If I add a check for filtering out text nodes (nodeType == 3) all work as expected.

**Comment by marvinhagemeister** [comment]
If you do want to control the `innerHTML` outside of (p)react it's probably not a good idea to abuse `ref`'s for that. They are meant to be used for readonly access like measuring with `getBoundingClientRect`. The property `dangerouslySetInnerHTML` is what you are looking for to manually mutate the DOM. This has the benefit that you don't have to do change detection yourself.

With that in mind your fiddle can be rewritten and shortened to:

```jsx
/* @jsx h */
const { Component, h, render } = preact

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      content: null
    }
    this.changeContent = this.changeContent.bind(this)
  }

  changeContent() {
    this.setState({
      content: 'test1<br>test2<br>test3'
    })
  }

  render() {
    return (
      <div>
        <div dangerouslySetInnerHtml={this.state.content}></div>
        <button onClick={this.changeContent}>Change content</button>
      </div>
    );
  }
}

render(<App />, document.querySelector("#app"))
```

**Comment by Panya** [comment]
I know about `dangerouslySetInnerHTML`. But I specifically want to use the described method for performance reasons (dangerouslySetInnerHTML will set `innerHTML` on each props or state change of the component even if the html was not changed). And this method works in React but not in Preact (even with preact-compat). So I think this is a bug.

**Comment by marvinhagemeister** [comment]
@Panya if your main goal is performance you can skip the `setState` call via a simple if-statement. See this codesandbox: https://codesandbox.io/s/0vl6y67xv

```jsx
const next = "test1<br>test2<br>test3";

// Check if state has changed
if (this.state.content !== next) {
  this.setState({ content: next });
}
```

Note we currently do not support returning `null` from `setState` like react does.

**Comment by Panya** [comment]
Yep, but I have a lot another props and state that changes in the component too. I could use `shouldComponentUpdate` but the check inside the method will be more complex, so I prefer updating the html in `componentWillUpdate`. It's sad that preact with preact-compat doesn't match react behaviour in this case.

**Comment by marvinhagemeister** [comment]
To be honest I think it's more of a bug on react's side that they allow this. Their docs actively discourage doing heavy things via refs https://reactjs.org/docs/refs-and-the-dom.html .

Perhaps a more cleaner way would be to abstract the `innerHTML` stuff into a custom components that does the change detection of it's prop changes

**Comment by developit** [comment]
@Panya you can avoid preact setting innerHTML on every render by reusing the same object:

```
render(props, state) {
  if (!this.html || this.html.__html !== state.html) {
    // this lets us pass the same object to dangerouslySetInnerHTML when HTML hasn't changed:
    this.html = { __html: state.html };
  }
  return <div ref={ .. } dangerouslySetInnerHTML={this.html} />
}
```

**Comment by Panya** [comment]
@developit yep, I've managed to do exactly the same. Thanks for taking your time on the issue. I love Preact :)
