### ISSUE TITLE
batched calls to setState: invalid previousState passed as this.state to shouldComponentUpdate

### ISSUE THREAD

**Issue by carlhopf** [developit/preact#1186]
problem
--------

```javascript
constructor(...args) {
  super(...args);
  this.state.foo = 'notbar';
}

componentDidMount() {
  // two calls with same value
  this.setState({ foo: 'bar' });
  this.setState({ foo: 'bar' });
}

shouldComponentUpdate(nextProps, nextState) {
  return this.state.foo !== nextState.foo;
}

```
according to

https://github.com/developit/preact/blob/master/src/component.js#L55

1.  the first ```setState``` call updates ```this.prevState``` correctly, sets the new value to ```this.state```, and enqueues a render.

2. the second ```setState``` call will update ```this.prevState``` again, **but this time also merging in the updated** ```this.state``` value from the **first** ```setState``` call.

https://github.com/developit/preact/blob/master/src/vdom/component.js#L98

3. the queued render happens and ```shouldComponentUpdate``` is invoked, with ```component.state``` set to ```component.prevState```. but ```prevState``` already is set to the value of the first ```setState``` call.

4. hence, ```shouldComponentUpdate``` returns false and the queued render never happens - **although the state changed.**

expected behaviour
--------------------

```this.state``` in ```shouldComponentUpdate``` should be the state value from the **last** render run. even if batching multiple ```setState``` calls.

test
----

https://github.com/carlhopf/preact/commit/8695663573a7ea2d4ab2f847a56e833fe8e179fb

**Comment by developit** [comment]
Thanks for finding this @carlhopf.  I believe this is a regression caused by #1170.
Would you be able to submit a PR to add your test?  Thanks!

**Comment by carlhopf** [comment]
thanks for the quick update :) PR submitted: https://github.com/developit/preact/pull/1189
