### ISSUE TITLE
CreateRef is missing in 8.3.1

### ISSUE THREAD

**Issue by gilnoycloudinary** [developit/preact#1190]
Hey,

I was updating to the new version 8.3.1, however createRef is missing.

Really strange.

https://registry.yarnpkg.com/preact/-/preact-8.3.1.tgz#ed34f79d09edc5efd32a378a3416ef5dc531e3ac

Thanks

Gil

**Comment by Kanaye** [comment]
Hi @gilnoycloudinary!
`createRef` is *not* included in 8.3.1 as it's only a bugfix release.
Also it 's nowhere mentioned in the release notes, so you shouldn't expect it to be in 8.3.1 ;)
As far as I can tell `createRef` will make it into 8.4.0.

**Comment by marvinhagemeister** [comment]
@gilnoycloudinary @Kanaye 's answer is correct. `8.3.1` was only a patch release and as such doesn't include any new features.

**Comment by Vibing** [comment]
![1](https://user-images.githubusercontent.com/10387532/48817311-c61a2880-ed80-11e8-8e8b-58c081466964.png)
[react-countup](https://github.com/glennreyes/react-countup) used createRef，so i can't use the 8.3.1 version of preact
