### ISSUE TITLE
Unexpected behavior of getDerivedStateFromProps

### ISSUE THREAD

**Issue by janbaer** [developit/preact#1191]
I just wanted to use the with version 8.3 introduced static function **getDerivedStateFromProps**. And it will be called correctly, whenever the props of the component will be changed. But when I change the state somewhere in this component, for example in a change event handler, the function **getDerivedStateFromProps** and this behavior I don't expected. Is it correct or not that **getDerivedStateFromProps** will be called when setState was called? I assume that not.

Used version of Preact: 8.3.1

**Comment by andrewiggins** [comment]
For lifecycle methods we try to follow what React does, and our behavior here matches React's. From the [blog post for the release of React 16.4.0](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops):

> `getDerivedStateFromProps` is now called every time a component is rendered, regardless of the cause of the update. Previously, it was only called if the component was re-rendered by its parent, and would not fire as the result of a local `setState`. This was an oversight in the initial implementation that has now been corrected. The previous behavior was more similar to `componentWillReceiveProps`, but the improved behavior ensures compatibility with React’s upcoming asynchronous rendering mode.

^^That's the behavior you are witnessing in `getDerivedStateFromProps`. [This codesandbox](https://codesandbox.io/s/w6488xr3kk) demonstrates the React behavior mentioned above.

I'd suggest reading some of their docs on `getDerivedStateFromProps` to understand some use cases for it:
[`getDerivedStateFromProps` documentation](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops)
[You Probably Don't Need Derived State](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html)

**Comment by janbaer** [comment]
Thanks for the clarification. To be honest, I don't like this decision from the React team to change the behavior since it makes it some difficult to differentiate why the function was called and if I should return a state from the props or not. But now I know and can handle it.
