### ISSUE TITLE
Importing styles from a component in a parent directory fails

### ISSUE THREAD

**Issue by brwnll** [developit/preact#1196]
I'm in a situation where in one repository, I have a Preact app. Then, in a directory several directories higher, I have a shared component directory. I'm able to import the component fine, but the styles object is empty. 

If I move that component into the same directory, the styles import works as expected.

```js
// header.js
import styles from './styles';
console.log({ styles });
````

```js
// App.js
import Header from '../../../shared/header';
// Result log: styles empty object
```

```js
// App.js
import Header from './header';
// Result log: styles with class properties
```

Is this a known/expected limitation? Should I be importing them in a different way?

**Comment by developit** [comment]
Hello - this is an issue with [preact-cli](https://github.com/developit/preact-cli), not Preact. The behavior described is expected - CSS modules is only enabled within the `src/components` directory, so if you import CSS from outside that directory it is treated as "global" (non-modular) CSS that has no exports.
Please open an issue on the preact-cli repo if you need some more help.
