### ISSUE TITLE
Cannot resolve name `React` when using preact v8.3.1 with Flow v0.79.1

### ISSUE THREAD

**Issue by bit2pixel** [developit/preact#1200]
I'm encountering the following issue when using `flow` with `preact`.
I've followed your flow integration doc but it's not working as expected.

*Error*
```
[flow] Cannot resolve name `React`. (view.js:36:5)
(property) JSX.IntrinsicElements.h1: JSX.HTMLAttributes
Flow-IDE
h1: (unknown)
```
*Code (Shortened)*
```jsx
/* @flow */
'use strict';

import { h, Component } from 'preact';

type Props = {};

type State = {};

export class HelloWorld extends Component<Props, State> {
	constructor (props: Props) {
		super(props);
		this.state = { };
	}

	render (): any {
		return (
			<div class='hello-world'>
				<h1>Hello World</h1>  // This line fails
			</div>
		);
	}
}
```

**Comment by bit2pixel** [comment]
Good to note that I've also tried the following `.flowconfig` and variations of it. No luck.

```ini
[ignore]

[include]

[libs]

[lints]

[options]
emoji=true

esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

module.system.node.resolve_dirname=.
module.system.node.resolve_dirname=src
module.system.node.resolve_dirname=node_modules

module.file_ext=.js
module.file_ext=.json
module.file_ext=.jsx
module.file_ext=.css
module.file_ext=.scss

server.max_workers=1

[strict]
```

**Comment by marvinhagemeister** [comment]
I'm not a flow user so I may be totally wrong:

For TypeScript there are usually dedicated types for react and preact. When both are installed they fight for the jsx namespace globally and TypeScript throws a similar error to yours.

Perhaps it's something of this sort? Hopefully somebody with experience in flow can chime in.

**Comment by bit2pixel** [comment]
Adding `/** @jsx h */` manually to the top of each file seems to do the trick.
More typing but at least it's working.

**Comment by Hubro** [comment]
I'm getting this error currently, and adding that comment to all my source files is not an acceptable solution.

**Comment by ForsakenHarmony** [comment]
Sorry, but flow seems to have lost against typescript (so you might be better off using that) and afaik no one in the core team uses it, so solving flow errors isn't really something we can do

If you can improve them with a PR you're very much welcome to (for preact v8 that would be the `8` branch where we could do a release for flow typings)

**Comment by SerzN1** [comment]
Think adding something to the top of each file, not the best approach. There is a better way at least for TS

https://github.com/preactjs/preact#default

For using Preact along with TypeScript add to tsconfig.json:

{
  "jsx": "react",
  "jsxFactory": "h",
}
