### ISSUE TITLE
TypeScript typings for render(props.children) should be ComponentChild[], not ComponentChildren

### ISSUE THREAD

**Issue by AlexVallat** [developit/preact#1203]
Since preact makes the very useful guarantee that, in the ```render``` function, ```props.children``` will always be an array, typing the ```props``` as ```RenderableProps<P>``` gives the overly-broad type for the ```children``` property of ```ComponentChildren```. This used to be just ```ComponentChild[]```, but has now been extended significantly (I believe to improve tsx support).

For example:
```
render(props:RenderableProps<MyProps>) {
   if(props.children.length) {  <= FAIL
```

You have to do the rather ugly:
```
render(props:RenderableProps<MyProps>) {
    if((props.children as ComponentChild[]).length) {
```

instead, to encode the assertion that we know that .children is guaranteed to be an array in the render function.

**Comment by timpur** [comment]
+ 1 

Not sure if actually is should just be `ComponentChildren[]`

Also to add shouldn't `render` be able to return `props.children` ? thus `render: ComponentChildren[]`

**Comment by AlexVallat** [comment]
Pretty sure it shouldn't be `ComponentChildren[]`, it's supposed to be normalised to a flattened array, isn't it? If it was `ComponentChildren[]` then that would/could be an array of `ComponentChild` arrays...

I don't think preact currently supports fragments, so you can't return an array from render. Yet. Looks like it's coming soon, though: [#946](https://github.com/developit/preact/issues/946#issuecomment-415766043)

**Comment by Alexendoo** [comment]
I have been taking another look at this using `JSX.LibraryManagedAttributes` recently and there's a couple questions that have come up that I'd like to get some feedback on. 

**Firstly**, as the issue mentions the children property of a component is mixed into the Props generic  - we could just simply remove this, it gets very complicated to have this with generic children that are correctly typed for TSX and for the component. Should we?

https://github.com/developit/preact/blob/8b2f56a54d7fd46ec23ee280977860ca015d5236/src/preact.d.ts#L55-L57

If we do remove it then it would be a pretty large breaking change for TypeScript codebases, every component that uses `this.props.children` would have to specify a type in the Props for them (if they already specify the type it wouldn't be breaking). I think this could actually be quite desirable but I'd like some thoughts on it.

**Second**, should there be any leeway on the type of children in the Props generic? Currently you can have a `Component<{ children: string }>` for example but this is technically incorrect for preact, it should be using a single valued tuple: `Component<{ children: [string] }>`.

It's possible (though substantially more complicated) to allow the `{ children: string }` form and have RenderProps map it back to the correct form with a conditional type.

cc @marvinhagemeister

**Comment by marvinhagemeister** [comment]
@Alexendoo I'd prefer not having to explicitly specify `children` for each Prop interface. Regarding the second point: We will not normalize `children` to an `array` anymore like we currently do with preact. Instead we follow `react's` behaviour to leave children as is.

**Comment by AlexVallat** [comment]
> We will not normalize children to an array anymore

Oh, that's a shame, I thought that was a useful feature. Does that mean you will be adding the [React.Children](https://reactjs.org/docs/react-api.html#reactchildren) API instead?

**Comment by Alexendoo** [comment]
Oh is that to say a TS change wouldn't be needed in that case @marvinhagemeister? That is kind of relieving since I was finding it difficult to model the preact behaviour.

I think I agree with you on the children front too, in practise most components I write rarely have an opinion about the type of children passed to it

**Comment by AlexVallat** [comment]
>most components I write rarely have an opinion about the type of children passed to it

Really? Unless I'm just passing them down the line to the next component, I find the opposite, at least as far as expecting a .length and to be able to iterate over them. If they are no longer going to be guaranteed an array, then an api like React.Children is needed to do array-like things to them.

**Comment by developit** [comment]
@AlexVallat We're still waffling on that to be honest. I too liked the simplicity of `props.children[]`. I believe the current plan is to expose `.Children` helpers, since we needed them internally anyway.  We'll see though, there's also been some experimentation with keeping the root of `props.children` as an Array but allowing arbitrary nesting and values.

**Comment by marvinhagemeister** [comment]
Closing: In Preact X `children` are not guaranteed to be an array anymore.
