### ISSUE TITLE
JavaScript errors are not thrown in Firefox during rendering

### ISSUE THREAD

**Issue by exebook** [developit/preact#1205]
Developing with preact (no JSX, no build step) became almost impossible for me, because my syntax errors in render functions are not shown in the browser, they are just silently swallowed somewhere in preact internals, see this minimal example:

```js
<html>

<head>
	<meta charset=utf8>
	<script src="https://unpkg.com/preact@6.4.0/dist/preact.min.js"></script>
</head>

<div id=root>...</div>
<script>
	const { Component, h, render } = window.preact
	
	class App extends Component {
		constructor(props) {
			super(props)
		}
		componentDidMount() {
			this.setState({ stage:'choose-lesson' })
		}
		render() {
			if (this.state.stage == 'choose-lesson') {
				return h(TicketChoiceMenu, {})
			}
			else {
				return h('b',{},'oh')
			}
		}
	}
	
	function TicketChoiceMenu() {
		un = de.fi.ned // this is not reported in FireFox
		return 'bla'
	}
	
	render(h(App), root)

</script>

</html>

```
Although in Chrome everything is awesome. 
I temporarily fixed this by wrapping `buildFunctionalComponent` in try catch with a log:

```js
    function buildFunctionalComponent(vnode, context) {
	  try{return vnode.nodeName(getNodeProps(vnode), context || EMPTY);}catch(e){console.log(e)}
    }
```

**Comment by exebook** [comment]
Firefox 61.0.2

**Comment by rjoydip** [comment]
@exebook I think `buildFunctionalComponent ` wrapping issue is comming for this typo `<div id=root>...</div>` ***>*** `<div id="root">...</div>`. You may re-check your code once again

**Comment by exebook** [comment]
@rjoydip you mean double quotes around the div id parameter? No, it is irrelevant, I checked.

**Comment by exebook** [comment]
@andrewiggins I did not know preact 6 was not the latest one, switching to 8 fixed the problem, thank you!
