### ISSUE TITLE
Dealing with exceptions

### ISSUE THREAD

**Issue by photz** [developit/preact#1213]
Thanks to the new componentDidCatch lifecycle method it's possible for parent components to intercept exceptions raised by child component constructors or lifecycle methods.  The problem I currently have is that I would like to catch all exceptions in my Preact app and respond to them.

**Comment by developit** [comment]
How do you intend to respond to them?  You can define a component at the root of your application that accepts all errors.

**Comment by photz** [comment]
Thanks for your response.  When an exception is caught (globally, in my entire app), then I would like a method of my root component to get called so that I can, for instance, change its state to display an error message.  Maybe I'm being a bit thick, but I fail to see how this could be accomplished without messing with Preact itself.

**Comment by developit** [comment]
This is how componentDidCatch works - it catches all errors for all descendent components (not just parent/child).  You can do something like:

```js
class App extends Component {
  componentDidCatch(err) {
    this.setState({ error: err });
  }
}
```

**Comment by marvinhagemeister** [comment]
We released an alpha for next version of Preact just a few hours ago. It includes full support for `componentDidCatch` 👍
