### ISSUE TITLE
ComponentChild should also allow boolean in TypeScript

### ISSUE THREAD

**Issue by KasparEtter** [developit/preact#1215]
Is there a reason why a ComponentChild cannot be a boolean? https://github.com/developit/preact/blob/b5c4a36576b65623c2664d04c03a04e57dc1e06a/src/preact.d.ts#L7-L8

Due to this, I get the following error:
```
[ts]
Type '{ children: boolean; }' is not assignable to type 'HTMLAttributes'.
  Types of property 'children' are incompatible.
    Type 'boolean' is not assignable to type 'string | number | object | VNode<any> | ComponentChild[] | null | undefined'.
```

And is there a reason why ComponentChildren repeats many of the same types as ComponentChild?

If you want, I can make a pull request that replaces those two lines with
```
	type ComponentChild = VNode<any> | string | number | boolean | null;
	type ComponentChildren = ComponentChild[] | ComponentChild;
```
(which would also remove 'object' which seems strange to me anyway – including the fact that it only exists for ComponentChildren). Please note that I haven't checked yet whether still everything works with such a change.

**Comment by developit** [comment]
TBH, Preact will currently accept any value except an Array as the return value of a Component or its render method.  I don't know if that's something we're intending to change in the future, though.  React, for example, does not allow returning strings, numbers or booleans from render.

**Comment by marvinhagemeister** [comment]
@KasparEtter That's awesome 🍀 The `boolean` type is indeed missing there and should be added. Happy to review any PRs related to this👍
