### ISSUE TITLE
How to integrate preact in angular 1 ?

### ISSUE THREAD

**Issue by prasad0612** [developit/preact#1216]
Hi 
We have integrated react into angular 1.6 based framework which we have written, We are using ReactDom.render api to render the react component from angular context. Also this API allows to pass properties to React component.
Can we integrate preact with angular same wat? I saw there is preact. render API but it does not accept any parameters or properties.
Please suggest
Thanks
Prasad

**Comment by developit** [comment]
The methods are all the same as React, not sure where you read there are no parameters.

```
import FooComponent from './foo'
import { createElement, render } from 'preact'

render(
  createElement(FooComponent, props),
  this._el[0]  // or whatever it's called in angular
);
```
