### ISSUE TITLE
Need umd build 

### ISSUE THREAD

**Issue by prasad0612** [developit/preact#1218]
Hi,
We are using angular1.6 in our framework where we load modules or js using requirejs (umd). I am trying to integrate preact in our framwork which fails to load since preact lib does not support umd.
Is it possible to publish umd build as well

Thanks,
Prasad

**Comment by prasad0612** [comment]
Hello
Any updates?

Thanks
Prasad

**Comment by developit** [comment]
I'd like to publish a UMD bundle. PR's welcome if you have time.

**Comment by developit** [comment]
This will go out in the next release.

**Comment by marvinhagemeister** [comment]
The release (alpha version) went out just a few hours ago 🎉
