### ISSUE TITLE
ref() called only once with a DOM element on conditional rendering

### ISSUE THREAD

**Issue by tomazy** [developit/preact#1225]
I'm trying to get a reference to an input displayed in a modal dialog in an app that looks more or less like this:

```jsx
class App extends Component {
  render() {
    const { open } = this.state
    return (
      <div>
        { // ... more code }
        {
          open ? (
            <Overlay>
              <input type="file" ref={this.refInput} />
            </Overlay>
          ) : null
        }
        { // ... more code }
       </div>
    )
  }

  refInput = (el) => {
    console.log('refInput', el)
  }
}
```

When the `open` flag is set to `true` for the first time, the `refInput` is called with a DOM element as expected. 
Now, when the `open` flag is set to `false`, the `refInput` is called with `null` - as expected.

The problem appears when we set the `open` flag to `true` again. `refInput` is never called with a DOM element again. 

Interestingly, when we replace `<Overlay/>` with a `<div/>` - `refInput` gets called as expected.

Here is an example illustrating the issue: https://jsfiddle.net/3hvru6ex/2990/
And here the same example in React, working correctly: https://jsfiddle.net/n5u2wwjg/206396/

**Comment by developit** [comment]
Looks like this is a symptom of component recycling.

**Comment by marvinhagemeister** [comment]
We fixed this for our next release 🎉 An alpha version is already available on npm 👍
