### ISSUE TITLE
There is a little confusion, I hope answers

### ISSUE THREAD

**Issue by aimwhy** [developit/preact#123]
function unmountComponent(dom, component, remove) 

"dom" is unuserful
"remove" in "removeOrphanedChildren" and  "recollectNodeTree"  transformation values
unmountComponent is Recursived

Can I have a flow graph ?

I understand that it is： 

```javascript
    function unmountComponent(component) {
        hook(component, '__ref', null);
        hook(component, 'componentWillUnmount');

        var inner = component._component;

        if (inner) {
            unmountComponent(inner);
        } else {
            var base = component.base;
            var ancestorComponent = base._component;
            
            removeNode(base);
            removeOrphanedChildren(base.childNodes, true);
            ancestorComponent._parentComponent = null;
            collectComponent(ancestorComponent);
        }

        hook(component, 'componentDidUnmount');
    }
``` 

right?

**Comment by developit** [comment]
@aimwhy I still need to merge your PR for removing `dom` - I'll try to get that done later today.  Regarding the `remove` flag in `unmountComponent()`, that is used to trigger the two different types of unmount.

Given this hierarchy:

```
<root>
    <ComponentA>
        <ComponentB>
            <div>
                <ComponentC>
```

Here's a diagram:

<img width="499" alt="screen shot 2016-04-12 at 8 16 14 am" src="https://cloud.githubusercontent.com/assets/105127/14459599/dd77f5be-0086-11e6-95c8-cec8ca3eb815.png">

**Comment by developit** [comment]
Closing since this method has changed since initial question 👍
