### ISSUE TITLE
"ref" is not a function

### ISSUE THREAD

**Issue by ArthurYidi** [developit/preact#1232]
After introducing https://github.com/developit/preact/pull/1138 `ref` is not always a function.

The following code causes an exception.
https://github.com/developit/preact/blob/329d7c14140624d8b194f04f6c093f7f55e19d97/src/vdom/component.js#L285

**Comment by developit** [comment]
@ArthurYidi good catch, I must have missed that when converting things over to applyRef. I've opened #1235 to fix.
