### ISSUE TITLE
Error when using ES6 classes

### ISSUE THREAD

**Issue by LinusU** [developit/preact#125]
When using pure ES6 (no transpiling) you are not allowed to instantiate a class by `.call`-ing the constructor. It will throw `TypeError: Cannot call a class constructor`. Yet this seems to be happening in the `rerender` function.

As soon as I navigate back to a view that have been previously viewed, I get just that error, `TypeError: Cannot call a class constructor`.

Here is a stack trace:

<img width="303" alt="screen shot 2016-04-14 at 18 56 49" src="https://cloud.githubusercontent.com/assets/189580/14536444/ae0a5d42-0272-11e6-8d58-88fa26ed4b95.png">

`CompanyList` is my class.

**Comment by developit** [comment]
@LinusU which version of Preact is this?  4.6.2 reverted the only use of callable constructors I am aware of, prior to that I could see this error happening in rerender for sure.  For reverence, here's the change:
https://github.com/developit/preact/commit/99d46f9ede8737cf332b69f65d6a3e579a307c88

If you're on 4.6.1, can you check 4.6.2? Thanks!

**Comment by LinusU** [comment]
:facepalm: It works with 4.6.2, thank you for the quick response!

Awesome support on this library 🙌

**Comment by developit** [comment]
Yesss! When I saw this come in I was cooking but I really hoped it was fixed by that commit, haha. Cheers!
