### ISSUE TITLE
[Question] QT Web tool kit 5.6.3

### ISSUE THREAD

**Issue by renanmpn** [developit/preact#1252]
Hi everyone,

I need to use an old version of  QT web toolkit 5.6.3 and I need to know if Preact will work properly. 
Anyone knows this information?

These are the links about my QT version:

http://doc.qt.io/qt-5/qtwebengine-platform-notes.html
http://download.qt.io/community_releases/5.6/5.6.3/

Best,

**Comment by developit** [comment]
Yes, it should support Preact. Preact doesn't really use much API surface, and a quick perusal of the docs suggest this supports fairly recent DOM spec.
