### ISSUE TITLE
Autofocus doesn't work

### ISSUE THREAD

**Issue by dkirchhof** [developit/preact#1255]
Hi,

i have a textarea which will be rendered, if some state is true. This input should get the focus automatically. So i use the `autoFocus` attribute. Unfortunatelly the component doesn't get the focus. When i use react, it works.

Tested with:
- preact: 8.3.1
- preact-compat: 3.18.4

**Comment by marvinhagemeister** [comment]
@dkirchhof According to [the HTML spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autofocus) setting the `autofocus` attribute will focus the form-control as soon as the page is loaded. In your case it seems like the page is already loaded when setting the `autofocus` attribute, resulting in having no effect.

If you want to focus elements after the page is loaded you can use the native `focus()` method.

```jsx
class Foo extends Component {
  constructor(props) {
    super(props);
    this.ref = createRef();
    this.onClick = this.onClick.bind(this);
  }

  onClick() {
    if (this.ref.current) {
      this.ref.current.focus();
    }
  }

  render() {
    return (
      <div>
        <input ref={this.ref} />
		<button onClick={this.onClick}>Set focus on input</button>
      </div>
    );
  }
}
```

**Comment by dkirchhof** [comment]
Well, i was just wondering, why it works in react and doesn't in preact. So i have to refactor my code or will keep react.
