### ISSUE TITLE
diffLevel can be removed?

### ISSUE THREAD

**Issue by AnthonyYY** [developit/preact#1258]
https://github.com/developit/preact/blob/95075f4a817d86f715ddbafc9928e847cd6aba4b/src/vdom/diff.js#L17

Don't see what `diffLevel`'s use case, since it can't track the true diff level, or does this exported variable have any other purpose?

**Comment by marvinhagemeister** [comment]
Yup, `diffLevel` is only used to track the topmost diff, so that we know when to fire `componentDidMount` hooks. It serves no other purpose, so we removed it for Preact X.
