### ISSUE TITLE
preact@8.4.1 and preact-portal: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pl12133** [developit/preact#1269]
Howdy! I was excited to test the new release of `preact@8.4.1` today but my App won't run because it makes heavy use of `preact-portal` which seems to now cause an infinite loop when rendered.

Reproduction: https://jsfiddle.net/bfqxrghu/2/

**Comment by developit** [comment]
Looks like this is because the mount queue only gets emptied after iteration. Because preact-portal uses `componentDidMount()` to render a second tree, that tree appends an entry to the mount queue, which causes the indices to shift and Portal.componentDidMount() to be called again (repeated).

**Comment by developit** [comment]
Was due to #1211.

**Comment by developit** [comment]
Fixed in [8.4.2](https://github.com/developit/preact/releases/tag/8.4.2)!
