### ISSUE TITLE
inconsistent ref/lifecycle ordering

### ISSUE THREAD

**Issue by quarterto** [developit/preact#1273]
when a class component with a `ref` gets unmounted then remounted, in certain circumstances the `ref` is never called with (slash set to, in the case of `createRef` refs) the instance. here's a reduced example:

https://codesandbox.io/s/xj4pllynxw

which logs:

```
===toggling=== 
will unmount 
null
R {__d: false, context: Object, props: Object, state: Object, __h: Array[0]…}
did mount 
===toggling=== 
R {__d: false, context: Object, props: Object, state: Object, __h: Array[0]…}
will unmount 
null
did mount 
```

the second remount has some odd/unexpected ordering. although this example uses a function ref, this also happens with `createRef`.

**Comment by marvinhagemeister** [comment]
Closing, we completely rewrote ref handling in #1302 and fixed this issue in the process :+1:
