### ISSUE TITLE
TS: createRef not an exported member

### ISSUE THREAD

**Issue by SolarLiner** [developit/preact#1279]
```bash
 ERROR [at-loader] ./src/components/AppNavbar.tsx:1:21
    TS2305: Module '"/home/solarliner/Documents/Projects/Website/test-rest-framework/preact-frontend/node_modules/preact/dist/preact"' has no exported member 'createRef'.
```

I have version 8.4.2, and checked the installed package to see if the javascript contains the function (it does). It seems that the TypeScript definition file hasn't been updated for the inclusion of `createRef` yet.

**Comment by developit** [comment]
Good catch! Want to PR it? :)

**Comment by SolarLiner** [comment]
I've been playing with the definitions file and couldn't find a way to make it work. If somebody finds a way before me, please do send a PR, otherwise when I do I will!
