### ISSUE TITLE
class keyword is not working properly, but className is in React-Grid-Layout.

### ISSUE THREAD

**Issue by kono-paku** [developit/preact#1282]
Hello,

I do like the naming of class in Preact instead of className in React.

On using react-grid-layout below,
it seems that class keyword in tag affects properly in react-grid-layout.
But, className keyword does not..
https://github.com/STRML/react-grid-layout

I set the value of layout in graphContainer.css.
class keyword is not applied..

```
import { h, Component } from 'preact';
import style from './graphContainer.css';
import GridLayout from 'react-grid-layout';

class GraphContainer extends Component{
  render() {
    return (
      <GridLayout className="layout" cols={12} rowHeight={30} width={1200}>
        <div key="a" data-grid={{x: 0, y: 0, w: 1, h: 2, static: true}}>a</div>
        <div key="b" data-grid={{x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4}}>b</div>
        <div key="c" data-grid={{x: 4, y: 0, w: 1, h: 2}}>c</div>
      </GridLayout>
    )
  }
}
```

Do I have to use className out of preact?

**Comment by developit** [comment]
Preact-compat should be handling this automatically. It installs a getter on `props.className` that makes it an alias of `props.class`:

https://github.com/developit/preact-compat/blob/master/src/index.js#L374-L386

What versions of Preact and Preact-compat are you using?

**Comment by kono-paku** [comment]
I expected and it appears that ,as you said, most of cases are successfully converting class into className. 
I am using preact-cli, it might be webpack configuration problem rather than preact and preact-compat..?

```
    "preact-compat": "^3.17.0",
    "preact": "^8.4.2",
    "react-grid-layout": "^0.16.6",
  ```

**Comment by nmquebb** [comment]
If you're using css modules it may be that the styles just aren't being referenced.

```
import style from './graphContainer.css';

...

<GridLayout class={style.layout} cols={12} rowHeight={30} width={1200}>
```

The difference being ` class={style.layout}` instead of ` className="layout"`

**Comment by marvinhagemeister** [comment]
Looks like this issue has been resolved 🎉
@kono-paku If you're still running into this issue, please ping me :)

**Comment by kono-paku** [comment]
@marvinhagemeister 
Actually, I have another compatibility issue vx react library.
As soon as I changed into pure react one, all issues has gone.
I think preact and preact-cli are fantastic to start with light-weight app.
Nevertheless, it is so difficult to resolve react-third-party library following on latest react version.

But, thank you very much for your consideration.

**Comment by marvinhagemeister** [comment]
@kono-paku Thanks for getting back. A bummer that `preact` didn't work out for you. We're close to cutting a beta/rc version of our next major version Preact X. Besides adding several new features like `Fragments`, `componentDidCatch`, and so on, we managed to improve compatibility with third-party libraries a lot. It be super awesome if you could give it another go once it's out 👍
