### ISSUE TITLE
Providing a minified mjs bundle

### ISSUE THREAD

**Issue by rmacklin** [developit/preact#1285]
It's recommended to use `preact.min.js` instead of `preact.js` in production builds due to the file size reduction from the property mangling: https://github.com/developit/preact/blob/87a4ebe99dc068eaeb8503644c60ffe8ad735771/config/properties.json#L1-L27

This works well if you are using a regular script to pull preact from the CDN and relying on the `preact` global or if you are bundling with webpack. However, it doesn't work if you are importing preact as a native ES module.

In that case, you can successfully import the unminified `preact.mjs` bundle, as seen here:
http://jsfiddle.net/tpck6Lf4/
But since `preact.min.js` is not a native ES module, you cannot change it like this:
```diff
- import { Component, h, render } from 'https://npmcdn.com/preact@8.4.2/dist/preact.mjs'
+ import { Component, h, render } from 'https://npmcdn.com/preact@8.4.2/dist/preact.min.js'
```
(you'd get `SyntaxError: The requested module 'https://npmcdn.com/preact@8.4.2/dist/preact.min.js' does not provide an export named 'h'`)

It'd be awesome if there was a corresponding `preact.min.mjs` that we could import from in production builds to take advantage of the reduced file size.

One way to do this might be to switch from uglify to terser where the minifier can understand ES2015 syntax. Alternatively perhaps we can minify the code with `export` stripped out, and then add it back. Thoughts?

**Comment by developit** [comment]
This is something already fixed in Preact X 💃 
I think we made the call not to backport all the build system changes. Once the repos are merged though it's probably something worth considering (9.x updates that move to microbundle).

**Comment by marvinhagemeister** [comment]
We published an alpha version for Preact X just a few hours ago. It's available on npm via the `preact@next` tag and ships with a minified `mjs` bundle 💯
