### ISSUE TITLE
this.props.history is not available in componentWillReceiveProps()

### ISSUE THREAD

**Issue by WaqarHassan** [developit/preact#1287]
I am trying to access 

`this.props.history`

inside componentWillReceiveProps() 
but it is giving me undefined.

**Comment by marvinhagemeister** [comment]
@WaqarHassan Please post the code of your component where `this.props.history` is not present. We'd love to help you, but without any information at hand, it's impossible know what's going on ;)

**Comment by WaqarHassan** [comment]
`import { h, Component } from "preact";
// import { Link } from "preact-router/match";
import style from "./style";
import { loginUser } from "../../actions/authActions";
import { connect } from "preact-redux";

class Login extends Component {
  constructor(props) {
    super(props);
    this.state = {
      email: "",
      password: ""
    };
    this.onChange = this.onChange.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
  }

  onSubmit(e) {
    e.preventDefault();
    const loginData = {
      email: this.state.email,
      password: this.state.password
    };
    // debugger;

    this.props.loginUser(loginData);
  }
  onChange(e) {
    this.setState({ [e.target.name]: e.target.value });
  }
  componentWillReceiveProps(nextProps) {
    if (nextProps.auth.isAuthenticated) {
      // debugger;
      window.location.href = "/admin/orders";
      // this.props.history.push("/admin/orders");
    }
  }

  render() {
    return (
      <body class="authentication-bg">
        <div class="account-pages mt-5 mb-5">
          <div class="container">
          </div>
          </div>
       </body>
);
}
}

const mapStateToProps = state => state;
export default connect(
  mapStateToProps,
  { loginUser }
)(Login);`

**Comment by marvinhagemeister** [comment]
Awesome, thanks for posting. Where do you expect the prop `history` to be coming from? It is accessed in `componentWillReceiveProps` but the sample doesn't show how `Login` receives it. Do pass it around via `props` directly, via `context` or in some way via `redux`?

**Comment by WaqarHassan** [comment]
@marvinhagemeister Thanks for quick reply.
Actually, In React I always had it available to me via props.
I really don't know how to get it in preact.

**Comment by marvinhagemeister** [comment]
Can you show us the code where you'll pass `history` to the component? It should work the same way in preact as it does in react. There is very likely something else going on that's not related to the underlying framework but has to do with app code. Can you make a simple example in https://codesandbox.io/ where the issue can be reproduced?

**Comment by WaqarHassan** [comment]
Figured it out.
**Preact**

`preact-router` gives route(`${PATH}`) to navigate.

**React**

`this.props.history` is available through `react-router-dom` by importing it and then wrapping exported component with `withRouter` to navigate.
