### ISSUE TITLE
componentWillMount not triggering under certain scenarios

### ISSUE THREAD

**Issue by impronunciable** [developit/preact#129]
Hi, I'm using `preact-router` along with `react-redux`. As @developit pointed, this check is the problem https://github.com/developit/preact/blob/master/src/vdom/component.js#L131

Removing the if did the trick and triggered componentWillMount. This is my scenario https://github.com/impronunciable/hackdash-front/blob/master/src/containers/Dashboard.js#L8

**Comment by developit** [comment]
@impronunciable I might have fixed this with [4.7.1](https://github.com/developit/preact/releases/tag/4.7.1). I found a regression in `4.6.2` a case very similar to the one you encountered.  Let me know if it's fixed :)

**Comment by impronunciable** [comment]
not working for me event after update.

**Comment by developit** [comment]
Alright, I'll get some tests around this. Going to need to queue some lifecycle events, there are 3 open issues relating to their timing now.

**Comment by developit** [comment]
Confirmed this is a bug, so I'm holding off on any releases until I have a complete fix in place. Hopefully very very soon!

**Comment by developit** [comment]
Confirmed fix for this coming shortly!

**Comment by developit** [comment]
This should be fixed in 5.0.0-beta1 :)

**Comment by developit** [comment]
Fix verification: http://codepen.io/developit/pen/reXZvd?editors=0010
