### ISSUE TITLE
Encoding images in base64 in scss

### ISSUE THREAD

**Issue by Acika00mk** [developit/preact#1291]
Preactjs automatically encodes images in base64 format when i try to add like background image on element written in the scss.

Any suggestion for configuration regarding this ?

<img width="387" alt="screen shot 2019-01-18 at 16 02 04" src="https://user-images.githubusercontent.com/4304026/51433288-b36c8480-1c47-11e9-901f-8d13c38a4782.png">
<img width="500" alt="screen shot 2019-01-18 at 16 01 57" src="https://user-images.githubusercontent.com/4304026/51433289-b36c8480-1c47-11e9-8170-ff75b1a93913.png">

**Comment by marvinhagemeister** [comment]
Preact is a framework for writing components and doesn't have any knowledge of files. It looks like you're using some sort of bundler (probably `webpack`) which seems to be configured to inline smaller images as base64 strings.
This is typically done to save a network request.

If you're encountering this with the `preact-cli` (which is a wrapper around `webpack`) you should file an issue there. The CLI team is pretty quick to narrow down issues 👍
