### ISSUE TITLE
Handling for external DOM mutations across React vs. Preact (vs. Preact X?)

### ISSUE THREAD

**Issue by natevw** [developit/preact#1294]
I am trying to wrap an existing D3 view inside a Preact component. The D3 logic is complex and needs its DOM left alone. However, the D3 logic should be triggered every time its `Component` wrapper's `props` change  — i.e. the DOM inside is ± unidirectionally "data-driven" but takes care of its own diffing.

Looking into the right way to handle this, I am struck by a significant difference between Preact and React.

With Preact the advice according to the [External DOM Mutations](https://preactjs.com/guide/external-dom-mutations) page in the official guide is essentially:

1. Always return false from `shouldComponentUpdate` to prevent all but the first call to `render()`.
2. Trigger DOM mutations based on the new arguments to `componentWillReceiveProps`.

With React the situation is flipped almost completely on its head:

1. According to the [React.Component lifecyle documentation](https://reactjs.org/docs/react-component.html#shouldcomponentupdate):

>  In the future React may treat `shouldComponentUpdate()` as a hint rather than a strict directive, and returning `false` may still result in a re-rendering of the component.

2. According to their [Integrating with Other Libraries](https://reactjs.org/docs/integrating-with-other-libraries.html):

> The easiest way to avoid conflicts is to prevent the React component from updating. You can do this by rendering elements that React has no reason to update, like an empty `<div />`.

This seems like a fundamental incompatibility! With preact the DOM will be strictly reconciled *unless* I completely avoid a re-render, whereas with React there's *no way* to prevent re-render but the reconciliation is lax.

I guess I don't need compatibility with both (in this case), but it seems worth pointing out as I can see situations where that would be required and it's unclear what the solution would be. I'm also wondering if I should be aware of any potential changes that Preact X will bring regarding this handling?

**Comment by natevw** [comment]
May be related/dupe of #1250, reviewing.

**Comment by marvinhagemeister** [comment]
@natevw That's a great question! For current `preact` the situation is exactly like you described. We always compare the passed children against the actual DOM and will remove any nodes that are not part of the `vnode` tree.

For Preact X we're in a much better position as we are not diffing against the DOM anymore, but against a second virtual tree. This aligns much better with `react`'s behavior. Just tried the official recommendation from the react docs with `Preact X` and it works as expected :+1: 

Seeing that the X release isn't too far away in the future I'd go with just rendering an empty div with a `ref` on it :)

**Comment by natevw** [comment]
Thanks for the quick reply! (And glad to hear; imo the React way seemed more convenient since it doesn't bypass as much of the normal lifecycle stuff….)
