### ISSUE TITLE
Webpack-dev-server can't serve inner routes with publicPath set

### ISSUE THREAD

**Issue by bendtherules** [developit/preact#1300]
Repoduction: 
I have started a app with preact-cli (default template). Now all the routes (like /profile) are served correctly from dev server (works with page reload).

Then, added publicPath (="/frame") to both output and devServer in webpack config. Also changed the route path and link paths. (See in repo)

Now, on running dev server -
1.  `/frame` serves the main app correctly and client-side routing works from there. 
2. But if we directly hit `/frame/profile`, dev server says can't get page.

Using route path as `<Profile path="/profile/" user="me" />` or `<Profile path="/frame/profile/" user="me" />` didn't help.

Repo: 
https://github.com/bendtherules/preact-publicpath-bug

Edit:
Just to be clear, something like this works with react - so it shouldn't be a problem with dev server itself, but the dev server configurations that we are setting.

**Comment by marvinhagemeister** [comment]
Looks like this is an issue with `preact-cli` and not with `preact` the framework itself. Issues with the CLI should be filed over at the [preact-cli repo](https://github.com/developit/preact-cli).
