### ISSUE TITLE
Hoisted/memoized component VNodes without DOM elements should handle all edge cases with unmounting

### ISSUE THREAD

**Issue by localvoid** [developit/preact#1323]
Preact X: https://codesandbox.io/s/vn9z29096l
React: https://codesandbox.io/s/2xmq294rjj

**Comment by developit** [comment]
Thinking I may have broken this.

**Comment by localvoid** [comment]
I though about this edge case when I saw [this line](https://github.com/developit/preact/blob/2a8ad14756ed570af7db6163ed16b1f627a3fcdd/src/create-element.js#L95), checking for `_component!=null` probably fixes this issue.

**Comment by developit** [comment]
I was staring at it and hadn't yet come to the same conclusion!
