### ISSUE TITLE
Preact-x React Dev Tools bundle issue with __REACT_DEVTOOLS_GLOBAL_HOOK__

### ISSUE THREAD

**Issue by timpur** [developit/preact#1330]
In version `10.0.0-alpha.0` `window.__REACT_DEVTOOLS_GLOBAL_HOOK__` is bundled as `window.t`

this obviously causes devtools to never load

![image](https://user-images.githubusercontent.com/7701482/53802952-4f9fe000-3f97-11e9-86d0-7a9ed2362821.png)

**Comment by marvinhagemeister** [comment]
Good catch! Looks like it is missing from the exclusion list in `mangle.json`
