### ISSUE TITLE
hooks.mjs: TypeError: r is undefined

### ISSUE THREAD

**Issue by weijarz** [developit/preact#1331]
Browser throws TypeError when using hooks

repo: 
https://github.com/weijarz/preact-x-bug-r-is-undefined

**Comment by danieldiekmeier** [comment]
I had a similar issue with Webpack and was able to solve it with the solution in #1321, does that help?

**Comment by faelpinho** [comment]
Any solution for this error?

**Comment by faelpinho** [comment]
In my case, this error occurs when I tryed to using a Context (get or set) in a wrong way.
I just changed to Zustand, and no more problems.

**Comment by rschristian** [comment]
We'd need a reproduction and preferably a new issue (comments in long-closed issues probably won't be addressed).
