### ISSUE TITLE
[Compat] 10.0.0-alpha.0 - Component.prototype.isReactComponent is undefined

### ISSUE THREAD

**Issue by pl12133** [developit/preact#1335]
It looks like the `isReactComponent` property is missing from the new `compat` bundle, so I'm unable to run components that use `react-transition-group` because of the dependency on `react-lifecycles-compat` which will error out if it cannot find a React component:

https://github.com/reactjs/react-lifecycles-compat/blob/f457b78edcf85e44285ce8a840d133917de160da/index.js#L53-L55

Even though `isReactComponent` is not part of the public API it should probably be added back for compat.

To resolve this we could probably copy from the existing `preact-compat`: 

https://github.com/developit/preact-compat/blob/ae018abbefdfeb61a0e0f7a50ac0d7c9f12940ea/src/index.js#L574

**Comment by Sexual** [comment]
Can confirm this is also occurring with `react-virtualized`.
