### ISSUE TITLE
Preact X: Issue with hooks code when running on jest

### ISSUE THREAD

**Issue by armand1m** [developit/preact#1341]
Disclaimer: I am not using preact hooks yet nor react hooks here =)

When trying to render a component in Jest while using `preact@10.0.0-alpha.0` and`preact-render-to-string@^4.1.0`:

```js
/* eslint-env node, jest */

import { h } from "preact"
import { render } from "preact-render-to-string"

import Widget from "./"

describe("Widget Snapshot", () => {
  it("should render", () => {
    const tree = render(<Widget />);
    expect(tree).toMatchSnapshot();
  });
});
```

I got this error:

```
  ● Test suite failed to run

    ReferenceError: MessageChannel is not defined
      at Object.component (node_modules/preact/hooks/src/index.js:199:16)
      at Object.<anonymous> (node_modules/preact/compat/src/index.js:8:45)
      at Object.<anonymous> (node_modules/rebass/dist/Provider.js:12:14)
      at Object.<anonymous> (src/components/Widget/index.tsx:4:1)
      at Object.<anonymous> (src/components/Widget/index.test.tsx:6:1)
```

It seems that running [these lines of code](https://github.com/developit/preact/blob/master/compat/src/index.js#L2~L3):

```js
import * as hooks from 'preact/hooks';
export * from 'preact/hooks';
```

is preparing the hooks environment making calls to the window even though I am not using hooks at all.

- https://github.com/developit/preact/blob/master/hooks/src/index.js#L196~L214

```js
if (typeof window !== 'undefined') {
	mc = new MessageChannel();

	afterPaint = (component) => {
		if (!component._afterPaintQueued && (component._afterPaintQueued = true) && afterPaintEffects.push(component) === 1) {
			requestAnimationFrame(onPaint);
		}
	};

	mc.port2.onmessage = () => {
		afterPaintEffects.forEach(component => {
			component._afterPaintQueued = false;
			if (!component._parentDom) return;
			component.__hooks._pendingEffects.forEach(invokeEffect);
			component.__hooks._pendingEffects = [];
		});
		afterPaintEffects = [];
	};
}
```

## Workaround

Mock `MessageChannel` in jest `setupFilesAfterEnv` hook:

```js
(function mockMessageChannel() {
  const MessageChannel = function () {
    return {
      port1: jest.fn(),
      port2: jest.fn(),
    };
  };

  global.MessageChannel = MessageChannel;
  global.onmessage = jest.fn();
})();
```

**Comment by developit** [comment]
My proposal is that we simplify while fixing this by switching from MessageChannel to setTimeout.

**Comment by JoviDeCroock** [comment]
I'm facing the same issue in testing hooks, only that it behaves really odd when testing it. For example, in React we use `act` exposed by React-dom/test-utils which basically does an batched_update on the body and rerenders.

When trying this with preact it does not seem to update the state in any way.

**Comment by marvinhagemeister** [comment]
@JoviDeCroock our internals are very different from `react`. The way it does batched updates is very specific to them and will never work with `preact`. For `preact` you can swap out the scheduler which has a similar effect as using `act()`.

In our case a batched update is only necessary when you're calling `setState` or `forceUpdate` somewhere in your test. In that case you can just call `render()` and do your test assertions:

```jsx
// render() is always synchronous, no need to wrap it with anything
render(<MyApp />, dom);

// Some assertion
expect(...)
```

We currently use this helper function in our test suite:

https://github.com/developit/preact/blob/cd6f005bceb4b34e33063b8f131d97a62bf55993/test/_util/helpers.js#L18-L27

Usage:

```jsx
// State updates need to be batched via the helper function above
const rerender = setupRerender();

// Trigger setState/forceUpdate somehow
doYourStateUpdate();

// Flush update queue;
rerender();

// do your assertions
expect(...)
```

**Comment by JoviDeCroock** [comment]
Well I have made this now:

````
import '../utils/mockMessageChannel';
import * as React from 'react';
import { act as nativeAct, cleanup, render } from 'react-testing-library';

import { ErrorMessage, Form } from '../../src';
import { setupRerender } from '../utils/setupRerenderPreact';

let act = nativeAct;
if (!act) {
  act = func => {
    func();
    setupRerender();
  };
}
```

It still does not seem to result in anything, func in this case is my hook executing (for example a setState), tryint to test if my react library is compatible with preact atm. So I might not be the ideal scenario to see if this is a bug or not.

**Comment by marvinhagemeister** [comment]
@JoviDeCroock Oh right, I see what you mean now. I misunderstood your first comment. That's something that we should add before our final release. We currently don't ship an equivalent package to `react-dom/test-utils`. Let's continue the discussion here #1353 :+1: 

Closing this issue because #1346 has been merged which swapped out `MessageChannel` with a simple `setTimeout` :+1:
