### ISSUE TITLE
10.0.0-alpha.0 - compat cloneElement ignoring props and children

### ISSUE THREAD

**Issue by dsgh** [developit/preact#1349]
I believe this bug might have originated here: https://github.com/developit/preact/commit/d3c12b7ea3c16f0fa545842ac3bd2b79567e347c

**Comment by marvinhagemeister** [comment]
Can you share some code where the issue can be reproduced? Something like a simple snippet in [CodeSandbox](https://codesandbox.io/) helps tremendously in fixing issues.

**Comment by dsgh** [comment]
@marvinhagemeister Here is a snippet showing a difference between using `cloneElement` from `preact` vs from `preact/compat` https://codesandbox.io/s/34z0lkm6pm

**Comment by marvinhagemeister** [comment]
Ok, I was able to narrow down the issue to using `compat` together with `createElement` from `core`. Because we're only checking for `$$typeof` to mark a vnode as valid it seems like we need to allow standard preact `vnodes`, too. Will investigate further.
