### ISSUE TITLE
jsxPragma is removed in Babel 6

### ISSUE THREAD

**Issue by ratson** [developit/preact#135]
> Using removed Babel 5 option: base.jsxPragma - use the `pragma` option in the `react-jsx` plugin . Check out http://babeljs.io/docs/plugins/transform-react-jsx/

README only refers to "jsxPragma", better to include the Babel 6 instruction.

**Comment by developit** [comment]
@ratson What is giving you this error? Preact is built with Babel 5.

**Comment by ratson** [comment]
I added `{ "jsxPragma": "h" }` to `.babelrc` and I am using Babel 6.

**Comment by developit** [comment]
Added it to the readme.  It was already updated on the [Preact site](https://preactjs.com/guide/getting-started#import-what-you-need) so I just grabbed it from there.
