### ISSUE TITLE
Portal renders `<undefined>` DOM element where `createPortal(...)` is rendered

### ISSUE THREAD

**Issue by robertknight** [developit/preact#1352]
Rendering components into a container outside of the current root DOM element using `createPortal` results in an `<undefined>` DOM element being created at the place where the portal was rendered:

**Test case:** https://codesandbox.io/s/9o0l8rvmyr

**Input HTML and code:**

```html
<body>
  <div id="app"></div>
  <div id="dialog-container"></div>
  <script src="src/index.js"></script>
</body>
```

```js
import { h, render } from 'preact';
import { createPortal } from 'preact/compat';

const appEl = document.querySelector('#app');
const dialogEl = document.querySelector('#dialog-container');

function Dialog() {
  return <div>Dialog content</div>
}

function App() {
  return <div>
    The dialog should be rendered outside the '#app' container.
    {createPortal(<Dialog/>, dialogEl)}
  </div>
}

render(<App/>, appEl);
```

**Rendered HTML with unexpected `<undefined>` element:**

```html
<body>
  <div id="app">
    <div>The dialog should be rendered outside the '#app' container.
      <undefined></undefined>
     </div></div>
     <div id="dialog-container"><div>Dialog content</div></div>
</body>
```

From a quick investigation, it looks as though this has to do with the internal `Portal` component returning a `Component` instance rather than a VNode, which the DOM diffing logic fails to handle: https://github.com/developit/preact/blob/cd6f005bceb4b34e33063b8f131d97a62bf55993/compat/src/index.js#L75

**Comment by robertknight** [comment]
For context, I was looking into whether [react-modal](https://github.com/reactjs/react-modal) could be used with Preact.

To fix this, I think one option is that the `Portal` implementation could return `null`, since nothing should appear in the location where the portal is rendered.

A limitation of the current `Portal` implementation though is that [event bubbling](https://reactjs.org/docs/portals.html#event-bubbling-through-portals) is not currently implemented as far as I can see. If we did want to implement that, perhaps we would need some DOM element rendered in order to capture bubbling events from the portal's container and then re-dispatch them from the place where the portal was rendered?

**Comment by marvinhagemeister** [comment]
Even't bubbling will be a bit tricky, because we don't have a custom event system. It's something we can tackle later if the demand is there :+1:

**Comment by developit** [comment]
Yup - my vote is to get this working without the event bubbling and then document the limitation. Anecdotally, I don't think it's common to actually leverage this type of bubbling in portals.

**Comment by marvinhagemeister** [comment]
@robertknight Thanks for the detailed bug report 🎉 Made a PR with your suggested solution and it works perfectly 👍 #1367
