### ISSUE TITLE
Investigate adding a test-util package

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact#1353]
We've been getting reports of users trying to make Preact work with `react-dom/test-utils`. Problem is that this package relies on a lot of very react-specific internals that prevent it from working with preact. Nonetheless users will need something to flush update queues synchronously so that are easy to test.

Ideas:
- create a `preact/test-utils` package
- make `setupRerender` public
- ship with our own implementation for `act`

**Comment by JoviDeCroock** [comment]
I would love to help with this but I suppose this requires some deep knowledge of the library, I'll try to give it a shot tonight since I've got a use case for it in my own tests.

**Comment by marvinhagemeister** [comment]
Nah, it's mostly about making all scheduling logic synchronous. Search for any `setTimeout/requestAnimationFrame` calls and you should be right at the heart of it :)

This makes `state` updates synchronous: https://github.com/developit/preact/blob/15d4d07d93ff5846e825da4ea81a14fb03327bbd/test/_util/helpers.js#L22

We don't have anything for hooks right now. We likely need a way to patch `afterPaint` in a similar way. https://github.com/developit/preact/blob/15d4d07d93ff5846e825da4ea81a14fb03327bbd/hooks/src/index.js#L207-L210

When available both could be leveraged to implement an `act()` function like react does. If you need any help please ping us. We're pretty active here or on [slack](https://t.co/FM173fEs1W) 💯
