### ISSUE TITLE
The `useEffect` hook with empty array inconsistent with React

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact#1354]
When I define the `useEffect` with an empty array - so it behaves like the `componentDidMount` method - it never gets called;

```js
useEffect(() => {
  // This never gets called...
}, [])
```

I expected the behaviour to be similar like React's hook.

**Comment by marvinhagemeister** [comment]
Thanks for your bug report. This looks like a duplicate of #1328 . Let's continue the discussion over there :+1:
