### ISSUE TITLE
Breaking change of setState()

### ISSUE THREAD

**Issue by 38elements** [developit/preact#1372]
`component.setState()` is not updated.

https://github.com/developit/preact/blob/4f671e7fb99425f84434c0c8b56d830ade4ea792/src/component.js#L55

**Comment by developit** [comment]
Yup - I mentioned this to @marvinhagemeister earlier today. I think we may be working the same way as React's setState() as a result of this change though, so Unistore really needs the update here.

**Comment by marvinhagemeister** [comment]
Here is a [https://codesandbox.io/s/v81rznrm50](codesandbox) of the behaviour in react. They don't do an update when `setState` is called without any arguments.

**Comment by 38elements** [comment]
I think it is better to documented to this change.
https://github.com/developit/preact/releases/tag/10.0.0-alpha.0

**Comment by marvinhagemeister** [comment]
Fair point! I've just added it to the release notes :+1:
