### ISSUE TITLE
Error when using a React.PureComponent in PreactX Alpha 01

### ISSUE THREAD

**Issue by janbaer** [developit/preact#1382]
I just migrated my project to the newest version of Preact and in my Project I use one React component , but whenever the view which contains the React component. The view is part of a page but it will not be rendered when the page will be rendered first. It'll be rendered when the user is switching into the edit mode of the page. The component I use is **react-simplemde-editor** and it's a PureComponent.

The error I get is the following:

```
Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at new SimpleMDEEditor (index.tsx:61)
    at _ (index.js:69)
    at d (children.js:74)
    at A (index.js:263)
    at _ (index.js:154)
    at _ (index.js:140)
    at d (children.js:74)
    at A (index.js:263)
    at _ (index.js:154)
    at d (children.js:74)
```

It happens in the SimpleMDEditor when the state will be initialized because props is undefined.

```
value: this.props.value || ""
```

The props will be passed in the index.js in line 69

```
if (newType.prototype && newType.prototype.render) {
   newVNode._component = c = new newType(newVNode.props, cctx); // eslint-disable-line new-cap
}
```

I think this code comes from Preact.

What I changed as part of the migration is to change the reference for the aliases for **react** and **react-dom** in this way.

```
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  }
```

Before the migration to PreactX it was running fine.

**Comment by marvinhagemeister** [comment]
Thanks for the bug report 👍 Do you have a look to a repo or a [code sandbox](https://codesandbox.io) where the error is visible? It helps us tremendously in making a fix 🙂

**Comment by janbaer** [comment]
The repo you can find here https://github.com/janbaer/mdwiki

Do you have any prepared CodeSandbox where Preact compat is preconfigured to be able to use React components inside. It would make it easier for me to try to reproduce it there. Thanks.

**Comment by marvinhagemeister** [comment]
Awesome thanks for the link :+1: :tada: With it I was able to reproduce the error and narrow it down to what was causing it. Submitted a PR #1384 with the fix :+1: 

That's a good question! According to [this issue](https://github.com/CompuIves/codesandbox-client/issues/467) aliasing should be possible via an `alias` property in `package.json`. Apart from that the preact template should set up an alias for `react` by default. That likely hasn't been updated for Preact X yet.

In either case a repo link, like you did works fine too! As long as we have something where we can poke a round and see the same error, we're all good :+1: 

Thanks again for your report and helping in making Preact X more stable than ever :100:

**Comment by janbaer** [comment]
Great! Thanks! I'm very impressed about how quick you could reproduce and also fix the bug! Will test it again, with the next alpha version, when the PR is merged!
