### ISSUE TITLE
Typings: label's for change to htmlFor

### ISSUE THREAD

**Issue by ohute-couture** [developit/preact#1389]
Hi, I have a question. 
Of the attributes of the label, the `for` was changed to `htmlFor` the same as React. https://github.com/developit/preact/pull/695 (2018.03.04)
However, when defining the type of jsx file, it is changed back to `for`. https://github.com/developit/preact/commit/f91d5e1a268b31a8c07d6ddc83ac30e83a30bd27#diff-70083611527b9d7d728e1e14dd8f977fR518 (2018.09.02)
How about changing to `htmlFor`?

**Comment by marvinhagemeister** [comment]
Good catch! This is something that got lost when merging the Preact X repo into the public one here.
