### ISSUE TITLE
10.0.0-alpha.1 - Can't reexport the named export 'Component' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by fc** [developit/preact#1399]
Temporarily fixing it by adding this to the rules section of webpack:

```
{
  type: 'javascript/auto',
  test: /\.mjs$/,
  use: []
}
```

**Comment by JoviDeCroock** [comment]
Hey, have you tried this plugin: https://www.npmjs.com/package/webpack-modules

I had an issue with preact aswell and that's because webpack treats .mjs in an odd way

**Comment by marvinhagemeister** [comment]
yup @JoviDeCroock is right on the money. Webpack doesn't resolve `.mjs` ignores the resolution files specified in `package.json` for some reason. This breaks module resolution leading to the mentioned error. The linked webpack plugin will fix webpack for you.

We're tracking this in #1321 . Let's continue the discussion there :+1:
