### ISSUE TITLE
10.0.0-alpha.1 - Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by fc** [developit/preact#1400]
I'm trying to convert an existing project to Preact and get this error.

If I understand the error correctly based on what I've read on Google, it's because there is a version mismatch.  Apparently it can happen when someone is trying to run both React 15 and React 16... but in this case it might be that ReactCurrentOwner simply isn't being passed down?..

I have a library I have created that is generating this error.

The purpose of `ReactCurrentOwner` is:
> The current owner is the component who should own any components that are currently being constructed.
https://github.com/facebook/react/blob/19ef0ec116a2c5fd1a8dc86d38c2185d62abc6a1/packages/react/src/ReactCurrentOwner.js

**Comment by marvinhagemeister** [comment]
@fc Do you have a repository or a link to a [codesandbox](https://codesandbox.io) where the issue can be reproduced? This helps us tremendously in getting to the bottom of this and making a fix. The error likely occurs in a specific third-party library.

**Comment by fc** [comment]
Unfortunately this is in a work project and there is some complexity in creating a test case since I'm not 100% sure where the error is coming from since the error/stack trace is pretty vague.  I also will be removing the dependency that is causing this error.  So... you can close maybe? or leave it open in case someone else runs into the issue?

**Comment by marvinhagemeister** [comment]
@fc what dependency is causing the error? If it's something that's on npm we can take a look at it👍

**Comment by fc** [comment]
No it's an internal dependency.. a project I created.

**Comment by marvinhagemeister** [comment]
Alright, looks like there is nothing actionable we can do. We'll reopen it in case somebody runs into the same issue. Feel free to ping us :)

**Comment by IgnusG** [comment]
@marvinhagemeister I've just ran into this issue with a library wrapper I've created https://github.com/IgnusG/react-shepherd-steroids and wanted to use inside of my preact code-base

I've built it with the new react-jsx active - so maybe that's an issue?

> Preact: 10.4.6
