### ISSUE TITLE
10.0.0-alpha.1 - The callback argument to setState errors when used in a constructor

### ISSUE THREAD

**Issue by litonico** [developit/preact#1402]
Repro:
https://codesandbox.io/s/ppmor1k9lq

Expected behavior:
Inside the constructor, calling `setState` with a callback as the **second** argument calls the callback after the state change.

Actual behavior:
Providing a callback as the second argument causes an error in Preact, but **only** when provided in the constructor.

The error is:
```
TypeError
Cannot read property 'push' of undefined
```

Notes:
`setState()` without the callback works as expected whether or not it's called from the constructor. Usually, calling setState wouldn't make sense in a constructor — just assigning to state directly would cover things. The case that's occurring in our app is that there's a 'reset' button that does other setup and then calls `setState`.

**Comment by marvinhagemeister** [comment]
@litonico Thanks for the repro sandbox. It's great to show what's happening. Calling `setState` inside the constructor doesn't make sense, as you said.

React just ignores any calls to `setState` there [codesandbox](https://codesandbox.io/s/jpwxko9wnw), so the callback will never be called. The `setState` call is effectively treated as a no-op.

To be honest, I don't see us ever supporting calling `setState` inside the constructor. In all cases we've seen so far this can be solved by assigning to `this.state` directly or triggering the initialization code in `componentDidMount`.

Can you share some code that show why calling `setState` inside the constructor is necessary? Maybe we can come up with a different solution here.

**Comment by developit** [comment]
I've occasionally ended up doing setState in the constructor as a result of calling a generic "update state from props" method. We could guard against this by checking for the existence of `this._vnode`. If it's missing, skip enqueing a render and don't call the callback.
