### ISSUE TITLE
10.0.0-alpha.1 - Passing tagName as a (redundant) prop to an HTML node causes an error

### ISSUE THREAD

**Issue by MaxPower15** [developit/preact#1404]
Passing `tagName` as a prop like:

```js
export default function () {
  return <button tagName='button' />
};
```

Will result in an error like:

```
E-v1.js:formatted:10882 Uncaught (in promise) TypeError: Cannot assign to read only property 'tagName' of object '#<HTMLButtonElement>'
    at w (E-v1.js:formatted:10882)
    at g (E-v1.js:formatted:10859)
    at A (E-v1.js:formatted:10999)
    at _ (E-v1.js:formatted:10953)
    at _ (E-v1.js:formatted:10948)
    at _ (E-v1.js:formatted:10948)
    at d (E-v1.js:formatted:10816)
    at A (E-v1.js:formatted:11001)
    at _ (E-v1.js:formatted:10953)
    at _ (E-v1.js:formatted:10948)
```

I noticed this because I have a (sloppy but allowed) pattern in a couple places where we have custom elements (not shown in example), and specify tagName like so:

```js
class CustomElement extends Component {
  render () {
    const TagName = this.props.tagName;
    return <TagName {...this.props} />;
  }
}
render(<CustomElement tagName='button' class='the-class'>...</CustomElement>, parentEl);
```

To accommodate this, I need to explicitly remove `tagName` from props before passing it down. This can be solved like `const propsToPass = Object.assign({}, this.props); delete propsToPass.tagName`, but it's not a convenient pattern. Still, I think it might still be okay to leave it as is, as long as it's mentioned as a breaking change. Thoughts?

**Comment by JoviDeCroock** [comment]
Well my first thought would be you can solve this much shorter like this:

```
  render () {
    const { TagName, ...props } = this.props;
    return <TagName {...props} />;
  }
```

**Comment by MaxPower15** [comment]
I think I need to update my webpack config to support object rest like that, but point taken. 😄 

On the lib side, I kinda agree, and in the spirit of keeping things small for preact, I agree that it could prob be left to the consumer. I guess it might just be worth flagging this for a look since, if there are no special checks, then there may be other footguns like this that didn't exist before. This particular issue is the kind of thing that I expect to see mild pain for upgrades and almost no pain for new usage.

**Comment by marvinhagemeister** [comment]
This is probably fixed with #1377 . My guess is that our minifier turned `this._force` into `this.t` because we set that to `false` on each state update.

**Comment by JoviDeCroock** [comment]
> This is probably fixed with #1377 . My guess is that our minifier turned `this._force` into `this.t` because we set that to `false` on each state update.

Isn't this meant for the other issue? :D

**Comment by marvinhagemeister** [comment]
@JoviDeCroock you're right, I messed up and linked the wrong issue :man_facepalming:

**Comment by JoviDeCroock** [comment]
We could introduce a `delete tagName` before we stick everything to the native node but that decision is not up to me
