### ISSUE TITLE
Preact X Browser support

### ISSUE THREAD

**Issue by cloudkite** [developit/preact#1408]
Nice work on Preact X ❤️! Are there any guidelines on what browser versions Preact X will support? is the intention to support IE9+ like previous Preact versions?

**Comment by JoviDeCroock** [comment]
In the readme: https://github.com/developit/preact#preact

the browser support is shown

**Comment by developit** [comment]
I believe as of the next release Preact core supports IE9+ once again (courtesy of #1395).

**Comment by marvinhagemeister** [comment]
We should summon @StoneCypher for that. He may even get it to work in older versions of IE<9 :+1:
