### ISSUE TITLE
dangerouslySetInnerHTML doesn't work on SVG tag

### ISSUE THREAD

**Issue by fdaciuk** [developit/preact#141]
Hey @developit! 

This property should work on svg tags, isn't?

I'm trying to use it to generate SVG sprites:

```js
const SvgIcon = ({ id, label }) => {
  const props = {
    className: 'icon',
    'aria-hidden': true,
    'aria-label': label,
    dangerouslySetInnerHTML: {
      __html: `<use xlink:href="/svg/icons.svg#${id}" />`
    }
  }

  return <svg {...props} />
}
```

But `use` tag is not being inserted inside of `svg` :(

**Comment by developit** [comment]
@fdaciuk - if you swap `<svg>` for `<SVG>` where SVG is `import SVG from 'preact-svg';` the code you posted should work.

**Comment by developit** [comment]
(Or I'm totally wrong, in which case let me know and let's fix it :)

**Comment by fdaciuk** [comment]
I tried using `preact-svg` =)
The `use` tag is inserted, but the icon is not shown. I have the same problem with React.

Adding svg tag manually (via dev tools), it works =/
And I don't know why :joy:

**Comment by fdaciuk** [comment]
If I try to use something like:

```js
const SvgIcon = ({ id, label }) => {
  const props = {
    className: 'icon',
    'aria-hidden': true,
    'aria-label': label,
  }

  const useProps = {
    'xlink:href': `/svg/icons.svg#${id}`
  }

  return (
    <SVG {...props}>
      <use {...useProps} />
    </SVG>
  )
}
```

Using default `svg` tag or using `preact-svg`, the `use` tag is inserted inside `svg`, but the icon is not shown.

**Comment by developit** [comment]
Might be something to do with setAttributeNS?

**Comment by developit** [comment]
Need to try detecting colons in attributes within preact-svg and applying them via *NS

**Comment by fdaciuk** [comment]
I don't know :(
How can I use `setAttributeNS` with preact? Inside `componentDidMount`?

**Comment by developit** [comment]
Ideally preact-svg should handle it for us. It already shims attributes, so it should pick the method too.

**Comment by fdaciuk** [comment]
Understood. I tried one more time with React, using `xlinkHref` instead `xlink:href` and it works xD

**Comment by developit** [comment]
Ah okay so this is sort of a dupe of developit/preact-svg#15. On my to-do list!

**Comment by fdaciuk** [comment]
Very nice! :heart_eyes: I'll waiting for it =)
