### ISSUE TITLE
Typo in release note

### ISSUE THREAD

**Issue by 38elements** [developit/preact#1411]
> These testing utilities are inspired by the excellent react/test-utils tools and share a similar act() function :+1: 

https://github.com/developit/preact/releases/tag/10.0.0-alpha.2

I think `react-dom/test-utils`, not `react/test-utils`, is correct.

https://reactjs.org/docs/test-utils.html

**Comment by marvinhagemeister** [comment]
Good catch! Just updated the notes. Thanks for reporting :+1:
