### ISSUE TITLE
10.0.0-alpha.2 - React Developer Tools not active

### ISSUE THREAD

**Issue by janbaer** [developit/preact#1413]
I use Preact in two of my private projects together with Parcel.js as module bundler. In the last stable version I just had to import 'preact/devtools' in my index.js where the first render function from Preact will be called and then I could use to React Developer Tools too see my current context. Since Preact X this import is no longer available and I had to remove it. I just read in the release notes that the developer tools git a complete rewrite and the support for the Developer Tools was improved. But in both of my projects, the  Developer tools are not active and when I click on the Developer Tools icon, I get only "This page doesn’t appear to be using React."

So my question is what do I have todo to make the Developer tools usable in my project? Maybe it should work out of the box with Preact X but then I would like to know how I could find out, why it's not active in my projects.

The package.json where all the additional config for is made can be found here: https://github.com/janbaer/mdwiki/tree/feature/migration_to_preactx. But thanks to parcel.js there's not so much to configure additionally.

**Comment by Kanaye** [comment]
Hi @janbaer 
Just import `preact/debug` where you previously included `preact/devtools` and the react devtools will start working again.

**Comment by janbaer** [comment]
Thanks @Kanaye, works great. It should be mentioned in the release notes.

**Comment by marvinhagemeister** [comment]
I'll reopen this until we've added it to the notes 👍

**Comment by marvinhagemeister** [comment]
Back home again and I added a section about that to our release notes :+1: Thanks again for spotting this :)
