### ISSUE TITLE
default import not working

### ISSUE THREAD

**Issue by Akiyamka** [developit/preact#1414]
Next code from [Getting started guide](https://preactjs.com/guide/getting-started) will crush
```js
import preact from 'preact';

console.log(preact) // undefined

preact.render((
    <div id="foo">
        <span>Hello, world!</span>
    </div>
), document.body);
```
I see in console next warn and error
`Cannot read property 'render' of undefined`
`"export 'default' (imported as 'preact') was not found in 'preact'`

For fix i use next workaround:
```
import * as { preact } from 'preact';
```
If that expected behavior - please fix this example in manual.

My env:
```
preact: "10.0.0-alpha.2"
webpack: "4.29.6"
@babel/core: "7.3.4"
node: "v11.10.1"
yarn: "1.13.0"
```

**Comment by JoviDeCroock** [comment]
That's right, I don't think there is a default export in the regular preact package at this point. However there is one in the Preact/Compat one.

**Comment by marvinhagemeister** [comment]
yup, that's correct. We don't have a `default` export in core anymore. See the "Breaking Changes" section in the [release notes](https://github.com/developit/preact/releases/tag/10.0.0-alpha.0) for more information.
