### ISSUE TITLE
10.0.0-alpha.2 - useEffect bug - repeating execution

### ISSUE THREAD

**Issue by didymu5** [developit/preact#1427]
Hello, I'm not sure what's going on but I'm using useEffect hook to fetch some data. 

https://codesandbox.io/s/4r786j87

It seems as though the useEffect executing the call.

**Comment by didymu5** [comment]
I think this fixes my issue: https://stackoverflow.com/questions/53070970/infinite-loop-in-useeffect

**Comment by didymu5** [comment]
I passed in a 2nd parameter to useEffect()

**Comment by marvinhagemeister** [comment]
What's the actual issue? I just put the code into a [react sandbox](https://codesandbox.io/s/7392j7lmjq) and I can't see any difference between the preact version. Can you elaborate on the issue you're running into?

**Comment by didymu5** [comment]
I had fixed my sandbox example, I forgot to added a send parameter to useEffect.

**Comment by didymu5** [comment]
thanks @marvinhagemeister
