### ISSUE TITLE
Stateful functions

### ISSUE THREAD

**Issue by exebook** [developit/preact#1470]
This sounds exciting:

https://github.com/reactjs/react-future/blob/master/07%20-%20Returning%20State/01%20-%20Stateful%20Functions.js

I do not even know if React already supports it (or will ever be), but I want it in Preact!

**Comment by marvinhagemeister** [comment]
This was one of the earlier ideas that floated around and were later in-cooperated into what's known as `hooks` today. See the exmaple in the hooks section on the [release announcement for Preact X](https://github.com/developit/preact/releases/tag/10.0.0-alpha.0) or the react documentation for a [deep dive](https://reactjs.org/docs/hooks-intro.html) into hooks :tada:
