### ISSUE TITLE
Preact crashes when trying to access children property when rendering

### ISSUE THREAD

**Issue by BlackHoleFox** [developit/preact#1476]
Preact Version: 10-alpha.2

In a project im working on, Preact seems to be crashing when it tries to render because of a undefined error related to something its doing internally. Using TypeScript 3.3.4 with ts-loader, along with preact-cli.

Im trying to wait for data to come through a socket, update the state with the data, and then re-render the page with the new data.

Here's the error that appears in Chrome's console:
```console
debug.js?c91e:84 Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at p (debug.js?c91e:84)
    at Object.preact__WEBPACK_IMPORTED_MODULE_1__.options.diff (debug.js?c91e:11)
    at x (index.js?c988:34)
    at b (children.js?b0ec:57)
    at C (index.js?c988:261)
    at x (index.js?c988:152)
    at b (children.js?b0ec:57)
    at C (index.js?c988:261)
    at x (index.js?c988:152)
    at b (children.js?b0ec:57)
```

The source for the page can be found here: https://github.com/AEnterprise/GearBot/blob/secrets/web/src/components/guildpage.tsx

Any help would be greatly appreciated.

**Comment by marvinhagemeister** [comment]
@BlackHoleFox Can you share an example of a backend response? I got the frontend working but I'm unable to start the backend server.

**Comment by BlackHoleFox** [comment]
Sure, this is the JSON data that the backend is currently sending up through the socket (Python):
```json
guildPageData = {
            "name": "The Gearbox",
            "owner": "AEnterprise",
            "id": 365498559174410241,
            "members": 127,
            "textChannels": 22,
            "voiceChannels": 1,
            "totalChannels": 23,
            "creationDate": "05-10-2017 (538 days ago)",
            "vipFeatures": False,
            "serverIcon": "https://cdn.discordapp.com/icons/365498559174410241/735df5f0db5581592b7744f8fc10701f.webp?size=1024",
            "roles": [
                "Gear Spinners",
                "Gear Creators",
                "Amazing Gears"
            ],
            "serverEmojiCount": 51,
            "memberStatuses": {
                "online": 11,
                "idle": 10,
                "dnd": 10,
                "offline": 96
            }
        }
```

**Comment by marvinhagemeister** [comment]
The issue is caused by passing a random object into the template. Preact tries to render it but fails to do so, because it isn't a valid `vnode`.

```jsx
<tr>
  Member Statuses: {this.state.guildPageStats.memberStatuses}
</tr>
```

Where `memberStatus` equals:

```
{
  online: 11,
  idle: 10,
  dnd: 10,
  offline: 96
}
```

The above is not a valid `vnode`. One solution would be to pass the properties individually:

```jsx
const status = this.state.guildPageStats.memberStatuses;
<tr>
  Member Statuses:
  online: {status.online}
  idle: {status.idle}
  dnd: {status.dnd}
  offline: {status.offline}
</tr>
```

That resolves the issue.

Note: The html in that component is not quite valid. A `<td>` (=**t**able **d**ata cell) must include a `<tr>` (=**t**able **r**ow) element as its children. Per spec it must be the other way round :wink: 

```html
<!-- this is INVALID -->
<td>
  <tr>foo</tr>
</td>

<!-- this is VALID -->
<tr>
  <td>foo</td>
</tr>
```

**Comment by BlackHoleFox** [comment]
@marvinhagemeister Thanks for the quick response. Good to know in the future that I can't just toss whatever into Preact. With your method, its working fine now. I have also fixed the tables to fall into spec, the pointer is appreciated :)
