### ISSUE TITLE
Typescript: If an event handler whose event type is MouseEvent|TouchEvent, how do you get it to not throw errors if one of them does not have a certain property?

### ISSUE THREAD

**Issue by TimeDropsDream** [developit/preact#1479]
Using Preact 8.4.2.

Example: 
```ts
handleDragStart = (e: MouseEvent|TouchEvent) => {
   const val = e.constructor.name === "TouchEvent" ? e.touches[0].pageX : e.pageX;
};
```

In the above, an error is thrown for `e.touches[0].pageX`:
```
Property 'touches' does not exist on type 'MouseEvent|TouchEvent'. 
Property 'touches' does not exist on type 'MouseEvent'.
```

and for `e.pageX`:

```
Property 'pageX' does not exist on type 'MouseEvent|TouchEvent'. 
Property 'pageX' does not exist on type 'TouchEvent'.
```

In React, you can use `event.nativeEvent` to remove this error (see [Stackoverflow answer](https://stackoverflow.com/questions/54688147/react-typescript-event-type-for-both-interfaces-mouseevent-and-touchevent)) but no such thing exists in Preact.

What would you do in Preact to get the equivalent behavior?

**Comment by ForsakenHarmony** [comment]
yes we don't have `event.nativeEvent` because `event` is `event.nativeEvent` 👀

**Comment by marvinhagemeister** [comment]
In Preact the event itself **is** the native event. We don't ship a custom event system like react does.

```jsx
handleDragStart = (e: MouseEvent|TouchEvent) => {
  if (e instanceof TouchEvent) {
    // I'm a touch event
  } else {
    // I'm not a TouchEvent
  }
};
```

**Comment by TimeDropsDream** [comment]
Oh duh!  I completely forgot Preact doesn't use Synthetic Events.  I should read the docs again more carefully.

Thanks so much!

**Comment by ForsakenHarmony** [comment]
Also if you're sure it exists, you can tell typescript by using `e.touches[0].page!`, but you won't need that
