### ISSUE TITLE
[10.0.0-alpha.2] - rendering certain styles broken in IE9

### ISSUE THREAD

**Issue by cloudkite** [developit/preact#1482]
I was trying out PreactX on a project where I need to support IE9 😓.

IE9 throws an "Invalid Argument" error when PreactX calls `style.setProperty(key, value)`
as IE9 is very pendantic about what values it accepts.

The project works in Preact8 after some digging it looks like this is because it uses `style[key] = value` instead. This appears to behaves differently in IE9, it ignores properties it doesn't support. However when using setProperty IE9 will throw an error if the value is not supported.

For example the following throws an error in PreactX on IE9

```
<div style={{
zIndex: 100,
background: 'radial-gradient(at left bottom, rgba(0, 0, 0, 0.18) 0px, rgba(0, 0, 0, 0) 70%)'
}}>hello</div>
```

Was the switch to setProperty in order to support css vars?

**Comment by marvinhagemeister** [comment]
Yeah we switched to `setProperty` to support CSS Custom Properties, on top of that it's slightly faster than setting properties on the `style` object. I'm not sure what a good solution would be to support IE9 without adding unnecessary code. We officially only support IE11 and newer with Preact X, but where happy to accept PRs that add support for older browsers when they don't add too much to our size :tada:

**Comment by developit** [comment]
It should be possible to fix this per-project by patching CSSStyleDeclaration.prototype.setProperty() so that it swallows errors.

**Comment by cloudkite** [comment]
@developit, @marvinhagemeister thanks for the reply ❤️

would you accept a PR which does a check similar to the following:
https://github.com/facebook/react/blob/21d5f7d32d5becf5c8e986ff0202059be643dc15/packages/react-dom/src/shared/CSSPropertyOperations.js#L79

Totally understand if its a non-goal to support IE9 I'm happy to keep a fork for my own purposes or attempt monkey patching `CSSStyleDeclaration.prototype.setProperty`. Thanks

**Comment by cloudkite** [comment]
@marvinhagemeister, @developit I thought of something that could be broken (apart from not supporting IE9) due to the change to use setProperty.

setProperty requires the priority to be sent as a seperate argument so the following won't work anymore in PreactX?

```
<div style={{ background: 'red !important' }}>
```
