### ISSUE TITLE
[10.0.0-alpha.2] context component type error

### ISSUE THREAD

**Issue by AEnterprise** [developit/preact#1485]
i'm trying to use the context api to provide a firebase context to the entire app, but this is causing rendering to fail

![image](https://user-images.githubusercontent.com/5206666/55275042-5b559c80-52e0-11e9-9d76-259cad06dd5e.png)

error is on the ``<FirebaseContext.Provider value={new Firebase()}>`` line, repro case: https://gist.github.com/AEnterprise/7319775bd4ef6be86ff31bce40c55ee1

**Comment by JoviDeCroock** [comment]
Hmm, could it be something more specific to just your use case? I have no firebase key https://codesandbox.io/s/m9onljwrnx so I can't really test that part but if there's an error it should be located there or in your `<App />` component.

**Comment by AEnterprise** [comment]
i don't know, but here is my app component: https://gist.github.com/AEnterprise/e38e78764e89605f76473d7d6add80cd

but chrome dev tools do point at that line, or is that cause it's all one instruction? not sure how smart that thing is for that


![image](https://user-images.githubusercontent.com/5206666/55281663-004f9400-5338-11e9-8646-efe92dca8ebf.png)

replacing it with just a regular div with text in it doesn't fix the problem either so i don't think that the problem is there: 
![image](https://user-images.githubusercontent.com/5206666/55281678-312fc900-5338-11e9-9269-6be53b329e21.png)

**Comment by JoviDeCroock** [comment]
Does this happen on initial render? I'm going to try and reproduce this crash in my sandbox a bit more then

**Comment by AEnterprise** [comment]
yes this is on the initial render

i'm made a clone of my project, made a blank firebase project and put them in the env (the tokens to connect aren't private, cause they will be in the JS code anyways but i don't like random people being able to mess around in my dev project as i don't have security rules on the database and such yet)

might help with reproducing the problem

[preact-test.zip](https://github.com/developit/preact/files/3026393/preact-test.zip)

**Comment by JoviDeCroock** [comment]
Thank you very much for this repro.

The issue is not located in preact, it is because this line: 

```render(<FirebaseContext.Provider value={new Firebase()}>
        <div>test</div>
    </FirebaseContext.Provider>,
    document.getElementById('root'),
);
```

Tries to write to an element that does not exist, you have no div with id="root"

**Comment by AEnterprise** [comment]
thanks a lot! that was indeed the issue, sorry for wasting your time for something so stupid

also this is using preact X, i was running into other problems (like mapbox not working) with the stable release

**Comment by JoviDeCroock** [comment]
No problem @AEnterprise 

No need to excuse yourself it are bugs like these that help us see where we can improve in terms of Developer Experience.

This issue has been taken up in: https://github.com/developit/preact/pull/1487, so thank you for taking your time to submit an issue.
