### ISSUE TITLE
render 0 value

### ISSUE THREAD

**Issue by aeosynth** [developit/preact#149]
<input value={0}/>

the above does not render the zero, i assume because preact is treating it as undefined. i would like the zero rendered.

**Comment by developit** [comment]
Thanks for the report. How are you checking the rendered value?

**Comment by aeosynth** [comment]
just viewing it in the browser

**Comment by aeosynth** [comment]
jsfiddle: http://jsfiddle.net/eh0f7hc5/

**Comment by developit** [comment]
Perfect, I'll get this fixed ASAP.

**Comment by developit** [comment]
Confirmed fix coming shortly.

**Comment by developit** [comment]
@aeosynth I've released this under the beta tag: `npm i -S preact@beta`

**Comment by aeosynth** [comment]
works great, thanks. will you push this to master soon?

**Comment by developit** [comment]
It will graduate from beta once the other 3 fixes are confirmed.

On Sat, May 21, 2016, 12:37 PM James Campos <notifications@github.com>
wrote:

> Closed #149 <https://github.com/developit/preact/issues/149>.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/developit/preact/issues/149#event-667996355>
>
-- 

- Jason

**Comment by aeosynth** [comment]
i meant, will you push the beta. current master is still on 4.8

**Comment by developit** [comment]
Sorry, the commits are on master but not the version bump.

**Comment by developit** [comment]
@aeosynth pushed. I had the wrong remote set up, so the changes never actually got pushed to Github, haha.
