### ISSUE TITLE
[10.0.0-alpha.2] e.persist() errors in library dependency after Preact X upgrade

### ISSUE THREAD

**Issue by jessicabyrne** [developit/preact#1497]
## The Problem
With the upgrade to Preact X, suddenly [our react-day-picker](https://github.com/gpbl/react-day-picker) stopped working. It throws an error `Uncaught TypeError: e.persist is not a function`.

## One Fix
It's easy to fix directly in the library, so I've opened up a PR there to change e.persist() to `if (e.persist) { e.persist() } ` ( though `e.persist = () => {}` would work as well. )
[The PR](https://github.com/gpbl/react-day-picker/pull/888)

## The Ask
However, I am wondering what about Preact X would have changed the support here, and if this is already addressed in a preact-compat library or plugin of some sort. 

## Background for Preact
I'm aware of this:
https://github.com/developit/preact/wiki/Differences-to-React
```
Synthetic Events: Preact's browser support target does not require this extra overhead.

    A full events implementation would mean more maintenance and performance concerns, and a larger API.
```
but the day-picker used to work before the upgrade, so maybe I'm missing some context here.

**Comment by JoviDeCroock** [comment]
This should be fixed with my PR, thank you so much for taking your time to report this issue.

We will be providing the correct fallback (a func) for .persist
