### ISSUE TITLE
Circular dependency in latest build

### ISSUE THREAD

**Issue by van-nguyen** [developit/preact#1507]
```
Circular dependency: src/diff/index.js -> src/component.js -> src/diff/index.js
Circular dependency: src/diff/index.js -> src/diff/children.js -> src/diff/index.js
```

Not sure if this will cause any problems?

**Comment by marvinhagemeister** [comment]
This warning won't cause any problems, so nothing to worry about. Rollup correctly bundles both files together at which point the circular reference is gone :+1: 

The only option to prevent this warning would likely be to inline the code from `src/component.js` into `src/diff/index.js`. Not sure how I feel about that as it would make it only bigger.

**Comment by leeoniya** [comment]
> The only option to prevent this warning would likely be

better: https://github.com/rollup/rollup/issues/2271#issuecomment-475540827

**Comment by marvinhagemeister** [comment]
@leeoniya Nice! So we could at least opt-out of those warnings. Pinging @ForsakenHarmony and @lukeed who work on our build-system. Maybe you two can chime in? I'm not sure if that would be a good thing to have in `microbundle` by default.

**Comment by ForsakenHarmony** [comment]
Probably not the best as a default, sometimes it's unintended
