### ISSUE TITLE
[10] How to use compat with preact@10

### ISSUE THREAD

**Issue by chpio** [developit/preact#1514]
Hi,

there is no `preact-compat@4` on npm, but it get's released under `preact@10` as `preact/compat`. So the right way to use compat now is to replace the old `preact-compat` with `preact/compat` and remove the `preact-compat` dependency?

If that's true, then it should be documented in the README and the README shouldn't just link to the "outdated" (from the point of view of preact@10) `preact-compat` repo.

**Comment by JoviDeCroock** [comment]
At this point Preact X is in alpha so updating the docs would be a bit premature. Your assumption is right preact-compat is getting replaced with preact/compat.

**Comment by marvinhagemeister** [comment]
Agree that updating the README right now would only lead to confusion. We should do that when we're going gold 👍
