### ISSUE TITLE
forwardRef in Preact

### ISSUE THREAD

**Issue by elaineleeworld** [developit/preact#1521]
I have a Sidebar component with number images.  I have in my App.js sections of a webpage.  I would like to click the number image to scroll to that section of my webpage. For example, I click on number image 5, webpage scrolls to section 5.  

The onclick action is in my Sidebar component.  And I imported the Sidebar component into App.js.  I created refs in my App.js. How do I access the parent's refs?

**Comment by JoviDeCroock** [comment]
Preacr/compat has forwardRef and in normal preact you can pass it through to your Child in props.

**Comment by marvinhagemeister** [comment]
To elaborate on that a bit: We decided to put `forwardRef` into `preact/compat` instead of our core because in the future `forwardRef` will likely not be needed anymore. The reason it exists is because virtual-dom libraries filter out the `ref` from `props` when a Component is created. If it would be left on `props` we could just use that.

It would effectively change the current situation from this:

```jsx
import { h } from "preact";
import { forwardRef } from "preact/compat";

// Some high-order component
function withLog(Wrapped) {
  return forwardRef((props, ref) => {
    return (
      <Foo>
        <Bar>
          <Wrapped {...props} ref={ref} />
        </Bar>
      </Foo>
    );
  };
}
```

to this:

```jsx
// not possible today, but hopefully soon
import { h } from "preact";

// Some high-order component
function withLog(Wrapped) {
  return props => (
    <Foo>
      <Bar>
        <Wrapped {...props} />
      </Bar>
    </Foo>
  )};
}
```

which is a lot shorter and easier to understand. We're hoping that we can tackle the latter after Preact X went gold. For now the former snippet is the way to go :+1:

**Comment by elaineleeworld** [comment]
Thank you both for your quick response! This was very helpful! :)

**Comment by heymartinadams** [comment]
@marvinhagemeister, would the former example still work with Preact X?

**Comment by marvinhagemeister** [comment]
Yup, the former snippet is still the way to go for now. The changes to `createElement` haven't progressed past a proposal yet.

**Comment by rubencodes** [comment]
👋  Hi there! Wondering if there's any update on this—does ref behave as a normal prop now, or are we still forced to use `forwardRef`? Thanks!

**Comment by developit** [comment]
@rubencodes still forwardRef - I don't believe we're even able to land automatic ref forwarding in Preact 11, it'll likely come later (it causes a bunch of compatibility issues because `context` is already the second parameter to a function component).

**Comment by rejhgadellaa** [comment]
Could it be worth adding `forwardRef()` to core as removing the need for it has been on the roadmap for ~5 yrs now, and we don't know when (and if?) it will land?

I don't want to sound snarky, just it's been a while, and would be great to be able to use forwarded refs without importing the full compat package / side effects?

**Comment by cztomsik** [comment]
FYI you can use useId() as workaround in the meantime.
https://preactjs.com/guide/v10/hooks/#useid

**Comment by rejhgadellaa** [comment]
@cztomsik could you share a code snippet on how `useId()` would replace the need for `forwardRef` for hocs? Thanks!

**Comment by cztomsik** [comment]
It is not replacement for `forwardRef()` but it can be used instead of `useRef()` and `<Foo ref={ref}`:

```
const id = useId()

useEffect(() => {
  // instead of ref.current
  const el = document.getElementById(id)
   ...
}, [])

return <Foo id={id} ... />
```

and it should work as long as `<Foo` does spread rest of props into the element.

**Comment by bz2** [comment]
The change to drop the need for `forwardRef` does seem to have been landed on the (currently beta) v11 branch here: https://github.com/preactjs/preact/pull/4658
