### ISSUE TITLE
Video player in Preact

### ISSUE THREAD

**Issue by elaineleeworld** [developit/preact#1522]
Is there a Video Player component we can use for Preact like in React? I found some in my search but they didn't seem to be used too often.  Can you direct me to one that you recommend? I would like to create an onclick to a button that will open a modal with a video. Thank you!

**Comment by marvinhagemeister** [comment]
One of the big selling points of Preact is that one can use all components that were originally written for React. There is no need to convert them to Preact or anything. This is typically done via aliasing `react` and `react-dom` to `preact/compat`:

```js
// webpack.config.js
module.exports = {
  // ...rest of your webpack config
  resolve: {
    alias: {
      react: 'preact/compat',
      'react-dom': 'preact/compat'
    }
  }
};
```

And then you can import react libraries as usual. If that somehow doesn't work with any of the react libraries you're using, we'd love to take a look 🙂

**Comment by elaineleeworld** [comment]
ah okay!  I will give it a whirl!  this is my first preact project, you can take a look at the repo of the same name on my GitHub.  I already had the alias. Just didn't know how to use react components with it.  For example,  I just npm installed react player and am getting this warning in my terminal `react-player@1.10.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.`  Does that mean I have to install react? and if yes, won't that make the K weight larger?

**Comment by ForsakenHarmony** [comment]
no it's just a warning

**Comment by marvinhagemeister** [comment]
yup, as @ForsakenHarmony said this is a warning that cash be safely ignored. The reason it pops up is that npm doesn't support aliasing packages. It has no clue that we replace
 all `react` and `react-dom` imports with `preact/compat` at build time with webpack 👍

**Comment by elaineleeworld** [comment]
thanks everyone! that was helpful explanation!
