### ISSUE TITLE
Scroll to next section in Preact like Fullpage.js in React

### ISSUE THREAD

**Issue by elaineleeworld** [developit/preact#1523]
I have researched and have not found a good solution for window user scroll down a page and next section snaps to top of browser and vice versa, when scroll back up, previous section snaps into browser view(100% of height) without seeing the divide between sections.  I am able to create this effect with an onclick and refs for each section.  But how can I also add this same functionality with just a window scroll? Fullpage.js effect is what I would like to create in Preact.   How do you recommend to approach this in Preact?  Thank you!

**Comment by marvinhagemeister** [comment]
No need for a Preact specific adaptation. Just use [react-fullpage](https://github.com/alvarotrigo/react-fullpage) directly via aliasing 🎉 I've left a comment in #1522 that describes how that is done 🙂
