### ISSUE TITLE
[10.0.0-alpha.4] DOM stability dependent on order of parent/child hook calls

### ISSUE THREAD

**Issue by natevw** [developit/preact#1524]
I have a parent component that tracks an array, rendering a child component that renders and allows edits to the array:

```
const Parent = () => {
  let [items, setItems] = useState([]);
  return html`<${Child} items=${items} setItems=${setItems} />`;
}
```

In this child component, the existing items are editable and additionally there is a "pending item" input for adding a new item to the array:

```
const Child = ({items,setItems}) => {
  let [pendingId, setPendingId] = useState(null);
  if (!pendingId) {
    setPendingId(pendingId = Math.random().toFixed(20).slice(2));
  }
  
  return html`<div class="item-editor">
    ${items.map((item,idx) => html`<input key=${item._id}
      value=${item.val}
      oninput=${evt => {
        let val = evt.target.value,
            _items = [...items];
        _items.splice(idx, 1, {...item,val});
        setItems(_items);
      }}
    />`)}
    
    <input key=${pendingId} placeholder="type to add an item"
      oninput=${evt => {
        let val = evt.target.value;
            _items = [...items];
        _items.push({_id:pendingId, val});
        setItems(_items);
        setPendingId(null);
      }}
    />
  </div>`;
};
```

The problem is this: when using the code as written above, the `key=${pendingId}` input gets completely replaced in the DOM as soon as the user enters one letter.

Because that "pending" identifier is passed along into the new item my expectation was that, on the next render, the focused input **should** remain in the DOM and get reconciled with the lastmost of the newly rendered `key=${item._id}` inputs.

But instead, the input ends up getting removed from the DOM and the user's focus is lost!

## Workaround

If I take the two setters that together add the pending item into the array and reset the pending id:

```
setItems(_items);
setPendingId(null);
```

And simply re-order the calls so that the child's `pendingId` state gets set *before* the parent's `items` state like so:

```
setPendingId(null);
setItems(_items);
```

Then the input is reconciled as expected, i.e. the user's focus is retained when the new input is inserted after the one they are using!

## To reproduce

This code is available ready-to-run (plus some additional logging) at <https://codesandbox.io/s/74jll4q4v1>.

1. Leave the "Set child state before parent state." configuration unchecked.
2. Start typing in the placeholder text input

Expected results:

Despite a new placeholder getting inserted, the keyboard focus should be retained, and you should be able to keep typing. (And, if you check the "set child state before…" box it works this way!)

Actual results:

When the new placeholder is inserted, keyboard focus is completely lost. Debug logs indicate that the original placeholder input has been removed from the DOM, and both of the inputs now in the DOM are brand new.

**Comment by natevw** [comment]
@JoviDeCroock I'm not quite sure what you're saying. Since I've been curious and you provided a good start, I fixed up your React sandbox to test its behavior, see <https://codesandbox.io/s/62q2nnw9vr>.

With React, the order of which state is set (`setItems` vs. `setPendingId`) does **not** matter.

* if I render the `key=${pendingId}` input separately i.e. outside the `items.map` it **never** is reconciled, regardless if "Set child state before parent state." is checked or not
* if I render the `key=${pendingId}` input together with the other children (see the `.concat` in my fork of your sandbox) then it is **always** reconciled as desired, again regardless of `childFirst` checkbox.

So I stand by this issue. With React it seems the rules are a bit more clear that children nested together are reconciled together, regardless of how/when hooks are called.

With Preact there is something less predictable and possibly broken going on. It doesn't matter how the children are rendered. Using the `.concat` trick needed for React has no effect, demo at <https://codesandbox.io/s/yqrw433kpj> which behaves exactly the same as my initial report.

With Preact for some reason it works fine or breaks completely just depending on which hook I call first. I happened to implement it the "wrong" way first, and stumbled across the "fix" it by swapping the order, but now I'm stuck with code that says `// don't touch these two lines lest Preact mysteriously break the UX again`.

**Comment by JoviDeCroock** [comment]
Thanks for the awesome demo @natevw, it got added to our /demo repo and has effectively helped in solving this issue.
The fix is in PR now!

**Comment by natevw** [comment]
Excellent, glad the to be of some help and thank you for taking the time to actually track it down and fix it!

Are there existing utilities/patterns in the tests for tracking DOM stability issues like this? As a demo, I could probably share a bit more of the original code since the real UX was a bit more elaborate, removing blank rows and such… but also with things like this and #1481 since they have turned out to be bugs and not just misunderstandings on my part I'd like to help provide regression tests on them.

**Comment by JoviDeCroock** [comment]
At this point I am looking to pour it into a test but focus loss is hard to test. I’m trying though :)

**Comment by natevw** [comment]
@JoviDeCroock The key [no pun intended] in this case I think is to just make sure the DOM element stays the same, I wouldn't worry about the focus specifically. The *cause* of the focus loss was an element with key X getting removed from the DOM and getting replaced with a new element with key X.

So I imagine the test would be something like:

1. Set up a suitable virtual DOM
2. Do the first render into it
3. Note the object corresponding to the "pending" child
4. Trigger the formerly-broken ordered calls to setState
5. Make sure the object of step 3 is still in the DOM

In my original demo it was this bit of code that really confirmed for me what was happening, because it would log `false`:

    var dbgEl = evt.target;
    setTimeout(() => {
      console.log("still in DOM?", Boolean(dbgEl.parentNode));
    }, 25);

I was using the `parentNode` as an indicator just for convenience, whereas in a test we could probably just store the vnode or simulated DOM element in a variable after the first render result and do an `===` check on it compared to the second render result?

**Comment by JoviDeCroock** [comment]
@natevw the test to prevent regression is in, thanks again for the detailled and thorough issue report. It helped us close this issue rapidly.
