### ISSUE TITLE
Key property not exist on virtual dom

### ISSUE THREAD

**Issue by chemzqm** [developit/preact#155]
I'm using react component [animate](https://github.com/react-component/animate/) to help me add animation to element(s),  but I found not like what react did, preact not have key property on the dom:
<img width="475" alt="screen shot 2016-05-18 at 5 00 06 pm" src="https://cloud.githubusercontent.com/assets/251450/15353375/53b10fbc-1d1b-11e6-9724-4c862cb472f9.png">
<img width="507" alt="screen shot 2016-05-18 at 5 07 26 pm" src="https://cloud.githubusercontent.com/assets/251450/15353376/542cf618-1d1b-11e6-92cf-b26bd4c76b9f.png">

As a result, the animation library fails to find the key and throw an error.

It would be nice if we can make `key` to be a  readonly property on the virtual dom by using `Object.defindeProperty`

**Comment by zenfe** [comment]
Perhaps preact should consider aligning their vdom properties with those of react.

**Comment by developit** [comment]
Definitely something to consider. Preact-compat patches VNode to match React, but internally it would make little difference. Might be something I implement as part of `cloneElement`

**Comment by developit** [comment]
I have a confirmed fix for the `key` property coming shortly.

**Comment by developit** [comment]
@chemzqm I've released this under the beta tag: `npm i -S preact@beta`
