### ISSUE TITLE
Parent context eliminated when a new child context is introduced.

### ISSUE THREAD

**Issue by tylerbwilliams** [developit/preact#156]
When a new component with a `getChildContext` method is introduced, it doesn't merge the new context with any existing parent context.  This causes problems if context is set in multiple places.

Preact.js - Only uses latest childContext
https://github.com/developit/preact/blob/4de2fb9be5201b84f281d0f9d2fcef1017bedd11/src/vdom/component.js#L112

React.js - Assigns ( and shallow clones ) parent context with childContext
https://github.com/facebook/react/blob/378c879a6a65afe18acacb8e2a6fe6ea323974df/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L664

**Comment by developit** [comment]
Ahh good catch, I'll get a fix in for this ASAP.

**Comment by developit** [comment]
I have a confirmed fix coming for this.

**Comment by developit** [comment]
@tylerbwilliams I've released this under the beta tag: `npm i -S preact@beta`
