### ISSUE TITLE
back button handler for preact 

### ISSUE THREAD

**Issue by rushirrsomvanshi** [developit/preact#1563]
Like there is back button event handler present in react, is there any event handler to handle back button event on an android phone on preact?

**Comment by marvinhagemeister** [comment]
What you're referring to is part of the web platform in general and known as the `History` API. It is not tied to any framework and instead is available for any web page to use. MDN has a great introduction on how to use it: https://developer.mozilla.org/en-US/docs/Web/API/History_API
