### ISSUE TITLE
Crash with `null` element as last child of fragment

### ISSUE THREAD

**Issue by robertknight** [developit/preact#1567]
**Steps to reproduce**

The following snippet causes an exception in Preact 10.0.0-beta.0:

```js
import { Fragment, h, render } from "preact";

function Component() {
  return (
    <Fragment>
      <div />
      {null}
    </Fragment>
  );
}
render(<Component />, document.createElement("div"));
```

**Error:**

```
TypeError
null is not an object (evaluating '(w = t.__k[t.__k.length - 1]).l')
```

**Sandbox:** https://codesandbox.io/s/n9oqjl081m

**Notes:**

The exception does not occur:

- If the final `{null}` is removed or replaced with a DOM element
- With earlier alphas of Preact 10.
- If the outer element is not a `Fragment`

Looking at the minified code where the crash happens, I believe it refers to [this line](https://github.com/developit/preact/blob/7227027bbd21594fb79f70aeaf447e3b00841293/src/diff/index.js#L62).

**Comment by JoviDeCroock** [comment]
Thanks for the super clear report, your example was instantly usable in a test and made solving this fairly easy. 👍
