### ISSUE TITLE
Deconstruct props doesn't remove children

### ISSUE THREAD

**Issue by jeremycare** [developit/preact#1575]
Hi,

I found a bug when you deconstruct props, children are not deleted properly.

Here an example: 
https://codesandbox.io/s/k13proo6ko

in my case it generates a RangeError: Maximum call stack size exceeded.

```
const MyDiv = ({ children, ...rest }) => {
  console.log(rest);
  return (
    <div {...rest}>
      <div {...rest}>{children}</div>
    </div>
  );
};
```

Here the rest object still contains the children field.
Maybe _objectWithoutPropertiesLoose is not interpreted correctly.

**Comment by Kanaye** [comment]
Hi, this error isn't directly caused by preact but by bable *not* cloning your `rest` object but instead passing it directy twice to preacts `h` function.
Preact mutates the `rest` object as it is directly passed as `props`. 

Look at the transformed code:
```js
const MyDiv = ({
  children,
  ...rest
}) => {
  console.log(rest);
  return h("div", rest, h("div", rest, children));
};
```

You can prevent this issue by: Either [adding an other property to your first div](https://codesandbox.io/s/j3351q5q29) or by [cloning rest before passing it](https://codesandbox.io/s/k1o001y7zo) to the first div.

**Comment by jeremycare** [comment]
Hi,
Thanks for providing a solution to my problem on the actual version!

but the issue comes from the deconstruction step, right before,
```
const MyDiv = ({
  children,
  ...rest
})
```
is replaced by 
```
var MyDiv = function MyDiv(_ref) {
  var children = _ref.children,
        rest = _objectWithoutProperties(_ref, ['children']);
```
Here `_objectWithoutProperties` (generated by babel) doesn't works as expected with preact, it doesn't remove the children, this is generating the infinite childrend property.

**Comment by Kanaye** [comment]
No, the property is removed properly. 
`console.log` is *lazy* and prints the objects state *after* preacts `h` function modified it.
You can observe this behavior by logging `rest.children` which eveluates to `undefined` instead of `rest` [example](https://codesandbox.io/s/x7xrq4pqoz).

**Comment by marvinhagemeister** [comment]
@jeremycare which version of `babel` is used in your setup? The implementation for `_objectWithoutProperties` from `7.4.0` [works as expected](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUBvRAjAhgJwBpEA6M_AUwGdEBfASkQwChFEIEq4AbCk7uAHM0eIokpV6AbkTNazZinQZRALgCMhJaoBMDIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-2%2Ces2015-loose&prettier=true&targets=&version=7.4.3&externalPlugins=) for me

**Comment by jeremycare** [comment]
@marvinhagemeister, @Kanaye  is right, it works as expected! my bad

**Comment by marvinhagemeister** [comment]
@Kanaye is right. The issue is caused by us mutating `props` directly. Looks like we need to clone `props` in `createElement/h`.

**Comment by developit** [comment]
Mentioned it in chat, but here's the cause:

```js
<div {...props} />
// transpiles to:
createElement('div', props)  // passed by reference
// whereas
<div a {...props} />
// transpiles to:
createElement('div', Object.assign({ a: true }, props)) // cloned first

```
