### ISSUE TITLE
TypeScript definitions for microdata HTMLAttributes missing

### ISSUE THREAD

**Issue by Dangoo** [developit/preact#1582]
In order to being able to enrich the markup with [microdata](https://www.w3.org/TR/microdata/) attributes they have to be whitelisted in the `JSX.HTMLAttributes`.

The [React Types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1685) already include these like this:
```typescript
interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
  ...

  // Non-standard Attributes
  ...
  itemProp?: string;
  itemScope?: boolean;
  itemType?: string;
  itemID?: string;
  itemRef?: string;
  ...
}
```

Would you be open for a PR adding the above lines to `preact.d.ts`?

**Comment by JoviDeCroock** [comment]
I don't see why we shouldn't support this, looks like a fine addition to me. If you feel up to making a PR for it the team'd be grateful.
