### ISSUE TITLE
Preact X hook useState render execution order

### ISSUE THREAD

**Issue by fabiodcorreia** [developit/preact#1583]
I found strange behavior using the useState hook and I created a couple of sandboxes to show the case.

On this sandbox I implemented a component that gets a message, if the message is not null or empty the function return null and nothin is rendered. The component gets initialized with a message and when we click the parent sets the prop to '' and the child should return null. But it turns the rendered component with empty element `<p>.`

[![Edit Preact X Hook useState](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xpv213py2w?fontsize=14)

We can follow the render flow on the console and the line 
```javascript 
console.log("Message not visible");
```

On this other sandbox I did the exact same implementation but with React, in this case there is an extra render with the correct behavior happens.

[![Edit React Hook useState](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5k571v77lk?fontsize=14)

**Comment by JoviDeCroock** [comment]
Thanks for the superb reproductions, I have made a first attempt at fixing the issue.
