### ISSUE TITLE
Fragment child order with false/null child

### ISSUE THREAD

**Issue by mischnic** [developit/preact#1586]
Running the example and pressing "Run" outputs "B C A" but should be "A B C". That is corrected however when a re-render happens (the second button).

This is fixed by either making `Preview` not return `false` or `null` or by replacing `Fragment` with e.g. `div`.

I have a feeling this is related to https://github.com/developit/preact/pull/1440

The devtools always show the correct order.

https://codesandbox.io/s/m498m04nly

```jsx
import {h, render, Component, Fragment} from 'preact';

const Preview = () => null; // or false

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      output: null,
      value: null
    };
  }

  run() {
    this.setState({
      output: ['A', 'B', 'C']
    });
  }

  render() {
    return (
      <div style={{marginBottom: '20px'}}>
        <button onClick={() => this.run()}>Run</button>
        <button onClick={() => this.setState({value: {}})}>Re-render</button>
        {this.state.output && (
          <Fragment>
            {this.state.output.map(v => (
              <div style={{marginTop: '10px', backgroundColor: 'lightgrey'}}>
                {v}
              </div>
            ))}
            <Preview output={this.state.output} />
          </Fragment>
        )}
      </div>
    );
  }
}

render(<App />, document.getElementById('root'));
```

Using Preact 10.0.0-beta.0

**Comment by marvinhagemeister** [comment]
@mischnic Thank you so much for the detailed bug report. I was quickly able to reproduce it and create a proper fix. You rock :+1: :100:
