### ISSUE TITLE
Input loses focus

### ISSUE THREAD

**Issue by jrvidal** [developit/preact#159]
Codepen: http://codepen.io/anon/pen/ONKxeZ (write something in the input box to see the effect)

I tested a similar scenario with React and it works correctly. Apparently Preact detaches the text input during reconciliation, losing all focus info.

**Comment by developit** [comment]
Thanks for the bug report!  You're right, this is unintentional.  I have a fix, will publish it as soon as I can verify with some large codebases.

**Comment by developit** [comment]
Released in `5.0.0-beta2`.
