### ISSUE TITLE
10.0.0-beta.0 doesn't work with react-hot-loader due to unset "length" property

### ISSUE THREAD

**Issue by reaysawa** [developit/preact#1594]
10.0.0-beta.0 fails to work with react-hot-loader due to this PropType check **_enabled in dev mode_**

https://github.com/gaearon/react-hot-loader/blob/master/src/AppContainer.dev.js#L94

EDIT: Also should add it's not restricted to pure components, class components suffer from the same issue

The props' "children" field doesn't have the "length" property set, unlike 8.4.2, as shown below

---

8.4.2 still sets the property and works fine

![image](https://user-images.githubusercontent.com/17429390/57091311-45703880-6cdf-11e9-9205-4ac1617792c9.png)

**Comment by developit** [comment]
Hi there! This is actually caused by using `preact-compat` with `preact@next`. You need to change your aliases from `preact-compat` to `preact/compat`.

**Comment by reaysawa** [comment]
Right, thanks for the response. I'll post below how I changed the configuration in case someone finds the same problem.

#### package.json
```diff
  "dependencies": {
-    "preact": "^8.4.2",
-    "preact-compat": "^3.18.0",
-    "react": "npm:preact-compat",
+    "preact": "^10.0.0-beta.0",
    "react-hot-loader": "^4.1.2"
},
```

#### webpack.config.js
```diff
  resolve: {
    alias: {
-      "react": "preact-compat",
-      "react-dom": "preact-compat",
+      "react": "preact/compat",
+      "react-dom": "preact/compat",
    },
```
