### ISSUE TITLE
preact/compat not working properly using react-toolbox and @material-ui/core

### ISSUE THREAD

**Issue by agusmr** [developit/preact#1610]
When use @material-ui/core library using preact/compat, 
after click Button component show the error

_Uncaught (in promise) TypeError: Cannot read property 'cancelNextCallback' of undefined at componentWillUnmount (Transition.js:197)_
  
this also happens when click Drawer, 

> the problem when componentWillUnmount triggered cannot access 'this' on Transition.js

Preact version 10.0.0-beta.1

**Comment by marvinhagemeister** [comment]
Great find! Can you share a [sandbox](https://codesandbox.io) or a repo where the issue can be reproduced? This helps us tremendously in solving bugs :100:
