### ISSUE TITLE
DOM event props capitalization: onFocusIn v. onFocusin v. onfocusin

### ISSUE THREAD

**Issue by maranomynet** [developit/preact#1611]
I was trying to bind a [`focusin`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event) event handler to an element, and found out that the only way to do it was to use an all-lower case prop `onfocusin`.

Neither `onFocusin` nor `onFocusIn` work.

I'm not sure if this is a Preact 10 beta related issue, or simply a documentation issue.

Are, perhaps, camelCased event prop-names strictly a React-compatibility feature, and all-lower case event props encouraged by Preact?

If so, that fact should be clearly mentioned under [What's missing?](https://preactjs.com/guide/differences-to-react#what-s-missing-) or [What's Different?](https://preactjs.com/guide/differences-to-react#what-s-different-) in the Preact Guide.

(Using `preact@10.0.0-beta.1` – Firefox, Chrome)

**Comment by cristianbote** [comment]
Hey @maranomynet, indeed, `onfocusin/out` is not _supported_[1]. Also, looking over in `react` it seems as well that it's not supported https://github.com/facebook/react/issues/6410.

As an alternative perhaps you could rely on `focus/blur` events?

[1] The supported part is actually driven by the fact that the event exists on the Global Event Interface. MDN gives a 404 on these ones, even though they are linked on their website.

**Comment by maranomynet** [comment]
Ah, I see now that onFocus does _indeed_ "bubble" like in React! Wonderful!

My initial interpretation of "no synthetic events, just plain browser events" and what must have been a simple coding error with `onFocus` led me to hastily assume I needed to resort to `focusin`/`focusout`.

(...similar to the difference in Preact's `onChange` and React's event of same name)

Out of curiosity: Is there anything technically wrong with useing lower case event props instead of the camelCased ones?
I assume the hyperscript (`h()`) function simply tacks them on the DOM Element like any other JavaScript property, but does it really hurt outside being non-idiomatic?

**Comment by marvinhagemeister** [comment]
@maranomynet no, there is nothing wrong with using lowercased events. In fact we map those 1:1 to native DOM events👍
