### ISSUE TITLE
After upgrade preact 5.0.0@beta, the svg defs not working

### ISSUE THREAD

**Issue by zhenkunou** [developit/preact#162]
In my case, my code look like this:
```
...
        <SVG>
          <defs>
            <linearGradient id="bgFill" x1="0%" y1="100%" x2="50%" y2="0%">
              <stop offset="0%" style="stop-color:#AB0514;stop-opacity:1" />
              <stop offset="100%" style="stop-color:#E6021C;stop-opacity:1" />
            </linearGradient>
          </defs>
          <polygon
            fill='url(#bgFill)'
            points={`
              0,0
              100,0
              40,100
              0,100
            `}
          />
        </SVG>
...
```
with `preact@4.8.0` and `preact-svg@1.5.1` everything work fine;
after i upgrade to `preact@beta` the polygon doesn't fill any color.

http://codepen.io/ryan_ou/pen/mPKyrP?editors=0010

**Comment by developit** [comment]
Great catch - thanks!  This happened because preact started normalizing `nodeName` values it passes to `document.createElement()` to be lower case, which breaks `<linearGradient>` (odd!).  I'll revert that change since it has no other effect!

**Comment by developit** [comment]
Confirmation: http://codepen.io/developit/pen/vKBaPj?editors=0010

**Comment by zhenkunou** [comment]
perfect! Thanks for the quick fix!! 💯
