### ISSUE TITLE
Official adapter for enzyme

### ISSUE THREAD

**Issue by 38elements** [developit/preact#1622]
IMHO,
 If [enzyme-adapter-preact-pure](https://github.com/preactjs/enzyme-adapter-preact-pure) is the official adapter for enzyme, 
I think it is better to indicate it in the [release note](https://github.com/developit/preact/releases/tag/10.0.0-beta.0).

**Comment by robertknight** [comment]
Are you asking us just to add a link to this package in the release notes? I did also submit a PR to the Enzyme project updating the link in the official Enzyme docs, but they haven't had a new release yet.

**Comment by 38elements** [comment]
> Are you asking us just to add a link to this package in the release notes?

Yes, I am.
It makes the package to be easily found.

**Comment by robertknight** [comment]
The adapter needs to be mentioned in the preactjs.com docs when it is updated for Preact v10. In the meantime I have updated the changelog for the 10.0.0-beta.0 release with a link as you suggested. Thanks for the feedback 🙂
