### ISSUE TITLE
Accept `useEffect`/`useLayoutEffect` without second argument in debug

### ISSUE THREAD

**Issue by yuqianma** [developit/preact#1624]
According to [React Doc](https://reactjs.org/docs/hooks-reference.html#useeffect), `useEffect` does allow to omit the second argument. That makes sense if you want to update something in every render.

I encountered the debug Error when I was trying [redux-react-hook](https://github.com/facebookincubator/redux-react-hook). It uses `useLayoutEffect` to save an old state reference.
https://github.com/facebookincubator/redux-react-hook/blob/master/src/create.ts#L110

Indicating the possible missing to developers is great. But it should accept the simple `useEffect` at least.

Or we can remove the run-time checking here and use eslint like React? 

I replace the error with warn first:
https://github.com/developit/preact/pull/1623

**Comment by JoviDeCroock** [comment]
I think we can mark this as resolved or would you like to see this without a warning, else we should discuss it here.

**Comment by yuqianma** [comment]
@JoviDeCroock I'd like it without a warning. Because it will show the message in every render.
I think the problem here is, it forces to set the second argument. But it's unnecessary. And there's no way to disable the warning in specific hooks.

**Comment by JoviDeCroock** [comment]
Hey @yuqianma I've built in a mechanism that will prevent warning on every render. Can you live with this as a middle-ground solution?

**Comment by yuqianma** [comment]
@JoviDeCroock Seems acceptable. I have no idea what's the best solution here.
Anyway, thanks for your quick approach!

**Comment by JoviDeCroock** [comment]
No problem, glad I could help out!
