### ISSUE TITLE
InnerMost Component 'constructor' and 'getInitialState' not getting called when re-render

### ISSUE THREAD

**Issue by zhenkunou** [developit/preact#164]
When re-render, `preact@beta` doesn't refresh InnerMost Component's state:

http://codepen.io/ryan_ou/pen/LZYxxZ?editors=0011

**Comment by developit** [comment]
Hmm, yeah this is going to be an interesting one.  We already have the built vtree, but need to re-instantiate the components as we render.

**Comment by developit** [comment]
Just doing some performance testing and then I'll release this.

**Comment by zhenkunou** [comment]
I just tested the `preact@5.0.0-beta6` and one word: Excellent!! Thank you 👍
