### ISSUE TITLE
No re-render if an array is re-ordered

### ISSUE THREAD

**Issue by mmacdonald1** [developit/preact#1648]
Using Preact and Redux.  

I have an array of objects that I am ordering alphabetically in my redux store.
  
On edit of an object:
 redux: it successfully updates and changes position alphabetically in the store
 preact-component: I then use componentWillRecieveProps to update local state successfully.  

Problem: The change in local state triggers a render, but the objects stay in the old state order.

How do I trigger a re-render for a reorder of an array in state? Or is this a Preact bug?

Below is the relevant code. Tried to make it look as good as I could :3

![Screen Shot 2019-05-22 at 2 36 38 PM](https://user-images.githubusercontent.com/27786743/58199699-15450580-7c9f-11e9-897b-f67d7e078ab5.png)

**Comment by JoviDeCroock** [comment]
Hey, when logging your new state do you see the new order? Trying to figure out if this is due to stale state or a dom issue?

You might want to try getDerivedStateFromProps, might be a more suitable measure for your use case.

**Comment by mmacdonald1** [comment]
Yupp I see the new order when logging state.  My perspective is its a dom issue because all the right data is there just no order change in the Dom.

getDerivedStateFromProps is not in the Preact docs is it the same as React?

**Comment by JoviDeCroock** [comment]
Yes, docs need to be updated. I'll try and look into it this week, thanks for the error report.

**Comment by mmacdonald1** [comment]
I added key to the Catalog Card and the code above worked thanks!

**Comment by JoviDeCroock** [comment]
Oh, yeah. Didn't notice you had no key, mostly rely on my linter for that personally ^^
