### ISSUE TITLE
componentDidMount not called in a specific case

### ISSUE THREAD

**Issue by kruczy** [developit/preact#172]
The lifecycle hook `componentDidMount` does not get called for components that return false form `shouldComponentUpdate` and are wrapped in a normal component

see repro: 
http://jsfiddle.net/2sh26um7/4/ (4.8.0)
http://jsfiddle.net/48e5jdsk/2/ (5.0.0-beta5)

the beta fixes the immediate issue from 4.8.0 but if you wrap the component twice the same problem happens

click the toggle button 4 times in console you will see mount unmount unmount
the expected log would be mount unmount mount unmount

if you remove the wrapper the log is correct

If there is anything I can help with please let me know

**Comment by zhenkunou** [comment]
@kruczy I have the same issue before, and `preact@5.0.0-beta6` fixed it. please take a try. 
http://codepen.io/ryan_ou/pen/QNYegz?editors=0010

ref #143

**Comment by developit** [comment]
Yes, `5.0.0-beta6` fixes the mount event.  It looks like it might duplicate the unmount event though, looking into that now.

**Comment by kruczy** [comment]
Whoops, didn't see beta6
this is a version with beta6: http://jsfiddle.net/48e5jdsk/3/

it calls both mount and unmount now but unmount gets called 3 times in a row, this is much better now as protecting against multiple calls to unmount is quite easy, though probably should be fixed

**Comment by developit** [comment]
Agreed.  I'm thinking it might finally be time to store a "mounted" boolean, but I'd also just like to address why Preact is even trying to unmount them in the first place.  I think it's the High Order Component recursion seeing a new "owner" component for the same element 3 times (because the nesting level is 3).

Thanks so much for this repro!  You guys have been awesome.

**Comment by developit** [comment]
@kruczy + @zhenkunou - Forgot to tag [the commit](https://github.com/developit/preact/commit/1c76091304c455986d08cfd006fae15861118cad) with this issue, but I've published what I hope is a proper fix for this.  It fixes the repro: http://jsfiddle.net/developit/48e5jdsk/7/

Closing as hopeful for now but let me know if you have other cases/repros that are still affected!
