### ISSUE TITLE
Functional components break *mount methods

### ISSUE THREAD

**Issue by slmgc** [developit/preact#175]
I've created an example with a higher-order component which gets broken when it wraps a functional component which returns a class component... I think we need to go deeper:

http://codepen.io/anon/pen/RRPMVr

Constructors for Composed & Broken components get executed, but Broken's componentDidMount, componentWillMount, componentWillUnmount, etc. methods don't get executed.

And all is ok if I'll replace a functional component with a class component.

**Comment by developit** [comment]
Thanks for investigating this! I think I know what's causing it and will publish a new beta today. I believe you're running 5.0.0-beta6?

**Comment by slmgc** [comment]
@developit yeah, I was playing with beta6 and reproduced this issue.
