### ISSUE TITLE
SVG viewBox attribute is incorrectly applied

### ISSUE THREAD

**Issue by marklundin** [developit/preact#177]
When a component renders different svg elements depending on it's state, it will incorrectly apply the viewBox attribute from the first svg element rendered to the second.

Test case : https://jsfiddle.net/jdqhus9m/
1. First SVG is displayed with `viewBox="50 0 50 50"` attribute displaying a green rect.

2. Click on the SVG element to trigger a state change, rendering a different svg without the viewbox attribute. Notice in the dom, that the new svg contains the `viewBox="50 0 50 50"` attribute from the first render.

Expected result: SVG element should have no viewBox attribute and should display the red and greenbox side by side.

**Comment by developit** [comment]
Thanks for the detailed bug report! I'm thinking it's failing to set the property but the error is being caught and suppressed.  I can't check now, but maybe it's fixed in https://npmcdn.com/preact@beta ?

**Comment by marklundin** [comment]
Awesome. Will check in the morning and let you know

On Sun, 5 Jun 2016, 22:22 Jason Miller, <notifications@github.com> wrote:

> Thanks for the detailed bug report! I'm thinking it's failing to set the
> property but the error is being caught and suppressed. I can't check now,
> but maybe it's fixed in https://npmcdn.com/preact@beta ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/developit/preact/issues/177#issuecomment-223838525>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAaSrBMOx29nxOYDI9qnjAas-24PtOPMks5qIz4RgaJpZM4Iucv_>
> .
>
-- 

*Mark*

*// Mark Lundin* | Creative Coder
// www.mark-lundin.com
// @mark_lundin <https://twitter.com/intent/user?screen_name=mark_lundin>
// +44 (0)7789 021890

**Comment by developit** [comment]
@marklundin This ended up being a bug in [preact-svg](https://github.com/developit/preact-svg).  It's now fixed, released as `preact-svg@1.6.0`. Thanks again :)

**Comment by marklundin** [comment]
Great work @developit !
