### ISSUE TITLE
error when component returns null from render

### ISSUE THREAD

**Issue by kruczy** [developit/preact#182]
see repro: http://jsfiddle.net/zbkv3yma/4/ (beta9)

vnode is null in https://github.com/developit/preact/blob/ee58240bd8b2db496c8877a35543615b1ea82d8a/src/vdom/functional-component.js#L13

**Comment by developit** [comment]
Ah this must be in beta9. I knew I missed an edge case, will fix ASAP. Thanks.

**Comment by developit** [comment]
Fix released in `5.0.0-beta10`.
