### ISSUE TITLE
RFC / Poll: Should preact support SVG right out-of-the-box?

### ISSUE THREAD

**Issue by developit** [developit/preact#195]
Preact is an open project.  Features and priorities are decided based on feedback and suggestions given here and via Twitter or Gitter.  I'd like to propose adding a fairly significant new feature, which is to merge SVG support into Preact itself, rather than providing it as a separate `preact-svg` module.  Please take a moment to read the pros and cons I've laid out below, and feel free to suggest more.

> There is a [`native-svg` branch](https://github.com/developit/preact/compare/abfb2c3fcc1dcdd807b2940ec9ec64900b07ec89...native-svg) with the bundled implementation if you'd like to see how this would work.

| Pros | Cons |
|--------|--------|
| [preact-svg](http://git.io/preact-svg) is `1.7kb`, no longer needed <sup>1</sup> | Preact gets `115 bytes` larger <sup>1</sup> |
| `<svg>` "just works" - no imports / SVG | Preact gets slightly less modular |
| No [dirty][1] [hacks][2] would be necessary | Tiny performance hit for custom attributes <sup>2</sup> |

> \* All sizes listed are gzipped (because this is what Preact is optimized for)
>
> **1:** Meaning this would be a `1.6kb` size _reduction_ for anyone using SVG!
>
> **2:** This only affects custom attributes (eg: data attributes, etc), which are already significantly slower than properties. The performance hit is [a single regex match][3], which I don't even see making a meaningful difference in any of the perf stats I track.

[1]: https://github.com/developit/preact-svg/blob/master/src/index.js#L29-L48
[2]: https://github.com/developit/preact-svg/blob/master/src/index.js#L124-L137
[3]: https://github.com/developit/preact/blob/native-svg/src/dom/index.js#L65

**Comment by slmgc** [comment]
@developit I think Preact should stay as modular & small as possible but not at the cost of development convenience. A solution without hacks is a good one, I vote for merging SVG into Preact.

**Comment by amilajack** [comment]
Agree with @slmgc

**Comment by developit** [comment]
Glad to have the input, thanks to you both! I should have also added a pro: this brings preact a little but closer to react, which does support svg by default.

**Comment by developit** [comment]
Time to close this one out!  Built-in SVG support will be released as of `5.1.0-beta.16`.
