### ISSUE TITLE
use lowercase svg attributes

### ISSUE THREAD

**Issue by aeosynth** [developit/preact#207]
`preact-svg` has a [line](https://github.com/developit/preact-svg/blob/master/src/index.js#L105) which lowercases svg attributes, which is needed for eg `xlinkHref`.

**Comment by developit** [comment]
@aeosynth hmm - that operates on the latter half of the value, which should just normalize `Href` to `href`.  Here's a demo of `xlinkHref` and `xlink:href` working with preact-svg:
https://jsfiddle.net/developit/0qgbw2sg/

That being said, if you're using the beta, I just found a bug in the SVG release which I'm about to publish a fix for.  It's likely the issue you encountered if you were using the beta.  [Here's the bug](https://jsfiddle.net/developit/7r21abfm/1/) - basically, it's trying to set the attribute as `Href=""`, but SVG attributes are case-sensitive, so it fails.

**Comment by developit** [comment]
Fix released as `5.1.0-beta.18`!
