### ISSUE TITLE
Support namespaced tags

### ISSUE THREAD

**Issue by fandy** [developit/preact#215]
Is it worth supporting namespaced tags (commonly used in svgs)?

```html
<svg role="img" class="next-icon next-icon--size-16" aria-labelledby="next-website-aecd81959dee2d276ba35c68b2e61e59-title">
  <title id="next-website-aecd81959dee2d276ba35c68b2e61e59-title">View your online store</title>
  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#next-website"></use>
</svg>
```

Here `xmlns:xlink` and `xlink:href` are not valid in JSx. React works around this by allowing camel cased versions (`xmlnsXlink` and `xlinkHref`).

**Comment by developit** [comment]
@fandy These are supported in the beta.  Prior to 5.0 (the beta), [preact-svg](https://github.com/developit/preact-svg) was required in order to support SVG.

**Comment by trueadm** [comment]
@developit Namespaces are valid in JSX now, in fact they are the preferred route instead of camelCase.

**Comment by developit** [comment]
Woah, that's awesome. I've been supporting them because they were always possible via hyperscript, I guess that pays off now, haha.

**Comment by developit** [comment]
I'm not sure what to do with this issue, since both ways of specifying the attributes should already be supported.  Is there something missing we need to add?

**Comment by developit** [comment]
Can confirm this is working in 5.x:  https://jsfiddle.net/developit/0qgbw2sg/4/  (jsfiddle's version of Babel is not current so I'm using hyperscript directly).
