### ISSUE TITLE
Unexpected appendChild of text nodes during render with merge

### ISSUE THREAD

**Issue by bardt** [developit/preact#218]
I'm currently working on a Preact app with server rendering. So, I use `render()` with the third argument `root.lastChild`. As I render the same data on client and server, I expect this render to do nothing to real DOM nodes, except attaching events. But I see `appendChild` in the call tree. As a result, first rendering on client takes longer than expected (and longer than alternative libraries).

Naive debugging lead to a conclusion that this happens to text nodes. Looks like text node is not considered an existing child during diffing.

Before I go deeper into debugging, I'd like to know if this is an expected behavior and what are reasons for that.

**Comment by developit** [comment]
Hmm - that does sound like a bug. Preact should be updating existing text nodes by setting their `nodeValue` property. 

@bardt - which version of preact were you testing with?

**Comment by bardt** [comment]
@developit thank you for a really fast reaction! I will check if it solves my particular case tomorrow, hope so. 

Also, thank you for what you are doing!

**Comment by bardt** [comment]
@developit I can still see several `createElement` and `appendChild` calls. Should I provide an example?

**Comment by developit** [comment]
That would be helpful, yes. Thanks!

**Comment by developit** [comment]
I think this should be fixed in `5.4.0`. Can anyone verify?

**Comment by developit** [comment]
Closing since I've done as much testing as I can find time for and can't see new textnodes being created. Please re-open if there is still an issue in `5.6.0`!
