### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by bouk** [developit/preact#219]
Hi,

I was wondering if you have looked into supporting [Flow](https://flowtype.org), it has built in support for JSX type checking, but I'm unsure whether it would be possible to make it work with Preact.

**Comment by bouk** [comment]
Looking through the Flow code, it seems JSX tags are currently hardcoded to `React.createElement`, so this probably won't be possible without modifications to Flow

**Comment by slmgc** [comment]
@bouk preact has a compatibility layer, [preact-compat](https://github.com/developit/preact-compat), which allows to use different libraries which reference React directly. All you need is to add an alias like this (if you use webpack):

```js
alias: {
	react: 'preact-compat',
	'react-dom': 'preact-compat'
},
```

I've created a [boilerplate](https://github.com/slmgc/preact-baobab-template/tree/dev)  to experiment with preact, you can try it out.

**Comment by developit** [comment]
@slmgc Yeah for `preact-compat` I think a straight re-export (as a way to alias) would work.  The PR from @bouk does this and I wondered if we could strip out the things Preact (core) doesn't provide, but for preact-compat we're providing nearly all of the exports so it makes sense to just point to the thing we're emulating.
