### ISSUE TITLE
Improve style object performance by skipping serialization

### ISSUE THREAD

**Issue by trashhalo** [developit/preact#228]
Building that [pixel bench](http://codepen.io/developit/full/KrXZWY/) in inferno had me spend a chunk of time in their internals profiling various code paths. Ran your port through the same tests and I have some small feedback.

[When inferno goes to update an elements style, if it can, its directly manipulates the style object.](https://github.com/trueadm/inferno/blob/245117d0d77044da2d29c502350c2f712fb95ab6/src/DOM/patching.js#L468) Like `dom.style[style] = value;` where style might be something like 'background' and value might be something like 'blue'. [You can read more about the style object over at mdn.]( https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style)

[In contrast preact is discarding its nested style information and computing a string](https://github.com/developit/preact/blob/073022916169d8c49b9154b6153d2831454d90c6/src/h.js#L74) and swapping out it at the attr level. I found this to be the slowest approach to updating style information.

[You can try this yourself with a small performance bench I wrote comparing the two approaches.](https://albertxing.com/stool/#52dff768c46824d6d10499147bfbb8a4) (Warning flashing colors ahead) On my machine I am getting 546,067 ops/sec using `style['backgroundColor']` vs 352,944 ops/sec for `style = 'background-color'`
***
Feel free to close the issue if you dont want to change anything just thought I would share my findings :cat2:

**Comment by developit** [comment]
@trashhalo Great work, and I totally agree - this is actually extra work Preact is doing that is unnecessary.  If the pipeline for the style attribute were simplified to just copy object properties onto `node.style` when `style` is itself an Object, then the [rather large utility method](https://github.com/developit/preact/blob/master/src/util.js#L83-L102) for serializing style Objects could be dropped entirely!  I'll keep this issue open to track progress.

**Comment by developit** [comment]
Huzzah, we've got Blazing fast Object style support now! 😍 
Thanks for your great work with Pixel Bench @trashhalo!
