### ISSUE TITLE
Nested setState w/ immutability-helper issue?

### ISSUE THREAD

**Issue by aiphee** [developit/preact#238]
Hi, my apps work great with drop-in preact and preact-compat except one thing.

It seems that nested setState with immutability-helper's method update() is not working.

I use it like this:
```babel
import update from 'immutability-helper';
onCountryChange = (path, selected) => {
		let obj = {
			destinations: {
				[path.pop()]: {
					selected: {
						$set: selected
					}
				}
			}
		};

		var newState = update(this.state, obj);
		this.setState(newState);
	};
```

I works great with React, but with preact, model wont update and propagate. update() is working, newState contains the right data.

Ill keep trying, maybe i missed some important difference with react.

**Comment by aiphee** [comment]
Maybe the problem is elsewhere, i render the countries like this:

```JS	getCountries() {
		let countries = [];
		for (let country of this.state.destinations) {
			countries.push(
				{
					id      : country.id,
					index   : country.index,
					name    : country.name,
					selected: country.selected
				}
			);
		}

		return countries.filter(
			country => (new RegExp(this.state.filter_value, 'i')).test(country.name)
		);
	}

render() {
let countries =
				<CountryList
					recommended={recommended_destinations}
					openDestinations={this.openDestinations}
					countries={this.getCountries()}
					onChange={this.onCountryChange}
					filter={this.state.filter_value}
				/>;
...
{countries}
...
}

**Comment by developit** [comment]
@aiphee do you have a `shouldComponentUpadate` method defined?

Thanks for the detailed report, I hope we can get this working for you!

**Comment by aiphee** [comment]
I do have that method, i tried to always return true, but it didnt help. 
Should i try to make that (not) work on jsbin?
Is there some starter jsx bin i could clone?

**Comment by developit** [comment]
Thanks, I'll try to dig into this today!

**Comment by developit** [comment]
I was able to use immutability-helper via [browserify-cdn](https://wzrd.in/):
https://wzrd.in/standalone/immutability-helper

Here's your fiddle with a fix (missing `.deselectAll()` method):
https://jsfiddle.net/developit/kj8qvd9c/2/

I'm not 100% sure what the desired outcome for the fiddle is, I'm thinking it's still not working correctly?

**Comment by aiphee** [comment]
Thanks for looking into it. 
I managed the broking part to be working.
https://jsfiddle.net/h9byLyny/2/

My problem prevails, the drop in preact instead of react is not working but problem is clearly not in part written in current fiddle.

I guess this issue can be closed for now until i find out where else could be an error.

**Comment by mellogarrett** [comment]
I'm running into this issue now, but I'm unable to reproduce in codesandbox ☹️ 

It only happens when I use the `$set` function though. It's like Preact doesn't think my state has changed, so it doesn't actually update.

**Comment by mellogarrett** [comment]
Any pointers as to what would cause `setState` to NOT actually change the state?

**Comment by developit** [comment]
@mellogarrett setState() always triggers a re-render, Preact doesn't do any diffing/checking on state itself.
