### ISSUE TITLE
Possible Optimization

### ISSUE THREAD

**Issue by amilajack** [developit/preact#240]
@developit sure you've heard of this one before: rendering components that are only visible. Ben Alpert mentioned this one at react con 2016 I think

**Comment by developit** [comment]
Yup! It's a super interesting idea for sure. Personally I wonder if it could be implemented as a High-Order component that conditionally renders its children based on DOM layout, but that would still incur layout cost.  Actually, [preact-virtual-list](https://github.com/developit/preact-virtual-list) implements much more specific version of that idea.

**Comment by amilajack** [comment]
Is it possible to use preach-virtual-list with react or does it use preach-specific api's?

**Comment by developit** [comment]
It'd need to be slightly modified since I was lazy and used `this.base` instead of a `ref`.

**Comment by developit** [comment]
I think I might close this out for now since a solution here wouldn't happen in Preact's core. I'm actually currently looking into a composite component to accomplish this, I'll update here if/when I get something done.
