### ISSUE TITLE
Checkbox doesn't update checked value on setState

### ISSUE THREAD

**Issue by MozMorris** [developit/preact#241]
[Here's the failing example](https://preactjs.com/repl?code=export%20default%20class%20MyForm%20extends%20Component%20%7B%0A%20%20%20%20toggle(e)%20%7B%0A%20%20%20%20%20%20%20%20e.preventDefault()%3B%20%20%20%2F%2F%20we%27ll%20handle%20this%2C%20thanks%0A%20%20%20%20%20%20%20%20let%20checked%20%3D%20!this.state.checked%3B%0A%20%20%20%20%20%20%20%20this.setState(%7B%20checked%20%7D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20render(%7B%20%7D%2C%20%7B%20checked%20%7D)%20%7B%0A%09%09%09%09console.log(checked)%3B%0A%20%20%20%20%20%20%20%20return%20(%0A%09%09%09%09%09%09%3Cdiv%3E%0A%09%09%09%09%20%20%20%20%09%09%3Clabel%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09%3Cinput%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09type%3D%22checkbox%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09checked%3D%7Bchecked%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09onClick%3D%7B%3A%3Athis.toggle%7D%0A%09%09%09%09%09%09%09%09%09%09%2F%3E%0A%09%09%09%09%09%09%09%09%09%09Checkbox%0A%09%20%20%20%20%20%20%20%20%20%20%20%20%09%3C%2Flabel%3E%0A%09%09%09%09%09%09%09%09%3Cp%3EChecked%3A%20%7Bchecked%20%3F%20%27Yes%27%20%3A%20%27No%27%7D%3C%2Fp%3E%0A%09%09%09%09%09%09%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D%0A), taken directly from the docs.

Removing `e.preventDefault();` fixes the example.

**Comment by developit** [comment]
I think the solution might be to change the example to [this]. I'm not sure when this changed, but I think we're better off not asking people to call `preventDefault()` if that's an option.

[this]: https://preactjs.com/repl?code=export%20default%20class%20MyForm%20extends%20Component%20%7B%0A%20%20%20%20toggle%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20let%20checked%20%3D%20!this.state.checked%3B%0A%20%20%20%20%20%20%20%20this.setState(%7B%20checked%20%7D)%3B%0A%20%20%20%20%7D%3B%0A%0A%20%20%20%20render(%7B%20%7D%2C%20%7B%20checked%20%7D)%20%7B%0A%20%20%20%20%20%20%20%20return%20(%0A%09%09%09%09%09%09%3Cdiv%3E%0A%09%09%09%09%20%20%20%20%09%09%3Clabel%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09%3Cinput%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09type%3D%22checkbox%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09checked%3D%7Bchecked%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09onClick%3D%7Bthis.toggle%7D%0A%09%09%09%09%09%09%09%09%09%09%2F%3E%0A%09%09%09%09%09%09%09%09%09%09Checkbox%0A%09%20%20%20%20%20%20%20%20%20%20%20%20%09%3C%2Flabel%3E%0A%09%09%09%09%09%09%09%09%3Cp%3EChecked%3A%20%7Bchecked%20%3F%20%27Yes%27%20%3A%20%27No%27%7D%3C%2Fp%3E%0A%09%09%09%09%09%09%3C%2Fdiv%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D%0A

**Comment by MozMorris** [comment]
That's the way I'm handling it but something doesn't seem right here. Wouldn't one always expect the the input's `.checked` value to respect the value passed to it whether `e.preventDefault() ` was called or not?

**Comment by developit** [comment]
By preventing default in the click handler, the browsers default action of toggling the `.checked` property is cancelled, which means when grabbing the value back via `linkState()` or some other technique, it's unchanged.  Sadly, this would make sense except that for whatever reason, this causes the browser to invert the UI state with respect to `.checked`.

Here's a fiddle showing the very odd browser behavior on its own:
https://jsfiddle.net/developit/q88ydmy5/

**Comment by MozMorris** [comment]
I suspected as much was happening. Have updated the docs.

**Comment by developit** [comment]
Perfect, we can close this out now since I've merge that PR!

**Comment by z-vr** [comment]
@developit but what if after the click on the checkbox I want the `checked` attributed to stay in accordance with the `checked` property, e.g., `<input checked={false}>`. Is it even possible?

**Comment by z-vr** [comment]
@developit also the wiki is not updated here https://github.com/developit/preact/wiki/Forms
