### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by abacaj** [developit/preact#25]
All of this is cool and all... but if I can't find out what browser this supports then I won't use it for anything in production :smile:

**Comment by developit** [comment]
I've tested on IE9+, Firefox evergreen, Chrome and Safari. It should work in IE8 but might require a polyfill for Object.keys.

**Comment by developit** [comment]
@abacaj If this answers your question let me know! I've added it to the Wiki:
https://github.com/developit/preact/wiki/Browser-Support

**Comment by abacaj** [comment]
Cool, looks good - not totally relevant to my original question but does Preact router fallback to # hash routing if history is not supported.. IE9 and lower or does it perform a full-page reload as the official react-router does?

**Comment by developit** [comment]
@abacaj Currently it uses HTML5 history only, falling back to reloads. Would be cake to add, but I didn't want the bloat. My own requirements don't necessitate hash routing but I'd be open to PRs for sure. Could also just have two routers and pick which one:

```js
const Router = history.pushState ? PreactRouter : HashRouter;

<Router />
```

**Comment by developit** [comment]
Feel free to mark as closed if you're good with this.
