### ISSUE TITLE
Re-render fails to remove elements properly

### ISSUE THREAD

**Issue by eldh** [developit/preact#257]
I'm really sorry for what will be suckiest issue description ever, but I noticed an issue in 5.6.0 where elements would not be removed from DOM on re-render (even though they should). It works fine in 5.5.0.

I will try to provide a proper repo with reproducible example as soon as I have time.

For now: screenshots to illustrate the issue:

1)
![screen shot 2016-08-04 at 17 20 38](https://cloud.githubusercontent.com/assets/612703/17407551/009a99c6-5a68-11e6-9303-6ac2cc8135fe.png)

Click Login with email:
2)
![screen shot 2016-08-04 at 17 20 03](https://cloud.githubusercontent.com/assets/612703/17407553/00c3a294-5a68-11e6-9720-40e78b244107.png)

**Comment by developit** [comment]
No problem @eldh - any clues as to what type of re-render is leaving them around?  Pure components, classes, or just nodes within a render?

**Comment by developit** [comment]
Here's what I'd think are the suspects:

https://github.com/developit/preact/commit/1bdbe4403d1df65403a7f9c4a9e5431afb645516#diff-86702919356dad82cf58b1e4150288f5R166

https://github.com/developit/preact/commit/1bdbe4403d1df65403a7f9c4a9e5431afb645516#diff-86702919356dad82cf58b1e4150288f5R165

**Comment by eldh** [comment]
Hm, perhaps this can give you some clue: Basically this is the code that's rendering in the above scenario:

```js
  renderForm() {
    const {method, action} = this.state
    const {onDone, locale, country, track, intent, scopes, prefill, noSwitch} = this.props
    return h(Box, {className: appForm, key: 'formWrapper'},
      (!method ?
        h(MethodChoice,
          {action, onDone, track, intent, scopes,
            onMethodChoice: this.onMethodChoice.bind(this)}
        ) :
        h(AuthForm, {prefill, track, intent, noSwitch, action, locale, country,
          scopes, onDone, onFBLogin: () => this.setState({method: null})})
      ),
      h(Legaleze, {action, className: classnames(center, topHalfMargin)}),
      (noSwitch ? null : this.renderSwitchAction())
    )
  }
```
...clicking the "Login with email" button sets a value to ´this.state.method`. So `MethodChoice` (which is the two big buttons in the first picture) should be unmounted, but instead it's left in the DOM underneath `AuthForm`.

**Comment by developit** [comment]
@eldh yes, that helps immensely. Sorry for the delay on fixing this, I'm in LA this week and super jetlagged for some reason!

**Comment by eldh** [comment]
Awesome and no worries! Let me know if you need more info!

**Comment by developit** [comment]
I have a fix for this by the way, just I'm wondering if the mechanism for swapping children in `5.5` was simpler/better.
