### ISSUE TITLE
Webpack pulling in a timers-browserify polyfill due to setImmediate variable

### ISSUE THREAD

**Issue by insin** [developit/preact#261]
Noticed this while bundling up the React Tutorial while testing nwb's new `--preact` flag. 

Seems to be purely because there's a variable named `setImmediate`. If I `s/setImmediate/smellMyCheeseYouMother/` in `node_modules/preact`, the app still works and the gzipped vendor bundle is about 0.8 KB smaller due to omitting the polyfill.

Related: https://github.com/webpack/webpack/issues/756

**Comment by developit** [comment]
Good catch! I'll rename it.
