### ISSUE TITLE
Extra stuff in npm package

### ISSUE THREAD

**Issue by insin** [developit/preact#262]
See https://npmcdn.com/preact@5.6.0/ - dotfiles, `config/` and `coverage/` are being included.

Does adding the following to `package.json` and removing `.npmignore` give the desired bundle when you `npm pack`?

```
"files": [
  "dist",
  "src"
]
```

**Comment by developit** [comment]
Back! Thanks. I'm not sure if that overrides a gitignore

**Comment by developit** [comment]
It does! 🎉
