### ISSUE TITLE
Text input ignores value attribute

### ISSUE THREAD

**Issue by vdemedes** [developit/preact#263]
Hey Jason, thanks for Preact, I love it!

I noticed a compatibility issue in Preact, when it behaves differently to React. The case is a simple component with `input[type="text"]` inside. No event listeners, no updates, just a static component:

```js
class TextInput extends Component {
  render({ value }) {
    return <input type="text" value={ value } />;
  }
}
```

In React, input field ignores user input and remains empty (as it should). In Preact, input field accepts all user input.

Here are minimal test cases to compare Preact to React:

- Preact - http://www.webpackbin.com/NJ_pr2zYW
- React - http://www.webpackbin.com/EJthihMYW

*Press "Save" button at the top to run the code.*

**Additional info:**
Preact version: 5.6.0

Thanks!

**Comment by developit** [comment]
Thanks @vdemedes!  This seems to be a side effect of Preact not overriding the browser's event handling.  I'm not sure how to proceed though, since that's one of the things that Preact intentionally eschews in order to remain as small and unintrusive as possible.  Maybe this is something that ends up needing to go into [preact-compat](https://git.io/preact-compat)?

**Comment by vvo** [comment]
I too have this issue. I have selenium tests running on IE11 and trying to fill a controlled input like this:

```js
        <input
          onChange={e => this.setState({from: e.target.value})}
          ref={type}
          type="number"
          value={this.state.from}
        />
```

If I send "123", it will fill with "1". 2 and 3 being ignored. This seems to be a timer problem somewhere.

Sorry this is very vague I agree and I cannot reproduce the issue manually, only when using IE11 and selenium. But the react build works that's for sure.

**Comment by developit** [comment]
@vvo does changing `onChange` to `onInput` cause all 3 characters to be accepted?

**Comment by vvo** [comment]
> @vvo does changing onChange to onInput cause all 3 characters to be accepted?

I tried that and the result was the same, sometime 113 would be 11 or 13 but most of the time it ends up being 1 in the input.

Maybe if we wrote a test simulating very close browser manipulation we would see it. I cannot refrain from adding this:

When I read "Batching of DOM updates, debounced/collated using setTimeout(1) (can also use requestAnimationFrame)" on the preact website. I think: "WARNING WARNING WARNING!" :D

**Comment by developit** [comment]
There are lots of tests in the suite that would fail if state batching didn't work as sync or tight async though - I've actually never had a bug show up relating to that (not to say it's impossible).

Try turning off batching:

```js
import { options } from 'preact';

options.debounceRendering = f => f();

// or:

options.syncComponentUpdates = true;
```

Here's a fiddle that shows the effects of batching on controlled inputs via `onChange`:
https://jsfiddle.net/developit/ufvm71L5/

**Comment by vvo** [comment]
> I've actually never had a bug show up relating to that (not to say it's impossible).

Do you also run the test suite on IE11?

**Comment by vvo** [comment]
Maybe that's just an issue of selenium not triggering the change events in a very clean way on the input on IE11. And somehow react solved it in their code maybe using some custom code. It's not worth it diving more in it (we solved it by changing the test a bit and adding a comment), sorry for interrupting

**Comment by developit** [comment]
Ah good point, I skipped over the browser specific bit.  I just pulled it up (and modified it to fire synthetic events) in IE11 on SauceLabs and it seemed to work:
https://jsfiddle.net/developit/ufvm71L5/19/

<img width="737" alt="screen shot 2016-08-29 at 11 15 15 am" src="https://cloud.githubusercontent.com/assets/105127/18056444/e1ec408a-6dd9-11e6-9909-d9eceb1873c1.png">

**Comment by developit** [comment]
Thought: I could have `preact-compat`'s `Component#setState()` be synchronous?  Right now it's just preact's.

**Comment by vvo** [comment]
I am all in for trying that in my selenium test, I will try to do so tomorrow just to see if that would do it. but setState is asyn in react right? So this should already be good.

**Comment by developit** [comment]
It is batched yeah, though the way preact batches will collect DOM updates as well.

**Comment by developit** [comment]
I believe any remaining issue here has been corrected by the fix for #327. Anyone able to confirm?

**Comment by developit** [comment]
I'm going to mark this as resolved for now, since the value pinning idea is unlikely to be feasible in Preact's size and the other DOM state issue [seems to be resolved](https://jsfiddle.net/developit/ufvm71L5/20/).  Shout if you think this should be re-opened!

**Comment by thinkloop** [comment]
> Text input ignores value attribute

Preact basically has react's uncontrolled inputs model. This means the dom maintains the input's state, and  input values are free to change as the user interacts with them, regardless of what new props are coming in.

Most of the time this is what is needed. Sometimes, however, it is important to be able to override existing values based on new props. For example, clearing a form after successful submission. To accomplish this, we can bind inputs to state, and use setState when new props come in. For example:

```
export default class Input extends Component {
  constructor({ inputValue }) {
    super();
    this.stateFromProps(inputValue);
  }

  componentWillReceiveProps({ inputValue }) {
    this.stateFromProps(inputValue);
  }

  render(props, { inputValue }) {
    return (
      <input value={ inputValue } />
    );
  }

  stateFromProps = (inputValue) => {
    this.setState({ inputValue });
  }
}
```

@developit thoughts?

**Comment by developit** [comment]
@thinkloop that's mostly true, though as of 6.3.0+ (including the just released 7.1.0) re-rendering an input will diff against its DOM state value.  The case where inputs are uncontrolled is only when you don't trigger a re-render in response to input.  I've found this is relatively uncommon, but let me know if you have a case where you're seeing it cause issues.  React does a lot of work to prevent inputs from accruing state at all (preventing input that isn't propagated into state through event handlers), but for a minimalist library like Preact that is just too much surface area.

I'm happy to discuss though, just it comes down to tradeoffs (like many things haha). I've found it best to re-render form fields in response to input anyway, which turns them into proper controlled inputs.

**Comment by thinkloop** [comment]
> the case where inputs are uncontrolled is only when you don't trigger a re-render in response to input

You're right! :-P

How does this work? How does preact know if a re-render is coming and to therefore to control the input?

For example, how would the [OP's demo](http://www.webpackbin.com/E1NOzxszM) be modified so that the input is controlled:

```
const { h, render, Component } = require('preact');

class TextInput extends Component {
  render({ value }) {
    value = value || 123;
    return (
      <input type="text" value={ 'tester' } onInput={ () => { bin.log('yo') }} />  
    );
  }
}

render(<TextInput value="" />, document.body);
```

**Comment by developit** [comment]
It works because the diff doesn't compare against the previous Virtual DOM tree, it compares against the DOM.  If the input's DOM state is out of sync with the tree, rendering pushes the value out to the DOM.

**Comment by bodaz** [comment]
struggling with how to make a controlled component in Preact...

```js
import { h, Component } from "preact"

class TextInput extends Component {
  state = {
    input: ""
  }
  render({}, { input }) {
    return (
      <input value={input} />
    )
  }
}
```
In React, `<input />` value would be empty even when the user types, how could we do this in Preact? For example, I'm trying to limit user's input so no spaces allowed...

**Comment by lukeed** [comment]
Attach an `onkeydown` listener. If it's not a space, update the state. Updating the state will then update your input value.

**Comment by deadlyicon** [comment]
I dont know if this is the same problem but I ran into a weird case where my `<input/>` was not respecting the given value. I'm using `preact-8.2.7` and `preact-compat-3.18.0`. 


```js
import React, { Component, PropTypes } from 'react'

import ErrorMessage from 'components/ErrorMessage'

import './index.sass'

export default class TextInput extends Component {
  static propTypes = {
    disabled: PropTypes.bool,
    className: PropTypes.string,
    onChange: PropTypes.func,
    onInput: PropTypes.func,
    onClick: PropTypes.func,
    type: PropTypes.string,
    name: PropTypes.string,
    value: PropTypes.string,
  }

  componentDidMount(){
    if (this.props.autofocus) this.input.focus()

    // THIS IS THE HACK THAT WORKED :(
    setTimeout(() => {
      if (this.input.value !== String(this.props.value)) this.forceUpdate()
    }, 10)
  }

  onChange = () => {
    if (this.props.onChange) this.props.onChange(this.input.value)
  }

  onInput = () => {
    if (this.props.onInput) this.props.onInput(this.input.value)
  }

  onClick = event => {
    if (this.props.onClick) this.props.onClick(event)
  }

  focus(){
    return this.input.focus()
  }

  render(){
    const {
      className = '',
      type = 'text',
      ...props
    } = this.props
    props.type = type
    props.onChange = this.onChange
    props.onInput = this.onInput
    delete props.onClick
    props.autoCapitalize = "none"
    props.autoCorrect = "off"

    return <div
      className={`TextInput ${className}`}
      disabled={props.disabled}
      onClick={this.onClick}
    >
      <div className="TextInput-wrapper">
        <input
          ref={input => { this.input = input }}
          {...props}
        />
      </div>
    </div>
  }
}
```

I hope this helps someone :(

**Comment by developit** [comment]
@deadlyicon are you providing a `value` prop to the input? (can't tell from the code sample since props is dynamic)

**Comment by deadlyicon** [comment]
@developit yes I am providing both a `value` and an `onChange` prop. I suspect this new bug behavior is a recent change in chrome but that's just a guess.

**Comment by dg-sserrano** [comment]
Still the same error in 10.4.0.

**Comment by JoviDeCroock** [comment]
@dg-sserrano this is an old issue, could you make a new one with a reproduction. It seems to work for me https://codesandbox.io/s/epic-snowflake-w7rwi?file=/src/index.js

**Comment by deadlyicon** [comment]
can you please link the new issue here so i can follow it too

**Comment by JoviDeCroock** [comment]
@deadlyicon I think the issue you posted above should be fixed in Preact X (gave it a quick glance)
