### ISSUE TITLE
Style attribute doesn't apply subsequent changes

### ISSUE THREAD

**Issue by legomushroom** [developit/preact#265]
Hi, 

I have a component with `render` method which sets `style` attribute on the root element:
```javascript
// ...
render () {
    const CLASSES  = require('../../css/blocks/curve-editor.postcss.css.json');

    const style = this._getStyle();
    console.log(style);

    return  (<div className={CLASSES['curve-editor']} style={ style } >
                </div>);
  }
// ..
```
When my `redux store` updates, the component gets re-rendered but the contents of the `style attribute` don't change at all - it remains at the initialization state. I can claim that the `style` variable changes and the component do updates because I see `console.log` outputs in the dev tools. Am I missing something? Would appreciate any help!

**Comment by developit** [comment]
Is `style` the same reference on subsequent renders, mutated in-place?

**Comment by legomushroom** [comment]
@developit thanks for the fast reply! The `style` variable has new (not mutated) `string` on each render and then is passed to the `style` attribute. I also tried to use an `object` (not mutated also)  in place of the string but no luck :/

**Comment by legomushroom** [comment]
@developit I'm using preact `^5.6.0`.

**Comment by developit** [comment]
Interesting - so this is happening regardless of whether `style` is a string or an object??

**Comment by legomushroom** [comment]
yup :/

**Comment by legomushroom** [comment]
I've added you to the repo I'm experiencing the issue in https://github.com/legomushroom/mojs-curve-editor . If you will take a time to investigate - you'll need to use the `dev` branch. There is `app.babel.jsx` entry point that renders `CurveEditor` component, which has the issue in the `render` method.

**Comment by legomushroom** [comment]
Interestingly, I noticed that `comonentWillUpdate` and `componentDidUpdate` lifecycle methods don't fire too. Seems like it acts like that because I do:
```javascript
store.subscribe( () => {
  this.render();
});
```
i.e. calling the `render` method on every `store` change. If I do `setState` calls with something generic I works fine:
```javascript
store.subscribe( () => {
  this.setState( { a: Math.random() } )
});
```
Is that intentional? I think react does allow you to call the `render` method like that and have style updates? I don't really need the inner componnet sate.

**Comment by developit** [comment]
@legomushroom Ah, so `this.render()` actually doesn't do anything, it just returns your JSX.  To trigger a render, use `this.setState({})` or `this.forceUpdate()`:

```js
store.subscribe( () => {
  this.forceUpdate();
});
```

This should actually fix both issues.
Let me know!

**Comment by legomushroom** [comment]
@developit works good, thanks for your support! 👍

**Comment by developit** [comment]
hooray! 🎉
