### ISSUE TITLE
[svg] `foreignObject`'s contents are invisible

### ISSUE THREAD

**Issue by amio** [developit/preact#278]
I couldn't figure out why but here is the example code:
https://esnextb.in/?gist=8983fe352fb6664e7f13716af7a12744

the same svg code works in a plain html:
https://jsfiddle.net/leaverou/qwg3r/

More infomation:
- Adding attribute `style="background-color: yellow"` to `<foreignObject />` has correct effect
- Adding attribute `style="background-color: yellow"` to foreignObject's children has no effect

**Comment by developit** [comment]
@amio Good catch - Preact [switches into an SVG mode](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L84-L86) during rendering, and needs to switch back out of that mode when encountering `<foreignObject>`.  We can use this issue to track fixing that oversight.

**Comment by developit** [comment]
Waiting on a couple more things in order to release this, but it looks like the fix works!

**Comment by amio** [comment]
Lighting fast! 👍

**Comment by developit** [comment]
Thanks! Hoping to get this released shortly.

**Comment by johnrees** [comment]
Just ran into this issue whilst using the latest preact-cli. Was a fix added?

**Comment by developit** [comment]
it's been fixed for a whilte!
