### ISSUE TITLE
test runner transformation

### ISSUE THREAD

**Issue by matthewmueller** [developit/preact#286]
Another idea that lends itself well to Preact's vnode abstraction is a super easy way to create frontend integration tests.

You could have something like this:

**index.js:**

``` js
const App = module.exports = (props) => {
  <div class="App">
     <button class="login" onClick={onClick}>Click Me!</button>
  </div>
}
```

**test.js:**

``` js
// This would walk the vnodes, and build a selector list along with their handlers
let $ = Runner(require('./app')(testProps))

// query the selector list and then trigger the handler
$('.login').click(e) // optional "e" that you could pass through
```

**Comment by developit** [comment]
@matthewmueller yes!! This is similar to [enzyme](https://github.com/airbnb/enzyme, just lighter. Super high on my to-do list!  That was actually why I wrote undom, as the faked rendering target that can still be queried and asserted on like a DOM.

**Comment by chrismatheson** [comment]
im just about to get into these sort of tests. Does enzyme work with preact? whats undom? currently as far as i can see my best option for testing would be jsdom, but that feels a bit heavy for what i want to do (trigger event handlers)

**Comment by wjagodfrey** [comment]
Also interested in this. Spiking a large react project migration to preact, and migrating tests will be a considerable overhead.

**Comment by developit** [comment]
@wjagodfrey which test framework(s) are you using?

**Comment by developit** [comment]
I feel horrible I missed @chrismatheson's question! [undom](https://github.com/developit/undom) is a tiny (~1kb) implementation of DOM Core I wrote that works well with Preact. It supports events - I actually designed it for basically the same case we're looking at here.  I'd really like to come up with a nice testing library based around undom and preact-jsx-chai, but I haven't had the time to devote to it, and Enzyme is such a well-thought-out solution on the React side that I don't really want to compete.

**Comment by developit** [comment]
I'm leaving this issue open because I think a great solution here would be to bundle up something like `undom` or `jsdom`, and maybe `cheerio` - mix them together to build a little VDOM assertion library.  If anyone wants to take on that task, I'd be happy to help out.

**Comment by wjagodfrey** [comment]
@developit Enzyme, Chai and Mocha. We have a few hundred tests using the render/shallow/mount methodology.

**Comment by developit** [comment]
Perfect, thanks @wjagodfrey - that's the lowest-hanging fruit in any case. If you have an example test you could safely share that would be great!

**Comment by marvinhagemeister** [comment]
If anyone stumbles upon this issue, we have great guide on how to use `preact` with `enzyme` on our main site: https://preactjs.com/guide/unit-testing-with-enzyme
