### ISSUE TITLE
input + datalist don't work

### ISSUE THREAD

**Issue by matthewmueller** [developit/preact#287]
This is rather obscure, but I was trying to get the new `<datalist>` element working with `<input type="range">` today. For some reason, Preact isn't picking up the `list="..."` element on the input.

Here's a working (non-working) example: http://jsfiddle.net/4apL8a8t/

Here's what it should look like: http://stackoverflow.com/questions/26612700/ticks-for-type-range-html-input

FWIW, it looks like it doesn't work in React either: https://github.com/facebook/react/issues/6717

**Comment by developit** [comment]
@matthewmueller Looks like we might need to blacklist using the `list` property so that it falls through to setting the `list` attribute.  If you change the case of the `list` prop it'll fall through already, so this actually works haha:
http://jsfiddle.net/developit/LLweb8jo/

**Comment by matthewmueller** [comment]
niceee ahhaa that works for me!
