### ISSUE TITLE
[Question] Does Preact support event capturing ?

### ISSUE THREAD

**Issue by bigopon** [developit/preact#293]
As titled, I tried `onClickCapture` but no luck. Wonder if it exists ? If not, how should I add it into my app ?

**Comment by developit** [comment]
@bigopon It does not, no.  By default there are 5 event types that are automatically registered with `useCapture` - you can see that list here:

https://github.com/developit/preact/blob/master/src/constants.js#L20

I believe the `*Capture` events are something we'd want to support via `preact-compat`, though I haven't yet thought of an elegant mechanism for doing that yet.

**Comment by bigopon** [comment]
Thanks, Idk why capture wasn't support but maybe bubbling is enough for me atm. Having it would be really nice though.

**Comment by bigopon** [comment]
Sorry, just curious, what are the differences between Preact and React events? How was React able to support `useCapture` ?

**Comment by developit** [comment]
React re-implements the entire HTML5 event model on top of delegate handlers, and changes the meaning of some events outright. Preact does not do this, instead aiming to work more similarly to how the browser works.

Just for reference - the bubbling behavior changed in Preact 6.0.0, so I'd recommend making sure that's the version you're running.

Cheers!
