### ISSUE TITLE
How to clear state properties?

### ISSUE THREAD

**Issue by dk00** [developit/preact#308]
See this [pen].

[pen]: http://codepen.io/dk0/pen/kkrGxj

Click some values other than `undefined`, then click `undefined`.

Setting state to other values works as expected, but `setState({value: void 1})` doesn't change the property, and there's no `replaceState`.

**Comment by developit** [comment]
Ah interesting. It should probably not skip undefined when copying!

As a workaround, you can pass a mutator function to setState:

```js
setState( state => {
    delete state.foo;
});
```

**Comment by developit** [comment]
Fix released in `6.1`.
