### ISSUE TITLE
Redux example or shim

### ISSUE THREAD

**Issue by tracker1** [developit/preact#31]
It would be nice to see `preact-redux`[1] and `preact-router-redux`[2] adapter similar to the corresponding react components.  So that a redux store can be used/connected to Preact component properties.

[1] https://github.com/rackt/react-redux
[2] https://github.com/rackt/react-router-redux

**Comment by developit** [comment]
100% agree, I'm dying to get a few minutes to put together even something as simple as a direct port. While it's likely possible to use [preact-compat](https://git.io/preact-compat) to import those directly, it's sub-optimal. Has been some discussion in the [gitter room](http://gitter.im/developit/preact) about this.

**Comment by andyhu** [comment]
+1

**Comment by developit** [comment]
I threw a working to-do example together:
https://github.com/developit/preact-redux-example

**Comment by developit** [comment]
Closing since this is now technically available. Any feedback on the linked example is greatly appreciated.

**Comment by lxe** [comment]
react-router-redux still suffers from incompatibility in syncHistoryWithStore:

```
sync.js:104 Uncaught TypeError: Cannot read property 'listen' of undefined
```

**Comment by developit** [comment]
@lxe hmm - are you trying to substitute preact-router in for react-router? They are very different. If you want to use react-router, just alias react out for preact-compat and use react-router itself.  It should be fully supported.
