### ISSUE TITLE
Any tipps on using Preact via CDN?

### ISSUE THREAD

**Issue by kay-is** [developit/preact#317]
I saw an example of using Preact directly in a browser, over CDN.

It's pretty nice for fast prototyping.

But one thing bothers me, the creation of VNodes is rather cumbersome.

I tried to use stuff like hyperscript, but it seems that the implementations I found either don't work with Preact or are only usable without babel etc.

I also looked into [t7](https://github.com/trueadm/t7) which runs directly in the browser, but their "Universal" v-dom nodes don't seem to be universal enough to work with Preact. 

Any tipps how to get a nicer interface to h?

**Comment by developit** [comment]
Hi @kay-is!

There are a few options here for sure.

### Easiest: [preact-hyperscript](https://github.com/queckezz/preact-hyperscript)

Pretty simple, though this might be too similar to the direct hyperscript (via `h()` calls) approach.

[Codepen Demo](http://codepen.io/queckezz/pen/XKkEyj?editors=1010) (hotlinked, no transpile step)

```js
var { createElement:h, div, h2, h3, button, ul, li } = preactHyperscript;

var App = () => div([
  h2('#subtitle', 'Preact is a fast, 3kb alternative to React, with the same ES2015 API'),
  button({ href: 'http://ghub.io/preact' }, 'Learn More'),
  h3('Features'),
  ul(['preact', 'small', 'es2015', 'fast'].map(key => li(key)))
]);

preact.render(h(App), document.body);
```

### Fairly Easy: Substack's [hyperx](https://github.com/substack/hyperx/)

This parses tagged template literals into VDOM. It's pretty elegant and making it work with preact is as simple as passing it preact's `h()`.

[JSFiddle Demo](https://jsfiddle.net/developit/2y9jes63/) (no compilation, CDN hotlinks only!)

```js
var FooComponent = props => hx`
  <div>
    <h1>${props.title}</h1>
    <a href=${props.link}>Go Somewhere!</a>
  </div>
`;

render(h(FooComponent), document.body);
```

This second option sounds like what you were trying to get t7 to do :)

**Comment by kay-is** [comment]
Ah nice, thank you :)

When I tried t7 with Preact I got a `React not found` error, so I added preact-compat and got an `in not usable on undefined` error on a `PropTypes` thingy.

Maybe I just got the script loading in the wrong order.

**Comment by Badestrand** [comment]
Sorry, I know this is an old thread but it still shows up on Google.

Here is a small template that uses preact and JSX in the browser: https://gist.github.com/Badestrand/641a22bfcdce66a65d5a07d518237507
