### ISSUE TITLE
Extension to 'Differences to React'

### ISSUE THREAD

**Issue by nickcolley** [developit/preact#32]
This project is really interesting thanks for sharing,

I've read through https://github.com/developit/preact/wiki/Differences-to-React and I'm really curious how this can be so much smaller than React, you mentioned you couldn't contribute upstream to React, what do you think React could do to make their build sizes smaller?

What are the biggest parts of React that you were able to avoid?

**Comment by developit** [comment]
Preact does not even attempt to support rendering targets other than the DOM, which removes a lot of complexity. The diff algorithm is far less complex than React's, which amounts to a fair bit of code (their diff is stellar).  Lastly, Preact does not include an event implementation of its own, it simply uses the browser's. Those three things mean there is a lot less indirection in the codebase, with fewer layers of abstraction (ex: creating an element is one function).

**Comment by nickcolley** [comment]
@developit thanks for replying that is interesting to know, I'll close this out! :+1: :D
