### ISSUE TITLE
compatibility with React developer tools

### ISSUE THREAD

**Issue by ddm-flipkart** [developit/preact#320]
React provides a convenient [chrome extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi/related?hl=en) as a debugger tool.

Preact doesn't seem to work with it. So, adding compatibility - is it in the road map?

**Comment by developit** [comment]
Yes, absolutely. I'm working under the assumption we can fake out the debugging API.

**Comment by developit** [comment]
Of note to others, and something I'd love to hear thoughts about:  I want this to be an add-on module, not actually shipped in Preact's core.  You'd `npm install preact-devtools` (or maybe `preact-debugger`?) and expose in in development like:

```js
import 'preact-devtools';  // auto-patches.
```

You can then really easily strip this out of your webpack bundle without build flags or anything (just using Dead Code Elim):

```js
if (module.hot) {
  require('preact-devtools');
  // HMR stuff
}
```

**Comment by wagerfield** [comment]
I would LOVE this! 😃

**Comment by ddm-flipkart** [comment]
Absolutely. Making it part of the core will bloat it and will damage the USP, it's size. And, not everyone uses the dev-tool. Hence, +1 to you sire @developit

**Comment by robertknight** [comment]
Fantastic work on preact @developit ! - I'm currently having a stab at this. The work in progress code is in this branch https://github.com/robertknight/preact/tree/devtools .

So far I have the basics working, although there are still issues to resolve in more complex components (eg. the markdown view in `preact-www` is not working on that branch) and tests to write:

![preact-devtools](https://cloud.githubusercontent.com/assets/2458/19016376/d3da7f66-880f-11e6-9cbc-89b53fc387a9.png)

The basic approach is to create minimal emulations of the `ReactComponentTree`, `ReactMount` and `ReactReconciler` interfaces that React exposes to devtools, plus functions that map preact components and DOM nodes to `ReactCompositeComponent` and `ReactDOMComponent`-like objects.

I have some questions about the implementation:

1. What's the best way to notify the devtools code when components are mounted, unmounted and updated? This is currently implemented by adding three hooks to the `options` object which are then invoked from preact's render/diff logic.
2. Functional components in preact are completely transparent (which is cool (!)), so no information about them is attached to DOM objects at all. This would make the hierarchy incomplete so I've solved this for now by wrapping all functional components using `Component`-based wrappers via an `options.vnode` hook. Are there any better/alternative ways of doing this?
3. The implementation is decoupled from preact's core so it doesn't have to be included in thedist  bundle, but it still depends on some internal details of preact's implementation and a few helper functions. For that reason I wonder if perhaps it should still live in the same repository, even if it is shipped as part of a separate package?

**Comment by developit** [comment]
Wow.... Man @robertknight you are a superstar....

1. You are probably best going with those hooks. Could also inject hooks into Component.prototype.
2. That's decent for now, and there is actually movement towards using a Component backing instance for pure functional components. That would give you the same format you're working withfor classful components. 
3. Could do, as a separate entry point. Or we can look into exposing whatever internals are needed. 

Amazing work!!!

**Comment by Download** [comment]
Just one question/remark:

> You can then really easily strip this out of your webpack bundle without build flags or anything (just using Dead Code Elim):
>
> ```js
> if (module.hot) {
>   require('preact-devtools');
>   // HMR stuff
> }
> ```

Does this actually work? I think you need a build step (webpack plugin etc) that actually replaces `module.hit` with a literal, e.g. `false`, for dead code elimination to work. Uglify is smart, but not smart enough to know the value of `module.hot` in advance.

Or is this possible without extra build step?

**Comment by ForsakenHarmony** [comment]
pretty sure webpack removes that completely

you can `import 'preact/debug'` which already includes a check internally

**Comment by Cromefire** [comment]
Okay I think you have to put this code **after** `render()`

**Comment by Sandstedt** [comment]
As the [debug page](https://github.com/developit/preact/#debug-mode) in readme suggest:

Set `process.env.NODE_ENV=development`

Add this in the end of your entry/root file.

```javascript
if (module.hot) {
  require('preact/debug')
}
```

In my configuration I cant get the states to update in the editor though. It only shows the initial states.

**Comment by jakub-g** [comment]
Note for future visitors: react devtools v4 (released August 2019) do not work with preact anymore; relevant issue: https://github.com/preactjs/preact/issues/1882
