### ISSUE TITLE
diffAttributes() skips updates in some cases

### ISSUE THREAD

**Issue by mootari** [developit/preact#327]
The DOM properties "min" and "max" of the input element are initialized as empty strings. Since [diffAttributes() uses weak comparison](https://github.com/developit/preact/blob/d32aa464dcc780015e483d6c99dbc07eed3afd09/src/vdom/diff.js#L252) when checking the new value against the old it fails to update either min or max when 0 is passed as value.

**Comment by developit** [comment]
Ah good catch. I don't think we need to keep the weak comparison, this would affect any diff of `0` and another false value. I can get a fix into 6.1 for the right away!

**Comment by mootari** [comment]
Sounds good! You'll probably want to cast ```attrs[name]``` to string though before comparing.

**Comment by developit** [comment]
Good call, that would keep the lazy typing semantic. Hopefully it's still cheap!
