### ISSUE TITLE
typo in the source code?

### ISSUE THREAD

**Issue by whwei** [developit/preact#33]
https://github.com/developit/preact/blob/master/src%2Fpreact.js#L202

```javascript
if (build.parentNode!==parent) {
```
`build` should be `built` ?

**Comment by developit** [comment]
Wow , thanks for spotting this! Would be causing a small performance drop in some of the benchmarks, so this is key! I'll get a fix in right away.

**Comment by developit** [comment]
@whwei Fix has just been released, version `2.8.3`.
