### ISSUE TITLE
props.children unavailable in stateless function

### ISSUE THREAD

**Issue by peter-mouland** [developit/preact#335]
I have tried to migrate from React and most of it went really well.

For some reason though, children for one of my stateless function were being ignored.  I can see that `children` has worked fine in other places. 

 In this instance though, the child is only a text node (rather than fully blown JSX), so not sure if this is anything to do with it?

the code I've used is here : https://github.com/peter-mouland/react-lego/compare/master...preact#diff-6e90eca97c3fe0837836dfe4f8472197R3

**Comment by developit** [comment]
Hi Peter!  In Preact, `props.children` is always an Array, even if there are no children or one child.  Perhaps that was triggering one of [these conditions](https://github.com/peter-mouland/react-lego/compare/master...preact#diff-6e90eca97c3fe0837836dfe4f8472197L5)?  Or were you seeing your `children` local variable there be `undefined`?

**Comment by developit** [comment]
Ah - perhaps this is the same root issue @devgeeks just ran into with 6.1.0 and React Router.

**Comment by peter-mouland** [comment]
thanks! it was because it was an array. apologies for not checking it out properly first... it was late 😴

**Comment by iam4x** [comment]
@developit Where's the issue from @devgeeks? It might the same thing I get...

**Comment by devgeeks** [comment]
@iam4x Sorry... didn't raise an issue like a decent human, heh. Just went straight to Gitter. 

I'll raise one now for public visibility.
