### ISSUE TITLE
Contents of noscript rendered

### ISSUE THREAD

**Issue by gdub22** [developit/preact#341]
https://jsfiddle.net/q4mo2cph/

If you check the Network panel, you can see the img inside the noscript is (incorrectly) loaded when rendered with preact.

```html
<div>
  <noscript>
    <img src="http://placekitten.com/100/100" />
  </noscript>
  <img data-src="http://placekitten.com/200/200" />
</div>
```

I use this pattern to lazy load images while also serving images to users without js via server-side rendering.

**Comment by developit** [comment]
Interesting. I'm not sure if there is a way around this...

**Comment by gdub22** [comment]
The browser (directly given some html) actually sets the content of `noscript` as `innerText`

https://jsfiddle.net/r0fe9spz/

**Comment by developit** [comment]
Right, but this is VDOM - JSX elements only ever represent elements, not inert strings. Does this work (and not issue network requests) when rendered with React?

**Comment by gdub22** [comment]
I got it working by using `preact-render-to-string`:
```jsx
const noscriptImg = __SERVER__ ? renderToString(<img src={ src } />) : ''
return (
  <div>
    <noscript dangerouslySetInnerHTML={ { __html: noscriptImg } } />
    <img data-src={ src }  />
  </div>
)
```

It appears to trigger network requests in React too, FWIW.

**Comment by developit** [comment]
Ahh that makes more sense. Maybe this warrants building your solution as a library? It doesn't seem like something Preact should handle out of the box.

**Comment by gdub22** [comment]
This solution is fine. Thanks for talking through.  Doesn't seem to affect rehydrating the ssr'ed content either.
