### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by Download** [developit/preact#343]
``` sh
c:\ws\preact> npm install

...

> preact@6.2.1 prepublish c:\ws\preact
> npm run build


> preact@6.2.1 build c:\ws\preact
> npm-run-all --silent clean transpile copy-flow-definition copy-typescript-definition strip optimize minify size

'cp' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "copy-flow-definition" exited with 1.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\v6.3.1\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! preact@6.2.1 build: `npm-run-all --silent clean transpile copy-flow-definition copy-typescript-definition strip optimize minify size`
npm ERR! Exit status 1
```

Also, I see files getting created named `$npm_package_aliases_main.js` etc and I guess that's wrong  :)

I will create a PR to see if we can make this build cross-platform together. I will need your help though as I don't yet fully understand how the build works.

**Comment by developit** [comment]
Ack! Sounds good, I think it will just be the `npm-scripts` that need to be adjusted.  Might just be a matter of adding [cross-env](https://npm.im/cross-env) as a prefix?

**Comment by Download** [comment]
I found this lib that will fix the cp issue I think:
https://www.npmjs.com/package/copy

But I'm really fuzzy on the `$npm_package_*` identifiers you are using. Do you have any pointers to info on these?

**Comment by Download** [comment]
I ended up using [copyfiles](https://npmjs.com/package/copyfiles) instead. It seems to work. The build is progressing further now, but I'm stuck on those `$npm_package_*` expressions. They don't work under Windows... 

```sh
c:\ws\preact> npm install

> preact@6.2.1 prepublish c:\ws\preact
> npm run build


> preact@6.2.1 build c:\ws\preact
> npm-run-all --silent clean transpile copy-flow-definition copy-typescript-definition strip optimize minify size

Skipping path dist/preact.dev.js which does not exist.
No files selected, nothing to do.
Skipping path dist/preact.dev.js which does not exist.
No files selected, nothing to do.
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'c:\ws\preact\${npm_package_dev_main}.map'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (C:\ws\preact\node_modules\uglify-js\bin\uglifyjs:290:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
 ERROR: "optimize" exited with 1.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\v6.3.1\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! preact@6.2.1 build: `npm-run-all --silent clean transpile copy-flow-definition copy-typescript-definition strip optimize minify size`
npm ERR! Exit status 1
```

It is failing now at the `strip` script, because that is referring to `dist/preact.dev.js`, but the file that got created is called $npm_package_dev_main

**Comment by Download** [comment]
Ok I got it to work. Will create a PR now.

**Comment by developit** [comment]
Cool! yeah sorry about that - those are environment variables defined by NPM during script running: https://docs.npmjs.com/misc/scripts#packagejson-vars

**Comment by Download** [comment]
Yeah I thought so. I'm not sure if there is a way to read those in a cross-platform way... Do you know if `cross-env` can do that? I think it's just for setting vars right?

The way I solved it now is with my own lib, `pkgcfg` that I wrote to be able to use transforms on the JSON to enrich it with things like references to other nodes in the tree, data from environment variables or just brute-force eval some JS. It's a bit heavy-handed for just a single env var though. Upside is this woks on my end so I'll leave it to you whether polluting the build with yet another dev dependency is worth it.

**Comment by developit** [comment]
Hey @Download - are we good to close this now that #344 is merged?

**Comment by Download** [comment]
Hi @developit 
I tested the new build script and it works!  👍 

```sh
c:\ws\preact> npm run build

> preact@6.4.0 build c:\ws\preact
> npm-run-all --silent clean transpile copy-flow-definition copy-typescript-definition strip optimize minify size

Inlining constant: NO_RENDER=0
Inlining constant: SYNC_RENDER=1
Inlining constant: FORCE_RENDER=2
Inlining constant: ASYNC_RENDER=3
WARN: Dropping side-effect-free statement [preact.dev.js:1047,4]
gzip size: 3852
```

The `release` task does not work due to the use of the `$npm_package_version`, but that's ok. These changes allow me to build and test and make PR's and that's what's important.

I do wonder what the issues with `pkgcfg` were that you encountered? Something happening twice you said?
