### ISSUE TITLE
Is Preact trimming too agressively?

### ISSUE THREAD

**Issue by Download** [developit/preact#346]
I noticed that Preact is a bit aggressive in trimming text. Markup like this:

```html
<h1>
	Preact Kickstart
	<sub>powered by preact</sub>
</h1>
```

Will render the text `'powered by preact'` right next to the text `'Preact Kickstart'`. However, I would expect that the newline and the tab/spaces after `'Kickstart'` and before the `<sub>` tag would be maintained (or at most trimmed down to a single space).

I also noticed that if we add a space after `<sub>` but before `'powered'`, it does make it into the final output, separating the words as expected. 

I would expect the text node with the text Preact Kickstart to contain this text: `' Preact Kickstart '` *(note the spaces)*.

**Comment by developit** [comment]
hmm - this is actually done by the JSX parser itself, preact doesn't trim whitespace at all.  `preact-render-to-string` does, but it provides an option to turn that off via `trim={false}`.

You can see babel doing its trimming in [this REPL example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015-loose%2Creact%2Cstage-0&experimental=true&loose=true&spec=false&playground=false&code=%2F**%20%40jsx%20h%20*%2F%0A%0A%3Ch1%3E%0A%20%20%20%20Preact%20Kickstart%0A%20%20%20%20%3Csub%3Epowered%20by%20preact%3C%2Fsub%3E%0A%3C%2Fh1%3E%0A).

For what it's worth, you can inject more arbitrary strings by using String literals:

```js
<h1>
    {' '}Preact Kickstart{' '}
    <sub>powered by preact</sub>
</h1>
// or:
<h1>
    {' Preact Kickstart '}
    <sub>powered by preact</sub>
</h1>
```

**Comment by developit** [comment]
Closing as per gitter discussion since this is just sort-of how JSX works!
