### ISSUE TITLE
Rerender occurs during event propagation

### ISSUE THREAD

**Issue by dk00** [developit/preact#356]
The component in this [example](http://codepen.io/anon/pen/rrKzzw) have following structure:
- ein
  - [zwei]
    - flip button

Clicking the flip button toggles the `flag`.
Parent elements also listen to click events, and increase their own counters only when `flag` is on, but they do the opposite when rendered with preact.

Event handling / rerender occurs in following order when the flag is off:
- `onClick` of the button
- Rerender
- Propagate the event (zwei)
- Rerender
- Propagate the event (ein)
- Rerender

`onClick` of the button toggles `flag`, and triggers rerender, then pass the event to the button's new parent element.

**Comment by developit** [comment]
Hmm - this seems to have become an issue since 5.7.0 (switching to 5.7.0 makes your codepen function identically across both preact and react).  I think this is a direct result of PR #271, which aimed to address #266. Pinging @i-like-robots since he seemed to know quite a bit about the details here.

For my own purposes, I have never needed event capturing and found the normal bubbling phase to be sufficient for the rare times I must rely on event delegation.

I guess this really comes down to a question of: should we be automatically deciding between capturing and bubbling phase on behalf of people like Preact currently does?  Or should we revert that and instead add support for the more explicit `on*Capture` notation?

**Comment by developit** [comment]
@dk00 hmm - now I can't get the demo to break?

**Comment by dk00** [comment]
I created [a simpler pen][another] to reproduce the issue.
[another]: http://codepen.io/anon/pen/amKRXb

Click the buttons to toggle the state. When rendered with preact, it pops an unexpected file upload after toggling from 'paste a link' to 'drag images'. Tested this with both 5.7.0 and 6.3.0, on chrome and firefox.

Conditional behaviors of this example component is arranged to expose the issue.

The original is too big to fit a pen. It has a 'Create Post' button, clicking on that button opens the post editor, ...... and pops a file upload of one of image slots, which is rendered by reusing the 'Create Post' button.

Maybe we can fix this by defer rerendering until events are completely handled?

**Comment by developit** [comment]
I'm not sure deferring rendering during event propagation (which is already synchronous) is a good idea - there are equally valid reasons to want rendering to happen during event propagation.

That said, if I simply remove the conditional placed around `.stopPropagation()` in your pen, it works as expected. I'm not sure why that conditional would be necessary:
http://codepen.io/developit/pen/zKaykP?editors=1010

**Comment by i-like-robots** [comment]
Am I correct in thinking that React binds events to the component root (or possibly global scope)? If this is the case then there is no possibility to respond to an event at each level of the tree as it bubbles/captures and subsequently cause many renders.

**Comment by developit** [comment]
Correct, it uses delegation bound at the root, though they manually reimplement capturing/bubbling on top of that, which I think opens up the same can of worms?

**Comment by dk00** [comment]
The conditional `stopPropagation` is necessary to expose the issue. 

I'm using `setTimeout` (defer it manually) [workaround]  in my project, and `stopPropagation` also works.

[workaround]: http://codepen.io/anon/pen/LRAqoN

The problem is, after first iteration of event propagation, the clicked button(Create Post) is recycled to render other component(sometimes Image Field 3), and the event is dispatch to its new parent(`onClick={props.popUpload}`), then accidentally pops the file upload.

I have to add workaround to every event handler to avoid unexpected triggering, it's a bit annoying.

**Comment by dk00** [comment]
Close in favor of #470
