### ISSUE TITLE
Use es2015 classes instead of util.extend

### ISSUE THREAD

**Issue by PaulBGD** [developit/preact#361]
One example where this would drop bytes is in the component.js file. Because of the util.extend use, the linkState method doesn't get remove because it appears as if it's needed. Because that's not removed, the createLinkedState method isn't remove and the methods that it depends on.

In my examples (removing the linkState method manually so that the methods it depends on are removed as well) it drops my final bundle size by 400 bytes.

**Comment by developit** [comment]
Hey Paul,

I can see some value here except that es classes transform to significantly larger bundle size (somewhere around 500b larger!) and also depend on Object.setPrototypeOf(). The latter is not the end of the world, but it would certainly make browser support more cumbersome. 

I've been meaning to test out switching from Babel (currently preact is built with Babel 5) to Bublé. Bublé transforms ES classes to something quite similar to the current implementation, but would still allow for your linkStste suggestion when using the modules source. 

Just so I know - are you using the prebuilt ES5 bundle, or `src/`?

**Comment by PaulBGD** [comment]
> es classes transform to significantly larger bundle size

Yeah, that's definitely down to how the transpiler handles classes.
I've used buble before, it's very fast and lightweight which is nice. But it doesn't support things like import statements, so you have to use it in conjunction with Rollup (I'm not arguing with that!)

I use the src/ directory with Rollup + TypeScript.

**Comment by PaulBGD** [comment]
If you're interested, I could open a PR using buble to compare the differences.

**Comment by developit** [comment]
Might be worth testing your bundle size using the provided `dist/preact.min.js` - for me that almost always produces a smaller bundle (likely due to the codemods). Build is already using Rollup so Bublé should be a simple change.

**Comment by PaulBGD** [comment]
My build is bigger (500+ bytes) when using the dist build.

**Comment by PaulBGD** [comment]
Babel + util.extend: gzip size: 3844 / 3.84 kB
Buble + ES2015 class: gzip size: 3862 / 3.86 kB

It appears that the reason that buble is bigger is because it constantly calls `Component.prototype`. I'll see if I can open a MR on buble for this.

![Image](https://i.imgur.com/gUBzih7.png)

**Comment by developit** [comment]
Here's hoping @Rich_Harris will be open to the suggestion :)
I'm thinking it could be enabled by Rollup when a method name is provided for the `objectAssign` config property...
