### ISSUE TITLE
Race condition causes failure in render queue

### ISSUE THREAD

**Issue by billneff79** [developit/preact#367]
I've got a project where part of my app is structured like the following.  That parent object has a onMouseMove handler that calculates new data that is rendered in the children.   The children themselves can re-render because it is auto-sizing the rect element to the size of the text element. 

What is happening, is that very consistently after about 800 mouse events are fired, preact stops calling the render function on my components entirely.  I dug around, and it turns out it's because it is hitting this line:

https://github.com/developit/preact/blob/master/src/render-queue.js#L11

When it fails, the component already has the `_dirty` flag set to true, so it never gets past the first check.  Since it fails that, rerender is never called.   In a nutshell, I'm not sure sure how I'm getting into this state, but once you do, you can't get out.

If I simply change the code on that line from:
`items.push(component)==1`
to
`items.push(component)>0`

then I no longer encounter this issue.  That could be fixing a symptom and not a root cause.

Based on other threads, I also added debounce stack trace rendering and I don't see any sort of rendering loop: 
````
import { options } from 'preact';

options.debounceRendering = fn => {
  console.trace('render');
  setTimeout(fn, 1);  // throttle updates at 1ms
};
````

````
<parent>
    <child/>
    <child/>
<parent>
````

pseudo-code for my setup:
````
class Parent {
...
    onMouseMove = () => {
    //do stuff
    this.setState({foo, bar})
   }

  render() {
    <div>
      <child label={this.state.foo}/>
      <child label={this.state.bar}/>
    </dvi>
  }
}

class Child {
  
  updateWidth = {
     //calculate bounding box of the text element to apply it to the rect element
     this.setState({width});
  }

  componentDidUpdate() {
    if(somethingChangeThatWouldEffectLengthOfBasisComponent)
      //I've verified that I don't have some ugly loop here - this is only being called as necessary
      this.updateWidth()
  }

  render() {
    //render an SVG rectangle sized to fit some SVG text
    return (
      <g>
        <rect width={this.state.width} />
        <text>{this.props.label}</text>
      </g>
    )
  }
}
````

**Comment by developit** [comment]
Update: this is actually a bug in Chrome m54, not an issue in Preact! 😄
https://twitter.com/_developit/status/788776980829175808
