### ISSUE TITLE
Use of onInput in docs

### ISSUE THREAD

**Issue by jakearchibald** [developit/preact#377]
https://preactjs.com/guide/linked-state#linked-state-to-the-rescue

`onInput` is used to update state, but https://facebook.github.io/react/docs/forms.html recommends avoiding `onInput` and using `onChange` instead. Might be worth changing to `onChange` or adding a note to explain why `onInput` should be used despite React's advice.

**Comment by developit** [comment]
Good point, it's definitely a little under-explained. `onInput` is used because preact doesn't change the behavior of the DOM `onchange` event like React does. Instead, it encourages using the existing browser events under their existing names.

**Comment by pl12133** [comment]
A footnote in the "Differences to React" section might help clarify this. https://github.com/pl12133/preact-www/commit/ffa906b704cf52ee39d3a3d705d3188b0cf39de7

**Comment by developit** [comment]
@pl12133's change [is published](https://preactjs.com/guide/differences-to-react#what-s-missing-), but I think it might be worth adding a blurb to the Linked State page abount onInput as well.

**Comment by rubencodes** [comment]
Not sure I entirely understand—is this is a breaking change when switching from React? If so would kindly suggest also adding a line about this under the [Switching to Preact](https://preactjs.com/guide/switching-to-preact) page :)

**Comment by developit** [comment]
Only if you're switching from React to Preact itself - if you're using `preact-compat`, `onChange` behaves the same as React's.

**Comment by danedavid** [comment]
What should be done here ? Update the [**Switching to Preact**](https://preactjs.com/guide/switching-to-preact) page ?

**Comment by marvinhagemeister** [comment]
I think we can safely close this. On https://preactjs.com/guide/differences-to-react we have a section about relying on native events and not using an abstraction like react does.

**Comment by dandv** [comment]
@marvinhagemeister: which section is that? The "Synthetic Events" bullet under "What's missing?"?

I think that should be expanded upon, at least to recommend using `onInput` instead of `onChange`.
