### ISSUE TITLE
Placeholder dissappears in IE11 on rerender

### ISSUE THREAD

**Issue by lohfu** [developit/preact#378]
When a textarea is present in a ES6 Class Component, the placeholder dissappears in Internet Explorer 11 if the state is changed and the component is rerendered.

I created a simple Codepen example at <http://codepen.io/lohfu/pen/qaeYjP>. The `TextareaTouchable` component changes the state on blur events. In IE11, this causes the placeholder to dissappear.

**Comment by developit** [comment]
@lohfu I don't have a quick way to test on IE11 right now, but what happens if you change the prop name to `placeHolder` (capital H)?

**Comment by lohfu** [comment]
@developit Thanks for a quick response... But no, that does not seem to affect the behavior.

**Comment by developit** [comment]
@lohfu IE9 doesn't support `<input placeholder>` - are you using a polyfill?

**Comment by lohfu** [comment]
I am only trying to support IE11...

**Comment by developit** [comment]
Ah sorry, mixed this up with a different issue that was 9-edge!

**Comment by robertknight** [comment]
IE 11 has some quirky behavior with placeholders where the placeholder content shows up as a child node of the `<textarea>` element. ie. For a textarea with a placeholder, "<textarea>.childNodes.length" returns 1.  My guess is that what is happening is that Preact tries to sync the VDOM node for the textarea (which has no children) with the DOM and ends up removing the DOM Node for the placeholder.

**Comment by developit** [comment]
@robertknight That is actually horrifying..

I'm guessing the `nodeType` of that placeholder element is also nothing useful that would indicate it should be skipped?

**Comment by robertknight** [comment]
Unfortunately not that I can see. `nodeType` returns `Node.TEXT_NODE`, I can't see any properties that would differentiate it from an ordinary text node.

**Comment by robertknight** [comment]
FWIW React deals with this by requiring the user to set `value` or `defaultValue` props for a textarea and disallowing passing children to a textarea element. When it updates a textarea, it then only mutates the value attribute and never modifies the child nodes. See `ReactDOMTextArea.js` in the React source.

**Comment by developit** [comment]
Hmm - yeah that seems like a decent solution since it's not a browser-specific hack or anything. Also pretty easy to bail out of the diff if `nodeName=='textarea'`

**Comment by developit** [comment]
This should be fixed in the next version since Preact will begin skipping elements it didn't create!

**Comment by lohfu** [comment]
@developit i just found a way to get around this... if you turn the `textarea` into a controlled component (which is required to function in IE11 anyway), and ensure you set `state.value` to undefined instead of empty strings the problem dissapears.

Ie...

```
class TextAreaState extends preact.Component {
  render(props, state) {
    return (
      preact.h('textarea', {
        class: {
          touched: state.touched
        },
        value: state.value,
        placeholder: 'TextareaState',
        onBlur: () => this.setState({ touched: true }),
        onInput: (e) => this.setState({ value: e.target.value || undefined }),
      })
    );
  }
}
```

I updated the codepen i linked to earlier to reflect the updates... <http://codepen.io/lohfu/pen/qaeYjP>

**Comment by developit** [comment]
Perfect, that's good to know. I really only ever use controlled inputs so that explains why this hadn't come up!

FWIW the uncontrolled textarea should be fixed on `master` (I am fairly certain but haven't tested in IE11 directly yet).

**Comment by developit** [comment]
@lohfu this should be fixed in version 7, available via `npm i -S preact@beta`. Re-open if not!
