### ISSUE TITLE
Preact remounts nodes when a child element is perpended

### ISSUE THREAD

**Issue by linde12** [developit/preact#394]
Hello!

I have an issue with Preact where Preact remounts my nodes in the DOM whenever a new node is prepended(an ELEMENT_NODE, not TEXT_NODE). This causes css transitions to break.

If my DOM tree looks like this:

```
<div id="parent">
  <div id="childA"></div>
  <div id="childB"></div>
</div>

```
And i then prepend a child via a Preact component, it will now look like this:
```
<div id="parent">
  <div id="newChild"></div>
  <input type="checkbox" id="childA-with-transition"></div> // removed and then placed into dom again
  <div id="childB"></div> // removed and then placed into dom again
</div>
```
This is troublesome because CSS transitions are broken. Let's say i have a smooth transition on my checkbox and as i check the checkbox something is prepended(It could be an error message) then the css-transition would be interrupted because the DOM node is remounted.

Watch(in chrome debugger) as the `<input>` element is remounted into the DOM whenever `<span>Required field</span>` is prepended. This example has react aliased to `preact-compat`:

```
import React from 'react';

class Field extends React.Component {
  constructor () {
    super();
    this.state = {checked: false};
    this.onChange = this.onChange.bind(this);
  }
  onChange () {
    this.setState({checked: !this.state.checked});
  }
  render () {
    const {checked} = this.state;
    return (
      <div>
        {checked ? '' : <span>Required field</span>}<br />
        <input type="checkbox" onChange={this.onChange} value={checked} />
      </div>
    )
  }
}

export default Field;
```

**Comment by developit** [comment]
Interesting issue - looking into it! It'd be solvable by adding keys, but I think that's inelegant. I'll let you know if I find something.

**Comment by ritz078** [comment]
Facing the same issue

**Comment by developit** [comment]
Ack! Looking into it! It's something to do with the way TextNodes are reconciled.

**Comment by developit** [comment]
This is my current top issue. Will be fixed ASAP!

**Comment by linde12** [comment]
Sweet! I'd love to see how you solve it so that i can get a better understanding of how the vdom in Preact works

**Comment by developit** [comment]
Have a fix incoming in the beta tag :)
