### ISSUE TITLE
[Feature Request] Allow omit props in h function

### ISSUE THREAD

**Issue by NicolasParada** [developit/preact#399]
Sometimes you are using preact from a CDN and you are not transpiling any jsx, you're just using the h function directly.
It would be nicer to allow omit the props.
For example:
```js
const HelloWorld = () =>
  h('h1', null, 'Hello, world!')
```
It could be writen as:
```js
const HelloWorld = () =>
  h('h1', 'Hello, world!')
```

**Comment by developit** [comment]
I'd actually really recommend trying out preact-hyperscript if you haven't, it adds even more stuff for using h() directly 😍

**Comment by NicolasParada** [comment]
I saw it, but never use it.

**Comment by NicolasParada** [comment]
It's like in Elm 😆

**Comment by developit** [comment]
Indeed! I suggested it because I think the other stuff it adds is equally useful for hyperscript use, but it's a little out of scope for preact core. Nicely integrated though.

**Comment by developit** [comment]
What should we do with this issue then? Maybe it's worth adding a page to the preact site for "integrations", and put some info there?

**Comment by NicolasParada** [comment]
`preact-hyperscript` is cool, but this unique feature could be in preact I think.
If you thinkf it's ok I could do the PR 😉

**Comment by developit** [comment]
I'm actually worried about the size increase and it de-opting `h()`, which would have a really big effect on performance. FWIW, any falsey value works so you could use 0.

**Comment by NicolasParada** [comment]
I see.

**Comment by developit** [comment]
Might still be worth checking what the file size impact is, so I'm open to the PR, just can't guarantee it'll be doable.
