### ISSUE TITLE
createElement does not exist in default preact.js library. This breaks typescript

### ISSUE THREAD

**Issue by nojvek** [developit/preact#403]
I see createElement being exposed in rollup aliases. I'm not sure why there are so many rollup targets. Its confusing.

why isn't createElement just bundled by default as an alias of h?

**Comment by developit** [comment]
@nojvek Use the provided TS definition, the React one doesn't make sense for Preact.  If you want 100% compat with React, you should alias `preact-compat`, which does export all of those things by default.

The extra alias is provided for those who cannot change their JSX pragma.  In the latest Typescript, you can set it to anything you want (including `h`): https://github.com/Microsoft/TypeScript/issues/9582#issuecomment-260202346

**Comment by nojvek** [comment]
Ahhh I see. It was jsxFactory compiler option.

I think I'll submit another PR for a little preact-typescript example.

Works with you?

**Comment by developit** [comment]
A typescript example would be amazing 😍
Repo or gist, either is fine. If you link it here, we can also add it to the website.

**Comment by developit** [comment]
@nojvek Should we keep this issue open, or close it since you're considering a more documentation-related PR? Cheers

**Comment by nojvek** [comment]
There are two ways to look at it.

JsxFactory is very new. It's not in the major Typescript build. I had
to install tsc@next which is in beta. I also had to change vscode
Typescript.sdk settings. All in all it seemed a bit of pain.

On the other hand
createElement is just an alias of h and only a minor change for compat
reason.

Export {h, h as createElement,...

I prefer having createElement as it will work with most tsc builds and sdks
in atom, vscode, sublime out of the box. It's not that disruptive and only
adds couple of bytes to the dist code.

I also think we should document the new way of using preact but show
the fallback incase someone's having an older tsc compiler.

I'll create a nice medium article and get back to you.

Thoughts?

**Comment by developit** [comment]
I'm pretty resistant to adding that alias to the default build - it's come up before and it just doesn't seem worth the cost given most people don't use it. There are currently no aliases at all in preact's core, and `createElement()` is entirely a compatibility thing - it is not a name anyone would choose if it weren't already a name React picked out of a hat.  Generally that means it's something that gets left to preact-compat, where all the crazy old aliases and legacy support stuff ends up.

One option is to alias `preact` to `preact/aliases`, which would get you `h()` and `createElement()` when importing `'preact'` - seems like the best of both as long as it is respected by IDEs and whatnot (I don't really use editor integrations so I'm not super up-to-date on what they support).  Another would be to create a standalone package like `preactsx` or something that does the re-export, maybe easing installation and linking.

Agreed regarding documentation though - it'd be good to show the old and the new way, and I think that'd actually be a great reference for people wondering why TypeScript has added the new `jsxFactory` option.  It was difficult to make the pitch for why it was preferable over the old limited option, so maybe your medium post can serve as an in-depth explanation of the advantages.

**Comment by developit** [comment]
Closing since TypeScript 2 is out of beta now and supports the custom pragma nicely, and we also now ship `preact/aliases` to cover this case. Let me know if I'm being presumptuous though :octocat:
