### ISSUE TITLE
Preact and custom elements

### ISSUE THREAD

**Issue by oskbor** [developit/preact#405]
Hello, 
I have a native custom element, lets call it `<custom-video-player>`.
It handles its own children. The children can be a `<video>` or an `<image>` for example.
Unfortunately preact clobbers the child dom that I create in my `createdCallback` and the entire component breaks. 
Is there an option I can pass in to make preact accept the component as it is and not traverse its children?
I am guessing this is related/identical to #39

**Comment by developit** [comment]
This is fixed in version 7. `npm I preact@beta`. 
Also I believe it only affects polyfilled custom Elements.

**Comment by oskbor** [comment]
woho! that works very well for me :+1: thanks

**Comment by developit** [comment]
Awesome, I really appreciate you opening this issue since I didn't have time to manually test this fix out myself. I was convinced it would work and I'm happy it does!  Thanks @oskbor!!

**Comment by tconroy** [comment]
Hi @oskbor -- I'm running into a similar issue you described (mine is #344). So my custom elements are rendering as-expected on initial page render, but when navigating to subsequent views (in a SPA etc), they stop updating.

They also maintain their own internal nodes, and after inspecting the nodes it seems like there contents have been wiped out. Seems like Preact is breaking the shadow dom for custom elements.

Wondering if you had to do anything in addition to get this working aside from just bumping preact version? I've tried the latest versions and still running into issues. :( 

Any input much apprecaited.

**Comment by oskbor** [comment]
Hi, I didn't need to do anything more, but also I didn't use shadow dom in
my component.
I no longer have access to that code base, so I can't dig into it any more.
Sorry I couldn't be more helpful
