### ISSUE TITLE
If node is moved, prop updates create a new node

### ISSUE THREAD

**Issue by mohsen1** [developit/preact#410]
I faced this issue when we migrated to Preact using Preact-compat. 

I had following Google Maps code that moves one of the nodes under Google Maps DOM element:

```ts
const rideCard = document.querySelector('main > article');
this.map.controls[google.maps.ControlPosition.BOTTOM_CENTER].push(rideCard);
```

With React, even though the element was moved out of its location it was still rendering with new props. But with Preact, we are seeing that element rendered twice after first new set of props change. One inside Google Maps div and another where it was located originally.

**Comment by mohsen1** [comment]
I might be wrong. Maybe React was doing this as well... I need to double check

**Comment by developit** [comment]
Hmm - this won't work in preact because it diffs against the DOM. I would recommend using something like [preact-portal](https://github.com/developit/preact-portal) or one of the similar libraries, to redirect rendering into an alternative parent element.

**Comment by mohsen1** [comment]
Thanks! `preact-portal` did worked for us. Because the map loads later I use Portal under the condition of map is loaded.

Great stuff! Thanks!

**Comment by developit** [comment]
Awesome! So happy that worked for you 😍
