### ISSUE TITLE
Component state leakage

### ISSUE THREAD

**Issue by slmgc** [developit/preact#413]
I found an issue with the state of a component in preact, for example:

```jsx
render(
    <Parent>
        <Child />
    </Parent>,
    document.body
)

class Parent extends Component {
     componentDidMount() {
          this.setState({FUBAR: true})
     }

     render() {
         return this.props.children
     }
}

class Child extends Component {
     render() {
         console.log(this.state) // <-- {FUBAR: true}, not undefined or {}
         return null
     }
}
```

As you can see, `Parent` leaks its state to `Child` because the default state object is reused across all components.

**Comment by developit** [comment]
Seems crazy this didn't come up before - maybe it's a regression? What version of preact by the way?

**Comment by slmgc** [comment]
"preact": "7.0.3",
"preact-compat": "3.9.2",

**Comment by slmgc** [comment]
I was able to reproduce it with `preact@6.4.0`. Checked in two different applications. Switching to React fixes the issue:
```
console.log(this.state) // <-- null
```
I think the reason why it didn't come up earlier was the missing state initialization, because you usually initialize the state in the constructor or in the class property:
```
class Parent extends Component {
    state = {} // <-- it works fine, because the default state object is replaced

    componentDidMount() {
         this.setState({FUBAR: true})
    }

     render() {
         return this.props.children
     }
}

class Child extends Component {
     render() {
         console.log(this.state) // <-- ok, returns {}
         return null
     }
}
```

**Comment by developit** [comment]
Is it possible this is related to preact-compat? Which `Component` class is that?

**Comment by slmgc** [comment]
Hm, it could be, I'm using `preact-compat`, so it's `React.Component` in my app.

**Comment by developit** [comment]
Ah ok I will scour that repo for a cause.

**Comment by slmgc** [comment]
Do you need a repo to reproduce this issue?

**Comment by developit** [comment]
I'm using this: https://jsfiddle.net/developit/rojcvahn/

**Comment by developit** [comment]
Can confirm, this only happens in preact-compat.

**Comment by ritz078** [comment]
Same problem here. Surely a preact-compat issue.

**Comment by developit** [comment]
Alright, let's prioritize this then, it's just too strange to leave open.

**Comment by ritz078** [comment]
working great 👍
