### ISSUE TITLE
Component root node changing is broken

### ISSUE THREAD

**Issue by localvoid** [developit/preact#414]
http://codepen.io/localvoid/pen/WojeKN

**Comment by developit** [comment]
@localvoid hmm - I'm not sure I'm seeing the bug?

![demo](https://i.gyazo.com/3fdcc52dd071027f57c00261b79c54b6.gif)

**Comment by slmgc** [comment]
@developit I think you were checking the wrong implementation, for React. The repro for Preact is here: https://jsfiddle.net/localvoid/h84zogmc/

**Comment by developit** [comment]
Bleh, shouldn't have done issue triage before finishing my morning coffee.

**Comment by ochervak** [comment]
what feedback needed ? this issue looks dangerous when using preact with preact-compat and react 3rd party libraries

**Comment by developit** [comment]
I had labelled it prior to realizing I was looking at the React version. It's a corner case that I have not yet seen any third party react library rely on, likely since very few libraries render the root element for a complete application.
