### ISSUE TITLE
Boot speed

### ISSUE THREAD

**Issue by chrisdavies** [developit/preact#416]
Preact is amazing, but it's boot-speed seems to be slow, per the tests referenced below.

I found this set of boot-speed tests, and added Preact and Mithril to the mix. The numbers are in milliseconds.

Preact: 563
https://plnkr.co/edit/GwYRps6ANxqgeCvcmf6S?p=preview

Vue: 236
http://plnkr.co/edit/KTqvngteLKmX3ZXMDyZO?p=preview

React: 104
https://plnkr.co/edit/TqrC3o5MIHQLWR0QIWaN?p=preview

Mithril: 40
https://plnkr.co/edit/JZtplOYAwA4u1exyebfO?p=preview

Mithril is hella fast. I'm surprised by Preact's performance. I thought I'd share.

**Comment by developit** [comment]
@chrisdavies wow! Thanks for investigating this😍
I figured out a way to speed things up for the initial boot, and the number went from `560` to `60`. I'll publish the fix ASAP!

**Comment by chrisdavies** [comment]
Sweet!

**Comment by developit** [comment]
I'm so happy you found this! This will also massively improve the performance of @PaulLewis' example he was needing the async renderer for!

#### Before:

<img width="242" alt="screen shot 2016-11-23 at 10 33 38 pm" src="https://cloud.githubusercontent.com/assets/105127/20585892/ed3b3626-b1cc-11e6-828f-0954fe7c2335.png">


#### After:

<img width="241" alt="screen shot 2016-11-23 at 10 31 20 pm" src="https://cloud.githubusercontent.com/assets/105127/20585867/a9b88098-b1cc-11e6-90b3-71f94dd454b3.png">

**Comment by chrisdavies** [comment]
A 10x improvement. Pretty impressive. Out of curiosity, what was the culprit?

**Comment by developit** [comment]
Preact always inserts using `.insertBefore()`, but that's incredibly slow when appending to the end of a long list of elements.  I just changed the diff so that if the iteration index is greater than the number of existing children, it always uses `.appendChild()`.

**Comment by leeoniya** [comment]
huh, this sounds suspicious. in my testing insertBefore and appendChild had the same profiles. gonna have to check it out.

**Comment by chrisdavies** [comment]
It might be a browser-specific thing, too. Not sure. My original results were Chrome on a relatively fast Mac.

**Comment by developit** [comment]
It's likely that insertBefore was shifting the list. The diff dynamically accesses `childNodes`, perhaps that was the expensive part. Either way, when the index of the current child is greater than the total previous children, there's no reason to check if it's a match for the current child.

**Comment by chrisdavies** [comment]
Yeah. Exactly. Shifting the list sounds like a reasonable explanation. Thanks for investigating and fixing so fast!

**Comment by developit** [comment]
I'm actually super happy about this haha. Now I want to test paul's stress test!

**Comment by leeoniya** [comment]
yes, accessing childNodes is very expensive for large number of children. it was almost certainly this.

PROTIP: always use firstChild, lastChild, nextSibling and previousSibling for dom itereration.

**Comment by developit** [comment]
@leeoniya yup, looking into that. `innerDiffNode` needs some love anyway, it's using sparse arrays.

**Comment by NicolasParada** [comment]
I don't understand a thing about those DOM manipulation thing, but kudos.
That boot speed up is amazing ❤

**Comment by lukeed** [comment]
Woot!! Any way we can get Inferno hooked up to this boot-time comparison? :innocent:

**Comment by yyx990803** [comment]
FYI, this boot test was using the dev version of Vue and not pre-compiling templates. It also is somewhat unfavorable against Vue (simple structure, large dataset count which makes Vue spend more time on data observation rather than rendering).

Aside from switching to prod mode, simply freezing inner items brings Vue's boot time to ~70ms: http://plnkr.co/edit/WDNuyd4WRYAuytNswoTf?p=preview

**Comment by developit** [comment]
@yyx990803 good to know! Preact's score was like double Vue's anyway before the fix, I don't think anyone was trying to call Vue out 👍

**Comment by chrisdavies** [comment]
Yeah. I didn't write the Vue tests. Just the preact one. I can't remember where I found these in the first place. I think it was in a Mithril support issue.
