### ISSUE TITLE
xlinkHref renders an 'href' attribute, not 'xlink:href' attribute

### ISSUE THREAD

**Issue by everdimension** [developit/preact#418]
Well, subject.
preact version: `6.4.0`

**Comment by developit** [comment]
On what type of element?

**Comment by everdimension** [comment]
`<use xlinkHref="#icon-name" />`

**Comment by developit** [comment]
Strange, I have demos of this working. Will check if there was a regression..

**Comment by everdimension** [comment]
Thanks!

**Comment by developit** [comment]
hmm - it definitely is still working:
https://jsfiddle.net/developit/0qgbw2sg/4/

Perhaps you're inserting the `<use />` prior to the href target being available?

**Comment by developit** [comment]
Might also be worth checking a second browser.

**Comment by everdimension** [comment]
Hm, you were right about inserting the `<use />` tag before target was available.

But still. If I have static `<use />` tags (inserted in raw html without javascript` with `xlink:href` tags, then it works even though the targets are loaded later.

I'm not completely sure, but I believe the reason is that `preact` strips the `xlink:` part.

In your jsfiddle example if you inspect the rendered elements you'll see that the `<use>` tag only has an `href` attribute.

**Comment by developit** [comment]
That's actually just an oddity with how attributes work from JS vs from HTML.  Preact uses [`.setAttributeNS()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttributeNS), which excludes the namespace ([explanation here](https://www.w3.org/Graphics/SVG/WG/wiki/Href#xlink:href)).

In that jsfiddle, if you grab the element in console and look at `$0.attributes`, you should see that the `xlink` attribute has the correct namespace.

CSS Tricks has an article that goes over some of these awkward bits, might be worth a read:
https://css-tricks.com/gotchas-on-getting-svg-into-production/#article-header-id-2

**Comment by developit** [comment]
@everdimension think we can close this out, at least in terms of being a preact issue? The oddity here is more about how inline SVG's work in HTML documents, not really about Preact itself.

**Comment by developit** [comment]
Closing for now but please feel free to discuss here on on gitter!

**Comment by rmales** [comment]
As far as I can see, when calling [`setAttributeNS`](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-ElSetAttrNS) the namespace prefix can 'optionally' be a part of the attribute (qualified) name. React uses the prefixed version, it might be worth doing the same if there is no downside?

(I've have a user report elements with `xlink:href` attributes becoming clickable links in Firefox 43, though I haven't been able to reproduce it.)

**Comment by developit** [comment]
@rmales You mean just to avoid stripping it out?

**Comment by rmales** [comment]
@developit I was actually looking into bug report which I thought might be related to this, but I think that is more likely a [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=847895).

It's probably not worth changing it, unless you want to match React or cover [some non-browser rendering cases](https://github.com/d3/d3/issues/291).

**Comment by developit** [comment]
@rmales I'm totally fine looking into this if adding the namespace to the `name` argument doesn't break anything.  Maybe it'll even let us shrink the size! 👍
