### ISSUE TITLE
Report test coverage to external service

### ISSUE THREAD

**Issue by mkautzmann** [developit/preact#420]
Hi.

I see we have a test coverage summary when testing. I wonder if we could publish it to a external service so we can easily keep track of it between changes.

The idea would be to modify the current `karma.conf.js` config to export an `lcov` file and publish it to a service like [coveralls](https://coveralls.io/) when testing in Travis.

Maybe even add a badge to the README stating the current test coverage.

What do you think?

**Comment by developit** [comment]
Coveralls and a badge for it would be amazing, I've had a todo item for ages to set that up. I haven't had to set that up before, but if you have I would be thrilled to merge that PR haha

**Comment by mkautzmann** [comment]
I can do the local changes and submit a PR.

Just remember that someone with admin access to `developit/preact` (like you @developit 😄 ) need to [set up the Coveralls side](https://coveralls.io/repos/new).

Thanks to the Travis CI/Coveralls built-in integration we should not need to setup any additional env variables in Travis.

I will submit the PR soon assuming that the Coveralls side is operational.

**Comment by developit** [comment]
Awesome I think I can set that up now

**Comment by developit** [comment]
It's so beautiful! thanks a million! I added you as a collaborator since you're much better at build setups than I am 😇

<img width="645" alt="screen shot 2016-11-29 at 3 17 53 pm" src="https://cloud.githubusercontent.com/assets/105127/20727330/12573c06-b647-11e6-8441-d60446e0b9df.png">

**Comment by mkautzmann** [comment]
WOW, thank you! 😎
