### ISSUE TITLE
Remote testing branches

### ISSUE THREAD

**Issue by mkautzmann** [developit/preact#424]
Currently we are running Sauce Labs on **pushes** to all branches. PRs are not included as of #390.

That is OK and working fine for PRs and pushes to `master`.

After checking the Greenkeeper behavior, I noticed that it pushes it's changes to a newly created local branch and then it creates a PR to `master`.

The problem is that it ends up starting two Travis jobs, one using Sauce Labs (push to branch) and one using local Chrome (PR). Since Sauce Labs connection can be flakey, it may not be ideal to use it to check dependency updates or even simple branch experiments.

I believe that we should only keep Sauce on for pushes to the `master` branch.

This seems right because the widget on README is related to `master` as well.

The question now is: how do we want to handle `beta`? Should we test it on Sauce Labs too or wait until it arrives on `master`?

**Comment by developit** [comment]
That would be ideal. I think we can ignore beta - I've just been using it to keep my nearly-merged work public so that people don't submit PRs against 6.x.  I'll merge it into master now :)

**Comment by developit** [comment]
Running sauce only on master was for some reason not working for me - I was trying to do it from within Karma, maybe it'd be simpler to just do that conditional in `npm run test`?

**Comment by mkautzmann** [comment]
OK, I'll see what I can do.

**Comment by mkautzmann** [comment]
OK, created branch `remote-testing` to test the new behavior.

Works fine so far (only Chrome running): https://travis-ci.org/developit/preact/builds/180537936

Now let's do a PR to `master` to complete walking through @greenkeeperio-bot's steps.

**Comment by mkautzmann** [comment]
OK, #426 got merged and Sauce Labs tests [ran successfully](https://travis-ci.org/developit/preact/builds/180693798).

I think this ends this remote testing quest 😄.

**Comment by developit** [comment]
Yay! 👍
