### ISSUE TITLE
Check for process.env === 'production' to not include devtools

### ISSUE THREAD

**Issue by mohsen1** [developit/preact#431]
Just wrapping entire module code in `if (process.env !== 'production') {}`  will do it. Most minifiers will remove the code in production.

**Comment by developit** [comment]
I don't mind including this at all (prevents accidental inclusion), but I actually recommend skipping the require altogether. 

```js
if (module.hot) {
  require('preact/devtools');
  module.hot.accept( ... );
}

**Comment by mohsen1** [comment]
Since you can't put `import`s under conditions, it's something I've seen other dev tools (MobX and React) do.

**Comment by developit** [comment]
Ahh very true! I guess also for Rollup et al. Sounds like a plan :)

**Comment by t47io** [comment]
This is a great ideas, but seem not yet implemented in `preact/devtools`?

**Comment by developit** [comment]
@t47io correct. PR's welcome!

**Comment by marvinhagemeister** [comment]
Already supported via `preact/debug` 💯
