### ISSUE TITLE
forceUpdate should take a callback

### ISSUE THREAD

**Issue by Stuk** [developit/preact#434]
As per the [React API docs](https://facebook.github.io/react/docs/react-component.html#forceupdate)

**Comment by developit** [comment]
Good catch! This is a strange one since `forceUpdate()` is always synchronous, so there is no real purpose to the callback. However, it should be cheap/free to add (just duplicating [this line](https://github.com/developit/preact/blob/master/src/component.js#L80)) so we're probably fine to add it.

**Comment by Stuk** [comment]
I think it's because React queues all component updates (e.g. in setState) and so in React it may not happen synchronously.

**Comment by developit** [comment]
I don't see anything in their docs about it, but maybe it's something preact is doing unnecessarily.  Perhaps `forceUpdate()` doesn't need to be synchronous and just has to bypass `shouldComponentUpdate()`...

**Comment by developit** [comment]
Released in 8.
