### ISSUE TITLE
span's orphaned after being added to the dom

### ISSUE THREAD

**Issue by gtibbitts** [developit/preact#437]
Hi,
I am using mdl (Material Design Lite) to render checkboxes on a menu. I am currently converting from React to preact. This works fine in React, however with preact, the checkboxes render the first time, but after the menu is closed and reopened they don't display. The issue is that mdl inserts several spans it uses into the dom. preact is removing these when the component is unmounted. I can add them back when the component is rendered, but hate to hack. I am using preact v7.1.0 and preact-compat v3.9.3. I am using webpack to bundle the code. I have tried this with mdl as a standalone library and mdl-react which is experimental. Both result in the same issue. Let me know if you need anything else. Thanks!

**Comment by developit** [comment]
Hi there! This library needs to be update to work with Preact 7+. For now, please use preact 6. Hopefully I will get to update it this weekend :)

**Comment by developit** [comment]
Actually scratch that! sorry, thought you said you were using preact-mdl.  The unmount issue is interesting - I think there's a check missing where it shouldn't remove elements it didn't create.

**Comment by gtibbitts** [comment]
I downgraded to 6.4.0 and that issue went away, so that resolved the
problem There must be something different in 7.1.0. The issue I'm having
now is the checkboxes don't actually uncheck like they did before. I'm
looking at that problem trying to determine why.

**Comment by gtibbitts** [comment]
In looking at my code, I was mistaken. I had disabled the mdl classes and that allowed this to work. Once I add them back in, it stops working. My apologies, I had forgotten where I was in trying to resolve this. I'm back to square one with the issue.

**Comment by developit** [comment]
I think we can get a fix into 7.1 for this. 6.4.0 will constantly remove elements when you re-renders if they weren't appended by preact itself.

**Comment by gtibbitts** [comment]
That would be most appreciated. One other issue I am having is with mdl-tooltip. When I hover over the element tagged with a mdl-tooltip class, it is supposed to append the is-active class. It is also supposed to insert a style attribute to the span. Neither of these occur with preact, but with React both succeed. Thanks for your help.

**Comment by gtibbitts** [comment]
Just an update to this. The problem with checkboxes seems to work with preact-mdl on preact 7.1. It doesn't work with react-mdl.

**Comment by developit** [comment]
Ah - this issue might be better migrated to the `preact-mdl` repo. It'll likely be fixed there.

**Comment by marvinhagemeister** [comment]
@gtibbitts If this is still a problem that should be solved in preact core, feel free to ping me.
