### ISSUE TITLE
Requesting feedback on my blog "Inner workings of Virtual DOM"

### ISSUE THREAD

**Issue by rajaraodv** [developit/preact#438]
I just finished draft of my blog "Inner workings of Virtual DOM" where I use Preact to go over various scenarios and explain how VDOM works. 
Really appreciate if you can take a look. 
https://medium.com/@rajaraodv/the-inner-workings-of-virtual-dom-666ee7ad47cf

Note: If there are any typos or issues, simply select the text and click on the "lock" tooltip. It allows you to leave me a private comment.

Thanks!

CC: @developit

**Comment by leeoniya** [comment]
@rajaraodv wow that's one heck of a writeup! it certainly doesnt that complex in my head but if i had to write it all out i guess it would be. I guess it shows how much more expressive code is than prose. The entire lib compresses to a tiny fraction of the blog post :)

**Comment by luisvinicius167** [comment]
Wow, great post! (Y)

**Comment by robertknight** [comment]
Thanks for writing this post! I'm going to close the issue now since it has been published - https://medium.com/@rajaraodv/the-inner-workings-of-virtual-dom-666ee7ad47cf#.haddaztcs
