### ISSUE TITLE
ReactDevTools doesn't see preact components in browser

### ISSUE THREAD

**Issue by budarin** [developit/preact#439]
open any demo and try to inspect it in ReactDevTools extension in chrome - but it doesn't present on a page.
meanwhile when open react demo - its present

**Comment by robertknight** [comment]
In order for devtools to be able to find Preact components, you need to load the `preact/devtools` module. See https://github.com/developit/preact#developer-tools

Unlike React, the devtools integration has to be loaded explicitly in Preact. This is done to keep the size of the core Preact library down.

If you have added the devtools module explicitly and it is still not working, let me know and I'll reopen this issue.

**Comment by budarin** [comment]
I'm sorry - I've missed it
Thanks!
