### ISSUE TITLE
SSR'd diffing taking ~2x the time of non-SSR'd boot.

### ISSUE THREAD

**Issue by paullewis** [developit/preact#445]
I've just pushed a blog post, and I've noticed that in 7.1.0 I'm seeing SSR'd content boot take upto 2x as long as Client-Side: https://aerotwist.com/blog/when-everything-is-important-nothing-is/

Looking at a timeline it seems it's mostly in the diffing.

![screen shot 2016-12-12 at 3 39 57 pm](https://cloud.githubusercontent.com/assets/617438/21105192/3e849406-c081-11e6-99fa-b6027eac5c01.png)

**Comment by developit** [comment]
Very strange that it's stripping nodes for sure. I can see how that would take 2x longer. There's some combination of components in the hierarchy that is being considered a mismatch when doing the initial render. I'm diving into your repo to take a look!

**Comment by developit** [comment]
Discovered the source! Since the HTML you're treating as the server render contains whitespace, Preact is diffing against that instead of the firstChild of `<section class="post">`. It's discarding the entire tree.

**Comment by matthewp** [comment]
Interesting findings. Since JSX treats whitespace differently than HTML is there anything you can do about this? Maybe ignore whitespace if it seems to be unimportant?

**Comment by developit** [comment]
Trying to look into the edge cases. It'd be something like "ignore whitespace nodes adjacent to element boundaries" (so leading/trailing whitespace, and whitespace-only Text node siblings of Elements).

**Comment by scurker** [comment]
What would be the most efficient way of helping to eliminate this in the short term? Would stripping white space on the SSR'd content do it? (i.e. with something like [htmlmin](https://www.npmjs.com/package/htmlmin)

**Comment by developit** [comment]
Yes. Using minified HTML entirely solves the issue.

**Comment by scurker** [comment]
Thanks @developit I didn't notice that preact-render-to-string already did that.

**Comment by developit** [comment]
Indeed! There's an option to turn on pretty whitespace (really just used because it can output JSX, which gets used in [preact-jsx-chai](https://github.com/developit/preact-jsx-chai)).

**Comment by Aweary** [comment]
Does it make sense to supporting diffing against HTML rendered by something other than Preact?

**Comment by developit** [comment]
To me it sortof comes down to whether it can reasonably be supported without adding much overhead.  I've been wrestling with that issue and I do have a fairly elegant solution that meets the need and only seems to add 30-40 bytes of overhead (not 0, but not a ton).

Another option we have at our disposal is modularity.  For example, to fix the whitespace issue Paul's demo showed, you could run this standalone function against the DOM prior to invoking Preact:

```js
// process(document.body);
function process(node) {
  if (node.nodeType==3 && !node.nodeValue.trim()) node.remove();
  for (var i=(node.childNodes || '').length; i--; ) process(node.childNodes[i]);
}
```

This is essentially the whitespace fix I've applied, but as a standalone module.

**Comment by matthewp** [comment]
I'm not a Preact user, so take this as a low value comment, but I think it's the correct thing to do. I don't think using Preact should require that you use Node.js and use Preact for server templating. Requiring that HTML be identical, including TextNodes, imo restricts Preact's usefulness.

**Comment by Aweary** [comment]
I'm not saying that it should require the HTML to be generated by Preact, but I do think it's reasonable that the responsibility should be on the user to make sure they're maintaining consistency with what Preact expects.

Deferring to an optional package that the user should include does exactly that, so I'm 👍 with that!

**Comment by developit** [comment]
Bah I'm so undecided on this. It's such a small amount of code to support the use-case. I'm going to keep running benchmarks and if I find something horrible about it at least that's a line in the sand. Right now I can't decided.

**Comment by chrisdavies** [comment]
For what it's worth, I'm of the same opinion as @aweary. I think it's fine if preact just clearly documents what is necessary to get isomorphic behavior working properly, but then leaves it up to the developer to make sure they do this correctly.

**Comment by developit** [comment]
Plus there's a module now that handles it for you, just have to invoke it on document.body.

**Comment by lukeed** [comment]
FWIW, Inferno gets around this by removing all whitespace during the compilation step via its `babel-plugin-jsx`.

**Comment by developit** [comment]
That happens in the default JSX plugin. Issue we ran I to here was whitespace in the server rendered HTML DOM. JSX rendered by preact-render-to-string never has extra whitespace, but this HTML wasn't re served by preact-render-to-string. Funky case but the fix was simple enough.

**Comment by developit** [comment]
The last bit of this is going into `8.0`, which involves having Preact's diff ignore whitespace-only nodes why doing SSR hydration.

**Comment by developit** [comment]
Fixed in 8!
