### ISSUE TITLE
React could do render array of components and function, but PReact - doesnt (

### ISSUE THREAD

**Issue by budarin** [developit/preact#457]
I love functions as child component technique (https://medium.com/merrickchristensen/function-as-child-components-5f3920a9ace9#.5led279v9), but it appear PReact doesnt support neither it nor render arrays of component (

**Comment by developit** [comment]
That technique works in preact, just use `props.children[0]`. In Preact, `props.children` is always an Array.

**Comment by NekR** [comment]
IMO `<Something render={() => { ... }} />` is better than putting function to the children.

**Comment by developit** [comment]
Closing since this will not change. It's worth noting, the technique you linked to works perfectly in [preact-compat](https://github.com/developit/preact-compat).  If you're looking for a perfect drop-in for React, that's probably the better way to go.

**Comment by budarin** [comment]
```
const App = () => {
    return [
        <h1>App</h1>,
        <img src={img1} />
    ];
};

const Container = ({ children }) => {
    return (<div>
        {children}
    </div>);
};

......
return render(
        <Container>
            <App />
        </Container>
    );
```

if I try to render this - I get :
[object Object],[object Object]

**Comment by developit** [comment]
You cannot return an array from a component. That would be a fragment, which is not supported.
