### ISSUE TITLE
PReact is not for complex async routing with code-splitting on server-side?

### ISSUE THREAD

**Issue by budarin** [developit/preact#458]
Am I right?
It is most for client side?

**Comment by developit** [comment]
No, It works the same as react for both cases. Use preact-render-to-string to render on the server side, and whatever your preferred approach to split points is.

We are looking into adding SSR and Bundle Splitting examples to preact-boilerplate.

**Comment by budarin** [comment]
Glad to hear about example - it would be the most important thing for those who want migrate to PReact!

**Comment by developit** [comment]
For sure! If you don't mind, I might add this example to the preact-compat README.
