### ISSUE TITLE
What's the catch?

### ISSUE THREAD

**Issue by tusharmath** [developit/preact#46]
If I can get all the features that react provides, then how can this be smaller? There should be some catch.

**Comment by developit** [comment]
Preact is inherently tied to the DOM, uses normal browser events, and doesn't have as complex of a diff algorithm. 

https://github.com/developit/preact/wiki/Differences-to-React#whats-missing

**Comment by developit** [comment]
Closing since it's in the wiki, but feel free to ask more if you don't think I've answered your question well enough!
