### ISSUE TITLE
Documentation on contextTypes support

### ISSUE THREAD

**Issue by nhunzaker** [developit/preact#460]
I was able to find documentation indicating that Preact supported contextTypes, but I didn't see much around how to implement them in Preact.

Preact doesn't bundle with a `PropTypes` module, which leaves some ambiguity around what the values should actually be. 

What are your thoughts on a document that goes through configuration context? I'd be happy to help.

**Comment by developit** [comment]
ContextTypes are not used by preact. Instead, context is always passed down rather than it being opt-in.  I guess that's why it's not really documented anywhere, in preact contextTypes just isn't a thing.  I think maybe it's worth putting a blurb on the [Differences To React](https://github.com/developit/preact-www/blob/master/content/guide/differences-to-react.md) page though?

**Comment by nhunzaker** [comment]
Oh interesting. Ya. I think so too. 👍.

**Comment by nhunzaker** [comment]
I don't want to be too assertive, but feel free to assign to me if you aren't feeling inspired to do this 😸

**Comment by developit** [comment]
Do it up! Just edit it via Github web, Travis takes care of the rest 😎

**Comment by NekR** [comment]
@developit I hope `context` is a getter, yeah?

**Comment by developit** [comment]
Nope! It's only cloned when calling `getChildContext()` so usage is free, creation is cheap.

**Comment by NekR** [comment]
@developit What i mean is this: imagine components are nested into each other and all have `getChildContext()`. Then the last nested one has 50 small components. Will those 50 components get `context` of all 10 ancestors on initialization regardless usage of that context?

**Comment by NekR** [comment]
That probably is not a real life use case, but having context as a getter may help with perf in such cases.

**Comment by developit** [comment]
ahh - so context is much simpler than that. rather then crawling up the tree to obtain a resolved/merged context object, it's actually built during render.  Only a re-render modifies context, and only at the point of `getChildContext()` and below.  In the case of your example, the context object is built up one time (during initial render) when rendering all the components with `getChildContext()`, and the 50 small child components simply receive the same object reference.

**Comment by NekR** [comment]
@developit I see, thanks for explanation. Sounds fine 🙂

**Comment by developit** [comment]
Closed now that @nhunzaker updated the docs :)
