### ISSUE TITLE
Recycling issues when rerendering 

### ISSUE THREAD

**Issue by arusanov** [developit/preact#461]
Hi, maybe it's not a bug at all, but I have some strange behavior in my project.
I wasn't able t reproduce it in jsfiddle so here's what I've discovered so far:

I have a button with attached `onClick` handler. When component containing this `button` is unmounted `button` HTMLElement got 'recycled' by 

https://github.com/developit/preact/blob/master/src/dom/recycler.js#L15

```
(nodes[name] || (nodes[name] = [])).push(node);
```

then when another instance of same component is mounted this `button` HTMLElement is getting back in 

https://github.com/developit/preact/blob/master/src/dom/recycler.js#L22

```
node = nodes[name] && nodes[name].pop() 
```

It has event handler `onClick` attached from previous use. 
Actually it's not an `onClick`, but it's `node._listeners` object with this handler.
And new event handler is not attached cause node ALREADY HAVE `_listeners` hash with given key from first time use pointing to an old function.

https://github.com/developit/preact/blob/master/src/dom/index.js#L60

```
if (!l[name]) node.addEventListener(name, eventProxy, !!NON_BUBBLING_EVENTS[name])
```

I've fixed it locally by removing any node recycling and creating new nodes every time.
Can you give me a short explanation why recycler work like this (storing element by element name and not taking into account other props)?

**Comment by developit** [comment]
It's keyed by name for a faster lookup, props wouldn't work because they are derived from immutable VNodes and would generally never be equal for subsequent renders. 

Your observation is interesting and another nailing the coffin for the element recycler. I think either we'll have to have it reset all props (easily done) or remove it entirely (already likely to happen in preact 8.0!).

**Comment by NekR** [comment]
@arusanov see this also: https://github.com/developit/preact/issues/459

> I've fixed it locally by removing any node recycling and creating new nodes every time.

Yeah, I did the same by commenting this mentioned line: `(nodes[name] || (nodes[name] = [])).push(node);`

**Comment by chrismatheson** [comment]
hi, i was just wondering if there is a work around for this problem (without hacking the preact lib itself? 😉  )

I've got some great stuff working with preact and id love to push out the next bit which is a rather large form. 😃 

happy to jump in and help if i can also, although this may be a long shot . . .

**Comment by developit** [comment]
I had indented to publish a short-term fix yesterday but got delayed with other things.  It'll be a minor performance impact though.

For forms there shouldn't be much of an issue as long as you use keys to prevent incorrect child reordering, and always maintain values in state (any kind of state) rather than relying on the DOM's internal state.

**Comment by cloudkite** [comment]
+1 for removing recycler in 8.0, getting alot of rendering artifacts when trying out preact on an older react app which sets styles directly on dom nodes in componentDidUpdate

**Comment by developit** [comment]
Heh - I'm assuming you are wanting to avoid changing that side effecting behavior 😁
I'll post some benchmarks soon.

**Comment by cloudkite** [comment]
@developit working towards getting rid of side effects 😀 . Unfortunately its not a small job as this app interfaces with a alot of jquery libs etc. Also think its also a trap for unwary as it breaks react compat

**Comment by developit** [comment]
Yup yup!  Just hate to have people waiting on `8.0` since it adds a lot of pressure on me 😅

**Comment by cloudkite** [comment]
No pressure at all, easy enough to point to local build with recycling
turned off. Thanks for your hard work on preact!

**Comment by rubencodes** [comment]
Wonder if this is why I'm seeing some unusual behavior with Bootstrap's tooltips as well—they're seemingly being attached "at random" to other elements (probably recycling I'm guessing).

**Comment by developit** [comment]
Yes! Recycling an element is probably not removing extra children, now that Preact allows those. Good point, and another nail in this coffin. Can't remove it soon enough 👍

**Comment by developit** [comment]
Fixed in 8.
