### ISSUE TITLE
Consider adding version number to exports.

### ISSUE THREAD

**Issue by thysultan** [developit/preact#479]
So in react, if you wanted to know the version of React an app is running you could do `React.version // => "15.0.0"`, this might be useful for preact when debugging to try to figure out what version of preact the live site is using if there's a bug.

**Comment by developit** [comment]
Makes sense, but I wonder - since preact is not a global, is it still useful despite not being visible from console?

**Comment by thysultan** [comment]
I guess when bundled with webpack you won't get that but you could mitigate this by exposing it when `window.window === window`;  when using return exports with a UMD like

```
!function(global, factory) {
'object' == typeof exports && 'undefined' != typeof module ? module.exports = factory(global) : 'function' == typeof define && define.amd ? define(factory(global)) : window.preact = factory(window);
}(this, function(window) {

...

var exports = {
    version: '7.1.0',
    h: h,
    cloneElement: cloneElement,
    Component: Component,
    render: render,
    rerender: rerender,
    options: options
};

if (window.window === window) window.preact = exports;
return exports;
```

**Comment by developit** [comment]
I'd be curious what the size hit would be. I agree it's nice to have. 

One thought: maybe a comment annotation in the source? They are free since comments are only pulled in via sourcemaps.

**Comment by thysultan** [comment]
~27 bytes gzipped...

```js
!function(global, factory) {
    'object' == typeof exports && 'undefined' != typeof module ? factory(exports) : 'function' == typeof define && define.amd ? define([ 'exports' ], factory) : factory(global.preact = global.preact || {});
}(this, function(e) {
    e.h = h;
    e.cloneElement = cloneElement;
    e.Component = Component;
    e.render = render;
    e.rerender = rerender;
    e.options = options;
});
```

vs

```js
!function(factory) {
'object' == typeof exports && 'undefined' != typeof module ? module.exports = factory(global) : 'function' == typeof define && define.amd ? define(factory(global)) : window.preact = factory(window);
}(function(w) {
var e = {
    version: '7.1.0',
    h: h,
    cloneElement: cloneElement,
    Component: Component,
    render: render,
    rerender: rerender,
    options: options
};
return w.window === w ? w.preact = e : e
});
```

But i somewhat see the concern, since preact is already at ~3.9kb gzipped there might not be much wiggle room if you wanted it to stay in the ~3kb mark.

**Comment by SleeplessByte** [comment]
Instead, add a cli command! So in your console you could do `preact -v` or `preact --version`

**Comment by developit** [comment]
@SleeplessByte that'll definitely be a feature if and when we release a sweet `preact-cli` 😉

**Comment by SleeplessByte** [comment]
Hehe. Do you need help?

**Comment by developit** [comment]
There are a bunch of efforts underway right now actually! If you're interested, you should totally drop into the [Preact Slack Channel](https://preact-slack.now.sh). Lots of people in there thinking about what a perfect CLI would look like.  In the meantime, I should note that [nwb's new QuickDevelopment mode](https://github.com/insin/nwb/blob/master/docs/guides/QuickDevelopment.md#example) is pretty sweet.

**Comment by marvinhagemeister** [comment]
Closing, because [preact-cli](https://github.com/developit/preact-cli) is released and adding the version to `window` can be done easily during the bundle step.
