### ISSUE TITLE
Setup Preact via <script> tag?

### ISSUE THREAD

**Issue by rafaelferreiraql** [developit/preact#484]
With React, you could simply upload it on your page via <script> tags, but the Preact docs only ever mention the npm route. At the same time, I'm aware Preact is hosted on [cdnjs](https://cdnjs.com/libraries/preact), but it doesn't seem to work, it's tailored to work only with ES6 import (which has no support from any browser).

**Comment by developit** [comment]
@rafaelferreiraql It works fine from the CDN. Preact and the examples are written in ES2015, but everything is actually shipped as ES3 / ES5.

Here's a CDNJS example ([view on JSFiddle](https://jsfiddle.net/rLprb9pc/)):

```html
<div id="root"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/preact/7.1.0/preact.js"></script>
<script>
  var h = preact.h;  // for convenience

  // an App classful component
  function App() {}
  App.prototype.render = function(props, state) {
    return h('div', { class:'app' },
      h('h1', null, 'Hello, World!'),
      h('ol', null,
        h('li', null, 'Item One'),
        h('li', null, 'Item Two')
      )
    );
  };

  // render the app
  preact.render(
    h(App),      // this is equivalent to <App />
    document.getElementById('root')
  );
</script>
```

**Comment by noway421** [comment]
You can also use unpkg.com:
```
    <script src="https://unpkg.com/preact@7.1.0"></script>
```

**Comment by developit** [comment]
yup yup. #protip the minified version is on there too:
`<script src="https://unpkg.com/preact/dist/preact.min.js"></script>`

**Comment by rafaelferreiraql** [comment]
It's a relief it's supposed to work via CDN too!

In fact, I found out what was the problem, I just didn't try to prefix h() or render(). In hindsight, those would be pretty nasty global variables to begin with.

Thanks for your help!

**Comment by avinashdvv** [comment]
@developit  how App is added to `h` function in preactjs if we write JSX?

**Comment by lukeed** [comment]
@avinashdvv To use JSX in a script tag, you'll need to include Babel runtime on your page as well. As mentioned above, it's recommended to avoid this if possible. However, if this is still something you need to do, you must include a JSX transformer preset or plugin for Babel (eg, `babel-preset-react`) and then tell Babel to use `h` or `preact.h`.

```js
/* @jsx preact.h */
preact.render(<h1>Demo</h1>, document.body); 

// or:

/* @jsx h */
var { render, h } = preact;
render(<h1>Demo</h1>, document.body); 
```

You're much better off (IMO) using the `h()` function directly since that's what Babel is returning as output anyway. I'd recommend you revisit Jason's answer above (https://github.com/developit/preact/issues/484#issuecomment-270023291) for more info.

**Comment by itsarnavsingh** [comment]
It's very simple
```
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.24.0/babel.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/preact/7.1.0/preact.js"></script>
<script>window.React = { createElement: preact.h }</script>

<script type='text/babel'>
    preact.render(<h1>we love preact</h1>, document.body);
 </script>

</head>
<body>
</body>
</html>
```

**Comment by ForsakenHarmony** [comment]
well if you use what luke posted above, you don't need to define `window.React`

**Comment by hacker-DOM** [comment]
https://github.com/preactjs/preact/issues/484#issuecomment-270023291

This snippet no longer works (it works as is, but not when preact==10.11.3 is loaded. It seems the new version no longer sets `global.preact`)

**Comment by developit** [comment]
@hacker-DOM the file is now called `preact.min.js` on that CDN (not sure why):

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/preact/10.11.3/preact.min.js"></script>
```

**Comment by developit** [comment]
For anyone finding this issue via Google, please use HTM instead of `h()` or Babel. It has vastly better performance than running Babel in your page, and is easier to type than `h()`.

### Preferred Script Tag Solution (2023)

```html
<script type="module">
  import { Component, render } from 'https://esm.sh/htm/preact';
  import { html } from 'https://esm.sh/htm/preact';

  /** If you're using hooks, you can import that from unpkg too: */
  // import { useState } from 'https://esm.sh/preact/hooks';

  function App() {
    return html`
      <div class="app">
        <h1>Hello, World!</h1>
        <ol>
          <li>Item One</li>
          <li>Item Two</li>
        </ol>
      </div>
    `;
  }

  // render <App /> into <body>
  render(html`<${App} />`, document.body);
</script>
```

<details>
<summary><strong>Or, if you can't use ES Modules</strong></summary>

```html
<!-- Load Preact's UMD build from CDNJS: -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/preact/10.11.3/preact.min.js"></script>

<!-- Load HTM from CDNJS: -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/htm/3.1.1/htm.min.js"></script>

<!-- If you're using hooks, you can get that from CDNJS too: -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/preact/10.11.3/hooks.umd.js"></script>

<script>
  const { h, Component, render } = preact;
  const html = htm.bind(h);

  function App() {
    return html`
      <div class="app">
        <h1>Hello, World!</h1>
        <ol>
          <li>Item One</li>
          <li>Item Two</li>
        </ol>
      </div>
    `;
  }

  // render <App /> into <body>
  render(html`<${App} />`, document.body);
</script>
```

</details>
