### ISSUE TITLE
spellcheck=false attribute can't be set

### ISSUE THREAD

**Issue by noway421** [developit/preact#485]
Looks like preact is replacing any value for spellcheck with true. 

So when I'm doing

```
class TextBox extends Component {
	render({ title, ph, value }) {
		return (<div class="form-group">
				<label for={ Util.mangle(title) }>{ title }</label>
				<input type="text" 
					id={ Util.mangle(title) } class="form-control" 
					placeholder={ ph } value={ value } 
					spellcheck="false" />
			</div>);
	}
}
```

it renders an element with `spellcheck="true"`

**Comment by developit** [comment]
What about with `spellcheck={false}`?

**Comment by noway421** [comment]
Then spellcheck attribute is not rendered at all. And by default spell check is still enabled :-(

**Comment by developit** [comment]
it would be setting the property, not the attribute.
Here's what preact is doing under the hood, which seems to work:
https://jsfiddle.net/developit/1vk3wu31/

**Comment by noway421** [comment]
I see. Indeed, it seems to be working with property just fine, attribute is not needed.

**Comment by developit** [comment]
awesome! Just for other who find this issue as well, you can also work with the spellcheck string attribute (rather than the property) by intentionally triggering a case mismatch in the prop name: `<input spellCheck="false">` - this will trick Preact into diffing against the attribute instead of the property.

**Comment by wilsonpage** [comment]
This just bit me, wasted well over an hour. Should this issue really be closed? The camel-case workaround fixed it for me.

```diff
-<input spellcheck="false" autocomplete="off" />
+<input spellCheck="false" autoComplete="off" />
```

**Comment by developit** [comment]
@wilsonpage hmm - "false" isn't correct there, use an actual Boolean:

```diff
-<input spellcheck="false" autocomplete="off" />
+<input spellcheck={false} autocomplete={false} />
```

**Comment by goliney** [comment]
`<input spellcheck={false} autocomplete={false} />` doesn't work for me, but camelcase does (`<input spellCheck="false" autoComplete="off" />`)

Thanks, @wilsonpage
