### ISSUE TITLE
doesn't work properly with react-css-modules

### ISSUE THREAD

**Issue by mqklin** [developit/preact#498]
[demo](https://github.com/mqklin/preact-css-modules-bug)

Only inner `styleName` compiles to 'class', but inners not. You can see that `div-2` value has `stylename` attribute, but should `class` as `div-1`.
![1](https://cloud.githubusercontent.com/assets/9456433/21816639/a79c086c-d782-11e6-9e67-a0d7481e4dbd.png)

---

Component code:
```
import React, { Component } from 'react';
import CSSModules from 'react-css-modules';
import styles from './styles.css';

@CSSModules(styles)
export default class App extends Component {
  render() {
    return (
      <div styleName="div-1">
        <div styleName="div-2">
          Big square should be red; <br /> Small square should be black.
        </div>
      </div>
    );
  }
}
```

styles.css:
```
.div-1 {
  width: 500px;
  height: 500px;
  background: red;
}

.div-2 {
  width: 200px;
  height: 200px;
  background: black;
  color: white;
}

```
---
How it looks:
![1](https://cloud.githubusercontent.com/assets/9456433/21816758/0f860586-d783-11e6-8af8-75a65435ad43.png)

How it should:
![1](https://cloud.githubusercontent.com/assets/9456433/21816791/33f1fa88-d783-11e6-9dea-5fd701c669d1.png)

**Comment by mkxml** [comment]
`react-css-modules` is not supported in preact core.

If you are willing to change the way you use CSS modules you can make it work today by changing your `App.js` file to be like this:
```javascript
import React, { Component } from 'react';
import styles from './styles.css';

export default class App extends Component {
  render() {
    return (
      <div class={styles["div-1"]}>
        <div class={styles["div-2"]}>
          Big square should be red; <br /> Small square should be black.
        </div>
      </div>
    );
  }
}
```

This way you don't need the decorator nor `react-css-modules`.

**Comment by developit** [comment]
@mkxml seems like he is using `preact-compat` - I was looking through the react-css-modules source to see if I could find where they're doing the VNode manipulation. Maybe just an issue with `vnode.props` being non-enumerable?

**Comment by mkxml** [comment]
@developit Hmm, with preact-compat it should work. Updated my comment.

**Comment by developit** [comment]
indeed - your comment is how I use CSS modules too 👌

**Comment by mqklin** [comment]
It's very verbose to write `styles` every time, css-modules allows to write it only once, that's why I use it. Will be very great for me if this will be fixed, I want to try preact in production. Thanks.

**Comment by developit** [comment]
@mqklin understandable! This will likely be solved over in `preact-compat`, but I'm fine tracking it here to avoid lots of issue juggling.

**Comment by mqklin** [comment]
Any progress on this issue? Maybe I should create issue in `react-css-modules` repo?

**Comment by developit** [comment]
@mqklin Might be useful - link me in there so maybe we can get more context. I'm not super familiar with react-css-modules, so any help is very much appreciated!

**Comment by mqklin** [comment]
I've migrated to styled-component. I don't think someone needs this issue to be fixed, so I'm closing it.

**Comment by pavelivanov** [comment]
so sad, hoped it to be fixed... =/

**Comment by evenfrost** [comment]
@developit maybe it could get a bit of attention for upcoming release of Preact X? I know this issue was a kind of dead-end, but I'm ready to help if had some clues where to start (have a little to no experience in Preact/Babel plugins development).

Currently `react-css-modules` moved to `babel-plugin-css-modules`, and here is corresponding issue in its repo: https://github.com/gajus/babel-plugin-react-css-modules/issues/250.

As for me, this is real helper in React project as you can switch from writing `className={styles.foo}` to just `styleName="foo"`, and would be awesome to use it in Preact projects as well.
