### ISSUE TITLE
Node reusage in IE 11

### ISSUE THREAD

**Issue by apfelbox** [developit/preact#499]
Hi, I have a component using the following code:

```js
return (
            <div className="file-browser-directory-listing">
                <div class="folder-view">
                    {parentDirectoryEntry}
                    {directory.subDirectories.map((subDir) => this.renderDirectoryEntry(subDir, false))}
                </div>
                <button type="button" className="button-add-subdirectory button button-link button-with-icon" onClick={() => this.initiateDirectoryAdd(directory)}>
                    <i className="icon icon-large icon-add" /> Unterverzeichnis hinzufügen
                </button>
            </div>
        );
```

I know have the problem in IE 11 that the node isn't properly reset when rendering, but instead the text node of the button with the text ("Unterverzeichnis hinzufügen") is just added and added again:

![2017-01-11 at 14 08](https://cloud.githubusercontent.com/assets/1032411/21849718/808a1932-d807-11e6-8d43-9e03bac03a0c.png)

Is there any known issue in IE 11?
I have the same issue nearly throught the complete app.

Installed version: `preact@7.1.0`

**Comment by apfelbox** [comment]
Ok, so I just rechecked the code in a VM on my machine, but there was no issue. It has to be an issue of the IE in this specific environment. Will keep investigating.

**Comment by mkxml** [comment]
It may be related to #430.

In that case the duplication happens only one time.

Can you test with the code that is currently in the `master` branch? We are looking to release the fix soon.

**Comment by apfelbox** [comment]
Thanks for the fast response!

I can confirm that the issue disappears when using `master`. 👍

**Comment by developit** [comment]
Yesssss
