### ISSUE TITLE
component constructor props

### ISSUE THREAD

**Issue by dimooze** [developit/preact#5]
Hi ! 

First of all thanks for this work ! 

I have a problem when I use props in my constructor from a Component 
```
export default class App extends Component {
  constructor(props) {
    super(props);
  }
}
```
props are always undefined. So i've found in the source that if i change createComponentFromVNode function like this 
```
function createComponentFromVNode(vnode) {
	console.log('createComponentFromVNode', vnode);
	let props = getNodeProps(vnode);
	let component = componentRecycler.create(vnode.nodeName, props);

	//let props = getNodeProps(vnode);
	console.log('les props', props);
	setComponentProps(component, props, NO_RENDER);
	renderComponent(component, DOM_RENDER);

	// let node = component.base;
	//if (!node._component) {
	//	node._component = component;
	//	node._componentConstructor = vnode.nodeName;
	//}

	return component.base;
}
```
and the corresponding create function 
```
create(ctor, props={}) {
  let list = componentRecycler.components[ctor.name];
  if (list && list.length) {
    for (let i=list.length; i--; ) {
      if (list[i].constructor===ctor) {
        return list.splice(i, 1)[0];
      }
    }
  }
  return new ctor(props);
}
```
It works fine, is that ok ? 

Thanks :)

**Comment by developit** [comment]
Hi @dimooze - yup, Preact was not passing props.  I can get a PR in for that change if you'd like, was about to do another one. 

If you don't mind my asking - what did you need `props` for within the constructor?

**Comment by developit** [comment]
@dimooze: Fix released in `2.5.0`. Thanks.

**Comment by dimooze** [comment]
Hey thanks for the merge ! 
I need it for react-redux Provider component :)

**Comment by developit** [comment]
Awesome, I was hoping you would say that :P
