### ISSUE TITLE
What is method like React.addons.batchedUpdates ?

### ISSUE THREAD

**Issue by windyGex** [developit/preact#509]
I want to write a library called `preact-test-utils` instead of `react-test-utils`, It only mock some apis that used in enzyme. The best problem is  `batchedUpdates `, `Simulate` , `findAllInRenderedTree`. What is your  suggestion ?

**Comment by robertknight** [comment]
If I understand correctly, `batchedUpdates` executes a user-provided callback and in the context of that callback, multiple `setState` calls on a component only result in a single-rerender of the component once the callback has finished running.

Preact does this batching by default, so `batchedUpdates` is unnecessary in the context of a normal application. When `setState` is called, the component is added to a queue of dirty components. All components on that queue are then rendered once in the next tick of the event loop.

In the source code, see `src/component.js` and `src/render-queue.js`.

If you want to flush the queue of pending updates synchronously rather than waiting for the next tick of the event loop, call the `rerender` function that Preact exports.

**Comment by robertknight** [comment]
See also https://github.com/developit/preact/issues/146

**Comment by developit** [comment]
@robertknight - good point about `rerender()`!

**Comment by windyGex** [comment]
And, What about `findAllInRenderedTree`? Any hooks like react ?

![image](https://cloud.githubusercontent.com/assets/197348/21972316/b2bc4732-dbf3-11e6-98d1-8b2bd98e6898.png)

**Comment by developit** [comment]
@windyGex That's probably a good library to write.  You can either crawl the DOM and look for `._component` properties, which recursively lead to components (including compositional components), or crawl the VDOM tree doing the same.

Here's an example that does the former:
https://gist.github.com/developit/63ffcd531381bee5a3d9959e3a90035b

**Comment by windyGex** [comment]
Ok. Now I can mock `findAllInRenderedTree` method, but I can't find hook like react when access vnode from instance, Could you add this to component instance? I'm not sure whether to add here。

https://github.com/developit/preact/blob/master/src/vdom/component.js#L204

#### React instance 

![image](https://cloud.githubusercontent.com/assets/197348/22179774/43800d1e-e098-11e6-8e14-c58811ec5cf0.png)

#### Preact compat instance

![image](https://cloud.githubusercontent.com/assets/197348/22179784/70b701de-e098-11e6-804a-7433d08a5709.png)

**Comment by windyGex** [comment]
Well, I find code from here, and I redefine this code.

https://github.com/developit/preact/blob/master/devtools/devtools.js#L32

```js
import preact from 'preact-compat';
const ATTR_KEY = typeof Symbol ==='function' ? Symbol.for('preactattr') : '__preactattr_';
const REACT_ELEMENT_TYPE = (typeof Symbol === 'function' && Symbol.for && Symbol.for('react.element')) || 0xeac7;
const Component = preact.Component;

function extend(base, props) {
	for (let key in props) {
		if (props.hasOwnProperty(key)) {
			base[key] = props[key];
		}
	}
	return base;
}

function createReactDOMComponent(node) {
    const childNodes = node.nodeType === 1 ? Array.from(node.childNodes) : [];
    const isText = node.nodeType === 3;
    return  {
        _currentElement: isText ? node.textContent : {
            $$typeof: REACT_ELEMENT_TYPE,
            type: node.nodeName.toLowerCase(),
            // Here are different from the react
            // react contains children
            // but polyfill have not
            props: node[ATTR_KEY]
        },
        // Here react return null
       //  but polyfill return array and contains a element
        _renderedChildren: childNodes.map(function(child){
            return child._component || child;
        }),
        getPublicInstance() {
            return node;
        },
        _stringText: isText ? node.textContent : null
    }
}

function createReactCompositeComponent(component) {
    const _currentElement = createReactElement(component);
    const node = component.base;
    return {
        _instance: component,
        _currentElement,
        _renderedComponent: createReactDOMComponent(node)
    }
}

function createReactElement(component) {
    return  {
        $$typeof: REACT_ELEMENT_TYPE,
        type: component.constructor,
        key: component.key,
        ref: null,
        props: component.props,
        // dev mode, we don't need
        _store: {}
    }
}

function patch (component) {
    extend(component._reactInternalInstance, createReactCompositeComponent(component));
}

function PolyfillComponent(props, context, opts){
    Component.call(this, props, context);
    this._reactInternalInstance = {};
    
    const component = this;
    const componentDidMount = component.componentDidMount;
    const componentDidUpate = component.componentDidUpate;
    this.componentDidMount = function() {
        patch(component);
        if (componentDidMount) {
            componentDidMount.apply(component, arguments);
        }
    }
    this.componentDidUpdate = function() {
        patch(component);
        if (componentDidUpdate) {
            componentDidUpdate.apply(component, arguments);
        }
    }
}

PolyfillComponent.prototype = new Component();

PolyfillComponent.prototype.constructor = PolyfillComponent;

preact.Component = PolyfillComponent;

export default preact;
```

but it has a problem that mock `_currentElement` from dom nodes。For examples

```js
class App extends React.Component {
   render() {
     return <div>123</div>
   }
   componentDidMount() {
     console.log(this)
  }
}

ReactDOM.render(<App/>, document.getElementbyId('app'))
```
If mock from dom nodes, the result will be difference from react, Any way can process?

@developit @robertknight 

#### React Result
![image](https://cloud.githubusercontent.com/assets/197348/22194489/ca387f4a-e17d-11e6-8401-1de665cd81eb.png)

![image](https://cloud.githubusercontent.com/assets/197348/22194497/d9ed2df0-e17d-11e6-98a4-4d7d7dcbf83d.png)


#### Preact polyfill Result

![image](https://cloud.githubusercontent.com/assets/197348/22194395/10320daa-e17d-11e6-9391-8d8a2f266fdb.png)

**Comment by developit** [comment]
You might be able to mock that out:

```js
import { options } from 'preact';

let old = options.vnode;
options.vnode = vnode => {
  let f = vnode.nodeName;
  // wrap the `render()` method for all Components (unless already wrapped)
  if (typeof f==='function' && f.prototype && f.prototype.render && !f.protoype._originalRender) {
    f.prototype._originalRender = f.prototype.render;
    f.prototype.render = injectedRender;
  }
  if (old) old(vnode);
};

// a wrapper around render() that retains a reference to the returned VNode
function injectedRender() {
  let vnode = this._originalRender.apply(this, arguments);
  let inst = this._reactInternalInstance || (this._reactInternalInstance = {});
  inst._currentElement = vnode;
  return vnode;
}
```

**Comment by windyGex** [comment]
Thx for your quick reply. I‘m so sorry, I still have a problem about [`ShallowRenderer`](https://github.com/facebook/react/blob/master/src/test/ReactShallowRenderer.js). It looks need to modify internal code of preact, is right?

**Comment by developit** [comment]
@windyGex I've been wanting to implement a `preact-shallow-render` module, which would probably meet that usecase.  It should just render VDOM to resolved VDOM - useful for testing.

**Comment by pracucci** [comment]
@developit is there any news on the ShallowRenderer on preact?

**Comment by developit** [comment]
No, not at this time.

**Comment by robertknight** [comment]
I'm closing this issue as the original question was answered above. Feel free to continue the other discussion.
