### ISSUE TITLE
element with attr `key` will not be removed after rerender

### ISSUE THREAD

**Issue by foray1010** [developit/preact#51]
My case:
1. render [node 1, node 2, node 3]
2. render again with only [node 4]
3. result in [node 1, node 4, node 2, node 3] in the DOM

all the nodes have different `key`

if I remove the `key`, the result will be only [node 4] in the DOM which is as expected

**Comment by developit** [comment]
Thanks for the bug report! Which version of preact are you seeing this with?

**Comment by foray1010** [comment]
I am using `3.3.0`

**Comment by developit** [comment]
Sure, that would be great. Imbusing your first example as a unit test already :)

**Comment by developit** [comment]
This is fixed in `3.4.0`! Please let me know if you still see the issue.

**Comment by foray1010** [comment]
Work like a charm!

**Comment by developit** [comment]
:100:
