### ISSUE TITLE
Event handlers are not attached when rendering over preact-render-to-string

### ISSUE THREAD

**Issue by vandrijevik** [developit/preact#520]
I am noticing the following with `preact-render-to-string`, and rendering a component that has event handlers:

1. I render the component on the server via `preact-render-to-string`.
1. In the browser, the exact same component is rendered in the same element, with the same props.
1. The `onChange` handler is not registered for radio buttons inside the component, and clicking on them does nothing.

By contrast, if I omit step 1 (server rendering), the event handlers are registered properly, and clicking has the expected effect (it executes the specified handler).

It _seems_ to me that when `preact` computes a diff in the browser, it does not take into account that the only differences may be event handlers, so it does nothing because there are no content updates. That’s why I am posting in this repo, rather than `preact-render-to-string`.

**Comment by vandrijevik** [comment]
Sorry about this, it seems to have been related to problems I am having getting the browser’s `render` call to merge into the HTML rendered by the server (instead of append), and not any event handling. Closing.

**Comment by developit** [comment]
Good to know, and thanks for following up!  FWIW I've been working hard on the way Preact's diff merges with static HTML, so there will be much fewer cases in 8.x that cause appends where you'd think it would merge.

**Comment by ashokvishwakarma** [comment]
@developit any updates on this?
