### ISSUE TITLE
h() missing from README.md example?

### ISSUE THREAD

**Issue by Pomax** [developit/preact#521]
The README.md example says to use
```
import { h, render } from 'preact';

render((
    <div id="foo">
        <span>Hello, world!</span>
        <button onClick={ e => alert("hi!") }>Click Me</button>
    </div>
), document.body);
```
but this makes `h` an unused import... should that be `render(h(....))`?

**Comment by ForsakenHarmony** [comment]
no, the generated code contains h

i.e. `<div id="foo">` will be transpiled to `h('div', {id: "foo"})` or smth like that

**Comment by Pomax** [comment]
oh, I see! As someone who'd never heard of hyperscript or one of its many friends that bit of information seemed to be missing from the README.md (since the examples above it contained special babel instructions, but this example did not)

**Comment by vutran** [comment]
@developit wrote a great article on [WTF is JSX](https://jasonformat.com/wtf-is-jsx/)/hyperscript. It's worth a read.

**Comment by Pomax** [comment]
Thanks, I'll definitely give that a read!

But, as someone who is super comfortable with JSX (I've written several longreads about react with jsx back when we were on React 0.12) and despite that had never heard of hyperscript. Tech stack bubbles are weird =)

**Comment by developit** [comment]
Agreed - are you able to suggest a specific place in the readme ([or the getting started guide](https://preactjs.com/guide/getting-started)) where you think a little `<aside>` type description might have been best for you as a reader?  I'm happy to write it, just not sure where it should go.  It's also possible the readme and Getting Started guide are now out-of-sync.

**Comment by Pomax** [comment]
I think the right place would be below the example, as an extension on the text that is already there:

>"This should seem pretty straightforward if you've used hyperscript or one of its many friends. If you're not, the short of it is that the `h` function import gets used in the final, transpiled code as a drop in replacement for `React.createElement`, and so needs to be imported even if you don't explicitly use it in the code you write. Also note that if you're the kind of person who likes writing your React code in "pure JavaScript" (you know who you are) you will need to use `h(...)` wherever you would otherwise use `React.createElement`."

Or something to that effect?

**Comment by developit** [comment]
Works for me!

**Comment by Pomax** [comment]
PR filed
