### ISSUE TITLE
Text next to input gets added multiple times after update in IE11

### ISSUE THREAD

**Issue by richardhinkamp** [developit/preact#525]
http://jsfiddle.net/u9m5x0L7/90/
I changed the clock demo so the time is in an input and has a " %" suffix. This works as expected in Chrome, Firefox, Edge, but in IE11 after a few seconds the suffix will be doubled to " % %" and this will keep growing. I don't know what triggers this, but when you leave the window open the amount of % will grow.

When the time is not in a input it works as expected, when you put the suffix in a span it also works as expected.

**Comment by mkxml** [comment]
I see you are using `7.1.0` in your fiddle.

Can you change it to use version `7.2.0` and check if the problem still happens? This might be related to the fixes we shipped in `7.2.0` that is currently in pre-release.

**Comment by richardhinkamp** [comment]
That does fix the issue indeed!

**Comment by developit** [comment]
@mkxml think it'd be good to roll 7.2 over to latest?

**Comment by mkxml** [comment]
@developit 👍 let's do it!
