### ISSUE TITLE
Is it possible to make movementX/movementY polyfill for preact?

### ISSUE THREAD

**Issue by nowaalex** [developit/preact#527]
Description:
https://developer.mozilla.org/ru/docs/Web/API/MouseEvent/movementX

I see two possible approaches to solve this:

1. modify addEventListener prototype
In this case I receive error `Uncaught TypeError: this._listeners[e.type] is not a function`
This is probably connected with eventProxy function, and I can't "get inside" it.
2. options.vnode hook
In this case I need to store previous screenX/screenY values somewhere. Mousemove handler is being often reassigned, so if I try to save previous screenX/screenY inside closure, I will always receive 0.

What would you advice me to do?

**Comment by developit** [comment]
I'd recommend a compositional component so that you don't have to rely on the vnode hook, which is global. A compositional component can call `this.base.addEventListener()` in `componentDidMount()`, then store state on `this` instead of using a closure.

**Comment by nowaalex** [comment]
Thank you for answering so fast! I'll try to do that

**Comment by developit** [comment]
I think we can close this out since it's more of a discussion type issue 👍
Always happy to chat more about this in the [Preact Slack](https://preact-slack.now.sh) 💯
