### ISSUE TITLE
Preact spanish translations are not neutral [preactjs.com]

### ISSUE THREAD

**Issue by erasmo-marin** [developit/preact#529]
Preact translations to spanish are in argentinian spanish, and it should be neutral spanish.

**Usá** Preact -- should be --> **Usa** Preact

La liviandad es mucho más divertida cuando no **tenés** que sacrificar productividad -- should be --> La liviandad es mucho más divertida cuando no **tienes** que sacrificar productividad

**Elegí** la guía que funciona mejor para **vos**! -- should be --> **Elige** la guía que funciona mejor para **ti**!

etc etc... it's annoying. I'm free to help you to fix translations.

Thanks.

**Comment by developit** [comment]
Hi @erasmo-marin! The preact website is over at [preact-www](https://github.com/developit/preact-www) - let's move to the issue @Download opened there 👍
