### ISSUE TITLE
Make preact support jsdom

### ISSUE THREAD

**Issue by Download** [developit/preact#530]
I'm working on fixing a test suite for React so it works with Preact. The original suite uses jsDom, but with Preact it gave some errors. The errors are caused by Preact assuming some globals exist and it can be easily fixed in userland code, like this:

```js
jsdom.env('<!doctype html><html><head></head><body></body></html>', (error, window) => {
  if (!error) {
    global.window = window;
    global.document = window.document;
    // preact tests for SVGElement, but jsdom does not support it
    // https://github.com/tmpvar/jsdom/issues/1423
    global.SVGElement = function(){};
    // Preact tests for Text, supported by jsdom
    global.Text = window.Text
  }

  done(error);
});
```

Still'I think it may be worth it to safeguard these tests. I.s.o:

```js
if (x instanceof SVGElement)
```

write:

```js
if (typeof SVGElement == 'function' && (x instanceof SVGElement))
```

It's a few more bytes but I think being compatible out of the box with jsDom would be a good thing for Preact.

Ideas?

**Comment by developit** [comment]
Hey @Download - I actually removed the dependency on `SVGElement` in `preact@7.2`.  It's beta though, so `npm i -S preact@beta`.

As for `Text`, I'm looking into that now.  It's the same type of check as SVGElement, so I might end up switching from `node instanceof Text` to `typeof node.wholeText!=='undefined`.

**Comment by developit** [comment]
Good news, the `Text` global is dropped in `8.0`.  Hoping to have a beta out this weekend :)

**Comment by Download** [comment]
Great job @developit !
Thanks a lot!

**Comment by peter-mouland** [comment]
was wondering why i was getting `Text is undefined`... glad I found this issue (which led me to adding `global.Text = win.Text` in my test / jsdom config.

**Comment by developit** [comment]
@peter-mouland Good to hear - setting that constructor will keep working in 8.0, just it won't be necessary anymore :)

**Comment by developit** [comment]
Fixed in 8.
