### ISSUE TITLE
moving node during diffing cause complex problem

### ISSUE THREAD

**Issue by gogoyqj** [developit/preact#532]
[src/vdom/diff.js#L251](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L251)
```
        // here cause reset some node properties, e.g scrollTop
	dom.insertBefore(child, originalChildren[i] || null);
```

like below, 

when child targets div.resize-triggers, originalChildren[i] targets div[key=3]

before 'dom.insertBefore', div.contract-trigger.scrollTop is greater than 0, 

after 'dom.insertBefore', div.contract-trigger.scrollTop becomes 0 without firing a scroll event, and  would never fire again

```html
<style type="text/css">
.resize-triggers, .contract-trigger, .contract-trigger:before {
    content: " ";
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    overflow: hidden;
}
</style>
<div class="scroll" style="position: relative; height:480px;overflow: hidden">
    <div class="scroller" style="position: absolute;min-height:100%;width:100%;">
        <div class="item" key="1">1</div>
        <div class="item" key="2">2</div>
        <div class="item" key="3">3</div>
        ...
        <div class="item" key="n">n</div>
        <div class="resize-triggers">
            <div class="contract-trigger"></div>
        </div>
    </div>
</div>
```

maybe it should recollectNodeTree nodes before child instead of moving child

```
if (dom === child.parentNode) {
    // here recollectNodeTree nodes before child
} else {
    dom.insertBefore(child, originalChildren[i] || null);
}
```

**Comment by developit** [comment]
Wouldn't that completely disable element reordering?  It's impossible to move/remove/add elements without triggering property resets, that's just how the DOM works.

**Comment by gogoyqj** [comment]
That's right. 

I wonder is there another diff algorithm to solve this problem.

In my example:

```html
<div class="scroller" style="position: absolute;min-height:100%;width:100%;">
    <div class="item" key="1">1</div>
    <div class="item" key="2">2</div>
    <div class="item" key="3">3</div>
    ...
    <div class="item" key="n">n</div>
    <div class="resize-triggers">
        <div class="contract-trigger"></div>
    </div>
</div>
```

ideally, div.resize-triggers should never be moved when those divs with item className change [e.g add/remove/reorder].

In original React, vnode data structure is:

```
{
    children: [
        0: [
            0: .item,
            1: .item,
            ...
            n: .item,
        ],
        1: .trigger-resize
    ]
}
```

And maybe in this way, can avoid moving node unnecessarily, also some unexpected problems.

**Comment by developit** [comment]
@gogoyqj I'm curious - with the keys they way you have them, were those on Pure Functional Components?  If so you might have actually been seeing Issue #338, which is a bug fixed in the next version of Preact.

**Comment by gogoyqj** [comment]
@developit  I'm trying to use preact in our react native web project, and  most of those are Pure Functional Components.

I found that once Component's render excuted[first render or re-render], dom will change[reorder/recollect].


In original React, I can cache dom reference in 'componentDidMount'

```
componentDidMount() {
    this.resizable = ReactDOM.findDOMNode(this.refs.resizable)
}
render() {
    return (
        <View {...this.props}
            ref="resizable"
            onScroll={this.onScroll}
        >....</View>
    );
}
```

While in Preact, I just have to reget dom in 'componentDidUpdate' since cached dom might be reordered/recollected

```
componentDidUpdate() {
    this.resizable = ReactDOM.findDOMNode(this.refs.resizable)
}

```

This is how I change a way of thinking and resolve the problem.

**Comment by developit** [comment]
@gogoyqj Until the PFC rewrite is released (it's done, just waiting for release), keys on pure functional components don't work properly in Preact.  This is also true for reordering as you noted - and that's also fixed by the rewrite.
