### ISSUE TITLE
Recycling issue switching video elements

### ISSUE THREAD

**Issue by xadh00m** [developit/preact#535]
Hi,

we encounter a pooling/recycling issue rendering different video elements based on the current state. E.g. we switch between two videos using [rc-animate](https://www.npmjs.com/package/rc-animate). The videos are set to "autoplay". 

The following happens when switching between the videos: When rendering the previous video element (again) the video is rendered paused at the position it was playing before it disappeared. 
The expected behavior is that the video is playing (due to the "autoplay" flag) from the beginning.

We need to explicitly reset the "currentTime" and call play() on the video reference to correct the issue at the moment.

Is there anything else we can do to track down the issue?

**Comment by developit** [comment]
@xadh00m Recycling is being removed in Preact 8, which should fix this issue. Your workaround is the best one I can think of, and it'll continue to work post Preact 8 (though would then be unnecessary).  We can keep this issue open to track things.

**Comment by marvinhagemeister** [comment]
@developit That sounds interesting. Does the recycling actually do more harm then good in real world scenarios?

+1 for `The Wreckoning`

**Comment by developit** [comment]
@marvinhagemeister I have come to believe that is the case, yeah. I'm happy to cut recycling too, since it's a very performance-oriented feature: if the cost doesn't pay off in terms of runtime perf, it's just added weight.  Preact can't have any added weight :)

**Comment by developit** [comment]
Fixed in 8.
