### ISSUE TITLE
componentWillUnmount not called when replacing classic with stateless component

### ISSUE THREAD

**Issue by Gertt** [developit/preact#536]
I am running into this issue where `componentWillUnmount` is not being called when my component is removed from the DOM. It seems to happen when it's replaced by a stateless component.

I managed to create this small example that exhibits the behaviour described above:

```js
import { h, Component, render } from 'preact';

class Foo extends Component {

    componentDidMount() {
        setTimeout(() => this.setState({ test: true }), 1000);
    };

    render(props, { test }) {
        return (
            <div>
                {test ? <Baz /> : <Bar />}
            </div>
        );
    }
}

class Bar extends Component {
    componentDidMount() {
        console.log('Bar mount');
    }

    componentWillUnmount() {
        console.log('Bar unmount');
    }

    render() {
        return (
            <div>
                <h1>Bar</h1>
            </div>
        )
    }
}

const Baz = (props) => (
    <div>
        <h1>Baz</h1>
    </div>
);

render(<Foo />, document.body);
```

**Comment by developit** [comment]
Yup! Just noticed this yesterday.  It's fixed by the Pure Functional Components rewrite, which I'm trying to ship as soon as possible.

**Comment by Gertt** [comment]
Is there somewhere I can track progress on that?

**Comment by ezekielchentnik** [comment]
@developit @Zashy any help needed to ship?  (verifying, second set of eyes, etc.)?  We've encountered this a couple times and have an existing real world use cases to go against.

**Comment by developit** [comment]
Just more time, as ever. I will try to get a beta out ASAP, spent a long time working on 8 this weekend :)

**Comment by developit** [comment]
Repros are still useful though if you have some spare cycles!

I will probably withdraw some funds from the [OpenCollective](https://opencollective.com/preact) to offset the hours I've had to push to get this stuff done.

**Comment by developit** [comment]
Confirmed, this is fixed in Preact 8.

![](https://i.gyazo.com/b2cd82bc0cc8fe1268e6d9c491f09fb3.gif)

**Comment by developit** [comment]
Fixed in 8.
