### ISSUE TITLE
Text nodes can't accept properties in IE8

### ISSUE THREAD

**Issue by gdorsi** [developit/preact#537]
Hi guys!

First of all, thanks for you work, this library is awesome!

I know that IE8 is not officialy supported, but i have to and in your 'Browser support' page you say:

> It should work fine in IE7 and IE8

I've fixed it locally with this patch:
```javascript
let supportsAddTextNodeProps;

try {
  document.createTextNode('').test = true;
  supportsAddTextNodeProps = true;
} catch (e) {
  supportsAddTextNodeProps = false;
}

function getEmptyVNode() {
  if (!supportsAddTextNodeProps) {
    return document.createElement('p-empty');
  }

  return '';
}
```
```javascript
// empty values (null & undefined) render as empty Text nodes
if (vnode==null) vnode = getEmptyVNode();
```

So, can we fix it?
Or at least, can you remove `"It should work fine in IE7 and IE8"`?

**Comment by developit** [comment]
@gdorsi hmm - where is Preact trying to set props on a Text node?  That should have been removed in 7.2.

**Comment by gdorsi** [comment]
[here](https://github.com/developit/preact/blob/master/src/vdom/component.js#L175)

**Comment by developit** [comment]
Ahh - interesting, I hadn't thought of that.  I wonder if it'd be worth changing back to use Comment nodes for empties?

**Comment by gdorsi** [comment]
I've tried it, but code breaks [here](https://github.com/developit/preact/blob/master/src/dom/recycler.js#L22), because of nodeName.

**Comment by developit** [comment]
@gdorsi it should bypass that - the old implementation was here:
https://github.com/developit/preact/commit/4c12c300d7090c57bb2426bc7925879896ccff3d#diff-a0896fa5d65b1d80ca4d496badbae50fR50

It was removed, though.  I can't recall the exact reason off-hand.  One option I'd be interested in would be to render a Comment node only for `null` component roots (not just any `null` element).

**Comment by gdorsi** [comment]
Ok, i'll try this way.

I have to use comments always, or only when text properties aren't accepted?

**Comment by developit** [comment]
Probably smaller to just always use comment nodes, the check would add a fair bit of weight.

**Comment by gdorsi** [comment]
I've rapidly made the fix [here](https://github.com/gdorsi/preact/commit/1520d964d7fbdca393106c16fa12466cd8f0a9e5)

If it's ok tomorrow i'll do the PR.

Thanks for the support :)

**Comment by NekR** [comment]
Are we still supporting IE8? What about `addEventListener` there?

**Comment by developit** [comment]
Nope, not officially supported. Probably doable via es5-shim though?

**Comment by NekR** [comment]
Events aren't fixed with that. I doubt there is a good events polyfill for IE8. I thought it's dead anyway.

**Comment by developit** [comment]
https://gist.github.com/jonathantneal/3748027

**Comment by NekR** [comment]
@developit well, that one isn't really compatible with W3C events, but ie8 shim linked there probably is.

**Comment by developit** [comment]
Anyone looking for a workaround, here's how to get Preact working (reasonably enough) in IE7 and IE8:

```js
document.createTextNode = function(data) {
  var text = document.createElement('x-text')
  text.innerText = data
  return text
}
```

This fixes the text node properties issue. It causes text nodes to be recreated on every render, but that's the price we pay :)
