### ISSUE TITLE
lose focus after inputing one key in newitem input box with firefox browser

### ISSUE THREAD

**Issue by steven88888** [developit/preact#54]
open https://preact-todomvc.surge.sh in Firefox Browser (ESR 38.5.0 for Linux)  and check adding item of the example,  after inputing any key, the focus will lose.  

But it works well without the same issue in Chrome Browser.

**Comment by steven88888** [comment]
add one new issue:
In Firefox,  edit function can not work well.  After appending some chars in editing status and pressing enter key, rendered result is the original value instead of new value.

**Comment by developit** [comment]
Hi @steven88888 - apologies for the delayed reply. Definitely a bug and something I'm looking into. It seems like something is invalidating the root node of the todomvc example, blurring the input. I'll keep you posted on progress.

**Comment by c58** [comment]
Just removed from app/index.js
```javascript
<Router onChange={this.handleRoute}><Noop path="/" /></Router>
```
and all works fine.

**Comment by developit** [comment]
@c58 Ah yeah, that makes sense. that was a hack at best anyway, I should have just parsed the URL without pulling in `preact-router`.

**Comment by c58** [comment]
I think i found the problem. Router's nodeType is 3 (text dom node), but it is not a "string" vnode, as expected in `isSameNodeType`.
```javascript
// attempt to pluck a node of the same type from the existing children
			if (!child && min<childrenLen) {
				for (let j=min; j<childrenLen; j++) {
					let c = children[j];
					if (c && isSameNodeType(c, vchild)) {
						child = c;
						children[j] = null;
						if (j===childrenLen-1) childrenLen--;
						if (j===min+1) min++;
						break;
					}
				}
			}
```
In this case every update will make a redraw from the root, because new children is never equals to previous children.

**Comment by developit** [comment]
@c58 Hmm - this must be using the old version of `preact-router` that was not using High Order components to render children?  The `package.json` for preact-todomvc has `preact-router@1.1.0` though, which was using High Order (switchover was `1.0.0`).

How are you checking the nodeType value of Router?

**Comment by c58** [comment]
> How are you checking the nodeType value of Router?
Just debug in a browser :) Open page, write some letters in input, set a pointer in a line:
```
if (c && isSameNodeType(c, vchild)) {
```
and write some letter in an input. And here we are, "c" is a dom node of a Router, vchild is a Router object. c.nodeType is 3

**Comment by c58** [comment]
If change `isSameNodeType` to:
```javascript
  function isSameNodeType(node, vnode) {
  	if (isString(vnode)) return node.nodeType === 3;
  	if (isFunctionalComponent(vnode)) return true;
  	var nodeName = vnode.nodeName;
  	if (isFunction(nodeName)) return node._componentConstructor === nodeName;
  	return toLowerCase(node.nodeName) === nodeName;
  }
```
issue will be fixed.
