### ISSUE TITLE
Missing SVG attributes in preact.d.ts

### ISSUE THREAD

**Issue by Avol-V** [developit/preact#541]
There are a lot of missing attributes, but some of them can be especially useful: width, height, id, tabindex, style, class.

Also some for accesibility in HTML (but them not in list of SVG attributes): role, title.

**Comment by shakyShane** [comment]
@Avol-V add these to any custom `d.ts` you might have 

```ts
declare namespace JSX {
    export interface SVGAttributes {
        class?:string | { [key:string]: boolean };
        className?:string | { [key:string]: boolean };
    }
}
```

**Comment by shakyShane** [comment]
^ temp fix

**Comment by Avol-V** [comment]
@shakyShane thanks, it can help.
But it's a regular attributes for SVG and I think it should be in package itself, why not?

**Comment by shakyShane** [comment]
@Avol-V - send a pr https://github.com/developit/preact/pull/542

:)

**Comment by Avol-V** [comment]
@shakyShane thaks again!

Can you please add these attributes too (all this attributes are valid for `svg` tag):

```
id?:string;
width?:number | string;
height?:number | string;
role?:string;
```

Or some of them should be in special interface for SVG tag itself?

**Comment by jmfirth** [comment]
To add to this discussion: the above PR is what I had to do locally to get what I needed with SVG and was adapted from the React definitions.

**Comment by marvinhagemeister** [comment]
Just checked with `8.2.9` and the requested types are present now.
