### ISSUE TITLE
Set DOM style， the node will be reused with the style

### ISSUE THREAD

**Issue by wulunyi** [developit/preact#544]

**Comment by LinusU** [comment]
I also think that I'm experiencing this. It destroys the layout in subtle ways.

I'm just rendering a lot of divs with different styles. Sometimes when moving between pages, some styles that where previously applied to another element is still applied to new unrelated elements. I suspect that this is due to DOM element reuse...

**Comment by wulunyi** [comment]
Now I set the DOM style to an empty object , when componentWillUnmount .

**Comment by gogoyqj** [comment]
I met the same problem while using pages switch animation - seems the reason is preact won't diff or reset style property those aren't in node[ATTR_KEY].style

And may be fixed  by reset dom style when recollect node
`
        if (node && node.style) {
	    options.processStyle(node, 'name', '', node[ATTR_KEY].style || '') // reset style 
	}
`

**Comment by LinusU** [comment]
Why was this closed? I believe that this is still an issue?

**Comment by wulunyi** [comment]
Sorry, click  wrong.

**Comment by developit** [comment]
Yes, currently preact only diffs properties that are set through Preact.  Removing recycling will fix this.

**Comment by LinusU** [comment]
> Yes, currently preact only diffs properties that are set through Preact. Removing recycling will fix this.

This is not what I am experiencing. I'm only using pure preact to render the entire application, yet the styles from divs in previous screens somehow appears on divs in the current one 🤔

**Comment by developit** [comment]
@LinusU that is very odd. any way to set up a repro? I thought the issue only affected externally mutated styles.

**Comment by wulunyi** [comment]
The \<img \/\> element with src will appear the same issue

**Comment by developit** [comment]
Yup, there's a separate issue open to track that. Also fixed in 8.

**Comment by developit** [comment]
Fixed in 8.

**Comment by dmitrykurmanov** [comment]
Hello! Thanks for the great job! We are using preact in our js library and we have an issue with updating DOM nodes during user customizations.

So we've added a test for this scenario: https://github.com/developit/preact/pull/977
