### ISSUE TITLE
Preact unmounts DOM Node (wrong diff?)

### ISSUE THREAD

**Issue by eightyfive** [developit/preact#547]
Hello,

I trimmed down my problem to the simplest example and I actually think the issue comes down to some difference in implementation with React.

So I have a pretty simple use case / page:
- A list of Hotels on the left
- A Google map on the right
- When I click a Hotel in the list, a detailed view appears on top of the map (`<HotelPane />`)

```js
const HotelListPage = ({ hotels, selectedHotel }) => {
  return (
    <div>
       <div className='HotelList'>
         <HotelList hotels ={hotels} />
       </div>

      {selectedHotel !== null &&
        <HotelPane hotel={selectedHotel} />
      }

      <div className='Map'>
        <Map hotels ={hotels} />
      </div>
    </div>
  )
}
```

Steps:
1. First time, `<HotelPane />` is not rendered, `<Map />` and `<HotelList />` are.
2. Hotel in the list is clicked
3. `<HotelListPage />` re-renders
4. `<HotelPane />` renders...
5. `<Map />` is unmounted ! `<HotelList />` not.

So I don't understand why 5- occurs. From my understanding there is no reason why this DOM node should be removed. There is no difference (regarding that exact component) between steps 1- and 5-.

This exact same use case works as expected with React (`<Map />` is not being unmounted).

The versions I am using are:
```json
    "preact": "^7.2.0",
    "preact-compat": "^3.13.1",
```

`<Map />` component quickly:
```js
class Map extends Component {
  ...
  render () {
    return (
      <div className='o-map'>
        <div className='o-map__canvas' ref={el => { this.mapElement = el }}>
        </div>
      </div>
    )
  }
}
```
__Note__: A Google Map is attached to `this.mapElement` on `componentDidMount`.

Thanks for your help.

**Comment by eightyfive** [comment]
Closing.

It seems to come from my code. I use some kind of `withGoogleApi()` HOC and if I remove it, the problem doesn't occur.

Thanks. If you have any hints though.

**Comment by developit** [comment]
@eightyfive Good to know you solved it - wondering which version of Preact this was with?

**Comment by eightyfive** [comment]
Sure:
```
    "preact": "^7.2.0",
    "preact-compat": "^3.13.1",
```

__Note__: Was really just my code / understanding. Hehe.

**Comment by developit** [comment]
Ahh ok, good to know!  If you ever run into things like this there are over 200 lovely people in the [Preact Slack](https://preact-slack.now.sh) that can help out super quick, if that is of interest to you 🙂
