### ISSUE TITLE
Adopt a more strict ESLint config

### ISSUE THREAD

**Issue by MinJieLiu** [developit/preact#548]
Like ` airbnb` 's `javascript` specification, which makes code easier to maintain

**Comment by developit** [comment]
This project already uses ESLint.

**Comment by MinJieLiu** [comment]
I mean it is not strict enough. @developit

**Comment by developit** [comment]
Ah, that's probably true - could use some tightening up.  I'll see if I can find a styleguide that matches the codebase.

**Comment by SaraVieira** [comment]
@developit can I pick this up and try to place the preact one and prettier?

**Comment by robertknight** [comment]
@kristoferbaxter made a proposed PR to adopt Prettier here: 
https://github.com/developit/preact/pull/1336. If we can get consensus around the config would that resolve this issue?

**Comment by marvinhagemeister** [comment]
In my opinion it's safe to close this issue. There doesn't seem to be any interest in changing our `ESLint` config in the past months. The Prettier initiative is awesome and can happen independently from this issue :+1:
