### ISSUE TITLE
Render into a different DOM node with same context.

### ISSUE THREAD

**Issue by jhernandezme** [developit/preact#552]
Actually this is possible in react through 
```ReactDOM.unstable_renderSubtreeIntoContainer(parent, element, containerNode)```
so you can do something like this in the render function
```
    render (){
      ReactDOM.unstable_renderSubtreeIntoContainer(this, <Component />, document.createElement('div'))
    }
```
The context is inherited from parent which is very useful when using stores like redux, or mobx.

Is there a way to achieve this in preact?

**Comment by jhernandezme** [comment]
Sorry I just saw this was recently added.

https://github.com/developit/preact-compat/pull/296

**Comment by developit** [comment]
FWIW, this is the main selling feature of [preact-portal](https://github.com/developit/preact-portal).

**Comment by jhernandezme** [comment]
@developit  thanks! this is exactly what I wanted.
