### ISSUE TITLE
redux-form 6.5 with preact throws an error

### ISSUE THREAD

**Issue by samouds** [developit/preact#554]
Hello,

I'm trying to use redux-form with preact but i get this error : 

```
Uncaught TypeError: component.__ref is not a function
    at setComponentProps (component.js:43)
    at renderComponent (component.js:124)
    at renderComponent (component.js:124)
    at renderComponent (component.js:124)
    at setComponentProps (component.js:43)
    at buildComponentFromVNode (component.js:223)
    at idiff (diff.js:91)
    at innerDiffNode (diff.js:233)
    at idiff (diff.js:145)
    at innerDiffNode (diff.js:233)
```

after digging a little bit I found that the reduxForm has a string "wrappedInstance" as ref.

Any idea how to get redux-form work with preact, or any replacement to it.

Thanks.

**Comment by developit** [comment]
You need to use `preact-compat` for libraries that rely.on String refs.

**Comment by samouds** [comment]
I'm already using preact-compat for react and react-dom via liases in the webpack config. but I still have the issue with redux-form.

**Comment by developit** [comment]
Using preact-redux?

**Comment by samouds** [comment]
Yes ! @developit I'm using `preact`, `preact-compat`, `preact-redux` and `preact-router` with redux-form.

Here are my component :  

```
import { h, Component } from 'preact';
import { connect } from 'preact-redux';
import { reduxForm, Field } from 'redux-form';
import { createStructuredSelector } from 'reselect';

import reduce from 'reducers';
import { actions } from 'actions';

import Button from 'components/_mwcore/Button';

import styles from './styles';

class LoginForm extends Component {
  render({ children, ...props }) {
    return (
      <form className={styles.loginForm}>
        <input type="email" name="email" ref={(input) => { this.emailInput = input; }} />
        <input type="password" name="password" ref={(input) => { this.passwordInput = input; }} />
        <Button onClick={this.login}>Login</Button>
      </form>
    );
  }
}

export default connect()(reduxForm({
  form: 'loginForm'
})(LoginForm));
```

**Comment by developit** [comment]
Try swapping `preact-redux` out for `react-redux` - if you're already aliasing via `preact-compat`, it'll likely fix the issue.

**Comment by samouds** [comment]
I tried but I still have the same error ... :(

**Comment by developit** [comment]
Looks like this is the offending code:
https://github.com/erikras/redux-form/blob/0a93994b1e204e3945ed157dfe32bc827665bdfd/src/ConnectedFieldArray.js#L95

TBH it would be nice if redux-form could just be updated to use function refs. It's combining two bad practises in one by using String refs and manually mutating props.

**Comment by samouds** [comment]
Ok I see. Thanks by the way. :)

**Comment by developit** [comment]
TBH I do think this is something `preact-compat` should normalize, I'm just not sure how it could.

**Comment by bboydflo** [comment]
@samouds have you fixed your issue somehow? I am having a similar issue with another react component... :(
