### ISSUE TITLE
drag n drop events

### ISSUE THREAD

**Issue by flosse** [developit/preact#557]
Attaching a function to `ondragstart` is working but `ondragover` and `ondrop` don't.
Do I miss something?

**Comment by developit** [comment]
Hmm, I've never seen an issue with these before. Preact is just using the broswer events. Are you sure your example is set up correctly?

**Comment by developit** [comment]
IIRC you need to preventDefault in dragstart to receive those other events.

**Comment by flosse** [comment]
Thanks for your fast reply!!
Now it works :) There it seemed to be a reference issue that didn't throw an error :-\

**Comment by developit** [comment]
Hmm! That's an interesting one - there are certain types of Error in Preact that might turn up as Promise errors - in newer browsers you should still see them in the console, but maybe they were filtered?
