### ISSUE TITLE
Proxy Properties

### ISSUE THREAD

**Issue by mindrage** [developit/preact#569]
So i had this idea of a way to add general functionality to elements in general.
The idea is to make proxies for components that can stack based on functionality rather than having to put components within each other.

How would it look like?
There could be multiple ways.

this is one based on having properties bound to a global namespace.

```es6

Preact.registerProxy("dragable", class {

	// The constructor feeds in the parameter of the data
	constructor(value) {
		console.log(value) // prints 43
	}

	onPrepareMount() {
		this // references the element it proxies. Often an html element.
	}
	
	onClick() {
		access childs, props of the element to stack proxies.
	}
	

})


// proxies are primarily meant to be used in HTML JSX tags to give additional functionality.
// Normally all other components are often just wrappers of some kind.
const DragableText = () => (
	<div dragable={43}>
		<p>I am a dragable element!</p>
	</div>
)

```

This feature would mostly give shorter code and complexity of the nodes.
It would extend the UI capabilities to generalized for elements.
However the upper example is pretty neat but it applies globally.
A more modular approach would be if the proxies would work a little bit like styles and class names.

```es6
// The Dragable.js
import { Proxy } from "preact"

export class Dragable extends Proxy {

	// The constructor feeds in the parameter of the data
	constructor(value) {
		console.log(value) // prints 43
	}

	onPrepareMount() {
		this // references the element it proxies. Often an html element.
	}
	
	onClick() {
		access childs, props of the element to stack proxies.
	}
	
}
```

Then in the actual component:
```es6

import Dragable from "./dragable"

const MyDragableElement = e => (
	<div proxy={[Dragable]}>
		<p> Yay! Drag me. </p>
	</div>
)
```

The pros with the modular approach is well, its modular, less chance for conflict.
The pros with the previous approach is cleaner code, and it would work really well with the preact-html concept.

**Comment by developit** [comment]
@mindrage This seems very similar to React's mixins.

Problems:
- stacking methods is at best a guess
  - it's hard/impossible to know whether all methods of a given name should be called, or only the outermost. 
  - method call ordering is important but can't be statically determined
- clashes between mixed-in methods
  - one method adds a property, the other triggers a re-render, resetting the property
- how would you compose a method like render()?
  - not really possible to merge two render() methods
  - prop merging (such as for assigning event handlers) also not possible

Personally, I think Compositional Components are an elegant solution to this.

Here's a rough implementation of something like what you described though:

```js
import { options, cloneElement } from 'preact';

const directives = {};
export function register(name, handler) {
  directives[name.toLowerCase()] = handler;
}

// hook vnode creation and install a directive middleware
let old = options.vnode;
options.vnode = vnode => {
  if (old) old(vnode);
  let tag = vnode.nodeName,
    props = vnode.attributes,
     directive = typeof tag=='string' && directives[tag.toLowerCase()] || props && directives[props.directive]
  if (directive) {
    let child = cloneElement(vnode);
    vnode.nodeName = directive;
    vnode.children = [child];
  }
};
```

**Comment by mindrage** [comment]
Ah always wondered why Github didnt have a separate discussion section. Like the project tab, but with commenting abilities.

I can understand stand some certain issues though like the render, but i never really wanted to add that.

The point was never to alter already existing structures, rather just add/remove events to them.
Mostly linked to the normal HTML elements like div, paragraph and so on.

Infact i think you could almost integrate that as an feature for only those elements.
(P)react components often only is a wrapper of somekind of the real elements.
an alternative method would be to apply proxies after each render usinq querySelectors, though not entirely sure how performant that would be.

Often when you do a component that adds to a function, you place a div of some kind then place thier child inside of them, now appending multiple functionalities and you start to have large nodes when all could just be applied using a single div.

An alternative name could be an EventGroup of some kind.
If you used the fixed property like
```es6

const RandomComponent = () => (
   <div events={[Dragable]}> 
   </div>
)
```

If you have them as a list there, you could do a ordered bind and reverse ordered unbind of events incase  of reusing DOM elements.

Wont really drag ou the discussion here, so just close after your reply, will join the slack chat to discuss it further.

**Comment by developit** [comment]
Awesome, happy to chat about it on Slack.  Curious if I can sell you on compositional components as a solution to this
