### ISSUE TITLE
react-addons-update dependency

### ISSUE THREAD

**Issue by arjunskumar47** [developit/preact#575]
Hello,

I'm migrating a fairly large codebase from React to Preact which has a lot of 3rd party React helper/component libraries. One of them is `react-toastr`. This have a dependency on `react-addons-update` which seems to cause an issue on my end even when I'm using `preact-compat`.

I added the alias configuration to my Webpack build process and I seem to get this error. 

```
ERROR in ./~/react-addons-update/index.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/update' in /xxx/xxx/xxx/project/node_modules/react-addons-update
 @ ./~/react-addons-update/index.js 3:17-44
```

Any thoughts on getting this resolved?

**Comment by dlindenkreuz** [comment]
I use this library as drop-in replacement for react-addons-update: https://github.com/kolodny/immutability-helper

**Comment by developit** [comment]
Ahh amazing @dlindenkreuz! I think we should install this into preact-compat and export it as lib/update` 🎉

**Comment by slaskis** [comment]
This is now added in preact-compat with https://github.com/developit/preact-compat/pull/339 🎈

**Comment by developit** [comment]
All good!
