### ISSUE TITLE
CSS transition group elements children are absorbed if using dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by rmales** [developit/preact#578]
Adding an issue for https://github.com/developit/preact-css-transition-group/issues/3
Example of the bug from that issue: http://jsfiddle.net/developit/c87fw8zu/

**Comment by rmales** [comment]
It seems like this can be fixed be reinstating the dangerouslySetInnerHTML clause of this condition:
https://github.com/developit/preact/commit/123978c108579f147c49906c31301ad1712926be#diff-a0896fa5d65b1d80ca4d496badbae50fL323

Without it the inner HTML nodes are absorbed and never recreated. I'm not really sure why it was removed though.

**Comment by rmales** [comment]
Seems like when using a CSS transition group the child element's `dangerouslySetInnerHTML` object is the same between diffs for some reason (maybe due to how children are manipulated/managed), so the `setAccessor` call gets skipped.

Given existing children are always absorbed when `dangerouslySetInnerHTML`, it seems like the equality check could just be skipped for that property.

**Comment by developit** [comment]
K, will try to add a test for this and skip the equality there. I had removed.it because it failed a test.

**Comment by rmales** [comment]
@developit There is a fix and test in my fork, if that helps. It seems kind of dumb though (the transition library is doing something weird rather than it being a bug in Preact).
https://github.com/rmales/preact/commit/f5c7574984be72be17d58a59076b76918beb7d4e

**Comment by developit** [comment]
Awesome, will get those in

**Comment by lluchs** [comment]
Any news on this? I'm seeing this issue as well. The linked fix works for me.

**Comment by marvinhagemeister** [comment]
This is very likely fixed with Preact X. We don't recreate `dangerouslySetInnerHTML` on each render anymore 👍
