### ISSUE TITLE
draggable cannot be set to "false"

### ISSUE THREAD

**Issue by foray1010** [developit/preact#58]
I am using 3.4.0

I have set an element to `draggable='false'` but result it is always `draggable="true"` in the DOM

Example:
https://github.com/foray1010/Popup-my-Bookmarks/blob/preact/js/_components/popup/components/BookmarkItem.jsx#L494
https://github.com/foray1010/Popup-my-Bookmarks/blob/preact/js/_components/popup/components/BookmarkItem.jsx#L500

**Comment by developit** [comment]
Hi @foray1010 - you need to use an actual Boolean value:

```js
<a draggable={false} />
```

**Comment by foray1010** [comment]
thanks! It is working now!

**Comment by developit** [comment]
Great :)
