### ISSUE TITLE
Unnecessary unmount when inserting new child

### ISSUE THREAD

**Issue by xtuc** [developit/preact#580]
Following the discussion I had with @developit.

I found a strange behavior with VDOM diffing.

The following example causes `Child2` to re-mount.

```js
render () {
  return (
    <div>
      {this.state.show ? <div>child 1</div> : ''}
      <Child2 />
    </div>
  );
}
```

All child components are unmounted when `show` becomes `true` in the state.

Here is repository where you can reproduice this issue: https://github.com/tomesch/preact-mount-bug

Note that this doesn't happen with React.

I will be happy to help with the resolution of this issue. Thanks.

**Comment by developit** [comment]
Going to add your example as a unit test.

**Comment by developit** [comment]
With the PFC change this can now be reliably diffed :)

**Comment by xtuc** [comment]
Awesome! Thanks :+1:
