### ISSUE TITLE
Rendered nodes order changing unexpectedly 

### ISSUE THREAD

**Issue by dharFr** [developit/preact#581]
Hi,
I'm seeing a weird behavior with conditional rendering and `preact-redux`'s `connect`.
Here is a jsfiddle to reproduce : https://jsfiddle.net/dhar/985cr5ct/5/

Clicking the toggle button hides `First!` and when clicking it again, it appears back after `Second`.

As discussed with @developit on slack, this will most likely be fixed in Preact 8. This issue so we don't forget to test it when the beta is out.

**Comment by developit** [comment]
Confirmed this will be fixed in 8.0 👍 

![](https://i.gyazo.com/bfd83f2f400b908440b0a4147d2c545d.gif)

**Comment by markov00** [comment]
hi @developit do you have ideal due date for the v8.0 release?

**Comment by developit** [comment]
@markov00 three weeks ago

**Comment by marvinhagemeister** [comment]
@developit Following you on Twitter I love what you have done so far with v8.0. I wouldn't worry about striving for too much perfection. There's lot of 8.x point releases available for further improvements.

Or perhaps just pushing a `next` branch of some sort would be a great step? That way people can make sure that their contributions (if any) matter for the next release.

Anyways, it's up to you and I'm really grateful for preact and the minimalistic you bring to the table. You likely know what's best for you 💯

**Comment by developit** [comment]
I'm thinking the cleanup and publish will happen today. It's been a constant fight for time the last couple weeks as I've been busy with release stuff for my job. Just means the size will be 3400b instead of 2999b 😱😭

**Comment by developit** [comment]
Fixed in 8.
