### ISSUE TITLE
Which / are polyfills are needed?

### ISSUE THREAD

**Issue by screendriver** [developit/preact#585]
Are there any polyfills that are needed for older browser to work with preact?

For example Inferno needs [this](https://github.com/infernojs/inferno#browser-support) ones.

**Comment by gdorsi** [comment]
I use es5-shim, es5-shim & addEventListner polyfill and it works for me.

**Comment by screendriver** [comment]
Hmm ok. The reason for the question is that I don't want to include everything from `core-js` or `es5-shim`. At the moment I only include what's really needed because I want my bundle as small as possible. For example `core-js/es6/promise`, `core-js/es6/map`, `core-js/es6/weak-map`, `core-js/fn/object/assign` and `core-js/fn/object/keys`

**Comment by gdorsi** [comment]
I've made a rapid check on the codebase and seems that addEventListener is the only polyfill needed

**Comment by screendriver** [comment]
Really? 😳 I expected more. That would be awesome if preact does not require any more polyfills 💃

**Comment by developit** [comment]
@screendriver hmm - what older browsers?  Preact supports IE9+ with no polyfills at all.

**Comment by screendriver** [comment]
Bam! That's all I wanted to hear 💃 Thank you very much @developit

**Comment by developit** [comment]
Awesome :)  For reference, here's the list of browser APIs Preact relies on:

- It will use `Promise` only if available, falling back to `setTimeout(0)`
- DOM APIs used are very minimal DOM core 1 / 2:
  - `document.createElement()` and `document.createTextNode()`
  - `Text.prototype.nodeValue`
  - From `Element.prototype`:
    - `.attributes` NodeList
    - `.setAttribute()`, `.getAttribute()`, `.removeAttribute()`
    - `.appendChild()`, `.insertBefore()`, `.replaceChild()`

If you use SVG, `createElementNS()` and `(get|set|remove)AttributeNS()` are used.

All of these are actually supported way back beyond IE9, but IE8 and prior includes an issue where you cannot define arbitrary properties on `Text` nodes (explained in #537)

**Comment by screendriver** [comment]
👍 

That should be either in the README or on https://preactjs.com 😉

**Comment by developit** [comment]
Totally - we have a browser support page [here](https://preactjs.com/about/browser-support) but it's woefully poor at explaining this.

**Comment by screendriver** [comment]
Ah I see. Thank you for your help. Hopefully the page will be updated in the future at some point.

**Comment by joshua-mason** [comment]
>screendriver hmm - what older browsers? Preact supports IE9+ with no polyfills at all.

@developit just wanted to check if this is still the case, or if there have been any added since this was discussed?

**Comment by developit** [comment]
@joshua-mason the current version of Preact still works perfectly in IE9.

<img width="1127" alt="Screenshot 2023-03-23 at 3 14 37 PM" src="https://user-images.githubusercontent.com/105127/227335544-50e30095-5430-477e-a024-07242b0d29de.png">

We will likely begin requiring some very minimal polyfills for IE9-11 starting in Preact 11 though.
