### ISSUE TITLE
Functional components defaultProps not applied when devtools is enabled.

### ISSUE THREAD

**Issue by avaly** [developit/preact#586]
It seems that whenever `preact/devtools` is enabled, functional components don't get the default props filled in.

To replicate, clone this branch of the boilerplate: https://github.com/avaly/preact-boilerplate/tree/bug-devtools-functional-defaultProps

If we enable the class version of the `Home` component, then the default prop gets filled in correctly: https://github.com/avaly/preact-boilerplate/blob/bug-devtools-functional-defaultProps/src/components/home/index.js#L13-L22

The same happens, if we keep the functional version of the component, but disable `preact/devtools`.

**Comment by developit** [comment]
Yikes! This is definitely fixed in Preact 8, since functional components no longer have a separate pipeline.

**Comment by developit** [comment]
Fixed in 8.
