### ISSUE TITLE
Feature Request: Option to turn off/configure VDOM diffing

### ISSUE THREAD

**Issue by seansd** [developit/preact#589]
Yes for the vast majority of folks, they won't want to do this.. . . 

The advantage of the component lifecycle means that all dom updates happen in one event loop pass, which is great.

Yet there are  many times where the virtual DOM increases run-time performance cost b/c of the constant comparisons that are done.    Seasoned developers could optimize those flows by telling Preact EXACTLY how to do the dom changes, or not doing them at all etc.  

An example is a never-ending scroll list, which unless very precisely implemented means you do a great deal of work / CPU in you're render method, even though only some % of that commits to the DOM.

``` 
  class List extends Component { 
         constructor() { 
         }
      
        getInitialState() { return { items:  ["Hi 1", "Hi 2", "Hi 3", "Hi 4"]; } }
 
        handleClick() { 
           var newState= {};

            newState.items = newProps.items.concat(["Hi", "Hi", "Hi"]);

           this.setState(newState);
        }
         render() {
              var items          = this.state.items,
                    renderedItems = [];

              for (var idx = 0; idx < items.length; idx++)
              {
                     renderedItems.push(<li key={idx}>items[idx]</li>);
              }
              return (<div><button onclick={this.handleClick}>Add More</button><ul>{renderedItems}</ul></div>);
          }

     }
```

In the above example, each time render is called, we have to loop over the ENTIRE set of items to regenerate ALL the mark up, even though only 3 new items have been added. 

There are some ways around that, but it would be awesome if we could tell the system to ADD only those items without being forced to re-render a virtual structure that Preact then must turn around and compare.

Additionally in this case, in vanillaJS you could actually add each group of new items in 1 single DOM operation with no reading at all.

So if there were a mechanism that gave the render method back what was already output, or allowed developers to choose what mode to run in etc. that would go a looong way. . .

**Comment by developit** [comment]
Hi @seansd - you can do this by returning `false` from `shouldComponentUpdate` on the child items. I've create a demo to show the technique - I think you'll find it's a way to achieve the granularity you're looking for, but without having to give up the declarative nature of Virtual DOM rendering, which is really the whole point of Preact:

https://jsfiddle.net/developit/6pbrpg8v/

![preview](https://i.gyazo.com/ad59ab7a3661baa49768621c4411c76c.gif)

FWIW you can also do direct DOM manipulation using this technique to achieve the exact setup you described, though I strongly recommend against doing so:

```js
class ListItem {
  shouldComponentUpdate() {
    return false   // never re-render
  }
  componentWillReceiveProps(props) {
    // You can compare props to this.props here.
    // `this.base` is the DOM for the component.
    this.base.setAttribute('value', props.text)
  }
  render(props) {
    // only gets run on first render (mount)
    return <div />
  }
}
```

**Comment by seansd** [comment]
Yes I know that, but that only works if you want to render nothing.  As a mentioned earlier, in my example you can render all 3 of the new items in the set with only 1 dom operation and no diffing when not being forced to go through the virtual dom, because the developer himself knows that. . .

Now, if render gave back what had already been rendered/knows about in the vdom and we could append to that (basically a stateful render) that would be a step in the right direction.

but the shouldComponentUpdate function does not help here b/c we're talking about aggregating the render

**Comment by developit** [comment]
Preact does not read from the DOM when diffing. Generally, if we're making the case for a more performant way to update the DOM, it would be best to benchmark first to avoid assumptions.

Hmm - I don't think I did a good job of explaining - in the example I gave, only the *appended* items are being diffed when re-rendering.  The previously created items are untouched and have no appreciable cost - they are not diffed at all.  Returning `false` from `shouldComponentUpdate` literally stops the Preact's diff (that is to say - it's an early-return in the diff, not the reconciler).

The entire purpose of Preact (and any other VDOM lib) is to abstract these types of performance issues in a way that scales well, and Preact does this effectively.  For example, there are a few different benchmarks that show exactly the effect you're going for: the cost of appending 1000 items to a list of 10000 items is roughly the same as the cost of appending 1000 items to an empty list.  That's the result of a year and a half's worth of performance optimization, and it really does work well at this point.

I don't mean to downplay your proposed approach - much the opposite - I just think you might be overlooking one of the more important things VDOM is providing for free.

**Comment by leeoniya** [comment]
> For example, there are a few different benchmarks that show exactly the effect you're going for: the cost of appending 1000 items to a list of 10000 items is roughly the same as the cost of appending 1000 items to an empty list.

This is not quite true [1]. The cost is double, even in the fastest frameworks. But most of it is dom reflow and browser css resyling rather than the vdom overhead.

[1] https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html

**Comment by seansd** [comment]
thank you @leeoniya for saying that. . . 

and yes i agree that most of the time that is true. . .but in large applications with whole pages being output, that's not true, especially when you as a developer can normalize the operations yourself into only a few. . .

experienced folks know that you can use strings/buffers with innerHTML/insertAdjancentHTML or ranges to minimize writes of markup and style.cssText to batch update node styles. . .it's just that most folks don't know that or fail to do so. . .

**Comment by seansd** [comment]
and the cost of appending 1000 items 1 at time in a loop is much much higher than appending 1000 items in 1 shot b/c there's only a single dom reflow computation

**Comment by leeoniya** [comment]
> and the cost of appending 1000 items 1 at time in a loop is much much higher than appending 1000 items in 1 shot b/c there's only a single dom reflow computation

modern browsers will batch this into a single reflow. it's to the point that `createDocumentFragment` offers no benefit, and can in fact make things slower. this was already true almost a  year ago [1]

much performance advice on the internet that's older than 6 months is likely invalid today.

[1] https://github.com/infernojs/inferno/issues/223

**Comment by leeoniya** [comment]
this whole discussion needs to be taken with a grain of salt since we are specifically talking about `data-driven` frameworks, which all vdom frameworks technically are.

yes, writing specific imperative code for every dom mutation will be faster than any vdom framework. but you will also have 10x the code to maintain that will be more fragile and difficult to refactor and understand later. you have to balance your team's and project's needs.

**Comment by seansd** [comment]
I don't agree about 10x the code, but i certainly get your point and as I said, in general i think it's fine. . .but advanced features would give us the best of both worlds and i fail to see why adding that is usually met with such disdain

**Comment by leeoniya** [comment]
to be clear, i have no opinion about whether this should be added to Preact, i'm just fact-checking.

**Comment by developit** [comment]
Appreciate the fact checking @leeoniya - Preact used to batch insertions using `createDocumentFragment`, but [it was removed](https://github.com/developit/preact/commit/7b79e8313c987df108ca12f65553a3571d5aaeb6) just over a year ago since it ends up being slower than the looping over appendChild in the majority case.

Naturally, this is basically a discussion of tradeoffs.  I think that's an interesting topic, but I'm fairly certain Preact (and react and anything else implementing React's component model).  @seansd - given that preact exposes the DOM element behind every component as `this.base`, aren't you already able get the desired bypass you spoke of?

```js
class GiantList extends Component {
  shouldComponentUpdate() {
    return false;
  }
  componentWillReceiveProps(nextProps, nextState) {
    for (let i=this.state.items.length; i<nextState.items.length; i++) {
      let item = nextState.items[i];
      let li = document.createElement('li');
      li.textContent = item;
      this.base.appendChild(li);
    }
  }
  render() {
    return <ul />;
  }
}
```

I'd be super curious to see this compared to the default diff. Even in the above example, which looks like it should be faster, it likely isn't because it's creating text nodes implicitly via `textContent`.  To write the equivalent DOM operations to what preact would normally perform for an initial render would look pretty ugly.

**Comment by seansd** [comment]
yes your right i can, but i'm afraid to do so due to side effects . . . perhaps i don't have to worry about that with preact? in react if i did that the next render call would make react puke with errors. . .

I can write up something tonite to show you what i mean. . . but it would be more like this:

```
componentWillReceiveProps(nextProps, nextState) { 
      let itemBuffer = [].slice.call(nextState.items),
           str  = itemBuffer.join('</li><li>');
           str  = `<li>${str}</li>`;
           this.base.insertAdjacentHTML("beforeEnd", str);
}
```

**Comment by developit** [comment]
Preact will simply ignore those elements in the diff, you won't see any errors.

If you are able to write up an example of that technique, that'd be awesome. I think it might be enlightening to benchmark, since it relies on HTML parsing which is extremely slow (especially when there are any browser extensions installed, which is the case for most users).

**Comment by thysultan** [comment]
Maybe this might be of interest https://github.com/facebook/react/issues/9218, the idea is to allow an overloaded `forceUpdate` to accept 2 optional number arguments that tell the reconciler where precisely to start and end diff'ing a components children at a much lower level than sCU.

**Comment by seansd** [comment]
yeah that would be an excellent start. . . . i ran out of time trying to do my own full impl, but the above comment for componentWillReceiveProps should be enough for you to get the idea.  When the number of items being added is say 5 or more, the above will always be faster than doing it the "right" way and re-rendering the whole list and letting preact deal with the diff. . .

that's b/c the string parser is native to the dom and thereby much faster than running js code in a loop, especially since I don't need any iteration at all. . .
