### ISSUE TITLE
Issue with code loaded in a separate iFrame

### ISSUE THREAD

**Issue by pstockley** [developit/preact#595]
I have a somewhat strange usage for Preact. I am the owner of a library ( [GWTReact](https://github.com/GWTReact/gwt-react)) that allows you to use React in Java via the Google GWT compiler. I am interested in also supporting Preact (with the react compat library). From my initial testing it basically works except for one case where arrays of child elements are passed. GWT loads the transpiled Java code in an iFrame which is different than the Preact script is loaded. The following line of code is the problem:

```javascript	    
    function h(nodeName, attributes) {
    .
    .
    while (stack.length) if ((child = stack.pop()) instanceof Array)  ....... {
```
The problem is that instanceof doesn't work if the array was created by code in the other iFrame. So I changed it to Array.isArray and it works fine

```javascript	 
    function h(nodeName, attributes) {
    .
    .
    while (stack.length) if ((child = stack.pop()) && Array.isArray(child)) ....... {
```

**Comment by robertknight** [comment]
Thanks for the report. Support for `Array.isArray` goes back to IE 9, which I think is good enough for us?

**Comment by pstockley** [comment]
Actually, this was the only spot in the code that wasn't using Array.isArray

**Comment by developit** [comment]
It was that way for performance reasons but I am happy to revisit. Perhaps there's a slightly larger (in terms of byte size) check that can give us similar perf without the iframe issue. Thanks for starting off the discussion!

**Comment by developit** [comment]
@pstockley I've found a way to remove the Array constructor reliance in 8.0 :)

**Comment by pstockley** [comment]
Great. Thanks a lot.
