### ISSUE TITLE
The type of render function

### ISSUE THREAD

**Issue by katyo** [developit/preact#597]
As I see the prototype of `render` function is next:
```typescript
function render(node:JSX.Element, parent:Element, mergeWith?:Element):Element;
```

In `react` I render the root component (i.e. starting from `html` node) using the `document` object as container (i.e. parent) node and it works fine for this case. I tried to do same using `preact` and it also works as expected.

Actually I think the prototype of `render` function must be like that:
```typescript
function render(node:JSX.Element, parent:Element|Document, mergeWith?:Element):Element;
```

**Comment by developit** [comment]
@katyo makes sense! Happy to accept a PR for this if you have the time.

**Comment by marvinhagemeister** [comment]
Closing this, as this has been merged a while ago.
