### ISSUE TITLE
_listeners is empty in eventProxy

### ISSUE THREAD

**Issue by angus-c** [developit/preact#616]
This may well be an issue in our application code, and not preact, but I'm wondering of you can shed some light on why it might happen.

I'm wrapping all event handlers so that we can trap errors and report them correctly (otherwise window.onerror receives no data from async events in cdn hosted bundles).

We're getting a significant number of *this._listeners[t.type] is not a function* errors in preact's `eventProxy` handler (which we wrap). 

The value of `this` is typically
```
context: {
_component: None, 
_componentConstructor: None, 
_listeners: {}, 
normalizedNodeName: div
},
```

and the event logs as simply `{isTrusted: true}`

I'm guessing that this is because handler function is not resolved until the event is triggered, and the registering component has already unmounted by then.

(Most of these errors seem to originate from various windows OSes btw.)

Is it worth you putting a guard into eventProxy, or is this something we should be preventing on our end. 

Thanks!

**Comment by developit** [comment]
@angus-c are you able to narrow the events down to a specific set of browsers?  Wondering if this is an IE9 issue.

Also, what technique are you using to wrap event handlers?

**Comment by angus-c** [comment]
It's happening on all browsers but predominantly in windows OS (but not exclusively—sometimes on iOS or blackberry). A common combo is windows OS and chrome browser.

The wrapping is pasted below. `orig.apply(this, args)` in `wrapFunction` is where the call to Preact's `eventProxy` occurs. My first thought was that I'm messing up the context, but since the `_listeners` object is still a property of `this` I don't think that's the case.

I'm wondering if it's on reload after onclick. (We have a button to click reload after some errors, to ensure user has latest deployment etc). That would perhaps explain the null component (and our in memory cache is null too, which would only happen when a window first loads). If that's the case I might feel ok swallowing such errors when the component is null.

```
const targets = ['EventTarget', 'Window', 'EventSource', 'HTMLUnknownElement'];
const events = '*';

// based on https://github.com/bugsnag/bugsnag-js/blob/master/src/bugsnag.js#L1214

export default function wrapEventListeners() {
  targets
    .map(target => window[target] && window[target].prototype)
    .filter(Boolean)
    .forEach(prototype => {
      augment(prototype, 'addEventListener', orig => {
        return function x(e, f, capture, secure) {
          if (events !== '*' && events.include(e)) {
            return;
          }
          try {
            if (f && f.handleEvent) {
              f.handleEvent = wrapFunction(f.handleEvent);
            }
          } catch (err) {
            // carry on
          }
          return orig.call(this, e, wrapFunction(f), capture, secure);
        };
      });
    });
}

function augment(obj, name, wrapListener) {
  var original = obj[name];
  var replacement = wrapListener(original);
  obj[name] = replacement;
}

function wrapFunction(orig) {
  return function fn(...args) {
    try {
      if (typeof orig !== 'function') {
        return orig;
      }
      try {
        return orig.apply(this, args);
      } catch (e) {
        e.origin = errorOrigins.asyncEvent;
        // temporary, for debugging
        e.args = args;
        e.context = this;
        // end temporary
        window.onerror(null, null, null, null, e);
      }
    } catch (e) {
      return orig;
    }
  };
}
```

**Comment by angus-c** [comment]
Update: we've reproduced it and the scenario was similar to the one I suggested above. Changing the location.href in the same timeframe as an onClick. We need to clean up these cases on our end, but I'll also log but swallow these errors whenever they are caught.

**Comment by developit** [comment]
Hmm - what about memoizing wrapFunction?

```js
function wrapFunction(orig) {
  return orig.__wrapped || (orig.__wrapped = function fn(...args) {
```

**Comment by angus-c** [comment]
Yep, I think you nailed it. I was recursively wrapping functions. Occurrences dropped dramatically. 
Thanks!

**Comment by rajeshsegu** [comment]
With wrapping these errors we now stop throwing run time exceptions, but we are still left with the question why an eventProxy is not cleaned up.

```
Error: this._listeners[t.type] is not a function
```

Could this be a race condition where cleanup does not happen as expected during componentDidUnmount or while trying to repurpose the dom elements ?

**Comment by developit** [comment]
It's possible - I'm just about to release preact 8 which fixes 2 unmount corner cases and tweaks the event management code to be more direct.  I'm fairly confident it'll remove those errors.

**Comment by rajeshsegu** [comment]
@developit are the specific pull requests that might have these changes.

**Comment by developit** [comment]
No - it'll be annotated commits on an `8` branch, will post them here. This release was a bit odd in terms of process, will be switching to a more transparent process once it's out.

**Comment by gdub22** [comment]
I'm experiencing something similar on 8.
Every so often after refreshing a bunch (Chrome mac), `this._listeners` is undefined in `eventProxy`.

Not doing anything fancy, just an `<img onLoad={ ... }>` and get
```
Uncaught TypeError: Cannot read property 'load' of undefined
    at HTMLImageElement.eventProxy (preact.js:96)
```

**Comment by sunlee-newyork** [comment]
I'm experiencing an issue where the value of `this._listeners[e.type]` is the target dom node and not a function:

<img width="455" alt="screen shot 2018-06-01 at 2 34 36 pm" src="https://user-images.githubusercontent.com/3077409/40857705-efb7307a-65a9-11e8-8fe4-3e8427764c72.png">

Really stumped as to how this happens! I have the same exact setup for 4 other buttons on the same page, and I checked the eventProxy function return value - they're all functions as expected.
