### ISSUE TITLE
Remove ComponentLifecycle interface in favour of individual interfaces

### ISSUE THREAD

**Issue by UnwrittenFun** [developit/preact#620]
I'd like to propose removing the [ComponentLifecycle](https://github.com/developit/preact/blob/master/src/preact.d.ts#L25-L34) interface and replace it with individual interfaces, e.g.
```ts
interface WillMount {
    componentWillMount(): void;
}

interface WillReceiveProps<PropsType, ContextType> {
    componentWillReceiveProps(nextProps: PropsType, nextContext: ContextType): void;
}
```

This way instead of Component implementing the ComponentLifecycle interface where everything is marked optional, the consumer would be able to explicitly implement WillMount, for example.

This allows for greater type safety as TypeScript will be able to know if the interface is implemented incorrectly, something it can't do with the current solution.
![](https://i.uwf.io/nwaIQg.png)

This has the added benefit of allowing vscode (and presumably other editors) to auto implement the interfaces. (And I wouldn't have to flick to the docs because I forgot the signature literally every time I need to implement a lifecycle event 😳)

I realise this would deviate from the React typings, but I am hoping that is not a major concern.

**Comment by robertknight** [comment]
Unless I'm missing something, splitting up the interface shouldn't be necessary to get type safety. Since JavaScript does not support overloaded methods (ie. there can only be one implementation with a given name), then TypeScript knows that if a particular optional method is implemented then it must conform to the signature of any method with the same name in implemented interfaces.

```ts
import { Component } from 'preact';

class Thing extends Component<any,any> implements preact.ComponentLifecycle<any,any> {
       // error TS2420: Class 'Thing' incorrectly implements interface 'ComponentLifecycle<any, any>'
	componentWillMount(a: string): number {
		return 42;
	}

	render() {
		return null;
	}
}
```

One slightly surprising thing I noticed here is that `implements` is not transitive, so although `Component` is declared to implement `ComponentLifecycle`, subclasses of `Component` are not automatically required to implement it.

**Comment by UnwrittenFun** [comment]
Yeah if you implement the ComponentLifecycle interface on your class that extends Component it will bring back that type safety, however as it stands Component already implements ComponentLifecycle and it would be odd to implement it twice.

The ComponentLifecycle interface as it is, isn't very useful as implementing it gives no guarantees to the methods on the class and when implementing the methods, gives no type info for the parameters (though separating them out also does not provide this, it does allow editor codegen)
![](https://i.uwf.io/rxxUvO.png)

**Comment by developit** [comment]
You guys know I'm a typescript newbie, but I had a thought:  would it help if we generated documentation output from the JSDoc annotations in the codebase?  That would probably be a good way to make sure we're keeping the TS definitions and JS annotations (and thus JS) in sync.

Thoughts?

**Comment by UnwrittenFun** [comment]
I agree that it would be a nice way to keep things in sync, though there would need to be a way to define extra types/interfaces either in jsdoc or in a separate .d.ts file.

There seems to be two existing solutions, [jsdoc-typescript-plugin](https://github.com/jumpinjackie/jsdoc-typescript-plugin) and [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc). I am unsure of benefits/downsides of either of them. I can probably play around with them sometime this week

**Comment by developit** [comment]
nice - I had no idea there were solutions for that. super curious to see if either could work.

**Comment by robertknight** [comment]
>  however as it stands Component already implements ComponentLifecycle and it would be odd to implement it twice.

Right, but I'm not clear on why it is the case that you need to explicitly implement it rather than having the interface be inherited from the component definition. It would be great to clarify this with someone who has a deeper understanding of the TS language.

> The ComponentLifecycle interface as it is, isn't very useful as implementing it gives no guarantees to the methods on the class and when implementing the methods, gives no type info for the parameters 

I'm assuming the lack of type info in your screenshot is related to the need to explicitly implement the `ComponentLifecycle` interface in `Thing`.

**Comment by UnwrittenFun** [comment]
I guess my main point is that the interface at the moment, isn't really doing much if anything for anyone. There is no reason the methods defined on the the interface couldn't just be defined on the component class, and as not every component will actually implement all if any of these methods, it seems incorrect to say `implements ComponentLifecycle` when in actuality it may not have implemented any of it.

At the moment given a Component
```ts
class Thing extends Component<any, any> {
  render() {
    return null;
  }
}

const myThing: Thing; // Somehow obtain a reference to Thing
myThing.componentDidMount() // Incorrect, but typescript will happily let you do this
// as Component implements ComponentLifecycle where all the methods are optional
```

Removing ComponentLifecycle in favour of user implementable interfaces allows this case to be correctly picked up on (though I do realise it's probably unlikely you would be calling lifecycle methods in your own code).

Angular also currently does with interfaces such as OnInit, OnDestroy, AfterViewInit, etc. They are optional in Angular as they would be here, but the [docs do advocate their use](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#interface-optional) "in order to benefit from strong typing and editor tooling"

Overall I feel like the current use of ComponentLifecycle provides little to no benefit over separate, user implementable interfaces, and fails to take advantage of the power of interfaces and TypeScript.

**Comment by matthewmueller** [comment]
does:

```js
render() {
  return null
}
```

Work right now? I'm running into:

```js
Class 'Head' incorrectly extends base class 'Component<any, any>'.
  Types of property 'render' are incompatible.
    Type '() => null' is not assignable to type '(props?: any, state?: any, context?: any) => Element'.
      Type 'null' is not assignable to type 'Element'.'
```

**Comment by marvinhagemeister** [comment]
@UnwrittenFun Great find! We should indeed make this work. Recent TypeScript versions handle optional methods correctly (just checked). So it is enough to simply declare the lifecycle methods as optional in the `Component`-interface.

**Comment by marvinhagemeister** [comment]
(note to self, never mention issues in git commit messages, to prevent github spam).
