### ISSUE TITLE
Ref's are called twice when rerendering

### ISSUE THREAD

**Issue by marvinhagemeister** [developit/preact#635]
Simple test case:

```js
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>Preact Ref Bug</title>
</head>
<body>
  <div id="root"></div>
  <script src="https://unpkg.com/preact@8.0.1"></script>
  <script>
    const { Component, h, render } = window.preact;

    class Container extends Component {
      onClick() {
        // noop to force re-rendering
        this.setState({});
      }

      render() {
        return h("div", null,
          h("button", { onClick: this.onClick.bind(this) }, "Click Me"),
          h(Child)
        );
      }
    } 

    class Child extends Component {
      ref(el) {
        console.log("called ref", el)
      }

      render() {
        return h("div", { ref: this.ref.bind(this) }, "hello");
      }
    }

    render(h(Container), document.getElementById("root"));
  </script>
</body>
```

When running the above test, the `console.log` statement is printed twice, once with `null` and once with the actual `ref`.

**Comment by developit** [comment]
@marvinhagemeister Ah - you're calling `bind()` in render, so every render is giving a newly created bound function as a `ref` to the div.  Hoisting the bind should fix the issue.

**Comment by marvinhagemeister** [comment]
@developit ohh.. you're right! One always learns something new. Thanks for the quick answer 💯

**Comment by NekR** [comment]
@developit sadly a lot of people from React world do so. Especially non-JS ones coming from Ruby, etc. and just doing so because it was done in some examples 😐
