### ISSUE TITLE
CodePen Template is not working

### ISSUE THREAD

**Issue by kmpkt** [developit/preact#640]
The Getting Started example on codepen isn't working:
http://codepen.io/developit/pen/pgaROe?editors=0010

Error: this.linkState is not a function

**Comment by KingPixil** [comment]
`linkState` was removed in Preact 8, which is what the demo is using. 

@developit needs to update it to include the [`linkState`](https://github.com/developit/linkstate) module.

**Comment by developit** [comment]
Fixed!

**Comment by kmpkt** [comment]
Thank you.
