### ISSUE TITLE
Please add preact-mdc to libraries and demos in preact README

### ISSUE THREAD

**Issue by BerndWessels** [developit/preact#644]
Hi @developit 

here is another great `preact` library that I believe is worth being mentioned in the `preact` readme.

[preact-mdc](https://github.com/BerndWessels/preact-mdc)
[preact-mdc-demo](https://github.com/BerndWessels/preact-mdc-demo)

Especially since `mdl` is now deprecated and replaced by `mdc`.

**Comment by developit** [comment]
This looks awesome!
