### ISSUE TITLE
Breaking change in behavior in interpolation (or bug?) 7.2.1 -> 8.1

### ISSUE THREAD

**Issue by oskarhane** [developit/preact#649]
Hi, I came across this when upgrading to Preact 8 recently.
I'm not sure of bug or new feature 😸  but I didn't find anything about it in the migration docs.

Open console and execute these two gists.

First 8.1: https://esnextb.in/?gist=7e1fb23c1b9d0dc43f1d6b9069ed5190
It logs `["xx", "Hello"]`.

Then 7.2.1: https://esnextb.in/?gist=e9b1d7c4da061b144c67d93291824d96
It logs: `["xxHello"]`

The only difference is the Preact version.

(adding the important parts of the code below if esnextb.in goes away)
```
const val = 'xx'
render(<Comp>{val}Hello</Comp>, document.getElementById('app'))
```

**Comment by developit** [comment]
It's a feature. We merge adjacent text nodes because that produces fewer DOM operations, but this was a bit arbitrary for Components. There was an issue opened that pointed out the flaw:

```js
render(<Foo>a{2}</Foo>)
```

In the above case in Preact 7.x and prior, Foo would be passed `props.children=['a2']`. This is also confusing for `null` values, since those are cast to empty strings.

In 8.x, `props.children` for components is not normalized to merge adjacent String values, and existing child types are preserved. 

Did this affect your app? I'd be happy to revisit.

**Comment by oskarhane** [comment]
Thanks for the info!

Not a big issue, just caught by surprise where the code assumed `children` to have a single element so we used `children[0]` instead of `children.join('')` (because everywhere we used that component it has `{varialbe}text text` as children)

**Comment by developit** [comment]
Ahhh, definitely. Heck, I think we might have some of those cases in our codebase...

Perhaps it's worth checking how others are handling this, I'm by no means an authority on the subject haha.

**Comment by NekR** [comment]
I just caught myself on thinking that text is a single child and that only components add another children item.

I'm not actually sure what's better, both approaches seems right.

**Comment by developit** [comment]
Yeah, I'm stuck on that. I guess really the only thought here is "what does react do?", and AFAIK it just treats children as whatever you pass, so it'd be the Array of strings/numbers/etc.

**Comment by robertknight** [comment]
React renders a separate text node for each child:

```js
import React from "react";
import { render } from "react-dom";

function App() {
  const two = "Two";
  return <div>One {two} Three</div>;
}

const root = document.querySelector("#app");
render(<App />, root);
```

Demo: https://codesandbox.io/s/ol0y4v26lq

Since Preact is consistent with React here and the current behaviour is easy to reason about, I think this issue can be closed. Please let me know if you can think of a strong reason to change this.
