### ISSUE TITLE
cloneElement is not working properly

### ISSUE THREAD

**Issue by seeden** [developit/preact#650]
cloneElement is not working for extended classes or stateless react components
Both examples are working in React but only second is working in Preact.

# working only in React
```js
class Test extends Component {
}

cloneElement(Test, { param: 111});
```

# working in both React and Preact
```js
class Test extends Component {
}

cloneElement(<Test />, { param: 111});
```

I know that standard is to return <Test param={111} /> but this behaviour is inconsistent with react. Maybe it is related to preact-compat

**Comment by developit** [comment]
Hmm - AFAIK React is just passthrough for that:

```js
cloneElement(Test) === Test  // true
```

**Comment by seeden** [comment]
but preact cloneElement will try to do h(Test.nodeName, ... and nodeName is undefined

**Comment by developit** [comment]
Right, I'm not saying Preact is correct here - I think we need to make preact's cloneElement() passthrough like React's is. It also affects Text nodes.  I just wanted to make the point that cloneElement() isn't doing anything in the example.

**Comment by paul-craciunoiu-ck** [comment]
👍  this is an issue for me as well.

@developit is there another way you suggest adding a prop to a child component? All the examples I'm finding use `React.Children` and `React.cloneElement`, e.g.:
https://jaketrent.com/post/send-props-to-children-react/

**Comment by developit** [comment]
@paul-craciunoiu-ck Preact supports `cloneElement()` like React, just use that.  This issue is just tracking support for `cloneElement()` ignoring (passing through) things it doesn't recognize.

**Comment by developit** [comment]
Just an update @seeden - it looks like more recent versions of React actually behave like Preact:

![image](https://cloud.githubusercontent.com/assets/105127/26432374/6a07488a-40c9-11e7-914f-b2eeb2942c78.png)

https://jsfiddle.net/developit/xo3Loy8t/

FWIW even with a fix in place, `cloneElement(Ctor, { foo: 'bar' })` would just return `Ctor`. Without being a VNode, there's no way for cloneElement() to actually apply the props.

**Comment by seeden** [comment]
I fixed my code after this issue with preact. I replaced my code with 
```js
return <Test params={111} />
```  
instead of 
```js
cloneElement(Test, { params: 111 })
```. 

You can close it if you want

**Comment by paul-craciunoiu-ck** [comment]
@developit ah I figured this out. It's actually the lack of support for synthetic events that was the issue.

**Comment by developit** [comment]
Gotch.

**Comment by prateekbh** [comment]
is this somewhere related to the fact that below code does not render anything
```
<TransitionGroup>
  {cloneElement(props.children)}
</TransitionGroup>
```

**Comment by marvinhagemeister** [comment]
@prateekbh `cloneElement` only works on single elements, and the `children` prop is always of type array. In your case you likely don't need `cloneElement` at all.

I just compared our implementation with react's and we both do the same thing, minus the difference with `synthetic events`.
