### ISSUE TITLE
Default-true boolean attributes mistakenly removed from nodes?

### ISSUE THREAD

**Issue by jcreedcmu** [developit/preact#651]
Thanks for all your work on this library!

When I write
```jsx
<input spellCheck={false}/>
```
I expected to get a `<input>` DOM element with `spellcheck` set to false --- but instead it appears to be set to `null`, and so effectively spellchecking remains on for that input element. Is this expectation sensible?

If so, does something else need to happen in the vicinity of https://github.com/developit/preact/blob/master/src/dom/index.js#L75-L87 ? There are two things going on with `spellCheck` in particular; one is that the (p)react name for it is camel-cased, but the actual DOM attribute is lowercase, so we fall into https://github.com/developit/preact/blob/master/src/dom/index.js#L80-L87 --- because while `"spellcheck" in node` is true, `"spellCheck" in node` isn't. Two is that all falsy values seem to be rendered into the DOM as absent attributes, which doesn't seem to make sense for attributes that are default-true, (like `spellcheck`) and require an explicit false setting to clear them.

**Comment by jcreedcmu** [comment]
Ah, for comparison, I see that React explicitly has a per-attribute bit of information called `hasBooleanValue` in https://github.com/facebook/react/blob/master/src/renderers/dom/shared/DOMProperty.js to signal that a boolean valued attribute expresses itself by being present or absent, and, as I'd expect, `spellCheck` has that flag *not* set in https://github.com/facebook/react/blob/master/src/renderers/dom/shared/HTMLDOMPropertyConfig.js .

**Comment by developit** [comment]
Indeed - if you want to trigger Preact to use a property instead of an attribute, you'll have to make sure the casing matches. In this case, the DOM property is actually called `spellcheck` (lowercase C):

```js
<input spellcheck={false} />
// is essentially the same as:
input.spellcheck = false;
```

**Comment by jcreedcmu** [comment]
Ok, the reason I thought your intent was to keep it camel-cased was because of it being camel-cased  https://github.com/developit/preact/blob/master/src/preact.d.ts#L567 . I get typescript type errors with it lowercase. Should that be changed?

But I am still observing the attribute not being set even when I refer to it lowercased. I think it's line
https://github.com/developit/preact/blob/master/src/dom/index.js#L77
that's removing it.

Concretely, if I inspect the `input` created by https://jsfiddle.net/5jtgv2zz/ it does not have spellcheck set to false; the attribute's just absent, and spellchecking still is turned on if I put nonsense words in the input field.

**Comment by jcreedcmu** [comment]
https://jsfiddle.net/ue86pdpb/ is a side-by-side comparison showing that afaict
```jsx
<input spellcheck={false} />
```
does _not_ in fact behave the same as
```js
input.spellcheck = false;
```
Hope that helps clarify what I'm asking about! I'm still happy to find out that I'm simply confused about something or asking an ill-formed question in some way, but so far this does seem like an unexpected behavior to me still.

**Comment by jcreedcmu** [comment]
Guess this is all traceable back to https://github.com/developit/preact/commit/460099f3bd6b96dab8eeaba3b7ebd7fd80d66016 ...

**Comment by developit** [comment]
Ahh that's an interesting one yup.
