### ISSUE TITLE
Children is lost when component reRender.

### ISSUE THREAD

**Issue by windyGex** [developit/preact#660]
code:

```js
class Table extends React.Component {
    render() {
        const {dataSource, checked, children} = this.props;
        return <div>{
                dataSource.map(item => {
                    return <div>{checked ? 'checked' : ''}{item.name}<em>{children.props.dataIndex}</em></div>
                })
            }</div>
    }
}

function mountMock(element) {
    class Wrapper extends React.Component {
        state = {
            props: element.props,
            Component: element.type
        };
        setProps(props) {
            props = {...this.state.props, ...props};
            this.setState({
                props
            });
        }
        render() {
            const {Component} = this.state;
            return <Component {...this.state.props} />;
        }
    }
    const div = document.createElement('div');
    document.body.appendChild(div);
    return ReactDOM.render(<Wrapper/>, div);
}
const dataSource = [{ id: '1', name: 'test' }, { id: '2', name: 'test2' }];
const table = (
        <Table dataSource={dataSource}>
            <div dataIndex='id'/>
        </Table>
        );
const inc = mountMock(table);
inc.setProps({
    checked: true
});
```
expected output:

![image](https://cloud.githubusercontent.com/assets/197348/25270469/6736bff8-26b3-11e7-9ee7-e1c16ae7f67d.png)

But preact will throw error.

![image](https://cloud.githubusercontent.com/assets/197348/25270539/9b00a560-26b3-11e7-99a9-a3c20c8e36f7.png)

![image](https://cloud.githubusercontent.com/assets/197348/25270562/acd05f38-26b3-11e7-9f60-ad97be1d91b9.png)

**Comment by developit** [comment]
Looks like it's due to `props.children` being mutated in-place, likely in preact-compat.

**Comment by windyGex** [comment]
So, Could you fix this? I can't find any problem by debug.

**Comment by developit** [comment]
Yes, I just don't know how yet.

**Comment by windyGex** [comment]
Maybe here
https://github.com/developit/preact/blob/master/src/h.js#L21

**Comment by developit** [comment]
should be added back in [here](https://github.com/developit/preact-compat/blob/master/src/index.js#L80) though..

**Comment by matthewmueller** [comment]
Interesting, I think I just ran into this too with https://github.com/ooade/preact-side-effect

I don't think it's related to preact-compat, and it seems to go back to atleast 5.x.

**Comment by simonjoom** [comment]
I have got as well some problem with children too but with dangerousetinnerHtml , 

Try to apply my patch in  preact.js code (yeah i write it in preact-compat issues but it's more relatif to preact.js
I think it's could work in your case too. 

after apply the patch code , just add innerHTML as a props in <Table innerHTML ... >

the code to change is explained in this thread:
https://github.com/developit/preact-compat/issues/371

if developit could see it and give a feedback . 
My website haven't got issue anymore with dangerousetinnerHtml  after that.


Regards

**Comment by windyGex** [comment]
I remove this line code and it work well. 

https://github.com/developit/preact/blob/master/src/h.js#L21
