### ISSUE TITLE
Unable to set a property with `false` value

### ISSUE THREAD

**Issue by NekR** [developit/preact#663]
I have a problem with `draggable` property which might be `true` by default, e.g. on `<img>`.
Problem is with this line: https://github.com/developit/preact/blob/master/src/dom/index.js#L77, if I set property to `false` preact adds it and then immediately removed via `removeAttribute`. The workaround is to use `0`, e.g. `draggable={0}` this way it isn't being caught by the problematic line and is converted to `false` to property assign by the browser.

**Comment by developit** [comment]
Hmm, yeah that's tricky.  I am trying to remember why the property setter would care about invoking `removeAttribute` in the first place. Any guesses?

**Comment by NekR** [comment]
@developit maybe something related to `<select>`/`<option>` and `selected` attribute, it was always a mess what attr or prop takes priority in the browser, not sure. Also maybe for hydration, i.e. SSR?

**Comment by Kagami** [comment]
Just encountered this. Seems like that behavior was added in https://github.com/developit/preact/commit/460099f3bd6b96dab8eeaba3b7ebd7fd80d66016.

**Comment by haskellcamargo** [comment]
I also had this issue. We should remember that JS has `true`, `false` and `null`, therefore explicitly falsy values **shouldn't** be removed as long as there is not specification on HTML that the absence of a property defaults it to `false` (and `draggable` is an example that defaults to `true`).

**Comment by Chopinsky** [comment]
I think a potential solution to this problem would be checking if the current node's property value is the same as the value to be set before removing the attribute, I think this will help us avoid the pitfall if the attribute's default value is not false or null. This might add a few overheads especially for the SSR cases, but it will make the components less dependent to the browser's implementation of the DOM elements. 

I can make a PR if this sounds like a plan.

**Comment by pl12133** [comment]
Related: https://github.com/developit/preact/issues/58

Linking because that one comes up when searching for `preact draggable false`.

**Comment by marvinhagemeister** [comment]
Just checked with our code in `master` and this is resolved :tada: Setting `draggable` to `false` works :+1:
