### ISSUE TITLE
 shouldComponentUpdate() Never called on State change.

### ISSUE THREAD

**Issue by zanderisrael** [developit/preact#668]
For some reason,  shouldComponentUpdate() is never called in the childeren components on parent state change...

Using: https://github.com/developit/preact-boilerplate as base.

Updated to latest preact release 8.1.0. 

Please guide me to what information can help identify the problem.

**Comment by developit** [comment]
Are you able to provide a reproduction of the issue?  There are quite a few things that could cause this to happen.

**Comment by zanderisrael** [comment]
@developit Added you to the project bitbucket, you have read access.

**Comment by zanderisrael** [comment]
*Update* 

A jquery lib I used F* things up, sorry for the false alarm.

**Comment by developit** [comment]
tee hee :D
I wondered when I saw that access, didn't make the connection.
Guess we can close this out :)

**Comment by faridz974** [comment]
Hello,
I have the same issue with a jquery lib. How did you solve it please ?
