### ISSUE TITLE
Use typescript's --checkJS to validate preact doc comments

### ISSUE THREAD

**Issue by nojvek** [developit/preact#679]
1. Community doesn't have to maintain a separate .d.ts, this could be generated from code. 
2. Preact already uses jsdoc, and --checkJS can actually validate the typings specified in jsdoc.
3. Anyone making changes to preactjs will get excellent code completion and intellisense if they are using a typescript plugin in vscode, sublime, atom, vim e.t.c

**Comment by developit** [comment]
Wow, had no idea it could do that. Definitely liking this idea.

**Comment by robertknight** [comment]
This is new in the [TypeScript 2.3](https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/) release.

> Community doesn't have to maintain a separate .d.ts, this could be generated from code.

I'm not sure that's possible. Does TypeScript's JSDoc support allow defining types in one module and then re-using them from another module? From my limited testing this appears not to be the case. On that basis, shared interfaces would still need to be defined in the `.d.ts` file but could then be referenced by JSDoc comments.

**Comment by mihailik** [comment]
Update: there's a feature in the works, apparently nearing completion:

https://github.com/Microsoft/TypeScript/issues/7546

https://github.com/Microsoft/TypeScript/pull/15911

**Comment by devmacmari** [comment]
+1 on the idea!
btw, how about moving preact code base to typescript?
it can be done gradually (like 10% -> 30% -> ...), IDEs starts to help devs with auto-suggestions & refactoring goodies, etc.

**Comment by screendriver** [comment]
@devmacmari you can read about it here https://github.com/developit/preact/issues/639#issuecomment-302917848

**Comment by marvinhagemeister** [comment]
We discussed moving to TS a few times internally and some of us even attempted to do that on our own. Two of us are quite the fans of TS, but we both came to the realization that it doesn't work well with our code. We employ some tricks to determine the type of a variable which are failing in TS (checked with 3.3.3333). 

Here is a simple example that breaks:

```ts
function isType(arg: object | any[]) {
    // Will break here
    if (arg.pop) return "array";
    return "boolean"
}
```

As much as I'd love to add this (or enable `checkJs`) we are blocked by this.
