### ISSUE TITLE
How to integrate material-ui with preact

### ISSUE THREAD

**Issue by marcosguti** [developit/preact#680]
I'm trying to use material-ui and I'm getting react-dom errors, preact-compact is the solution for this?

**Comment by developit** [comment]
yes, `material-ui` uses React-specific APIs like `findDOMNode()`, `Children.*()` and String refs.  It should work fine with `preact-compat`.  Let me know if that's not the case and we can re-open :)

**Comment by marcosguti** [comment]
Ok thanks, checking again I see that the problem is not with material-ui, but yes with react-tap-event-plugin for handle events in material-ui http://www.material-ui.com/#/get-started/installation, I am using preact-boilerplate which has already included all preact-compat settings, see the error in the screenshot
![error](https://cloud.githubusercontent.com/assets/18442798/25571053/47acf5ec-2df9-11e7-90fa-07eb7730b342.jpg). 
Why  this error?

**Comment by developit** [comment]
Ah yes, you'll need to alias that out for preact-tap-event-plugin in `webpack.config.babel.js`:

```js
{
  resolve: {
    alias: {
      'react-tap-event-plugin': 'preact-tap-event-plugin'
    }
  }
}
```
