### ISSUE TITLE
Would you accept a PR to `console.warn` about misspellings?

### ISSUE THREAD

**Issue by Emilios1995** [developit/preact#684]
React does it in dev mode. Should preact do the same?
see for example:
[GitHub code search for "componentDidUnmount"](https://github.com/search?utf8=%E2%9C%93&q=componentDidUnmount&type=Code)
[GitHub code search for "componentWillRecieveProps"](https://github.com/search?utf8=%E2%9C%93&q=componentWillRecieveProps&type=Code)
There are a lot of those

**Comment by developit** [comment]
Only as part of `preact/debug`. Preact does not have a dev mode, debug is how we intend to add these types of warnings. 

For what's it's worth a linter is a much nicer way to get warnings about these things :)

**Comment by marvinhagemeister** [comment]
Just checked the `react` repo and they do have code that checks for type errors in lifecycle methods. Nonetheless, I think this is already perfectly handled by linters or type systems (even better) 💯  We would just duplicate that effort.

@Emilios1995 Perhaps you can share your use case, where linters/Flow/TS didn't help you further? If there is still an issue feel free to ping me and I'll reopen this one.
