### ISSUE TITLE
Code coverage is not accurate

### ISSUE THREAD

**Issue by gdub22** [developit/preact#685]
The karma runner is compacting the src before running code coverage, therefore dead code eliminating anything that isn't used:

https://github.com/developit/preact/blob/9001436a453d736267359538e2d822ccf23e3115/test/karma.conf.js#L124

For example, `cloneElement` is never tested/imported.  Disable that line and you'll see coverage drop.  Uncovered during https://github.com/developit/preact/pull/683

**Comment by developit** [comment]
Ah , good catch.
