### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined 

### ISSUE THREAD

**Issue by zhuyinjing** [developit/preact#686]
hello,
recently,i use a plugin in my project.
And this plugin depend on preact
and when i import it to my project
it shows error in chrome console,it shows `Uncaught TypeError: Super expression must either be null or a function, not undefined `
and my project is using vue.js
how should i do?
thanks a lot!!!

**Comment by developit** [comment]
Need more information in order to know what's going on here - how are you using preact and vue at the same time?

**Comment by developit** [comment]
It seems like your build is not resolving the `Component` class from `preact`.  This may simply be due to preact not being installed.

**Comment by rajasimon** [comment]
May be because of this `import Component from 'preact';`

**Comment by rbenvenuto** [comment]
I faced the same issue with a package that depends on Preact.

- checked my `node_modules, preact is installed
- tried changing `import { Component } from 'preact'` to `import Preact from 'preact'` and doing `Preact.Component` where i needed
- Tried erasing `node_modules` and yarn.lok and installing the dependencies again.
- tried `console.log(Preact.Component)` and it prints `undefined`
- I'm in a create-react-app application

None of this worked
Can anyone help me?

Here's my `package.json`

`"dependencies": {
    "@private/package": "file:./path-to-private/package", // this is the package that's giving me the bug
    "react": "^16.4.1",
    "webpack": "3.8.1",
    ...
}`
