### ISSUE TITLE
Possible to alias React.createElement to h? (no preact-compat)

### ISSUE THREAD

**Issue by bwhitty** [developit/preact#692]
Hello! Inspired by your tweet @developit about react-router v4 working out of the box with preact, I tried to take that step further to see if I could get server rendering working. The blocker that I run into is that I'd like to do this *without `preact-compat`* and  `react-router` v4's `<StaticRouter/>` (and some other APIs) explicitly depend on `React.createElement` which when used in conjunction with `preact-render-to-string` ends up failing in unexpected ways (for obvious reasons).

Am I totally off base in thinking I can possibly alias this out the `React.createElement` usages in `react-router`'s raw ES build to `preact`'s `h` via webpack (yeah a bundled server, just bear with me) or a custom babel transform? Or possibly extract `preact-compat`'s `createElement` implementation and do the same?

Another possibility I was toying with was forking `react-router` and going in an replacing the `createElement` calls... but with what is kind of where I'm at. With `h`?

I know this sounds nuts but I'd really appreciate it if I could bounce these ideas off of you (or anyone listening) and get a quick sanity check.

Also: thank you so much for you and everyone else's time and effort on this project! 🌟

**Comment by developit** [comment]
We added this in 8.0! :D
https://github.com/developit/preact/blob/master/src/preact.js#L10

**Comment by bwhitty** [comment]
Yep, I'm a newbie. Thanks!
