### ISSUE TITLE
render-queue 

### ISSUE THREAD

**Issue by linxizhilu** [developit/preact#702]
I just have a question in render-queue.js.
why not use 
```javascript
if (!component._dirty && (component._dirty = true) && items.push(component)>=1) {
		
	}
```
to replace
```javascript
if (!component._dirty && (component._dirty = true) && items.push(component)==1) {
	
	}
```

**Comment by developit** [comment]
The render queue is only triggered when the first item is placed into the queue. Subsequent items are just added to the list since there is already a deferred rerender in place.

**Comment by developit** [comment]
I probably closed that preemptively - feel free to discuss! 👍

**Comment by linxizhilu** [comment]
Thanks，I think i have known what's your meaning
