### ISSUE TITLE
It's said 3kB. Why bundle.js for simplest app weight 20kb. 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [developit/preact#711]
Is there any way I can minify it yet? I wanna run it on nodeMCU.

**Comment by NekR** [comment]
What's bundle.is webpack bundle? If so, then there is webpack's code of course. Plus yes, you have to minify it yourself and make sure your server gzips the responses.

**Comment by AlexanderKozhevin** [comment]
Alright, then.

**Comment by tushar-singh** [comment]
@AlexanderKozhevin 3kb is gzipped size. non-gzipped minified bundle is about 8KB

The reason you're seeing 20kb is because webpack is bundling `dist/preact.js` instead of `dist/preact.min.js` 

You can tell webpack to use the minified bundle in production builds

```
resolve: {
    alias: {
        preact: process.env.NODE_ENV === 'production' ? 'node_modules/preact/dist/preact.min.js' : 'preact',
    }
 },
```

**Comment by mehmetkose** [comment]
it's gzipped size.
