### ISSUE TITLE
Uncaught TypeError: value is not a function

### ISSUE THREAD

**Issue by AlexanderKozhevin** [developit/preact#712]
I can't use **refs**?
```
<input type="text"  ref="myInput"  placeholder="API Key"   />
```
I'm getting an error. 
I'm using [preact-boilerplate](https://github.com/developit/preact-boilerplate).

**Comment by pl12133** [comment]
This looks like you are using string refs, which are not supported in Preact. Instead you can use a function just like in React, or use the [linkRef module](https://www.npmjs.com/package/linkref) for something that looks similar to string refs.

For differences like this between React and Preact, you can check on [Differences from React](https://preactjs.com/guide/differences-to-react) in the official docs for more details.

**Comment by marvinhagemeister** [comment]
Note that string refs are deprecated in react too.

**Comment by AlexanderKozhevin** [comment]
Oh, alright. Thanx for guidance!

**Comment by developit** [comment]
I somehow never saw this, but since it's in our docs I'll close the issue out. Hopefully anyone searching for the topic finds this helpful issue or the linked doc :)
