### ISSUE TITLE
Request for a How-to guide - sharing config info with multiple components

### ISSUE THREAD

**Issue by oren** [developit/preact#714]
My app was created using `preact create app --type full`.
I have a few config variables that are suppose to be available to multiple components:
```
const API_HOST = process.env.NODE_ENV === 'production' ? 'https://api.healthcobot.com' : 'http://localhost:3000';)
```

Right now I just add this line to every component that needs it but obviously this is not a good practice. [Here](https://github.com/oren/admin/blob/9cd58dd71f934098a4b619b2a396c069ba5d1e8c/src/routes/login/index.js#L172) is one example of using it.

I asked this on [slack](https://preact.slack.com/archives/C3NMBSJKH/p1496022635122614) and got a few response. The problem is I don't know how to implement any of them. Can anyone write complete code sample that demonstrates any of the approaches? My preferences is not to use 3rd party libraries so I would like to try the first or second approaches but here are the 4 responses I got: 

## 1. Pass those around via context

```
class Provider extends Component {
  getChildContext() {
    let { ...context, children } = this.props;
    return context;
  }
  render({ children }) {
    return children[0];
  }
}

class App extends Component {
  constructor(props, context) {
    let { API_HOST } = context.config;

    // also available as: this.context.config
  }
}

const myConfig = {
  API_HOST: '//foo.com'
}

render(
  <Provider config={myConfig}>
    <App />
  </Provider>
)
```

## 2. Create a decorator to pass configuration to components as props:

```
const configure = keys => Child => (props, context) => {
  let childProps = {};
  for (let i in keys) childProps[i] = context[keys[i]];
  return <Child {...childProps} {...props} />
}

@configure({ url: 'API_HOST' })
class Foo {
  render({ url }) {
    url  // config.API_HOST
  }
}
```

## 3. Holen - https://github.com/tkh44/holen
```
const MyFetch = (props) => <Holen {....props} url={process.env.NODE_ENV === 'production' ? 'https://api.healthcobot.com' : 'http://localhost:3000'}/>
```
you can append from props.url as well: `<MyFetch url="/foo" />`

**Comment by developit** [comment]
I wonder if we can close this out now that [preconf](https://github.com/synacor/preconf) is a thing?  It implements the first pattern and has its own docs that explain how to use it.

**Comment by oren** [comment]
is preconf part of preact or do i need to add it separately? I assume the latter. Thank you!

**Comment by developit** [comment]
Correct, it's a separate library, docs are here: https://github.com/synacor/preconf

**Comment by marvinhagemeister** [comment]
@oren Using `context` is a great solution. If you need something more complex than state management solutions like `unistore`, `redux` or `mobx` may fit the bill quite nicely.
