### ISSUE TITLE
Input elements are sometimes reused in other components

### ISSUE THREAD

**Issue by BenoitZugmeyer** [developit/preact#716]
With preact-router, I am building two similar pages (a signin form and a signup form), and I noticed that when the user starts to fill the signin form and switches to the signup form, the values he entered in the signin form may appear in the signup form. Then switching signup and signin pages back and forth, the values are still showing up in some inputs.

I tried to isolate the issue and it seems that preact is sometimes reusing elements. [Here is an illustration of the problem.](https://preactjs.com/repl?code=%2F*%0AInput%20elements%20are%20sometimes%20reused.%20I%20tried%20to%20isolate%20the%0Aissue%20from%20a%20larger%20issue%20I%20have%20using%20preact-cli%2Fpreact-router.%0A%0A%0AHere%20is%20what%20I%20do%3A%0A%0A*%20The%20Main%20component%20is%20rendered%20with%20a%20state%20value%20%22condition%22%0A%20%20alternating%20every%20500ms.%0A%09%0A*%20The%20Conditional%20component%20is%20rendering%20some%20children%0A%20%20following%20a%20condition%20(ex%3A%20a%20route%20of%20the%20preact-router)%0A%09%0A*%20The%20Foo%20component%20is%20a%20random%20component%20in%20the%20page%2C%0A%20displaying%20an%20%3Cinput%3E%0A%20%09%0A*%20A%20setTimeout%20is%20here%20to%20emulate%20the%20user%20writing%0A%20%20something%20in%20an%20input%2C%20once.%0A%0A%0AActual%20steps%20(input%20is%20strangely%20reused%20in%20other%20instances%20of%20Foo)%3A%0A%0A1.%20condition%20is%20true%2C%20%3CFoo%20label%3D%22A%22%3E%20is%20shown%2C%20value%20is%20in%20its%20input%0A2.%20condition%20is%20false%2C%20%3CFoo%20label%3D%22B%22%3E%20is%20shown%2C%20value%20is%20in%20its%20input%0A3.%20contition%20is%20true%2C%20%3CFoo%20label%3D%22A%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0A4.%20contition%20is%20false%2C%20%3CFoo%20label%3D%22B%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0A5.%20condition%20is%20true%2C%20%3CFoo%20label%3D%22A%22%3E%20is%20shown%2C%20value%20is%20in%20its%20input%0A6.%20condition%20is%20false%2C%20%3CFoo%20label%3D%22B%22%3E%20is%20shown%2C%20value%20is%20in%20its%20input%0Aetc..%0A%0A%0AExpected%20steps%20(input%20is%20only%20used%20for%20the%20first%20instance%20of%20Foo)%3A%0A1.%20condition%20is%20true%2C%20%3CFoo%20label%3D%22A%22%3E%20is%20shown%2C%20value%20is%20in%20its%20input%0A2.%20condition%20is%20false%2C%20%3CFoo%20label%3D%22B%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0A3.%20contition%20is%20true%2C%20%3CFoo%20label%3D%22A%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0A4.%20contition%20is%20false%2C%20%3CFoo%20label%3D%22B%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0A5.%20contition%20is%20true%2C%20%3CFoo%20label%3D%22A%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0A6.%20contition%20is%20false%2C%20%3CFoo%20label%3D%22B%22%3E%20is%20shown%2C%20value%20is%20not%20in%20its%20input%0Aetc..%0A*%2F%0A%0Aconst%20Conditional%20%3D%20(%7B%20condition%2C%20children%20%7D)%20%3D%3E%20(%0A%09%3Cspan%3E%7Bcondition%20%26%26%20children%7D%3C%2Fspan%3E%0A)%0A%0Aconst%20Foo%20%3D%20(%7B%20children%2C%20label%20%7D)%20%3D%3E%20(%0A%20%20%3Cdiv%3E%0A%20%20%20%20%3Cinput%20className%3D%22my-input%22%20%2F%3E%0A%20%20%20%20%7Blabel%7D%0A%20%20%3C%2Fdiv%3E%0A)%0A%0Aexport%20default%20class%20Main%20extends%20Component%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20super()%0A%20%20%20%20this.state%20%3D%20%7B%0A%20%20%20%20%20%20condition%3A%20true%2C%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20componentWillMount()%20%7B%0A%20%20%20%20setInterval(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20this.setState((%7B%20condition%20%7D)%20%3D%3E%20(%7B%20condition%3A%20!condition%20%7D))%0A%20%20%20%20%7D%2C%20500)%0A%20%20%7D%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3CConditional%20condition%3D%7Bthis.state.condition%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CFoo%20label%3D%22A%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FConditional%3E%0A%20%20%20%20%20%20%20%20%3CConditional%20condition%3D%7B!this.state.condition%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CFoo%20label%3D%22B%22%20%2F%3E%0A%20%20%20%20%20%20%20%20%3C%2FConditional%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%0A%20%20%7D%0A%7D%0A%0AsetTimeout(()%20%3D%3E%20%7B%0A%20%20document.querySelector(%22.my-input%22).value%20%3D%20Math.random()%0A%7D%2C%20250)%0A) I could have probably made a simpler example but I hope it's still easily undestandable.

This may be related to https://github.com/developit/preact-router/issues/192

**Comment by developit** [comment]
This should be fixed when we kill component recycling.

**Comment by krokofant** [comment]
@developit Is this planned? 😅

**Comment by developit** [comment]
yes.

**Comment by natevw** [comment]
I suspect this is causing a bug in my app, but wanted to confirm:

1. My app has many "pages", with each page living in a component
2. One of these pages has some uncontrolled (defaultValue) `<input>`s

After rendering many other pages (some of them containing their own inputs), returning to the page with uncontrolled inputs has them showing with an earlier value rather than the expected defaultValue. After much confusion and troubleshooting of my own code, I tracked it down to the "new" input being === to the old inputs, and so the previous `.value` was taking precedence over the `.defaultValue`.

Is this still an element recycling issue? I'm seeing a "now that recycling is gone this probably counts as a bug" at https://github.com/developit/preact/issues/941#issuecomment-350287228 (pre-dating your still-planned response here) and I think there may be some distinction between component vs. element recycling?

What is the second best workaround for this issue? (I expect the *best* workaround is convert to handling these as controlled components? ;-)

**Comment by billneff79** [comment]
Possibly related to issue #993

**Comment by natevw** [comment]
Via https://github.com/developit/preact/issues/769#issuecomment-317743541 I tried with the "scratch/perf" branch (commit 7a8e824).

This did make the unexpected input values go away, so apparently at least some sort of element recycling is still present in preact@8.2.7 which is gone on that old branch.

**Comment by HenrikJoreteg** [comment]
Yo @natevw! I hope you're well, buddy. I know it's been months, but also for whomever else stumbles across this... @developit was kind enough to spend a couple hours debugging something related to this issue and browser autofill behavior with me today. There's a way to forcibly avoid any recycling of elements. 

All of this will be unnecessary in upcoming "preact x" release but this did fix the problem I was having in 8.2.9.

Here it is as a Higher Order Component courtesy of @developit: https://gist.github.com/developit/fa084f3cb38778f93d58607377f416a3

**Comment by marvinhagemeister** [comment]
We completely removed the component recycler for Preact X. The code just landed in `master` #1302 and should be available on npm as an alpha soon :tada:
