### ISSUE TITLE
how to wake up the h function when parse jsx?

### ISSUE THREAD

**Issue by wangning0** [developit/preact#718]
In the preact inside,how to wake up the h function when parse jsx?

and more question is:
 the source code at `vnode.js` is
```
/** Virtual DOM Node */
export function VNode() {}
```

but when i debug [this project](https://preact-todomvc.surge.sh/) I find  the source code at `vnode.js`  has changed! would you mind me tell what happened ?  
```
/** Virtual DOM Node */
export function VNode(nodeName, attributes, children) {
	/** @type {string|function} */
	this.nodeName = nodeName;

	/** @type {object<string>|undefined} */
	this.attributes = attributes;

	/** @type {array<VNode>|undefined} */
	this.children = children;

	/** Reference to the given key. */
	this.key = attributes && attributes.key;
}
```

Thank u  😄

**Comment by developit** [comment]
I'm not 100% I understand, but I can explain a few things.  The source for `vnode.js` changed, but it still works exactly the same - object creation was just [moved into `h.js`](https://github.com/developit/preact/blob/master/src/h.js#L50-L54) for performance reasons:

```js
let p = new VNode();
p.nodeName = nodeName;
p.children = children;
p.attributes = attributes==null ? undefined : attributes;
p.key = attributes==null ? undefined : attributes.key;
```

To your original question, I think you're looking for a way to "hook" into h() - that's actually something Preact has an API for.  Here's an example that adds a `uuid` prop to every VNode automatically:

```js
import { options } from 'preact';

let counter = 0;

options.vnode = vnode => {
  // this function is called on every VNode created by h()

  vnode.attributes.uuid = ++counter;
};
```

Let me know if that answers your question! :)

**Comment by lensh** [comment]
thanks for your idea

**Comment by wangning0** [comment]
@developit Thanks for your answers, It helps me a lot ! 😄
