### ISSUE TITLE
server side rendering switch to preact webpack.config.js issue

### ISSUE THREAD

**Issue by wood1986** [developit/preact#720]
I am converting my project from React to Preact. Some React.Component is shared for client side and server side rendering.

The following only solves the client side rendering when the dependencies are bundling together
```
"resolve": {
    "alias": {
      "react": "preact-compat",
      "react-dom": "preact-compat"
    }
  }
```

As for the server side, I don't need the bundling because it will be run by node. How can I config the webpack.config.js to resolve `require("react-dom/server")`, `require("react-dom")` and `require("react")`. I don't want to change all require statement from `react-dom` to `preact-compat`. I dont want the `preact-compat` bundle with my server side rendering code.

**Comment by thangngoc89** [comment]
You can transpile your code with babel using [module-alias](https://www.npmjs.com/package/module-alias)

**Comment by marvinhagemeister** [comment]
As pointed out by @thangngoc89: if you don't want to touch your server code, your only option is to transpile with babel and to alias the `react` imports with `preact-compat`.

**Comment by developit** [comment]
@thangngoc89 is correct - the best way to properly alias in Node (without webpack) is [module-alias](https://www.npmjs.com/package/module-alias):

```js
require('module-alias').addAliases({
  'react'  : 'preact-compat',
  'react-dom': 'preact-compat'
});
```

or, specify this in your `package.json`:

```js
"_moduleAliases": {
  "react": "preact-compat",
  "react-dom": "preact-compat"
}
```

... and install the hook:

```js
require('module-alias/register');
```

**Comment by kappe** [comment]
I'm doing some tests using preact. Everything works fine, when I'm using preact client-side. Using preact for SSR I always run into the same problem: I'm using a component library called antd. I compile/bundle my source without error, but when I run "node index.js" I always get _Error: Cannot find module 'react'_ within the antd-files. Can anybody provide a webpack.config.js?

I'm using the following settings in different variations:
resolve: {
    alias: {
      react: "preact-compat",
      "react-dom": "preact-compat"
    }
  },

  target: "node",
  externals: nodeModules,
  //externals: nodeModules,

module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(bower_components)/,
        loader: "babel-loader",

        query: {
          presets: ["preact","latest", "env"],
          plugins: [
            ["transform-react-jsx", { "pragma":"h" } ],
            ["module-resolver", {
              "root": ["."],
              "alias": {
                  "react": "preact-compat",
                  "react-dom": "preact-compat",
                  "create-react-class": "preact-compat/lib/create-react-class"
              }
            } ]
          ]
        }
      },
    ]
  },

**Comment by lukeed** [comment]
@kappe Since you're running `node index.js`, I assuming you're _not_ compiling your server code with Webpack ahead of time. 

In which case, you probably need `module-alias` for creating an alias directly within Node.

```js
const moduleAlias = require('module-alias')

moduleAlias.addAlias('react', 'preact-compat')
moduleAlias.addAlias('react-dom', 'preact-compat')
```

**Comment by kappe** [comment]
@lukeed I'm compiling my index.js but do exclude the antd-file (externals: nodeModules)
I've put these 3 lines of code on top of my index.js but I've got the same error.
When I try to include the "externals" I get several compiler errors.
