### ISSUE TITLE
component functions not accessible?

### ISSUE THREAD

**Issue by Pomax** [developit/preact#722]
If I write the following component:
```
class Thing extends Component {
  constructor() { super(); }
  render() { return <div>blah</div>; }
  someFunction() { return "something; }
}
```
and I then use preact for the following:
```
const thing = <Thing />;
let somevalue = thing.someFunction();
```
then that is an error. How do I call functions on my component? The README.md does not explain how to do this, and in React this is something that is entirely possible.

**Comment by pl12133** [comment]
Perhaps you could solve this problem using a `ref`: https://zhenyong.github.io/react/docs/more-about-refs.html.

**Comment by developit** [comment]
Definitely a case for refs, yup.  FWIW React and Preact treat refs much the same, just Preact doesn't support String refs (since they are considered deprecated).

Here's your example written with refs:

```js
class Thing extends Component {
  render() { return <div>blah</div>; }
  someFunction() { return "something; }
}

class Parent extends Component {
  componentDidMount() {
    let somevalue = this.thing.someFunction();
  }
  render() {
    return <Thing ref={ thing => this.thing = thing } />;
  }
}
```

Alternatively, you can get the same functionality as string refs using a little helper library called [linkref](https://npm.im/linkref):

```js
import linkRef from 'linkref';

class Thing extends Component {
  render() { return <div>blah</div>; }
  someFunction() { return "something; }
}

class Parent extends Component {
  componentDidMount() {
    let somevalue = this.refs.thing.someFunction();
  }
  render() {
    return <Thing ref={linkRef(this, 'thing'} />;
  }
}
```

**Comment by Pomax** [comment]
good point, completely forgot about them! Totally fixed it.
