### ISSUE TITLE
How to use SSR? Where is the introduction or example?

### ISSUE THREAD

**Issue by youngwind** [developit/preact#723]
It said "Preact support SSR" In README.
But I can't find any introduction or example about SSR in neither the README nor the [website](https://preactjs.com/).
Do I miss something important? Any suggestion may help, thanks!
![image](https://cloud.githubusercontent.com/assets/8401872/26811065/08c30766-4aa2-11e7-978b-18b8a5ea2183.png)

**Comment by thangngoc89** [comment]
For SSR, use https://github.com/developit/preact-render-to-string
Example: https://github.com/developit/preact-www/blob/master/src/ssr.js

**Comment by youngwind** [comment]
Thanks a lot. @thangngoc89

**Comment by oren** [comment]
Should we have a section in the official docs with how to guides or q&a? I am sure this question will be asked again. It is better to create a short answer on the official docs somewhere and link to it the next time someone ask it.
