### ISSUE TITLE
svg textAnchor not work

### ISSUE THREAD

**Issue by danilobrinu** [developit/preact#724]
```jsx
// input
<g textAnchor="middle"></g>
// expect
<g text-anchor="middle"></g>
// result
<g textAnchor="middle"></g>
```
https://facebook.github.io/react/docs/dom-elements.html#all-supported-svg-attributes

**Comment by thangngoc89** [comment]
@danilobrinu Are you using preact-compat? Preact doesn't support camelCase. Just use kebab-case attribute name or use preact-compat for full React compaitable

**Comment by danilobrinu** [comment]
Where is doc ??

**Comment by developit** [comment]
Good point, need to call this out in the Preact docs.
