### ISSUE TITLE
Taking advantage of minified:main?

### ISSUE THREAD

**Issue by matthewmueller** [developit/preact#734]
Heya, wondering how we can take advantage of the rollup'd minified version in our webpack config.

Would it just be an alias in production or is there a way to get webpack to look for any module with that attribute in the package.json?

**Comment by mitchellhamilton** [comment]
You can use [`resolve.mainFields`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) so webpack will look for the main fields you specify. e.g.
```js
resolve: {
  mainFields: ['minified:main', ...otherMainFields]
}
```

**Comment by matthewmueller** [comment]
awesome, that's what i was looking for – thanks!

**Comment by developit** [comment]
FWIW I think once #675 or #674 are merged, the ESM bundle can actually get minified via uglify too so this will become unnecessary (I hope!).
