### ISSUE TITLE
Compilation problem with ts 2.4.0

### ISSUE THREAD

**Issue by valotas** [developit/preact#735]
Trying to compile a project with preact as a dependency and get the following error:

```
node_modules/preact/dist/preact.d.ts(48,17): error TS2559: Type 'Component<PropsType, StateType>' has no properties in common with type 'ComponentLifecycle<PropsType, StateType>'.
```

This only happens with ts `2.4.0`, `2.3.x` works file

**Comment by valotas** [comment]
It looks like it has to do with the introduction of [Weak types](https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/)

`ComponentLifecycle` should have at least one overlapping property with `Component`

**Comment by marvinhagemeister** [comment]
This is likely already fixed by https://github.com/developit/preact/pull/730

**Comment by developit** [comment]
Yup, that fix will go out in [8.2](https://github.com/developit/preact/milestone/20).

**Comment by valotas** [comment]
Feel free to close this then :)

**Comment by sxcooler** [comment]
there's a workaround: fix your typescript version to 2.3.4 until Preact 8.2 published.

**Comment by idchlife** [comment]
Waiting for this one too.

**Comment by 2advancesolutions** [comment]
getting error still
