### ISSUE TITLE
Router.js:130 Uncaught TypeError: _this.setState is not a function

### ISSUE THREAD

**Issue by hskww** [developit/preact#739]
page work error  when use react-router

**Comment by developit** [comment]
Can you provide more details? Are you using `preact-compat` to load `react-router`?  What version of the react-router library are you using?

**Comment by AnkitJainAJ** [comment]
yes , i am using preact-compat .
"preact-compat": "^3.16.0",
"react-router": "^3.0.0"

Please help.

**Comment by e-r-w** [comment]
hey @AnkitJainAJ, I'm getting the same issue with `react-router`. Digging into the source code, it seems that `react-router` uses `create-react-class`, which will need to be aliased the preact-compat version with [webpack](https://github.com/developit/preact-compat#usage-with-webpack), [browserify](https://github.com/developit/preact-compat#usage-with-browserify) or [babel](https://github.com/developit/preact-compat#usage-with-babel), e.g:

```js
// webpack.config.js
module.exports = {
// ...
    alias: {
        'react': 'preact-compat',
        'react-dom': 'preact-compat',
        'create-react-class': 'preact-compat/lib/create-react-class'
    }
}
```

I hope this helps!

**Comment by AnkitJainAJ** [comment]
Hi @e-r-w,
It worked , thanks for the help.

**Comment by developit** [comment]
Closing since @e-r-w found the issue - hopefully anyone searching for it finds this one :)

**Comment by donggw2030521** [comment]
@e-r-w Lying down! Cattle people ah! Sorry i'm so excited i used google translate, haha
