### ISSUE TITLE
Switching to Preact from CRA

### ISSUE THREAD

**Issue by c0debreaker** [developit/preact#745]
Forgive me if I posted it here. I'm not sure where to post my question. I built a webapp few months ago using create-react-app. I'd like to try using Preact. How do I switch to it if app was built using create-react-app? I read this link but create-react-app wasn't mentioned - https://preactjs.com/guide/switching-to-preact

**Comment by s-kris** [comment]
Did you find anything regarding this?

**Comment by c0debreaker** [comment]
No, I stopped since I had to do other work

**Comment by s-kris** [comment]
Okay, thank you.
