### ISSUE TITLE
Collect component may be make a mistake.

### ISSUE THREAD

**Issue by windyGex** [developit/preact#746]
Consider following code:

```js
class A extends Component {
  constructor(props) {
    super(props);
    this.state = {
      child: ''
    }
  }
  render() {
    return <div  onClick={(e)=>{this.onChange()}}>
    <div>{!this.state.child ? <C className="abc"/> : null}</div>
      123
      {this.state.child}
    </div>
  }

  onChange() {
    this.setState({
      child: <B className="bcd"/>
    })
  }
}

class C extends Component {
  render() {
    return <B {...this.props} ref={(b)=>this.b=b}/>
  }
  componentDidMount() {
    this.b.base.style.left = '20px';
  }
}

class B extends Component {
  render() {
    return <i {...this.props} />
  }
}
```
expected result:

```html
<i class="bcd"></i>
```

unexpected result: 

![image](https://user-images.githubusercontent.com/197348/27903170-e0eeab74-626a-11e7-87d7-517447f66a69.png)

Problem is here.

https://github.com/developit/preact/blob/master/src/vdom/component-recycler.js#L36

**Comment by OutThisLife** [comment]
It mounted and added the style. Why wouldn't it?

**Comment by windyGex** [comment]
Sorry for the code, I have update the code.

**Comment by developit** [comment]
I think we're pretty sold on removing component recycling entirely.  There is a branch `scratch/perf` with my latest changes that remove the recycler, originally from @NekR's work.  He uses a fork of preact with the recycler disabled.

**Comment by windyGex** [comment]
ok, I have remove the code in my fork version. Thx
