### ISSUE TITLE
`componentDidMount` called twice after upgrade from 8.0.1 to 8.1.0 in some case

### ISSUE THREAD

**Issue by ouzhenkun** [developit/preact#750]
hi~ @developit 

After i upgrade from 8.0.1 to 8.1.0,
I found the component's lifecycle methods called not as i expected in some case
It seem like that the `flushMount` conflict with re-render's diff method

Here is the demo, pls take a look:

https://codepen.io/ryan_ou/pen/jwQWoR?editors=0011

1. open the console tool
2. click `show title` button
3. `Title ComponentDidMount` and `App ComponentDidMount` called twice

**Comment by developit** [comment]
Yup, definitely looks like a bug.  The only culprit I could find is this line, which I'm testing now:
https://github.com/developit/preact/compare/8.0.1...8.1.0#diff-86702919356dad82cf58b1e4150288f5R178

**Comment by developit** [comment]
@robertknight I think I might have to revert the mount fix at least temporarily, can't seem to get it passing tests while also fixing this repro.  Thoughts?
