### ISSUE TITLE
8.1.0 unexpected children = [undefined]

### ISSUE THREAD

**Issue by ouzhenkun** [developit/preact#751]
In this demo:
https://codepen.io/ryan_ou/pen/VWVRWR?editors=0011 

```jsx
// App.js
...
render(_, state) {
  return (
    <Page>
      { state.isActive && <div>Content...</div> }
    </Page>
  )
}

// Page.js
...
componentDidMount() {
  console.log('Page componentDidMount', this.props.children)
}

render() {
  return (
    <div>
      Page Title
      { this.props.children }
    <div>
  )
}
...

```

The Page Component's children will be `[ undefined ]`, it should be `[]`?

**Comment by developit** [comment]
This is the correct behavior. In Preact 8, we started preserving holes in `children` since it improves diff performance.

**Comment by Cactucs** [comment]
This behavirour can break some libs that doesn't expect undefined in children (such as react-mdl - using via preact-compat).

**Comment by monalv** [comment]
it would also break preact-router https://github.com/developit/preact-router/issues/178

**Comment by marvinhagemeister** [comment]
Now this is a really tricky situation. Right now we're thinking of preserving holes again because it improves performance a lot for conditional children #1327 .

**Comment by marvinhagemeister** [comment]
Note that right now we don't keep any `null`-like values in the `children` array. That resolves this issue. I adapted #1440 to not keep them in `props.children` 🎉
