### ISSUE TITLE
Possible to use with Pug instead of JSX?

### ISSUE THREAD

**Issue by michaelalhilly** [developit/preact#756]
Was wondering if it would be possible to use some combination of Webpack loaders to precompile Preact components using Pug templates instead of JSX. Maybe something like this?
```
...
module: {
	rules: [{
		test: /\.(js|pug)$/,
		use: ["babel-loader", "pug-as-jsx"]
	}]
}
...
```

**Comment by developit** [comment]
I'm working on this. It's not a pug -> jsx loader though, essentially it is compiling the pug template to a virtual Dom component.

**Comment by michaelalhilly** [comment]
Sounds good. I'll keep an eye out for it.

**Comment by MichKael** [comment]
is this issue have been fixed?please

**Comment by ForsakenHarmony** [comment]
Could always write a webpack loader yourself

**Comment by marvinhagemeister** [comment]
Closing this, because this is not an issue with preact itself. A compiler/bundler like webpack is the perfect place to do such transformations 👍
