### ISSUE TITLE
Exclude src directory from npm package

### ISSUE THREAD

**Issue by steelbrain** [developit/preact#76]
To do that we need to add this to `.npmignore`
```
src
```

**Comment by developit** [comment]
Hi - the `src` directory is actually intentionally included, because it is referenced as `"jsnext:main"` for users who want the ES6 source (for things like Webpack 2 / Rollup tree shaking).

**Comment by steelbrain** [comment]
@developit but if we git ignore we'll get an extremely lightweight package

**Comment by steelbrain** [comment]
Nevermind the size difference is very small

**Comment by developit** [comment]
Yup, size diff is about 80k.
