### ISSUE TITLE
onClick doesn't trigger when 'space' key pressed on non button elements

### ISSUE THREAD

**Issue by dvh91** [developit/preact#760]
```
<a 
  tabIndex='0' 
  onClick={() => this.handleClick()} 
  role='button'
>
  a tag: press space on focus
</a>

<button 
  tabIndex='0' 
  onClick={() => this.handleClick()}
>
  button tag: press space on focus
</a>
```

**Steps to reproduce:**
1. Press 'tab' key and focus on the a element. press 'space' key
2. Press 'tab' key again and focus on the button element. press 'space' key

**Expected behaviour:** 
Both scenarios will trigger `handleClick` function.

**Actual behaviour:**
Only the button element trigger the function.

**Comment by NicolasParada** [comment]
Just use a button.
This isn't a problem of preact. Just try to do that on vanilla js and it doesn't work also.

**Comment by NekR** [comment]
Right. It's a web-compact thing that buttons can be activated by "space". No other elements can even with tabindex and focus. 

Submit button: form submit, space, enter, mouse/touch/etc
Buttons: space, enter, mouse/touch/etc
Links: space, enter, mouse/touch/etc
Regular elements: mouse/touch/etc
