### ISSUE TITLE
<select multiple> elements don't select <option selected> children

### ISSUE THREAD

**Issue by fabianonunes** [developit/preact#761]
CodePen: https://codepen.io/fabianonunes/pen/zzQgqo

When preact renders a `<select multiple>`  with multiple `option[selected]`, only the last option is selected:

```html
<select multiple>
  <option selected value='1'>One</option>
  <option selected value='2'>Two</option><!-- only this option is selected -->
</select>
```
This works in version 7.1.0., but commit 123978c108579f147c49906c31301ad1712926be broke it when  [children started being diffed prior to props](https://github.com/developit/preact/commit/123978c108579f147c49906c31301ad1712926be#diff-a0896fa5d65b1d80ca4d496badbae50fR163) in order to fix #446.

So, all the `<option selected>` are appended to dom before the attribute `multiple` is applied to the `<select>`, making only the last selected.

**Comment by developit** [comment]
Ah funky. We'll probably need to special-case `multiple` to handle this :(

**Comment by eduardoboucas** [comment]
Here is a REPL link to illustrate what I mean: https://preactjs.com/repl?code=export%20default%20class%20Foo%20extends%20Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%3Cselect%20value%3D%22two%22%3E%0A%20%20%20%20%20%20%20%20%20%20%3Coption%20value%3D%22one%22%3EOption%20one%3C%2Foption%3E%0A%20%20%20%20%20%20%20%20%20%20%3Coption%20value%3D%22two%22%3EOption%20two%3C%2Foption%3E%0A%20%20%20%20%20%20%20%20%20%20%3Coption%20value%3D%22three%22%3EOption%20three%3C%2Foption%3E%0A%20%20%20%20%20%20%20%20%3C%2Fselect%3E%0A%0A%20%20%20%20%20%20%20%20%3Cselect%20multiple%3D%7Btrue%7D%20value%3D%7B%5B%22two%22%2C%20%22three%22%5D%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3Coption%20value%3D%22one%22%3EOption%20one%3C%2Foption%3E%0A%20%20%20%20%20%20%20%20%20%20%3Coption%20value%3D%22two%22%3EOption%20two%3C%2Foption%3E%0A%20%20%20%20%20%20%20%20%20%20%3Coption%20value%3D%22three%22%3EOption%20three%3C%2Foption%3E%0A%20%20%20%20%20%20%20%20%3C%2Fselect%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%0A%20%20%7D%0A%7D%0A
