### ISSUE TITLE
why preact props has default children?

### ISSUE THREAD

**Issue by a993630** [developit/preact#762]
i didn't has children props,
![2017-07-19 5 08 43](https://user-images.githubusercontent.com/13556731/28359519-12fa0b9c-6ca5-11e7-9d05-75c1a87c9258.png)

but  i console this datepicker proptypes, why has a children is undefined?

![2017-07-19 5 07 29](https://user-images.githubusercontent.com/13556731/28359536-23e0d24c-6ca5-11e7-9945-7e0c8dcd4ddd.png)

**Comment by developit** [comment]
Preact normalizes `children` in `h()` - it will always set `props.children` to an Array.  `preact-compat` undoes this for React-style components, which is why you're seeing the undefined.  Deleting the property would mutate the shape of `props` and hurt performance, so it is simply set to `undefined`.

**Comment by webdeb** [comment]
@developit hmm, could we disable default children array? with an attribute like `noChilds` ?

**Comment by webdeb** [comment]
Just faced that issue with paypal integration, they are validating the props, and they only allow some limited props.. (children is not included) 

Really, don't want to install preact-compat just for this.

**Comment by sxcooler** [comment]
@developit I'm a colleague of @a993630 , I understand your pursuit of performance, but this hurt the compatibility of Preact. Unlike @webdeb , my project has included preact-compat, but still got some warnings with prop-types.
Not all the third-party packages is well-maintained / quickly-responded, nor every project would like to change some code to fit Preact, this means hurting the eco-system of Preact.
Please consider.

**Comment by webdeb** [comment]
@developit this will not add undefined children https://github.com/developit/preact/pull/774

**Comment by developit** [comment]
I'm happy with the proposed solution in #774.

**Comment by Zeroster** [comment]
We are also experiencing an issue with a 3rd party React library that is not compatible with undefined children when using preact-compat.

@webdeb Any progress on #774 or #822?

**Comment by webdeb** [comment]
Hey @Zeroster, because #822 adds more complexity, I decided to re-open #774 again. If @developit is still OK with it, it would make me proud if #774 could be merged any time soon. Btw, this would also allow me to use the official Preact package instead of mine custom fork in one of my projects ;)

**Comment by theramparts** [comment]
This is something that my team needs. Are there any updates on the progress of this issue? Information is appreciated. Thanks!

**Comment by webdeb** [comment]
@theramparts #774 should be ok to merge, IMHO

**Comment by theramparts** [comment]
@developit Can we get this merged in? My team would be very appreciative! Thanks.

**Comment by marvinhagemeister** [comment]
We just merged #1302 which doesn't automatically add `props.children` anymore :+1:
