### ISSUE TITLE
SVG vectorEffect property not handled properly

### ISSUE THREAD

**Issue by icewind1991** [developit/preact#765]
When setting the `vectorEffect` on an svg `<path>` element, it is not correctly transformed into the html `vector-effect` property, instead it is kept as `vectorEffect`.

Example: https://jsfiddle.net/4smrhnks/

Correct behavior with react: https://jsfiddle.net/Lyec0qye/

**Comment by icewind1991** [comment]
Looking further it looks like this is something that should be handled by preact-compat

**Comment by developit** [comment]
Might be able to generically map these in core.

**Comment by icewind1991** [comment]
The typescript definitions suggest that the camelCase variants are the correct ones.
