### ISSUE TITLE
Inconsistent radio input checked behaviour

### ISSUE THREAD

**Issue by dalehurwitz** [developit/preact#767]
The issue arises when using `true` or `false` to set the `checked` property of a radio input, ie

```
const checked = props.value === props.selected
return <input type='radio' checked={checked} />
```

It can be demonstrated in this fiddle (apologies, it is a little convoluted) - https://jsfiddle.net/be7mptfh/5/

You'll notice when the 1st or 2nd options are selected and the form is submitted, the next form renders the default option (2nd option) correctly as checked. 

However when the 3rd or 4th options are selected and submitted, the next form does not correctly render the default option as checked.

I was able to resolve the issue in Preact 7 using `key` but it resurfaced in Preact 8.

The fix in this case was:
`const checked = props.selected === props.value ? 'checked' : null`

**Comment by developit** [comment]
Using `key` on a pure functional component in Preact 7 would have been triggering a remount on every render.

I played around with your example for a bit and this is what I came up with - drop the `name` property and switch to `onChange` to prevent the browser from trying to normalize those inputs:

https://jsfiddle.net/developit/be7mptfh/8/

**Comment by marvinhagemeister** [comment]
Looks like the issue is resolved. Feel free to ping us to re-open when you run into something similar with Preact X :slightly_smiling_face:
