### ISSUE TITLE
DOM attributes getting applied from an unrelated component's props, nextBase not cleaned up

### ISSUE THREAD

**Issue by ngokevin** [developit/preact#769]
I have attributes from a different component somehow getting applied internally to another component. Here is the code for the component; the only props it defines are `id` and `className`, but it is somehow getting `position`, `rotation`, and `scale` attributes from another component.

```js
<!-- This component should not have any other props applied. -->
<Entity id={entity.id} className="entity"/>
```

Here is React Developer Tools showing the props. Those `position`, `rotation`, and `scale` props are getting applied to `#entity1` somehow. It's not in the props, but it does end up in the DOM node:

<img width="1436" alt="screen shot 2017-07-24 at 6 31 51 am" src="https://user-images.githubusercontent.com/674727/28526190-9f4a9618-703b-11e7-92b7-e7055e0ea66c.png">

Here's showing that those values are applied:

<img width="1433" alt="screen shot 2017-07-24 at 6 36 08 am" src="https://user-images.githubusercontent.com/674727/28526238-cb1e822c-703b-11e7-9d9b-e7174fa670ed.png">

I don't believe it is any of the application code doing this. Here I am logging the `attachedCallback`, and these values are there from the start:

<img width="1413" alt="screen shot 2017-07-24 at 6 38 47 am" src="https://user-images.githubusercontent.com/674727/28526261-e4ce8730-703b-11e7-9243-7014209b8f90.png">

And then logging from Preact's `afterMount`, those values are there:

<img width="1421" alt="screen shot 2017-07-24 at 6 41 59 am" src="https://user-images.githubusercontent.com/674727/28526275-ef5bc3ac-703b-11e7-8362-ae7f2e5dcc8b.png">

I've also confirmed that MutationObserver says those values are there when the DOM node is mounted. I've disabled my `ref`s and checked my `attributeChangedCallback`s, and they are not what's causing this. Adding `key` does not help.

I've tried poking around Preact's code (v8.2.1). Perhaps these values are being recycled somehow? Any tips on where to investigate?

**Repo:** https://github.com/ngokevin/architect
**Reproduce:** `npm install && npm run start` then head to `http://localhost:7001/?recording=https://gist.githubusercontent.com/anonymous/0bb931162b5b3280ec58dba4bd0d18e2/raw/cd9115e332e5ef0373282849255e7757362987b1/clone.json`. Do `document.querySelector('#entity1').getAttribute('position')` after the recording runs and it *should* return 0/0/0.

**Comment by ngokevin** [comment]
OK, working on debugging! Found that it's using a `base` against the offending component:

<img width="940" alt="screen shot 2017-07-24 at 7 44 34 am" src="https://user-images.githubusercontent.com/674727/28528937-04476b4c-7044-11e7-9792-c10c3774c6c1.png">

**Comment by developit** [comment]
@ngokevin Thanks for the debugging!  It looks like this is a result of component recycling, which I'd like to remove.  There is actually a [branch with recycling removed](https://github.com/developit/preact/tree/scratch/perf) - maybe it'd be worth giving it a try to see if the issue is fixed there?

**Comment by marvinhagemeister** [comment]
We completely removed the component recycler for Preact X, so issues like this should not be present anymore :+1: An alpha release is already out on npm and can be installed via `preact@next`.
