### ISSUE TITLE
[svg] Element `foreignObject` is being converted to foreignobject

### ISSUE THREAD

**Issue by grahm** [developit/preact#771]
When the preact processes the svg tag foreignObject it is converting its tag to lower case. However preact-render-to-string seems to maintain the correct case.

This is what is happening: 
https://codesandbox.io/s/583NKMMYx

This is what should be happening:
https://codepen.io/anon/pen/brNPod

Previously mentioned in this ticket:
https://github.com/developit/preact/issues/278

**Comment by grahm** [comment]
https://github.com/developit/preact/pull/773

**Comment by DLehenbauer** [comment]
Here is how I'm currently working around the issue:
```javascript
// Work around https://github.com/developit/preact/issues/771 by replacing the
// resulting HTMLUnknownElement with a manually constructed SVGForeignObject:
const oldFe = this.group.children[0];
const newFe = oldFe.ownerDocument.createElementNS('http://www.w3.org/2000/svg', 'foreignObject');
newFe.className.baseVal = oldFe.className;
newFe.width.baseVal.value = 140;            // Width/Height were not preserved by
newFe.height.baseVal.value = 25;            // the HTMLUnknownElement.
newFe.appendChild(oldFe.children[0]);
this.group.replaceChild(newFe, oldFe);
```
Note that this problem can be hard for users to diagnose because HTML parsers are lenient about constructing SVGForeignObjectElement for the incorrectly cased <foreignobject>.

(For example, if you copy the resulting markup from the F12 inspector and paste into a static *.html, the foreignObject and embedded HTML will likely appear.)

**Comment by jpecor-pmi** [comment]
This is still an issue 1 year later.  I am trying to embed a `<table>` object within an SVG graph, however preact is still converting `<foreignObject>` to `<foreignobject>` which will not render.

**Comment by marvinhagemeister** [comment]
Confirmed: The issue is that we're not treating `foreignObject` as an svg element. Instead only the children of `foreignObject` should have `isSvg` set to `false`.

https://github.com/developit/preact/blob/639bc321fc3800330c7f48421df0d26e32bf5204/src/diff/index.js#L219-L220

**Comment by sanchit-mendiratta** [comment]
Is this issue fixed ?
