### ISSUE TITLE
Is there a way to disable component recycling? 

### ISSUE THREAD

**Issue by LucaT1** [developit/preact#776]
In my application, I'm using [xterm](https://github.com/sourcelair/xterm.js), and I'm mounting it to a referred component on the `componentDidMount` event.
The application can handle several tabs that are looped through `.map`, and when a tab closes preact tries to reuse the <`Terminal />` component, which looks all the same to him(since he just diffs the JSX part without the terminal element I believe, correct me if I'm wrong).

The problem is that every terminal is linked to a shell, and when it tries to reuse the terminal component it reuses the shell too, so closing a tab will then mess up all the related terminals and shells.

My code is public on GitHub if you want to read it or give it a try feel free to do it.
A critical part of it could be the `willReciveProps` event that I'm using to prevent from re-rendering when cols, rows and selection of the terminal updates.
Here are the pieces of code:
[`<Terminal />`](https://github.com/LucaT1/yat/blob/master/src/components/terminal.jsx#L20-L38)
[`<Terminals />`](https://github.com/LucaT1/yat/blob/master/src/components/terminals.jsx#L145-L158) (loop)

**Comment by LucaT1** [comment]
Fixed.

**Comment by nisanth074** [comment]
@LucaT1 How did you solve it? By passing the `key` prop when instantiating `<Terminal />` components?

**Comment by LucaT1** [comment]
Yeah, but i don't know why it wasn't working before

**Comment by NekR** [comment]
Using `key` doesn't disable component recycling. `key={Date.now()}` for example makes your component be recreated on each re-render. Also "component recycling" in preact actually means "reusing dom nodes from components".

@LucaT1 in your case, indeed, having unique `key`s per terminal should help you.

**Comment by LucaT1** [comment]
Yeah in fact it worked. Tough i may have named the issue wrongly
