### ISSUE TITLE
window.addEventListener("scroll"... doesn't work

### ISSUE THREAD

**Issue by raycar5** [developit/preact#777]
I noticed this problem while using react-infinite and then I tried it in the [REPL](https://preactjs.com/repl), I added the following line to the default example: 
`window.addEventListener("scroll",()=>alert("hi"));`
The listener is registered 
![image](https://user-images.githubusercontent.com/5788355/28669250-c9707e4a-72d3-11e7-98cf-70047d9e7579.png)
But it does nothing.

**Comment by devdoomari** [comment]
the window element isn't being scrolled, but some element inside the window.

here's a temp fix:
```
var elem1 = document.getElementsByClassName("output_1hFrT")[0];
elem1.addEventListener("scroll",()=>alert("hi"));
```
Note that the classname 'output_1hFrT' might be different from yours.

cheers

**Comment by raycar5** [comment]
oh, maybe I poorly represented the issue with my example, the problem is react-infinite uses the window.addEventListener("scroll") when used with the useWindowAsScrollContainer prop, but the event isn't firing, so my question is, does preact have some sort of top level element that handles scrolling instead of the window?

**Comment by raycar5** [comment]
nvm, I figured it out, the problem comes from a different package, sorry for the inconvinience

**Comment by toniopelo** [comment]
If someone end up here having the same issue, on my side adding `{ capture: true }` as an options to `addEventListener` did the trick for me.

**Comment by PetracekSimon** [comment]
> If someone end up here having the same issue, on my side adding `{ capture: true }` as an options to `addEventListener` did the trick for me.

thx a lot man <3

**Comment by ungarmichael** [comment]
> If someone end up here having the same issue, on my side adding `{ capture: true }` as an options to `addEventListener` did the trick for me.

could you also state why it only works with that being enabled?

**Comment by CAYdenberg** [comment]
> could you also state why it only works with that being enabled?

It depends on what else is listening. See [here](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_capture) for an explanation of capturing.

**Comment by hojoungjang** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#capture

For my use case, I am not entirely sure what's happening under the hood that prevents the scroll event from hitting the provided listener but at least this documentation explains that before anything the provided event listener will be triggered first.
