### ISSUE TITLE
react-slick change preact-slick ? Is it easy?

### ISSUE THREAD

**Issue by sowdf** [developit/preact#785]
i want to react-slick change preact-slick ? Is it easy?

**Comment by sowdf** [comment]
import React, { Component } from 'react'  change 

import { Component } from 'preact'

Do i do right?

**Comment by SaraVieira** [comment]
Hello @sowdf ,


You don't need to make any changes to your code all you need is preact-compat and follow these [instructions](https://github.com/developit/preact-compat#usage-with-webpack) to get it up and running 😀

**Comment by developit** [comment]
👍
