### ISSUE TITLE
Pure module

### ISSUE THREAD

**Issue by jescalan** [developit/preact#791]
I might be off here, but I think that preact does qualify as a [pure module by webpack's definition](https://github.com/webpack/webpack/tree/feature/pure-module/examples/pure-module), correct? If so, I'd be happy to PR this property to the `package.json` file, I'm sure this would be a nice benefit when compressing with webpack 😁

**Comment by developit** [comment]
Not sure if I'm reading the docs correctly, but preact doesn't re-export anything (since it has no dependencies).

**Comment by pelotom** [comment]
If you're reexporting parts of your own package from the top level, this would allow someone to import just one thing and have the others get tree-shaken out. I'm not sure if this is the case with preact, just pointing out that it has nothing to do with package dependencies, only modules.

**Comment by kossnocorp** [comment]
I don't think it's applicable to Preact. As I can see the only _optional_ sub-module is `cloneElement` (https://github.com/developit/preact/blob/master/src/preact.js#L2) and it isn't big at all. In my opinion, it just doesn't worth it.

Btw, now it's "side-effects": https://github.com/webpack/webpack/tree/next/examples/side-effects
