### ISSUE TITLE
Confusing behavior on duplicate keys?

### ISSUE THREAD

**Issue by yelouafi** [developit/preact#794]
demo at https://codesandbox.io/s/PlWREDon

to reproduce the issue:

- type '1212' then click on `Patch!` button

- type '121211' then click again on `Patch!` button

Actual output

![image](https://user-images.githubusercontent.com/5453835/28966325-6721d8f2-790d-11e7-85fc-d739f2b89ac2.png)

For info here is a comparison with other virtual dom libs ([demo](https://codesandbox.io/s/BkLpXYQn))

![image](https://user-images.githubusercontent.com/5453835/28967423-f00670f6-7912-11e7-810a-9a6df325126f.png)

console output

![image](https://user-images.githubusercontent.com/5453835/28966470-46949b0a-790e-11e7-8e2f-d4feb96a7114.png)

React errors ~and breaks on the first duplicate key encountered but the UI stays frozen on the the last 'correct' state~. ~Actually react doesnt break on duplicate keys. it warns for each duplicate key encountered and just skips them~. react v16 no longer skips duplicate keys. see https://twitter.com/trueadm/status/893491470409154560

react v16 output

![image](https://user-images.githubusercontent.com/5453835/28977179-f1cc49ee-7938-11e7-8daf-ce5a1feec16b.png)

react v15 output

![image](https://user-images.githubusercontent.com/5453835/28967217-114369a0-7912-11e7-8598-2954182afd95.png)

Inferno warns  but doesn't break. Other libs handle duplicate keys without warning.

EDIT

Inferno warns early at the time the element with duplicate keys is created. While react error is not thrown until reconciliation.

**Comment by marvinhagemeister** [comment]
We now print a warning when children contain duplicate keys. It's unlikely that we'll introduce a workaround to somehow guessing the correct keys due to our strict size constraints ✔️
