### ISSUE TITLE
Support for componentDidCatch

### ISSUE THREAD

**Issue by valotas** [developit/preact#799]
Error handling with preact/react is anything but pleasant at the moment. [`componentDidCatch`](https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html) should make the process a little bit easier.

**Comment by marcelalburg** [comment]
+1

a nice example why we need this:

https://codeburst.io/catching-exceptions-using-higher-order-components-in-react-16-b8a401853a10

**Comment by developit** [comment]
Agreed, I would like to see this supported in Preact.

**Comment by adamsilverstein** [comment]
I took a first pass in https://github.com/developit/preact/pull/880. This will catch errors in render, but not those triggered by a click handler for example.

**Comment by adamsilverstein** [comment]
Use a component like this to test:

```
export default class Test extends Component {

	componentDidCatch( error, errorInfo ) {
		console.log( error, errorInfo )
	}

	render() {
		throw new Error( 'I crashed!' );
		return;
	}
}
```

**Comment by developit** [comment]
note: for visibility there's a PR here as well - #819

**Comment by marvinhagemeister** [comment]
Closing, `componentDidCatch` is now available in `master` :+1:
