### ISSUE TITLE
Invalid source map with rollup 0.40

### ISSUE THREAD

**Issue by tromey** [developit/preact#800]
https://github.com/mozilla/source-map/issues/247 mentions a source map problem with preact.  A couple of the generated source maps are definitely wrong -- they refer to lines that don't appear in the generated file.  I looked into this and found https://github.com/rollup/rollup/issues/1254.  Changing preact to require rollup 0.41 makes the bug go away.

**Comment by developit** [comment]
Nice! Feel free to submit a PR that updates Rollup, otherwise I'll make sure that's in the next release.

**Comment by sbking** [comment]
@developit  This still seems to be an issue. I get the mentioned source map issue only when using preact.

@tromey Are you still seeing this issue?

**Comment by tromey** [comment]
> @tromey Are you still seeing this issue?

I don't actually use preact; I just found this while investigating a bug filed against the source map library.  So, I don't know, sorry!
