### ISSUE TITLE
Key attributes in lists

### ISSUE THREAD

**Issue by philmander** [developit/preact#801]
Does Preact require [key attributes](https://facebook.github.io/react/docs/lists-and-keys.html) for list items, like React?

I assume it doesn't, but just curious because I can't see it mentioned anywhere in the Differences to React docs.

**Comment by developit** [comment]
It supports them, but neither library requires them. 
Here is a more detailed explanation:
https://stackoverflow.com/questions/42773892/wrong-components-rendered-by-preact/42775667#42775667
