### ISSUE TITLE
Can't install when npm is not available

### ISSUE THREAD

**Issue by andrejsm** [developit/preact#803]
This fd1df721a374e1ed97694cc5e837a08f4dcf5855 actually breaks things. In environments where only `yarn` is present Preact can't be installed.

**Comment by developit** [comment]
Hmm. I didn't think it was possible to have yarn without npm!  I can have the script use echo directly instead.

**Comment by andrejsm** [comment]
Alpinelinux has two packages with `nodejs` where one lacks `npm` for obvious reasons.

**Comment by developit** [comment]
Good to know!
