### ISSUE TITLE
How to prevent the console from being cleared at start up ?

### ISSUE THREAD

**Issue by HadrienPierart** [developit/preact#805]
Every time I launch de dev/watch env, I see my config logs at first, then everything is cleared and replaced by :
```
Compiled successfully!
You can view the application in browser.
...
```

Can I prevent that somehow ? It would be quite useful to see my logs...

**Comment by pl12133** [comment]
Is this a question about `preact-cli`?

**Comment by HadrienPierart** [comment]
Well, that's a good question. As it is the default behavour of the project scaffolded by the cli, I supposed that it was cli related...

**Comment by developit** [comment]
Indeed. Would you be able to open the issue there instead?

**Comment by developit** [comment]
I've added it to the todo list over there :)
