### ISSUE TITLE
preact/debug should support stringRefs option

### ISSUE THREAD

**Issue by ustccjw** [developit/preact#807]
stringRefs used in many components，so `preact/debug` should support stringRefs option.（I notice preact/debug remove stringRefs in one commit）

**Comment by pl12133** [comment]
Preact [does not support string refs](https://preactjs.com/guide/differences-to-react#what-s-included-), so I am not sure how this would fit into `preact/debug`.

Could you provide more detail on what is missing?

**Comment by ustccjw** [comment]
@pl12133 when i use `preact-compat`, `stringRefs ` is supported. So, `preact/debug` should provide `stringRefs option` or check `preact-compat` autoly.

**Comment by developit** [comment]
It might be possible to have debug check for the existence of compat by looking to see if it has injected itself into the VNode prototype.
