### ISSUE TITLE
preact/debug arrayChildren seems stranger

### ISSUE THREAD

**Issue by ustccjw** [developit/preact#808]
preact do not have `ReactFragment `，so we have other solutions to simulate ReactFragment？

**Comment by pl12133** [comment]
`ReactFragment` is not supported right now; follow https://github.com/developit/preact/pull/703 to join the discussion.

**Comment by marvinhagemeister** [comment]
We just published the alpha for our next release. It includes support for `Fragments` and lots of other cool new features :tada:
