### ISSUE TITLE
Unnecessary insertBefore / appendChild on conditional JSX that's not rendered

### ISSUE THREAD

**Issue by vaneenige** [developit/preact#809]
**Issue:** 
The DOM before and after render of a component are identical yet `insertBefore` and `appendChild` events are called on the prototype. Not sure what the impact on performance is or whether it's supposed to be like this or not.

**Scenario:**
- Initial DOM:
`<div></div>`
- JSX in component:
`<div>{false && (<h2>Unnecessary appendChild</h2>)}</div>`
- Output for both:
`<div></div>`

The output in the DOM is what you would expect yet the condition based element that won't be rendered triggers the unnecessary events. The div in this case doesn't trigger any updates.

**Example**
A working example of the issue based on Preact v8.2.1 can be found [here](https://codepen.io/cvaneenige/pen/vJJzVq).

**Comment by developit** [comment]
Preact uses empty text nodes to preserve "holes" in JSX.  This is more easily seen when the JSX is converted to hyperscript:

```js
// initial dom:
dom.childNodes;
> []

// JSX in component:
h('div', null, false && (h('h2', null, 'Unnecessary appendChild')))
// ^ which is equivalent to:
h('div', null, false)
// ... which is actually equivalent to:
h('div', null, '')
// (due to booleans being empty values in VDOM)

// Thus, the output looks the same but is actually slightly different:
dom.childNodes;
> [ #text ]
```

**Comment by vaneenige** [comment]
Thanks for the clear explanation! 🙌

> It's not a bug; it's a feature.
