### ISSUE TITLE
react-bootstrap??

### ISSUE THREAD

**Issue by pengliheng** [developit/preact#812]
how about react-bootstrap
is it still usefull?
while i import react-bootstrap
the component import from react-bootstrapt can't work
can i fix thar?

**Comment by pengliheng** [comment]
oh my god ---
preact-mui 
prefect fixed that

**Comment by SaraVieira** [comment]
@pengliheng Can we close this? 🤗

cc @developit

**Comment by developit** [comment]
yup! :)
