### ISSUE TITLE
Issue w/ react-select handleFocus

### ISSUE THREAD

**Issue by lucas-aragno** [developit/preact#814]
Hi I'm trying to use [react-select](https://github.com/JedWatson/react-select) on my site but after clicking i get this error:

<img width="479" alt="screen shot 2017-08-17 at 11 24 50 am" src="https://user-images.githubusercontent.com/5210254/29417239-e61cedb4-833e-11e7-9c9b-1a27539309a7.png">

I went to that line and everything looks right:

<img width="675" alt="screen shot 2017-08-17 at 11 26 38 am" src="https://user-images.githubusercontent.com/5210254/29417265-fdb22e1c-833e-11e7-9de9-2afa8d135e2a.png">

So I thought it could be related to differences between preact and react ( im using preact-compat but not the refs polyfill ) So I tried adding the package to a site created w/ preact-cli and it works fine there. I updated my preact, preact-compat and preact-router versions to match the ones on the site generated by preact cli but still no luck

```javascript
    "preact": "^8.2.1",
    "preact-compat": "^3.17.0",
    "preact-render-to-string": "^3.6.3",
    "preact-router": "^2.5.5",
```

The only difference is that im doing SSR w/ `preact-render-string` there is anything that I'm missing? all the other react libs work just fine

**Comment by developit** [comment]
Hi @lucas-aragno - just an update: I took a look at this in the morning and I'm not sure what could be causing the issue.  

When you say you're using preact-compat but not the refs polyfill, what do you mean?

**Comment by developit** [comment]
Ah yes. If you're using compat it patches string refs in automatically, that's likely the codepath being used here.  I wonder if it's a ref timing issue...

**Comment by lucas-aragno** [comment]
I think it might, I forked the library do you think porting the lib over to preact and adding linkref could help?

**Comment by marvinhagemeister** [comment]
I can't reproduce anything resembling the described issue with Preact X. Please ping us to reopen this issue when you find a way to recreate the error👍 From the looks of it, it seems to be solved💯✔️
