### ISSUE TITLE
`render` should throw error when `parentElement` === `mergeWithElement`

### ISSUE THREAD

**Issue by keichinger** [developit/preact#815]
The reason behind this is that:

1) it's not really logical to mount a specific component into a `parent` but also replace it using the `mergeWithElement` parameter
2) it causes side-effects: `componentDidMount` is never called, `componentWillMount` was though.

Doesn't work:
https://www.webpackbin.com/bins/-Krois9urpVTM55FmOc5

Works:
https://www.webpackbin.com/bins/-Krod_5fKllUPowAWlVe

The fix was to pass two different elements into the `render` method.

Fun fact: The error thrown on webpackbin is not thrown locally, though the results are the same.

**Comment by developit** [comment]
Seems like is already throws an error.

**Comment by NekR** [comment]
This was fixed.
