### ISSUE TITLE
Return array of jsx from map within render?

### ISSUE THREAD

**Issue by web2wire** [developit/preact#816]
In react I can do this (simplified)

```
render() {
  return(
    <ul>
    {arrayofThings.map( thing => {
      let results = [];
      if ( thing.isImportant )
        results.push( <li className="important">Important!!</li> );
      results.push( <li>{thing.details}</li>
      return results;
    })}
    </ul>
  );
}
```

And it will display correctly. In preact it doesn't, it just seems to return objects (according to devtools).
I can't see anywhere that is a documented inconsistency so is there some other reason?

**Comment by developit** [comment]
Your example works fine: https://jsfiddle.net/developit/8mt79gLz/

**Comment by web2wire** [comment]
Thanks for looking at this. Interestingly even your fiddle exhibits the issue when run through the command line babel (6.11.4 via the create-preact-app tools) whereas the same fiddle importing react instead of preact doesn't.

**Comment by developit** [comment]
Funky.  Generally if you're seeing raw objects in the output (or `[object Object]`) that is the result of a failed React alias.

**Comment by web2wire** [comment]
As in a webpack.config.js alias? I'm struggling to find a way to pin this down as it's difficult to find and intercept executable intermediate code between the raw preact/jsx which appears to work and the compiled variant which doesn't.
