### ISSUE TITLE
Found issue setInnerHTML and resolved for last preact (simple patch)

### ISSUE THREAD

**Issue by simonjoom** [developit/preact#817]
With preact we ve got some issue from setInnerHTML on state change
 Finally with lot of test, i found the clue of it: (and it's simple patch)

Line 154 change the line
        `} else if (vchildren && vchildren.length || null != fc) innerDiffNode(out, vchildren, context, mountAll, hydrating || null != props.dangerouslySetInnerHTML);`

to 
`} else if (vchildren && vchildren.length || null != fc) innerDiffNode(out, vchildren, context, mountAll, hydrating , null != props.dangerouslySetInnerHTML);`

nota: comma between hydrating and null

**Comment by developit** [comment]
Hi there,

By adding the comma, you're passing the result of `null != props.dangerouslySetInnerHTML` as a 6th argument to `innerDiffNode`, which only accepts 5 arguments. This has the same effect as removing the code entirely, so it's unlikely to be correct.

Can you provide more details about the issue you're running into?

**Comment by simonjoom** [comment]
in fact after did that i have got no one issue after changing state to display my popover, My application is quite complex; all the website work perfectly i didn't see any trouble after changing that
So maybe the code removed was not good

the website working with preact is:
https://www.skiscool.fr

You can check the size , i optimized react fully (from 500kb -> 100 kb) thanks to your preach and the last uglifyjs-webpack-plugin

Nota 
(maybe interesting to know)
i use the last version of babel 7.0.0-alpha.20 and the version loose work fully with preact too

**Comment by marvinhagemeister** [comment]
With Preact X the content of `dangerouslySetInnerHTML` will only change, when the actual value does :tada:

**Comment by zavr-1** [comment]
this bug is driving me mad... i'm sorry but how come you couldn't just merge the solution from this issue 2 years ago? preact X is still alpha what's the reason behind not fixing it. people still use 8.
