### ISSUE TITLE
[Question] Is there an effort to build something similar to react native with preact? 

### ISSUE THREAD

**Issue by japrogramer** [developit/preact#824]
Hello, It has recently come to my attention that react and other Facebook driven libraries have licenses that can become problematic in many projects https://github.com/facebook/react/issues/10191.
In this thread I learned about preact, and it looks like a near perfect drop in replacement for react on the web, however I couldn't help but notice that there doesn't appear to be native effort for mobile apps with preact. Is there a similar project that takes advantage of the preact libraries similar to how react native does?

**Comment by japrogramer** [comment]
oh, I see. I need to use something like cordova.

**Comment by developit** [comment]
There are efforts underway to pair Preact up with NativeScript.  That combination produces something quite similar to React Native:
https://github.com/staydecent/nativescript-preact

**Comment by japrogramer** [comment]
Thanks! I really like the patterns in both react/preact and was hoping for exactly this in a native dev environment.

**Comment by japrogramer** [comment]
@developit I did some more research, and i found that there is a library that uses the same syntax as react but with weex as the platform framework
 https://github.com/alibaba/rax

**Comment by japrogramer** [comment]
Well It seems that Facebook, changed their license again. This time it appears to be a good thing, 🦄
