### ISSUE TITLE
Stock ticker example is broken

### ISSUE THREAD

**Issue by JayAndCatchFire** [developit/preact#831]
In the readme, there's a link to this codepen under the name Stock Ticker: http://codepen.io/developit/pen/wMYoBb?editors=0010

The example doesn't work anymore because it pulls in the latest version of Preact and it relies on `linkState` still being bundled in.

As `linkState` is no longer bundled with Preact, there's two ways to fix this.  Either pull in the new linkstate package or use the 7.x Preact version.

The quickest fix would be to replace `//npmcdn.com/preact` with `//npmcdn.com/preact@7.2.1` in the pen settings.

The other way to fix it (if you want to continue using the latest version of Preact) would be to add `//npmcdn.com/linkstate` in the pen settings and change the portion of line 63 from `this.linkState('text')` to `linkState(this, 'text')`.

**Comment by developit** [comment]
Thanks for noticing!  I just updated the example (in-place) to remove linkState and replace it with a simple bound method:

```js
updateText = e => {
  this.setState({ text: e.target.value });
};
```
