### ISSUE TITLE
how to add the clock demo on the preact-cli created project

### ISSUE THREAD

**Issue by jnuc093** [developit/preact#832]
as a first day beginner of a PREACTer, i have "preact create” and “preact watch" a project by preach-cli,
where can i add the [Simple Clock](http://jsfiddle.net/developit/u9m5x0L7/embedded/result,js/
) demo code,in my project code [demo](http://git.oschina.net/jnuc093/equipment
) .i do’t know where to write the Clock class and where to show it

and i add 
[a test commit](http://git.oschina.net/jnuc093/equipment/commit/6e6f68920c770f8524b8153f075bafad4c090b46) bu the clock does’t show in home menu

**Comment by rubenmoya** [comment]
You almost got it, you just have to use it like: `<Clock />` in your `Home` `render` method! :)

**Comment by jnuc093** [comment]
@rubenmoya thanks a lot.
i just push a simple 
[render return <Clock/>](http://git.oschina.net/jnuc093/equipment/commit/ab6deb90c9ad3ec1ff2281151a3d7979076e6c6d)

**Comment by jnuc093** [comment]
[move clock to it's own file, and import it in home/index.js
](http://git.oschina.net/jnuc093/equipment/commit/4b04cead3fe8ce8f3b1012cea7b6db5d9df866fb)
