### ISSUE TITLE
Input type number field clears

### ISSUE THREAD

**Issue by chrisdavies** [developit/preact#84]
When you are syncing an `input[type=number]` field with state, in Preact, the field clears if a decimal is entered. (e.g. type "10." into the field)

This works as expected in React see this fiddle, or the code pasted below:  https://jsfiddle.net/3L94wkx9/ 

```js
var Hello = React.createClass({
  getInitialState: function () {
  	return {
    	  num: 2
        }
  },

  updateNum: function (e) {
  	this.setState({num: e.target.value})
  },

  render: function() {
    return <div>
      <input type="number"
      	value={this.state.num}
        onChange={this.updateNum} />
    </div>;
  }
});
```

**Comment by chrisdavies** [comment]
I was wrong. I was doing a parseFloat in my code, which caused the issue!

**Comment by developit** [comment]
You had me there! 
Cheers. Thanks for updating.
