### ISSUE TITLE
How to share/reuse component between react & preact？

### ISSUE THREAD

**Issue by zgayjjf** [developit/preact#840]
I hava a multi page appliaction which built with react。
Because it's scale is huge, so I don't want to rewrite the old codebase, just want to develop new page with preact.

While there are some components wrote with react，used by react. 
I can not simply transfer it to preact, so just copy & paste the components, then rename the components with different name for preact, finally add jsx pragma on top of them, looks like this:
![image](https://user-images.githubusercontent.com/24718872/29768425-bd539972-8c18-11e7-9724-5e0d88f78c77.png)
![image](https://user-images.githubusercontent.com/24718872/29768542-375501c0-8c19-11e7-8d5d-29407355550a.png)

Thouth this has solved some problem, but it has some inconvenience, for example, I had to copy & paste code between files when I frequently modify component.

**So is there any better way to share component between react & preact without copy & paste ?**

**Comment by developit** [comment]
Hi @zgayjjf - [preact-compat](https://github.com/developit/preact-compat) was specifically built to meet the need you described without any modification of source code.  Follow the [instructions in the readme](https://github.com/developit/preact-compat#usage-with-webpack) to add aliases to your build tool, then your React code will work unmodified with Preact.

**Comment by zgayjjf** [comment]
Thanks @developit for replying.

Maybe I didn't make me clear. 

I'm having a project with React code & Preact code in the same time, which i cannot simply make the React code work with Preact as they used lots of legacy react Apis.
I want them to coexist, but share some components with each other, so i can have time to modify them step by step.

I have a solution like I said before, but is't not elegant. I am wondering if there is better way.

**Comment by tedplumtree** [comment]
Hi, I'd like to know if there is a recommended way to do this as well.

I'm developing an application that uses Preact with web components, but it turns out that some library dependencies we have just don't work well with Preact. Instead of spending time to figure out why this particular component works with React but not with Preact, I'd like to know if I could just make both dependencies co-exist.

I couldn't find a nice way to do this via webpack aliasing.
