### ISSUE TITLE
dangerouslySetInnerHTML, children and setState quirks

### ISSUE THREAD

**Issue by molily** [developit/preact#844]
Hello,

first of all, thank you for this great project. After having built several React apps, we’ve decided to give Preact a try. We’ve built an app using preact-cli and almost everything worked flawlessly. I’m really excited about this project!

We ran into one strange issue that took me hours to track down. This is the smallest test case I was able to produce:

```js
import { h, render, Component } from 'preact';
import PropTypes from 'prop-types';

class Container extends Component {

  constructor() {
    super();
    this.state = { state: 'initial' };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({ state: 'updated' });
    }, 2000);
  }

  render() {
    const { children } = this.props;
    const { state } = this.state;
    return (
      <div>
        <div>Container state: {state}</div>
        {children}
      </div>
    );
  }

}

Container.propTypes = {
  children: PropTypes.element.isRequired
};

const App = () => (
  <Container>
    <div>App</div>
    <div>
      →
      <span dangerouslySetInnerHTML={{ __html: '<u>HTML</u>' }} />
      ←
    </div>
  </Container>
);

render(<App />, window.document.body);
```

Expected behavior: After the state change, the content set via dangerouslySetInnerHTML remains unchanged.

Actual behavior: After the state change, the content set via dangerouslySetInnerHTML is removed from the DOM completely.

I’m a newbie to the codebase so I can explain why this happens but I cannot come up with a fix.

Under normal circumstances, when the state of a component changes, the call stack is `rerender` → `idiff` → `innerDiffNode` (which removes the subtree added by `dangerouslySetInnerHTML`) → `diffAttributes` → `setAccessor` (which sets `innerHTML` again).

Under normal circumstances, `setAccessor` is called because this condition …

`attrs[name]!==(name==='value' || name==='checked' ? dom[name] : old[name]))`

yields true, in short

`attrs[name]!==old[name]`

yields true. The old value (an object `{ __html: '<u>HTML</u>' }`) is a equal but not identical to the new value (also an object `{ __html: '<u>HTML</u>' }`). This is because the object is created anew with each `App#render` call.

In contrast, in the test case above, `App#render` is not called again when `Container` re-renders, so it’s the same old attributes object. Therefore `diffAttributes` does not detect a difference so it does not call `setAccessor` to set `innerHTML` again.

Hopefully this analysis from an outsider helps. My guess would be that we need a separate check for `name === 'dangerouslySetInnerHTML'`. Another possible solution I can think of is to *not* remove the subtree in the first place, since no change happened.

For reference, here’s the same example based on Facebook’s React:
https://codepen.io/anon/pen/BdqVWQ?editors=0010

**Comment by developit** [comment]
Hi there - thanks for the awesome detailed bug report!

I actually think this might come down to the inequality here being reversed:
https://github.com/developit/preact/blob/master/src/vdom/diff.js#L143

**Comment by molily** [comment]
Here’s a simple workaround for those who encounter this bug too and need a quick fix. Make sure to not use `dangerouslySetInnerHTML` in the component that passes children (`App` in my example) to the component that changes its state (`Container` in my example). Put it in a child component instead, e.g.:

```js
const InnerHTMLHelper = ({ tagName, html }) =>
  h(tagName, { dangerouslySetInnerHTML: { __html: html } });

const App = () => (
  <Container>
    <div>App</div>
    <div>
      →
      {/* <span dangerouslySetInnerHTML={{ __html: '<u>HTML</u>' }} /> */}
      <InnerHTMLHelper tagName='div' html='<u>HTML</u>' />
      ←
    </div>
  </Container>
);
```

**Comment by developit** [comment]
Ah - neat fix. I'll try to include that in the durable fix as a test too!

**Comment by rmales** [comment]
I think this may be the same (underlying) issue as in https://github.com/developit/preact/issues/578

**Comment by simonjoom** [comment]
I ve got same problem of you on click on button to pop something updating state in innerhtml children
I resolved this by create this hack:

can you try my fix to resolve it and report to us if it's working as well for you?

in preact.js
change: 
innerDiffNode(out, vchildren, context, mountAll, hydrating || props.dangerouslySetInnerHTML != null);
to 
innerDiffNode(out, vchildren, context, mountAll, hydrating, props.dangerouslySetInnerHTML != null);

create 6args in innerdiffnode:
change that:
function innerDiffNode(dom, vchildren, context, mountAll, isHydrating) {
to
function innerDiffNode(dom, vchildren, context, mountAll, isHydrating,InnerHTML) {

then change:
} else if (!child && min < childrenLen)
to
} else if (!InnerHTML&&!child && min < childrenLen)

test and answer me thanks

**Comment by marvinhagemeister** [comment]
@molily We just released the alpha for our next version of Preact which doesn't recreate `innerHTML` on each render anymore. It checks if the `html` string has changed before proceeding further, just like you suggested :+1:

**Comment by horprogs** [comment]
I had the same problem, using preact `10.0.0-beta.3`. Had we already released fix?

**Comment by marvinhagemeister** [comment]
@horprogs Can you share a codesandbox or a repo where we can reproduce it?

**Comment by horprogs** [comment]
Hmm.. I removed yarn.lock and node_modules, reinstall, and now it works fine. 
I'm sorry to trouble you and thank you for your job!

**Comment by zavr-1** [comment]
@molily I know it's been a while, and thanks for explanation, however it's wrong. In your example `attrs[name]!==old[name]` is actually false and not true. Even if it was true, `setAccessor` won't do anything https://github.com/preactjs/preact/blob/b54401fb18098d990be9187db9764c39ab6b595c/src/dom/index.js#L93-L95
because it will set `innerHTML` on the old node which was recollected (removed from dom).
![Screenshot 2019-09-04 at 18 59 40](https://user-images.githubusercontent.com/21156791/64271563-30820b00-cf46-11e9-8317-28a3fce8536f.png)

It's not the problem with strict comparison, but with the fact that the text node was removed before because preact thought that new node has no children despite the `dangerouslySetInnerHTML` attribute.

Just thought I let you know :)
