### ISSUE TITLE
BUG with adjacent collections with same index (does not happen with React)

### ISSUE THREAD

**Issue by devnixs** [developit/preact#845]
Here's a minimal version of the bug.

Preact version :
https://preactjs.com/repl?code=export%20default%20class%20TodoList%20extends%20Component%20%7B%0A%20%20%20%20state%20%3D%20%7B%20todos%3A%20%5B%7Btext%3A%27Todo%201%27%7D%2C%7Btext%3A%27Todo%202%27%7D%2C%7Btext%3A%27Todo%203%27%7D%5D%2C%20text%3A%20%27%27%20%7D%3B%0A%0A%20%20%20%20render(%7B%20%7D%2C%20%7B%20todos%2C%20text%20%7D)%20%7B%0A%20%20%20%20%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cform%20onSubmit%3D%7Bthis.addTodo%7D%20action%3D%22javascript%3A%22%3E%0A%09%09%09%09%09%09%09%09%3Cbutton%20onClick%3D%7B()%3D%3Ethis.forceUpdate()%7D%3E%0A%09%09%09%09%09%09%09%09Trigger%20the%20bug.%20(this%20should%20do%20nothing%2C%20and%20yet%20it%20messes%20everything%20up)%0A%09%09%09%09%09%09%09%09%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cul%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%09%09%09%09%09%09%09%09todos.map(%20(todo%2Cindex)%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cli%20key%3D%7Bindex%7D%3E%7Btodo.text%7D%3C%2Fli%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20))%20%0A%09%09%09%09%09%09%09%09%09%09%7D%0A%09%09%09%09%09%09%09%09%20%7B%20%0A%09%09%09%09%09%09%09%09todos.map(%20(todo%2Cindex)%20%3D%3E%20(%0A%09%09%09%09%09%09%09%09%09%09%09%09%3Cli%20key%3D%7Bindex%7D%3E%7Btodo.text%7D%3C%2Fli%3E%0A%09%09%09%09%09%09%09%09%09%09))%20%0A%09%09%09%09%09%09%09%09%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ful%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fform%3E%0A%20%20%20%20%20%20%20%20)%3B%0A%20%20%20%20%7D%0A%7D

React version : 
[![Edit 4zqvzzqv34](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4zqvzzqv34)

I happen to work with react locally for the ease of development, and then on my production build I use preact. This didn't work on preact, but worked with react.

Thanks!

**Comment by developit** [comment]
Hi there - if we fix this, it'll have to be in `preact-compat`.  Preact does not support/allow duplicate keys, which is what is happening here.

This is technically a duplicate of #794, #655 and #642. Should we consolidate them?

**Comment by rubencodes** [comment]
Just noticed this myself! Glad I checked the first issue I posted. 

FWIW I think this case is different... Duplicate keys in *one* list: we all know we're not supposed to do it, and the ideal solution would be to merge duplicate keys to one item. But keys across lists...I wouldn't expect that to have any unusual behavior.

**Comment by marvinhagemeister** [comment]
Good news: This is fixed in Preact X. An alpha is out on npm and can be installed via `preact@next` :tada:
