### ISSUE TITLE
require IMG

### ISSUE THREAD

**Issue by allexon** [developit/preact#846]
Hello, if anyone can help me thanks, I'm only using Preact in my setup.

When I resolve to import an image I do this:
<Img src = '. / Porcoes-01.png' />, and it does not work!

When I do this:
<Img src = {require ('./ porcoes-01.png')} />, IT WORKS

But, if I remove require later, this way:
<Img src = ('./ porcoes-01.png') />, IT WORKS

Only works if I give this command require! Would it work without requiring it?

My Webpack Configuration dev:
...
     Output: {
         Path: PUBLIC,
         Filename: 'app.js',
         PublicPath: '/'
     },

     Module: {
         Rules: [
             {Test: / \. (Svg | jpe? G | png | gif) (\?. *)? $ / I, exclude: [/ (node_modules) /], loader: 'file-loader', options: {name : '[Name]. [Ext]'}},
         ]
     },

**Comment by developit** [comment]
Without the `require()` statement, the value is just an opaque String.  Adding the `require()` runs the image through Webpack's loaders - that's the only way to get it to be output in `assets/` after your build.

This is definitely more of a webpack question by the way, it doesn't really relate to Preact at all.
