### ISSUE TITLE
Passing children as props or via varargs to h(..)

### ISSUE THREAD

**Issue by fab1an** [developit/preact#848]
I'm writing a Kotlin-DSL wrapper for preact (Using [Type-Safe Builders](https://kotlinlang.org/docs/reference/type-safe-builders.html).
When it comes to statically known children, is it better to

* Pass them via varargs as third parameter
* Pass them as `.children` property 
* Or does it not matter?

**Comment by developit** [comment]
Pass an array of children as a third argument to h(). If your whole application does so, you'll see some great performance gains!

**Comment by fab1an** [comment]
So no varargs, but instead an array and create keys for all the members as well?

**Comment by developit** [comment]
Sorry, was on my phone there.  Varargs are fine, just they tend to eventually deopt `h()`.  Passing children as an Array avoids this and skips an Array copy in every h call.  Here's what it looks like in vanilla JS:

```js
// h(tagName, props, children)

h('div', { id: 'foo' }, ['a', 'b', 'c'])

h('ul', null, [
  h('li', { class: 'first' }, 'First Item'),
  h('li', { }, 'Second Item')
]);
```

As for keys - there's no need for keys in the general case - keys are only useful if you're rendering a list of items that have ID's of some kind (some indicator of which item is which that is consistent between renders).  In that case, passing those ID values as keys for each list item will enable more intelligent re-ordering, insertion and deletion.  Without keys, children of the same element type (or component type) are always added and remove from the end of the list of children.

**Comment by fab1an** [comment]
Great, thanks.

**Comment by developit** [comment]
Let me know if you have a link to the project. I was at I/O for the Kotlin announcement, and this sounds really interesting!

**Comment by fab1an** [comment]
Not at the moment, it's unfinished and partly closed source, but when I get around to polish and publish I'll tell you.

**Comment by developit** [comment]
Awesome. I'll close this for now since we arrived at an answer, but let me know when you publish!

**Comment by lambrospetrou** [comment]
@fab1an Did you ever get to finish the Kotlin wrappers for Preact? I am thinking on doing the same and trying to see if someone has already done it.

**Comment by fab1an** [comment]
No, not yet.
