### ISSUE TITLE
Range Input: Order of Attributes Bug

### ISSUE THREAD

**Issue by mikewesthad** [developit/preact#850]
I stumbled upon a bug while working with Preact today. If you create an input range, the initial render of the slider position may be wrong, depending on the order of the attributes. The `value` attribute needs to be set after `min`/`max`/`step`. If `value` is applied before `min`/`max`/`step` are properly set, the value will be forced to match the default min=0/max=100/step=1 on a slider.

E.g. if you create two sliders:

```js
// This one renders with the slider at 0
<input type="range" value={0.5} min="0" max="1" step="0.05" />

// This one renders with the slider at 0.5
<input type="range" min="0" max="1" step="0.05" value={0.5} />
```

![image](https://user-images.githubusercontent.com/1131802/30006088-12453c1e-90b6-11e7-8efd-06d275848719.png)

See minimal code to reproduce [here](https://codepen.io/mikewesthad/pen/gxEmmx)

When creating an dom element from a vnode, it looks like attributes are applied one at a time via a `for...in` loop. Since the ordering of keys in an object is arbitrary, it seems like [`diffAttributes`](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L294) needs to apply the attributes in a sorted way. I can't think of other potential ordering pitfalls with attributes (maybe the react source code would have insights), but at the very least, applying `value` last should fix this issue.

**Comment by developit** [comment]
Interesting! We might also be able to work around this by setting `value` as an attribute.

**Comment by mikewesthad** [comment]
@developit - isn't `value` already being passed as an attribute to `diffAttributes`? Or did you mean pulling `value` out into its own property during `h`?

**Comment by developit** [comment]
I mean special-casing `value` like we do `type` and `list`:
https://github.com/developit/preact/blob/master/src/dom/index.js#L76

Basically, forcing a `value` prop from VDOM/JSX to be applied to the DOM using setAttribute() instead of as a property.

**Comment by mikewesthad** [comment]
Hm, but the problem is the order in which `value` is applied relative to other attributes, not whether it's applied via prop or attribute ([vanilla js example](https://codepen.io/mikewesthad/pen/qXGyrx?editors=0010)). I might be missing something, but by the time we're in `setAccessor`, it's too late to adjust the order without doing something async.

**Comment by developit** [comment]
Interesting, I would have thought the step validation would only apply to the value property, not the attribute itself. You're right, this likely requires a bit of insane workaround magic in diffAttributes.

**Comment by mikewesthad** [comment]
Happy to contribute a PR to fix it if someone isn't already working on it.

**Comment by developit** [comment]
That would be awesome.

**Comment by gpoitch** [comment]
Here's the special input attr cases in react for reference: https://github.com/facebook/react/blob/8ab56e5c8b8f797a6b2bdd4188b4082c55a5190b/src/renderers/dom/stack/client/wrappers/ReactDOMInput.js#L58-L71

**Comment by bluemoehre** [comment]
I ran into this issue too. When will this be released?

**Comment by mbindseil** [comment]
plz fix :)

**Comment by mikewesthad** [comment]
@marvinhagemeister thanks! Closing my PR
