### ISSUE TITLE
What does the “Into the void 0” mean？

### ISSUE THREAD

**Issue by lewis617** [developit/preact#852]
I have watched your talk in jsconf: Preact: Into the void 0

https://www.youtube.com/watch?v=LY6y3HbDVmg

What does the "Into the void 0" mean?

**Comment by developit** [comment]
"the void" is a philosophical term meaning nothingness/vastness. The phrase "into the void" means to travel/look into the vast emptiness, and is a play on Preact's small size.

The `0` ("void 0") is a reference to JavaScript's [void keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void), and its [common usage](https://stackoverflow.com/a/1291950) for obtaining `undefined` - `void 0`.

**Comment by lewis617** [comment]
Thanks. This is very smart.
