### ISSUE TITLE
Why diff with Virtual Dom and HTML DOM Element？

### ISSUE THREAD

**Issue by lewis617** [developit/preact#856]
> we diff the return value from the previous call to render with the new one, and generate a minimal set of changes to be applied to the DOM.
The data returned from render is neither a string nor a DOM node -- it's a lightweight description of what the DOM should look like.

But, preact diff with HTML DOM Element, why?
https://github.com/developit/preact/blob/master/src/vdom/diff.js

**Comment by developit** [comment]
Doing so unifies initial render (eg: from prerender/SSR) and updates, eliminates the need to store the entire previous virtual DOM tree, and makes subtree updates simpler.

I've toyed with the idea of prototyping a preact-like diff against a previous VTree, and might try it out soon.

**Comment by lewis617** [comment]
Thanks, I'm look forward to your new idea.
