### ISSUE TITLE
Docs for `require("preact/debug");`?

### ISSUE THREAD

**Issue by ansballard** [developit/preact#858]
I can't find any mention of the relatlively new `require("preact/debug")` in the readme or the site. From the pull request it looks like it's configurable, but I don't see how. Is it meant to replace `require("preact/devtools")`, or be a more react-ish alternative? If the first, it should probably replace that section at the bottom of the readme, otherwise maybe a separate section underneath?

**Comment by developit** [comment]
Yes, we definitely need to add some documentation around it.  It's a drop-in replacement for `preact/devtools` that adds some logging akin to what you get from React's dev mode.  It pulls in `preact/devtools` as part of that, so you can just change any import to `preact/debug`.

**Comment by ansballard** [comment]
Gotcha, thanks for the quick response! Looks like the initial comment in the pull request has plenty of info for a section in the readme (https://github.com/developit/preact/pull/633#issue-220394871), I'll check in tonight after work if no one has claimed it and attempt a pull request. And did you have a preference for replacing the `preact/devtools` section with this, or adding the new docs under it?

**Comment by developit** [comment]
Maybe we just thin out the devtools section? It's more likely people would use it as part of `debug` now.  I'd say add the new docs above and just keep a minimal explanation of preact/devtools underneath (or as part of the docs for debug).  Happy to have the help updating docs!

**Comment by ansballard** [comment]
Sounds good, I'll get to it when I get a chance! And no prob!
