### ISSUE TITLE
Should `preact/debug` be checking for undefined keys in element arrays?

### ISSUE THREAD

**Issue by ansballard** [developit/preact#859]
Just wanted to confirm that this was the expected behavior. `preact/debug` explicitly ignores elements with undefined keys, but does check for dupes if keys exist. Is this just a difference in how preact and react render lists under the hood? Or is it because keys are not required, and there's currently no way to toggle the options in `preact/debug`? Asking for clarity for https://github.com/developit/preact/issues/858 and since it seems weird.

**Comment by developit** [comment]
This is a difference between Preact and React, yes.  Preact does not automatically add keys to VNodes without keys.

**Comment by ansballard** [comment]
Gotcha, makes sense to me, thanks!
