### ISSUE TITLE
Support findDOMNode

### ISSUE THREAD

**Issue by steelbrain** [developit/preact#88]
I have a use case where my components are given `HTMLElement`s and I have to append them to the component. My usage is blocked because of this

See it on [React Docs](https://facebook.github.io/react/docs/top-level-api.html#reactdom.finddomnode)

**Comment by developit** [comment]
Hi - `Component#getDOMNode()` and `.findDOMNode()` are both supported in [preact-compat](https://github.com/developit/preact-compat).  Preact simply exposes your DOM Node as `this.base` within any component.

**Comment by steelbrain** [comment]
Wow, I looked into `preact-markup` and not in compat, sorry about that :bow:

**Comment by developit** [comment]
No problem :)  I am not against potentially adding a proper API for this (`this.base` is something I came up with and not supported by React), but I'd like to wait until things shake out a bit with React's API changes to see what they end up standardizing on.  For reference, [here's the implementation in preact-compat](https://github.com/developit/preact-compat/blob/master/src/index.js#L184).
Cheers!

**Comment by steelbrain** [comment]
I don't really need anything else from `preact-compat` other than this method, are you going to keep compatibility in `.base` via semver? Is it okay to use it in my project?

**Comment by developit** [comment]
It will work indefinitely, and yes a major version change would occur if it were changed in any way. I'm using `.base` in nearly all of my projects, you can definitely consider it a safe part of the API. Preact is very careful about exposing things, anything you have access to is part of the versions, public API.

**Comment by steelbrain** [comment]
Beautiful, Thank you for your awesome project :+1:
