### ISSUE TITLE
redux-form

### ISSUE THREAD

**Issue by mysiar** [developit/preact#887]
Is there any way to make it working ?

**Comment by developit** [comment]
Are you using preact-compat?  redux-form uses String refs and a bunch of other deprecated things, it does not work with Preact unless you use compat.

**Comment by larrybotha** [comment]
Ran into the same issue with `preact-redux`. Using `preact-cli`, so reverted to relying on `preact-compat` and installed `react-redux` instead. Seems to be working!

```json
    "preact": "^8.2.1",
    "preact-compat": "^3.17.0",
    "react-redux": "^5.0.6",
```

**Comment by developit** [comment]
Makes sense - if redux-form is using react-redux, you'd have both libs in your bundle and they may not interoperate.  Good find @larrybotha!

**Comment by mysiar** [comment]
I gave this idea and moved back to react after license changed to MIT

**Comment by larrybotha** [comment]
@developit haha, all credit goes to you - I'm just following your instructions: https://github.com/developit/preact/issues/554#issuecomment-281710414 :)

Good to know that it'd add both libs to the bundle - got some evaluating to do with other deps!
