### ISSUE TITLE
Is this open source? or is this linked to Facebook?

### ISSUE THREAD

**Issue by redimongo** [developit/preact#888]
We are looking for tool which is as close to react as possible, but without the facebook patent license, Ideally we are looking for truly open source.

Also do reactjs plugins like the ones for mongodb work in preact as we use mongodb for our database.

**Comment by mysiar** [comment]
https://github.com/developit/preact/blob/master/LICENSE

**Comment by redimongo** [comment]
Thanks

**Comment by AbdulrahmanEng** [comment]
This issue needs to be closed.

**Comment by NekR** [comment]
Just in case, Facebook removed (will remove for 16 release) their patents for React and friends.
