### ISSUE TITLE
how to add mongoDB to preact?

### ISSUE THREAD

**Issue by redimongo** [developit/preact#889]
Sorry, i can't seem to find any well written document or sample code on how to add mongodb to preact or reactjs.

they all require me to use Express.JS which I will if I have to, but I want to keep the modules / plug ins to a minimum.

If anyone has a sample of how to do this I would much appreciate it.

**Comment by AbdulrahmanEng** [comment]
A good NoSQL alternative to MongoDB is Firebase which can operate exclusively on the client-side. Otherwise, an Express.js server would be necessary to use MongoDB.

**Comment by NekR** [comment]
Preact and React are client side libraries (sometimes used on a server to render html).
MongoDB is a database which requires a server software anyway. It could be ExpressJS or whatever server technology/framework you like, but that isn't related to Preact at all.
