### ISSUE TITLE
dangerouslySetInnerHTML not working

### ISSUE THREAD

**Issue by steelbrain** [developit/preact#89]
#### How to repro?

```
var preact = require('preact')
var vnode = preact.h('linter-message-line', {'dangerouslySetInnerHTML': 'Hey there'})
var element = document.createElement('div')
preact.render(vnode, element)
console.log(element.outerHTML) // '<linter-message-line>undefined</linter-message-line>'
```

#### Expected behavior

There should have been `Hey there` as the content

#### Current behavior

The content is `undefined`

#### Background info

I am on OSX with `preact@4.3.1`. The error is also present in `preact@4.0.0`

**Comment by steelbrain** [comment]
Nevermind, I was using it incorrectly, it should be `dangerouslySetInnerHTML:{__html: 'Hello there'}`

**Comment by developit** [comment]
@steelbrain Glad you were able to find the issue, and it's good to have a report that that API is still working in 4.3.1 out in the wild :) (not just in the tests haha)
