### ISSUE TITLE
Rate limit hit for Github API on Preact Site

### ISSUE THREAD

**Issue by LukePettway** [developit/preact#893]
I wasn't sure if this was the best place to put it or not but it looks like the rate limit for querying the Github API is being hit, which is called from the Stars example on the Preact site (https://preactjs.com/). 

Here's the message:

```
{
  "message": "API rate limit exceeded for 68.87.42.110. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}

```

**Comment by developit** [comment]
Hiya - if you were playing with the stars demo on the Preact REPL, after 150 updates you're IP will likely get rate-limited by Github.
