### ISSUE TITLE
Get different render result from React (15.6.1)

### ISSUE THREAD

**Issue by w-y** [developit/preact#897]
This code

outputs 'CD' in React (15.6.1),

outputs 'AB' in preact.

	
    let idx = 0;
    let msgs = ['A','B','C','D','E','F','G','H'];

	class Comp extends Component {                                                                                     
	 componentWillMount() {
	   this.innerMsg = msgs[(idx++ % 8)];
	 }
	 render() {
	   return <div>{this.innerMsg}</div>
	 }
	}

	class GoodContainer extends Component {
	  constructor(props) {
	    super(props);
	    this.state = { alt: false };
	  }
	  componentDidMount() {
	    this.setState({ alt: true });
	  }
	  render() {
	    const alt = this.state.alt;
	    return (
	      <div>
	        {alt ? null : (<Comp alt={alt}/>)}
	        {alt ? null : (<Comp alt={alt}/>)}
	        {alt ? (<Comp alt={alt}/>) : null}
	        {alt ? (<Comp alt={alt}/>) : null}
	      </div>
	    );
	  }
	}
	render(<GoodContainer />, document.getElementById('app'));

[react](http://jsbin.com/pakevagetu/edit?html,js,console,output)

[preact](https://preactjs.com/repl?code=import%20%7B%20h%2C%20render%2C%20Component%20%7D%20from%20%27preact%27%3B%0A%0Alet%20idx%20%3D%200%3B%0Alet%20msgs%20%3D%20%5B%27A%27%2C%27B%27%2C%27C%27%2C%27D%27%2C%27E%27%2C%27F%27%2C%27G%27%2C%27H%27%5D%3B%0A%0Aclass%20Comp%20extends%20Component%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20componentWillMount()%20%7B%0A%20%20%20this.innerMsg%20%3D%20msgs%5B(idx%2B%2B%20%25%208)%5D%3B%0A%20%7D%0A%20render()%20%7B%0A%20%20%20return%20%3Cdiv%3E%7Bthis.innerMsg%7D%3C%2Fdiv%3E%3B%0A%20%7D%0A%7D%0A%0Aclass%20GoodContainer%20extends%20Component%20%7B%0A%20%20constructor(props)%20%7B%0A%20%20%20%20super(props)%3B%0A%20%20%20%20this.state%20%3D%20%7B%20alt%3A%20false%20%7D%3B%0A%20%20%7D%0A%20%20componentDidMount()%20%7B%0A%20%20%20%20this.setState(%7B%20alt%3A%20true%20%7D)%3B%0A%20%20%7D%0A%20%20render()%20%7B%0A%20%20%20%20const%20alt%20%3D%20this.state.alt%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%7Balt%20%3F%20null%20%3A%20(%3CComp%20alt%3D%7Balt%7D%2F%3E)%7D%0A%20%20%20%20%20%20%20%20%7Balt%20%3F%20null%20%3A%20(%3CComp%20alt%3D%7Balt%7D%2F%3E)%7D%0A%20%20%20%20%20%20%20%20%7Balt%20%3F%20(%3CComp%20alt%3D%7Balt%7D%2F%3E)%20%3A%20null%7D%0A%20%20%20%20%20%20%20%20%7Balt%20%3F%20(%3CComp%20alt%3D%7Balt%7D%2F%3E)%20%3A%20null%7D%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0Arender(%3CGoodContainer%20%2F%3E%2C%20document.body)%3B)

**Comment by yaodingyd** [comment]
Because in react `null` is actually treated as a valid child, so multiple `null` results in the same amount of children, but in preact `null` is treated as a `simple` node and multiple `null` would result in a concatenated child and lated removed in the diff process. So in react there are new components mounted while in preact they are the same component, just attributes change.

**Comment by marvinhagemeister** [comment]
This is fixed with #1440 which changes our algorithm to use `null` as placeholders 👍
