### ISSUE TITLE
PropTypes for Preact

### ISSUE THREAD

**Issue by rumkin** [developit/preact#902]
Hi. I've realised PropTypes's alike extensible type checker which produce nice-looking report object. Instead of PropTypes which print's some output into console. And I want to add integration for preact. Is there any way to make it play together without patching preact itself?

It could be used like so:
```javascript
const TypedProps = require('typed-props');

const userShape = TypedProps.shape({
    username: TypedProps.string.isRequired,
    age: TypedProps.number,
});

TypedProps.check({}, userShape); // -> returns array of issues: {path:string[], rule:string, params:{}}
```

Thanks for any advise.

P.S. [Here](//github.com/rumkin/typed-props) it is.

**Comment by pl12133** [comment]
Hey @rumkin thanks for the issue. Preact offers an (undocumented) hook at the end of the `h` function which is called with every created vNode. You can use this hook to monkey-patch class methods. In this way, I think you could achieve checking `PropType`s on arbitrary class methods. Here is an example of patching `render` with the `prop-types` package from npm:

```javascript
import { options } from 'preact';
import PropTypes from 'prop-types';


function patchWithPropTypes(PatchingComponent) {
	let name = PatchingComponent.displayName || PatchingComponent.name || 'component';
	let render = PatchingComponent.prototype.render;

	PatchingComponent.__patchedWithPropTypes = true;

	if (render) {
		PatchingComponent.prototype.render = function renderWithPropTypes(props, state, ctx) {
			if (PatchingComponent.propTypes) {
				for (let prop in props) {
					PropTypes.checkPropTypes(PatchingComponent.propTypes, props, prop, name);
				}
			}
			return render.call(this, props, state, ctx);
		}
	}
}

let nextVnode = options.vnode;
options.vnode = vnode => {
	if (typeof vnode.nodeName==='function' && !vnode.nameNode.__patchedWithPropTypes) {
		patchWithPropTypes(vnode.nodeName)
	}
	if (nextVnode) {
		nextVode(vnode);
	}
}
```

I hope this helps you extend `preact` with your own project. If you get this working, it would be great to hear if this has a performance impact on your code.

**Comment by developit** [comment]
Also worth noting: `preact-compat` does PropType checking right now in a slightly odd way, but @tkh44 has opened a PR that works very similarly to @pl12133's suggestion above. You can see it here:
developit/preact-compat#370

**Comment by marvinhagemeister** [comment]
Looks like we use `prop-types + preact` today without any necessary changes to core 🎉 

@rumkin If you feel like the posted solutions don't solve your problem feel free to ping me to reopen this issue.

**Comment by marvinhagemeister** [comment]
I stand corrected, we indeed don't support it out of the box in core :/ I'll try to get this into Preact X before it's out.

**Comment by marvinhagemeister** [comment]
Just an FYI: PropType checking will be possible in Preact X itself. That means that compat won't be needed just for PropTypes anymore. Merged the PR for it yesterday 🎉

**Comment by DonGissel** [comment]
Hot diggety! Thanks!

**Comment by marvinhagemeister** [comment]
We just released the alpha for Preact X which will check for `prop-types` via `preact/debug`. It just needs to be included once (done automatically in preact-cli) to get `prop-type` checking to work :tada:

**Comment by shawnwall** [comment]
@marvinhagemeister thanks for the info. If I'm not using `preact-cli`, what is the preferred method of requiring/including `preact/debug` for development builds to get `prop-type` checking working?

**Comment by ForsakenHarmony** [comment]
it should be included by default

**Comment by shawnwall** [comment]
@ForsakenHarmony I'm not seeing that in my current setup. Only if I manually require `preact/debug` in one of my files do proptypes begin to actually validate.

**Comment by ForsakenHarmony** [comment]
Oh sorry I misread, I thought you were using `preact-cli`

**Comment by ForsakenHarmony** [comment]
https://github.com/preactjs/preact-cli/blob/d1718255d9a81c52ad022f3308e53bdda9917bc7/packages/cli/lib/lib/entry.js#L7

You can copy what we do there though, only enable it in dev, the check gets removed in a production build because of dead code elimination
