### ISSUE TITLE
Allow custom self-clsoing tags

### ISSUE THREAD

**Issue by DanielRuf** [developit/preact#919]
Is there some solution to use custom self-closing tags more than img, br, hr and so on)?

**Comment by NekR** [comment]
Like `<CustomComponent />` or `<div />` or `<x-something-we-component />`?

**Comment by DanielRuf** [comment]
Right, or when dealing with generating x(ht)ml.

**Comment by DanielRuf** [comment]
For example instead of `<img ... />` I want to generate the string `<f:image ... />` (Fluid template engine for TYPO3).

**Comment by developit** [comment]
@DanielRuf are you rendering using `preact`, or `preact-render-to-string`?  `preact` doesn't have a list of self-closing tags, but [here's preact-render-to-string's list](https://github.com/developit/preact-render-to-string/blob/master/src/index.js#L10-L25).

**Comment by DanielRuf** [comment]
Ah, that makes sense. Thanks for the hint.
