### ISSUE TITLE
Can I do the diff operation on another thread?

### ISSUE THREAD

**Issue by tanpuer** [developit/preact#920]
I want to record all the operations and pass to another javascript interceptor such as jsCore so that the webview interceptor such as V8 will not be blocked.

**Comment by Kanaye** [comment]
Hi @tanpuer!

@developit wrote an [example](https://github.com/developit/preact-worker-demo) using preact with webworkers a while ago.
The example should give you at least a hint on how this could be implemented.

**Comment by tanpuer** [comment]
@Kanaye 
Thanks, I will have a try

**Comment by developit** [comment]
Was just going to link to that - thanks @Kanaye!

The key points to look at in that repo are how [undom](https://github.com/developit/undom) is used to create a lightning-fast headless DOM in the worker thread, and how MutationRecords (from a MutationObserver) are used to send patches across the thread boundary.  Cheers!
