### ISSUE TITLE
`preact/debug` error only in v8.2.6

### ISSUE THREAD

**Issue by whitetrefoil** [developit/preact#924]
After upgraded my project from preact@v8.2.5 to v8.2.6, I had this error when loading the page:

```js
debug.js:49 Uncaught TypeError: Cannot set property render of #<Object> which has only a getter

// debug.js:L49
preact.render = function (vnode, parent, merge) {
```

If I stop requiring `preact/debug` it would be OK. I require it like this:
```ts
window['Promise'] = require('promise-polyfill')

if (process.env.ENV === 'production') {
  // Production
} else {
  // Development
  Error['stackTraceLimit'] = Infinity
  require('preact/debug')
}
```

When using v8.2.5 it was all good.

I'm using only preact with `webpack@2` without `preact-compat` or any react related stuff.

**Comment by brunomolteni** [comment]
I'm also having the same issue

**Comment by Kanaye** [comment]
The `render()` override was added in preact 8.2.6 or to be specific in #885.
The problem is the ES module exports are "read only" per rfc.
Webpack defines ES module exports as getter only properties and that is why this override fails.

I'm not sure what could be a viable long term solution for this.

For now you can just add
```
  'preact$': 'preact/dist/preact.js'
```
to the alias section of your webpack config.
This will ensure that webpack uses the commonjs version of preact and therefore the exports won't be readonly.

**Comment by NekR** [comment]
> I'm not sure what could be a viable long term solution for this.

The solution would be to not use `require('preact')` in `preact/debug`.

**Comment by NekR** [comment]
The solution in original `preact/debug` was to use `require('../')` and override `preact.h`, when we changed to using `preact.options.vnode` it was possible to just use `require('preact')`.

I'm not sure, but there possible could be an issue with webpack if we are going to use `require('../')` or `require('preact/dist/preact.js')` -- it may include the code twice.

**Comment by NekR** [comment]
@whitetrefoil you don't have to guard `preact/debug` with `process.env.NODE_ENV` guard, it does so for you automatically. That's why it's better to use than `preact/devtools`.

**Comment by developit** [comment]
Might be worth just wrapping the render override in a try/catch. We can inject it in Webpack 2.

**Comment by NekR** [comment]
That's webpack 2+, not only wepback 2.

**Comment by NekR** [comment]
The thing what you did is not a fix.

**Comment by developit** [comment]
We can't really work around this though - the object returned from `require('preact')` is immutable in Webpack 2+.

**Comment by NekR** [comment]
I think there should be a way. I'll take a look into that later this week.

**Comment by paranoidjk** [comment]
came across same problem, i think we should at least add some notice in Readme.
