### ISSUE TITLE
Preact doesn't work with FuseBox HRM

### ISSUE THREAD

**Issue by pedronauck** [developit/preact#925]
This same issue was raised in [fuse-box](https://github.com/fuse-box/fuse-box/issues/901), but talking with @nchanged (the creator of FuseBox) I think that's a problem of preact instead.

When use FuseBox HRM with Preact in each update preact render multiple instances in the same dom node at every turn. I made a repo with the source code, if you just running `yarn start`, then make some modification on `src/index.tsx` you'll see the bug

https://github.com/pedronauck/fusebox-preact-example

This is what's happening:

<img width="376" alt="screen shot 2017-10-26 at 16 05 07" src="https://user-images.githubusercontent.com/2029172/32069293-7812679e-ba67-11e7-9980-cfa3b3ed83c4.png">

How I spoke in the fuse-box issue, I tried to do the same with React and Inferno and they worked perfectly, so I guess maybe this can be a preact render's issue

**Comment by lukeed** [comment]
You need to pass `render` a third argument so that it can reuse what's there, otherwise it will definitely add/append new instances every call.

**Comment by lukeed** [comment]
Please see [here](https://github.com/lukeed/preact-starter/blob/master/src/index.js#L6-9) for an example.

**Comment by pedronauck** [comment]
Sorry @lukeed, but I did the same of your example, and preact keep append new instances every call...

https://github.com/pedronauck/fusebox-preact-example/blob/master/src/main.tsx

**Comment by nchanged** [comment]
@pedronauck you could just remove the div for development
```
const element =  document.getElementById('root');
element.parentNode.removeChild(element);
```
You would need to flush contents and store the new into memory, then re-trigger. If you are going for a custom HMR plugin here is what you need to read http://fuse-box.org/page/development#custom-hmr

**Comment by lukeed** [comment]
Your `bootstrap` code is now correct. Unfortunately, I haven't use Fusebox yet (been meaning to), but what @nchanged posted looks like it's on the right track.
