### ISSUE TITLE
Provide ES2015 dist bundle

### ISSUE THREAD

**Issue by yaodingyd** [developit/preact#927]
There is a feature request in vue [#6937](https://github.com/vuejs/vue/issues/6937) and I think it applies to preact too. The original post explains the issue quite well. Considering the ES6 compatibility in modern browsers, it just makes sense to have an ES6 bundle.

**Comment by marvinhagemeister** [comment]
To add to that: Preact already has a bundle that uses es2015-style `export`. The code itself remains  in `es5` , though. Making a true `es2015` bundle for modern browsers would likely make preact even smaller. Only issue could be module bundlers which may skip applying babel on anything that resides in `node_modules`. This could be a breaking change for app developers.

**Comment by developit** [comment]
I'd be interested to see stats on the output size. Right now we're hand-optimized for gzipped ES5, it's possible the ES2015 source is larger.
