### ISSUE TITLE
Wrong component instance picked upon re-render under certain circumstances

### ISSUE THREAD

**Issue by tomascasas** [developit/preact#928]
I am just guessing, but I think that `preact` is picking the wrong component instance while trying to possibly re-use VDOM nodes based on the branch they are for the same index.
I created an example project with the issue in `preact` and tried and finally got the same think with `react` which does not show the behavior.
Basically, the App has a main `div` and 2 or 3 three `div` children based on a `message` being set or not, see:
https://github.com/roomkey/preact-link/blob/master/src/preact.js#L52-L65

When the `message` is set after clicking on `init test` button, you will see that the contents of the 1st rendered`Link` now holds the state of what was the 2nd `Link` before the click.
I think that happens because `message` is display on a new sibling pre-pended and so, former 2nd `div` holding the 2nd and 3rd `Link` gets the first of these 2 reused (2nd `Link`).
If I add a `key` to the 1st `Link`, it pulls the right component instance.
Please, let me know how I can further describe the issue or provide valuable input.

**Comment by tomascasas** [comment]
This is related to this comment issuecomment-326360501

**Comment by developit** [comment]
Hi @tomascasas - which version of Preact are you using?

**Comment by tomascasas** [comment]
@developit thanks for you reply. Here it goes:
```
"preact": "8.2.6"
```

**Comment by marvinhagemeister** [comment]
Looks like this issue was caused by the component recycler. We completely removed it for our next version and published an alpha released a few hours ago. This issue is very likely fixed 👍
