### ISSUE TITLE
Could not multi components was rendered to body of document?

### ISSUE THREAD

**Issue by linychuo** [developit/preact#929]
Hi, there

I'm rewriting my blog using preact, and I found returning multi components to document, console occurs error: 
nents/app.js: Adjacent JSX elements must be wrapped in an enclosing tag
My code is below:

`export default class App extends Component {
	render() {
		return (
			<Header/>
			<Content/>
		);
	}
}`
Before all components was rendered, it must be wrapped <div> or other elements?

**Comment by vaishalshah** [comment]
I don't know much about Preact but from my React knowledge, you can't return multiple components from render method. You have to enclose them in `<div>` or any other tag and return them in render.
Note: In React 16, a new feature was added where you can return an array of elements without enclosing them in the single tag but I am not sure whether that feature exists in Preact or not.

**Comment by linychuo** [comment]
Thanks @vaishalshah, I have found the new features of React, Hope preact also add the feature in the newest version.

**Comment by developit** [comment]
It's on the ToDo list, but extremely difficult given Preact's current design.

**Comment by gaearon** [comment]
>Note: In React 16, a new feature was added where you can return an array of elements without enclosing them in the single tag but I am not sure whether that feature exists in Preact or not.

I'd mention that [React 16.2 adds a special `React.Fragment` export](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) with slightly different semantics from vanilla arrays. React fragments [can be keyed](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#keyed-fragments) which is handy for returning "tuples" from `map`.

The plan is to have JSX compile `<>` to `<React.Fragment>`, but there's a Babel pragma you can change (e.g. Preact could provide `Preact.Fragment` instead).

**Comment by marvinhagemeister** [comment]
@developit I had a go at this yesterday evening, but was blocked on getting the babel toolchain upgraded to `7.x` (jsx fragments are not supported in `6.x`).

```bash
[!] (babel plugin) TypeError: Cannot read property 'spec' of undefined (While processing preset: "preact/node_modules/@babel/preset-env/lib/index.js"
```

**Comment by marvinhagemeister** [comment]
Closing, because progress of `Fragments` is tracked in #946
