### ISSUE TITLE
Preact + WebSocket

### ISSUE THREAD

**Issue by mcmega** [developit/preact#930]
Hi guys!
How to make a bunch Preack + WebSocket.
Please share an example.

**Comment by mehmetkose** [comment]
just connect-it in the **componentDidMount** & set the states and manage the flow.
read the source code of this project; https://github.com/mehmetkose/react-websocket
you'll get some ideas.

**Comment by mcmega** [comment]
I just started working with the Web, I have basic knowledge.
It does not work for me to integrate the websocket into the project on Preact.
Help, how to solve the problem? Show an example code for Preact.

**Comment by mehmetkose** [comment]
If you know how to use websocket with basic js+html, you can do it same in preact&s  **componentDidMount** method. 

if you don't know web basics,  websockets and preactjs.. well, this not a good path for your case. Learn the basics first. This is not issue and not related question with the Preactjs. 

RTFM.

**Comment by mcmega** [comment]
I understand html + js.
My html code:
```
<script>
    // Create WebSocket
    const connection = new WebSocket('ws://'+location.hostname+'/ws', ['soi-tech']);
    // Successful connection event
    connection.onopen = () => { console.log('Connect OK'); };
    // Error handler
    connection.onerror = e => { console.error(e); };
    // Handler of received messages
    connection.onmessage = r => {
        // Parser of received messages
    };
    // Sending data to WebSocket
    function sendWS(data) {
        connection.send(data);
    }
</script>
```
I can not do this in the application. Handlers should work globally, but only work in componentDidMount.

**Comment by developit** [comment]
These types of questions are much better suited to StackOverflow - the preact issue tracker is for Preact bugs.
