### ISSUE TITLE
Render position

### ISSUE THREAD

**Issue by z-vr** [developit/preact#934]
I don't think it is possible to render a Component with a specific position, e.g., insert first rather than append? Would there be any consequences if I did something like:

```js
const node = render(<Component />, element);
element.insertBefore(element.firstElementChild, node);
```
?

**Comment by developit** [comment]
Hiya @z-vr - that would work fine, or you can insert a marker node and have Preact replace it:

```js
let marker = document.createElement('span');
element.insertBefore(element.firstElementChild, marker);

render(<Component />, element, marker);
```
