### ISSUE TITLE
render gives errors when TypeScript strictNullChecks = true

### ISSUE THREAD

**Issue by nickytonline** [developit/preact#936]
Preact TypeScript types work fine when `strictNullChecks` is set to false in tsconfig.json but when it is set to true, it errors out.

e.g.

```
import { render, h } from 'preact';
import TodoList from './components/todo-list';

const root = document.getElementById('root');

render(<TodoList />, *root*);
```

results in `root` not being compatible with the `render`'s `parent` parameter.

```
TS2345: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Document | Element'.
  Type 'null' is not assignable to type 'Document | Element'.
```

The reason being is because with `strictNullChecks` set to true, `root`'s union type becomes `HTMLElement|null` vs. just `HTMLElement` when `strictNullChecks` is set to false.

You could use the non-null operator, e.g. `const root = document.getElementById('root')!;`, but this is generally frowned upon. I looked at the `react-dom` types, and they have `null` in the union type, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dom/v15/index.d.ts#L28

**Comment by maltoze** [comment]
Why was `null` removed?
https://github.com/preactjs/preact/blob/4e29ec70332c8c1c7cfb002d4069f2c9db2831f2/src/index.d.ts#L225-L229

This error appears again.
`Type 'null' is not assignable to type 'Element | Document | ShadowRoot | DocumentFragment'.ts(2345)`

**Comment by andrewiggins** [comment]
Here, this is TypeScript informing you of a possible runtime exception in your code involving `null` (what `strictNullChecks` aims to do). Looking at the code sample again:

```js
import { render, h } from 'preact';
import TodoList from './components/todo-list';

const root = document.getElementById('root');

render(<TodoList />, root);
```

If browser can't find any element with the ID `root`, than `getElementById()` will return `null`. However, Preact requires a DOM element to render. We removed `null` from the allowed types in `render()` cause passing `null` will cause Preact to throw an exception (i.e. `render(<TodoList />, null)`). So TypeScript is letting you know "Hmmm... `getElementById()` may return `null`, but `render()` requires a non-null values. You should handle the null case explicitly`. 

You can fix this error in a couple different ways:

1. Handle the fatal error:
   ```js
   const root = document.getElementById('root');
   if (root == null) {
      // Handle fatal errors in your app.
      throw new Error("Could not find root element");
   }

   render(<TodoList />, root);
   ```

2. Ignore the error case
   ```js
   const root = document.getElementById('root');
   if (root != null) {
      render(<TodoList />, root);
   }
   ```

3. Tell TypeScript to trust you, the element will always be there and will return non-null values
   ```js
   // Note the ! at the end of the next line
   const root = document.getElementById('root')!;
   render(<TodoList />, root);
   ```
