### ISSUE TITLE
Lifecycle methods with preact.render

### ISSUE THREAD

**Issue by kohver** [developit/preact#938]
Is it ok that when I replace a component by `preact.render()` lifecycle methods like `componentWillUnmount` are not fired?

Let's say we have a component:
```jsx
class A extends Component {
  componentDidMount() {
    console.log('mount');
  }
  componentWillUnmount() {
    console.log('unmount');
  }
  render() {
    return <div>Hello</div>;
  }
}
```

### In React:
```jsx
ReactDOM.render(<A />, document.body.firstChild) // 'mount'
ReactDOM.render(<div />, document.body.firstChild) // 'unmount'
ReactDOM.render(<A />, document.body.firstChild) // 'mount'
```
👉 [repl](https://jsfiddle.net/69z2wepo/92090/)

### In Preact:
```jsx
render(<A />, document.body, document.body.firstChild) // 'mount'
render(<div />, document.body, document.body.firstChild) // no calls
render(<A />, document.body, document.body.firstChild) //  :-(
```
👉 [repl](https://preactjs.com/repl?code=import%20%7B%20h%2C%20render%2C%20Component%20%7D%20from%20%27preact%27%3B%0A%0Aclass%20A%20extends%20Component%20%7B%0A%20%20componentDidMount()%20%7B%0A%20%20%20%20console.log(%27mount%27)%3B%0A%20%20%7D%0A%20%20componentWillUnmount()%20%7B%0A%20%20%20%20console.log(%27unmount%27)%3B%0A%20%20%7D%0A%20%20render()%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3Cdiv%3EHello%3C%2Fdiv%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D%0A%0Arender(%3CA%20%2F%3E%2C%20document.body%2C%20document.body.firstChild)%3B%0Arender(%3Cdiv%20%2F%3E%2C%20document.body%2C%20document.body.firstChild)%3B%0Arender(%3CA%20%2F%3E%2C%20document.body%2C%20document.body.firstChild)%3B%0A)

Even if I will put `setTimeout` after each `render` there will be no calls.

---
In real world I want to `render` a component in tests and of course I expect that the methods will be fired each test.

And actually it's working if I clear dom in `afterEach()` (I use Jest). But if a component throws an expected error in constructor, the lifecycle `componentDidMount` will not be called in the next tests:
```jsx
import { Component, render, h } from 'preact';

class Select extends Component {
  constructor(props) {
    super(props);

    if (!props.items.length) {
      throw new Error(`props.items should be passed.`);
    }
  }

  componentDidMount() {
    console.log('mount');
  }

  render() {
    return <div />;
  }
}

beforeEach(() => {
  document.body.innerHTML = '<div></div>';
});

test(`should throw an error with empty array of items`, () => {
  expect(() => {
    render(
      <Select items={[]} />,
      document.body,
      document.body.firstChild,
    );
  }).toThrow();
});

test(`next test`, () => {
  render(
    <Select items={[{ label: 'xxx' }]} />,
    document.body,
    document.body.firstChild,
  ); // componentDidMount will not be called.
});
```

May be these two cases are caused by single reason.

**Comment by developit** [comment]
I think this is the same as another open bug.  Here's the [repro as a fiddle](https://jsfiddle.net/developit/ea80vdcu/).

**Comment by marvinhagemeister** [comment]
Closing because of duplicate. It's easier to track for us when we have one issue only :)
