### ISSUE TITLE
Question, any plans to allow return an array of elements on render?

### ISSUE THREAD

**Issue by k1r0s** [developit/preact#939]
React 16 seems to allow this https://reactjs.org/docs/react-component.html#fragments

having this:

```javascript
export const Loop = (props) => props.over.map(props.each);
```

```jsx
  <div>
    <h1>Hallo</h1>
    <Loop over={[2, 3, 5]} each={ item => <span>{item}</span>}/> // received

    {Loop({ over: [2, 3, 5], each: item => <span>{item}</span> })} // desired
  </div>
```

I'm facing this:
![image](https://user-images.githubusercontent.com/6052309/33034319-bfa072a8-ce27-11e7-96b4-587f0e9d119d.png)

Thanks!

**Comment by leeoniya** [comment]
https://github.com/developit/preact/issues/929#issuecomment-345283184

**Comment by developit** [comment]
It's on the To-Do list, but very difficult within the restrictions of Preact's current diff algorithm.

**Comment by k1r0s** [comment]
sry duplicate, thanks!
