### ISSUE TITLE
componentDidMount not called when using component from cache

### ISSUE THREAD

**Issue by kruczy** [developit/preact#94]
`componentDidMount` is called every second time when using a component from cache

click the toggle button in the example, the date picker will show every second time:
http://www.webpackbin.com/E1j567bal

**Comment by developit** [comment]
Fix released in [4.4](https://github.com/developit/preact/releases/tag/4.4.0).

**Comment by kruczy** [comment]
for reference: http://www.webpackbin.com/NyDjb-Bpx shows its fixed in the example
