### ISSUE TITLE
BUG with input[type="range"]

### ISSUE THREAD

**Issue by hufan-akari** [developit/preact#940]
Hi, I found a difference between React and preact.

I get the render result by React,

```html
<input type="range" step="any" min="0" max="10" value="8">
```
and this by preact.
```html
<input min="0" max="10" step="any" type="range">
```

there is no value attribute in preact render result.
I noticed the discussion in  #850 .

It works well in all browsers except EDGE 16.

![upload](https://user-images.githubusercontent.com/7829098/33115115-c53d6dbe-cf9a-11e7-9533-c73136b16948.png)

There is an initial value above the slider.
I don't know how to remove it.

The following content is example code. 
Replace /React(DOM)?/ with "preact", you will get the preact render result.
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Demo</title>
    <script crossorigin src="https://unpkg.com/preact@8.2.6/dist/preact.js"></script>
    <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/javascript">
    class App extends React.Component {
      constructor(props) {
        super(props);
        this.state = { value: this.props.value };
        this.handleChange = this.handleChange.bind(this);
      }

      handleChange(event) {
        this.setState({ value: event.target.value });
      }

      render() {
        return React.createElement(
          "input",
          {
            min: 0,
            max: 10,
            step: "any",
            value: this.state.value,
            type: "range",
            onInput: this.handleChange,
            onChange: this.handleChange
          },
          null
        );
      }
    }

    ReactDOM.render(
      React.createElement(App, { value: 8 }, null),
      document.getElementById("root")
    );
    </script>
  </body>
</html>
```

**Comment by developit** [comment]
Update: jsfiddle demo for the above - https://jsfiddle.net/m55r49jo/1/

You won't always see attributes when rendering with Preact - for something like `value`, preact sets the property, which may not be reflected in the DOM tree viewer of DevTools.

I haven't had time to test in Edge yet, will update here when I can.

**Comment by hufan-akari** [comment]
I use the `preact-render-to-string` to pre-render my page.
It render the value attribute which is expected.

Now, when I open the page, it changes from the right render result to the wrong result in EDGE 16.

**Comment by developit** [comment]
@hufan-akari put the `value` prop after the `type` prop. `type` should always go first:

```js
        return React.createElement(
          "input",
          {
            type: "range",
            min: 0,
            max: 10,
            step: "any",
            value: this.state.value,
            onInput: this.handleChange,
            onChange: this.handleChange
          },
          null
        );
```

**Comment by hufan-akari** [comment]
Thanks a lot, you solved my problem.
