### ISSUE TITLE
Boolean attributes are treated inconsistently

### ISSUE THREAD

**Issue by call-a3** [developit/preact#945]
When setting attributes to boolean values, preact interprets falsey values as "they don't need to be set". This makes sense and is good behaviour.

However, I would similarly expect that preact would also interpret `true` as the opposite "it simply needs to be set". It does do this, but it renders the attribute with value `"true"`. I would expect that it would be rendered with value `""` (empty string), which fits better with HTML's default syntax for boolean attributes.

For an example of what I mean: https://codesandbox.io/s/llq38jyrzz

Related to #83

**Comment by marvinhagemeister** [comment]
I checked against Preact X in master and we're correctly setting `boolean` values 🎉

**Comment by RobinMalfait** [comment]
👌
