### ISSUE TITLE
Browser native date picker

### ISSUE THREAD

**Issue by sirodoht** [developit/preact#949]
Browsers, for some time now, have a native date picker option.

You can see a demo here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Unfortunately, using Preact makes them unusable. The native widget opens but when the user picks the date, it does not appear on the field. Can I make them usable somehow? I have examined the event object but it doesn't seem to contain the date, so as I can set it.

PS. Hmm, it seems the problem appears when the binding happens:
`this.handleChange = this.handleChange.bind(this);`

**Comment by developit** [comment]
It sounds like you're consistently clearing the value of the input any time it changes. You should be able to use `e.target.value`, which is a string.

**Comment by sirodoht** [comment]
It seems the problem was elsewhere. Thank you for the input!
