### ISSUE TITLE
Inconsistent `setState` behavior between React and Preact (breaking react-select)

### ISSUE THREAD

**Issue by philmander** [developit/preact#951]
I'm using [react-select](https://github.com/JedWatson/react-select/) with Preact (+ Preact-compat) and the arrow to open the drop down is not working. This is because of the [following code in React Select](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L282):

```js
handleMouseDownOnArrow (event) {
	// if the event was triggered by a mousedown and not the primary
	// button, or if the component is disabled, ignore it.
	if (this.props.disabled || (event.type === 'mousedown' && event.button !== 0)) {
		return;
	}
	// If the menu isn't open, let the event bubble to the main handleMouseDown
	if (!this.state.isOpen) {
		this.setState({
			isOpen: true,
		});
	}
	// prevent default event handlers
	event.stopPropagation();
	event.preventDefault();
	// close the menu
	if(this.state.isOpen){
		this.closeMenu();
	}
}
```

When trying to open the select and in React, the `this.setState({ isOpen: true})` call will change the state async, whereas in Preact this happens immediately. This means that, in React, the expression in the line `if(this.state.isOpen){` will be `false`, but in Preact it's `true`. So `state.isOpen` is flicked to `true` and then straight back to `false` before `render()` is called. Meaning that in Preact this code has no effect.

It looks like this can be fixed with a simple `if/else` (Unless there's some deliberate reason those `event.stop/prevent` calls are sandwiched in there). But I thought this was worth sharing since I can imagine `react-select` is commonly used with Preact. 

Is this subtle difference in behavior considered a Preact bug?

I guess it could also be fixed be proxying setState calls via  `setTimeout` in Preact-compat. Happy to create a PR here.

**Comment by philmander** [comment]
I tried a quick fix in Preact Compat and this caused all kinds of extra problems with other React components. I think my solution was too simple.

**Comment by developit** [comment]
Hmm - setState() is actually async in Preact, moreso than it is in React.  Perhaps this is actually the other way around?

You can control how `setState` async works without modifying any libraries btw:

```js
import { options } from 'preact';

// Turn off async setState entirely:
options.debounceRendering = f => f()

// Use setTimeout(0) for async:
options.debounceRendering = setTimeout

// Use rAF for async:
options.debounceRendering = requestAnimationFrame
```

**Comment by natevw** [comment]
Hmm, there's something a bit odd going on here then. I have a situation where in response to a click I set a state in a parent, which causes a child component to mount, and that component registers listeners for clicks on `document.body` to dismiss itself. (Something like a custom dropdown menu or a modal.)

What's happening, at least in Chrome 63.0.3239.84 is that the click that triggers the re-render is actually still received by the new component! That is, when I press the button to show my modal I see it blit up — but then it instantly dismisses itself from the same click (bubbled to `document.body`)!

I don't think the Promise-based defer actual defers enough relative to the event loop or something. I noticed that in the debug console

```
var defer = Promise.resolve().then.bind(Promise.resolve());
defer(_ => console.log("DEFERRED"));
console.log("IMMEDIATE");
"DONE";
```

logs:

> IMMEDIATE
> DEFERRED
> "DONE"

Whereas

```
var defer = setTimeout
defer(_ => console.log("DEFERRED"));
console.log("IMMEDIATE");
"DONE";
```
displays

> IMMEDIATE
> "DONE"
> DEFERRED

And indeed, setting `preact.options.debounceRendering = setTimeout` prevents my modal from dismissing itself until the NEXT click as intended.

**Comment by developit** [comment]
Makes sense - the state change that triggers removal of the child is deferred until after the event has bubbled.

**Comment by natevw** [comment]
@developit Is it intentional that the default debounce will fire before an event has finished bubbling?

**Comment by developit** [comment]
Apparently yes! Here's a demo: https://jsfiddle.net/dpa91vbq/4/

I might lump this in with the list of reasons to switch from debounced setState to stack-based.

**Comment by natevw** [comment]
@developit I'm not sure what you mean by stack-based setState, is there a thread on that somewhere I could try catch up with?

My main concern is how I should be avoiding this in my app.

* `preact.options.debounceRendering = setTimeout` works, but sounds like that might go away?
* on #838 the suggestion is to call `stopPropagation` to stop the incoming child from seeing the event. I don't like this — it assumes the parent is the only other (current) observer which may not be the case.
* I could wrap my response to the event in `setTimeout`, basically a manual version of the debounce workaround — is this what I'd need to do if setState gets rid of the debounce option?

**Comment by philmander** [comment]
I was just talking about "copying properties from `state` to `this.state`" in [`component#setState`](https://github.com/developit/preact/blob/master/src/component.js#L56). Not re-rendering after a state change. Sorry if I'm being dumb but this looks synchronous to me, where it's not in React.

**Comment by natevw** [comment]
@philmander Sorry to hijack. Perhaps #838, or even a separate issue, would have been a better thread for how this is affecting my own code. I'm going to leave things be for now, and maybe @developit can suggest how he'd like my own maybe-separate issue organized relative to this (#951) and/or #838?

**Comment by developit** [comment]
Personally I'd opt for wrapping the problematic `setState()` call in a `setTimeout()`. 

Re: stack based - I've been investigating some major under-the-hood changes in Preact, which might include switching from debounced setState _(using time)_ to halted setState _(queuing up state changes until after the current render/event pass)_.

**Comment by philmander** [comment]
Just revisiting this issue. I created a couple of demos to illustrate the difference in case its not clear:

Preact: http://jsbin.com/taroyax/edit?html,js,console,output
React: http://jsbin.com/vozuguj/edit?html,js,console,output

**Comment by marvinhagemeister** [comment]
@philmander Thanks for the jsbin links! I just checked with the official react docs and they [actively discourage](https://reactjs.org/docs/react-component.html#setstate) relying on reading `this.state` right after a `setState` call. Instead they recommend using a callback function. For preact we encourage the same patterns, meaning it is always unsafe to rely on `this.state` immediately after `setState`.

The code currently found in master for `react-select` seems to have fixed this particular issue 🎉
