### ISSUE TITLE
No way to clean up resources from component recycler?

### ISSUE THREAD

**Issue by MaxPower15** [developit/preact#957]
The component recycler is a great idea for performance. However, its current implementation creates a situation where it is not possible--as far as I can tell--to ever clean up resources that are reclaimed but never reused.

Take a look at this jsfiddle to see what I mean:

https://jsfiddle.net/n5ngymr7/8/

If you open Google Chrome's Memory tab and snoop around, you'll see that CustomComponent and its orphaned HTML DOM nodes are hanging around in memory after I've caused them to unmount.

<img width="835" alt="screenshot 2017-12-17 13 21 15" src="https://user-images.githubusercontent.com/493992/34082682-bb8159f8-e330-11e7-99ef-e18b34763915.png">

<img width="836" alt="screenshot 2017-12-17 13 21 39" src="https://user-images.githubusercontent.com/493992/34082684-be9d2e32-e330-11e7-89a8-36d86af48578.png">

I think this is by design, the idea being that those components may eventually get reused, and at that point, it'll render faster. However, this approach is not desirable in the situation where those components are never (or infrequently) reused. Think of a single page app that moves to a rare view that uses 10,000 instances of a heavy custom component. The user navigates away from that page, and that memory is never reclaimed, making it effectively a memory leak. Any other javascript outside of preact that requires lots of memory will just have less to work with.

The situation is made worse by passing closures into props. Because the closure must hold onto references--and the reference to props is maintained by the component recycler--those references also hang around forever.

<img width="836" alt="screenshot 2017-12-17 13 35 04" src="https://user-images.githubusercontent.com/493992/34082702-0dbb3798-e331-11e7-9fc8-daf7696357fd.png">

In my specific case, I'm working with video embeds. When a customer calls `video.remove()`, they expect it to clean up after itself. We cannot accomplish that right now because of these recycled references in preact.

I was thinking that the right solution to this might be to create a legitimate top-level `destroy(parent, merge)` function. Functionally, it would perform a render() like in my jsfiddle, but also pass another argument that tells it not to collect components. I'd be interested in submitting a PR for that if you think it's the right approach. If not, I'm interested in hearing what else could work! Or if I'm totally wrong, that would be good to know, too. 😄 

Thanks for listening.

**Comment by developit** [comment]
You can effectively disable recycling like so:

```js
class MyHeavyComponent extends Component {
  destroy = () => {
    this.nextBase = null;
  };
  componentWillUnmount() {
    setTimeout(this.destroy);
  }
}
```

If you want to turn off recycling for all components, perhaps something like this:

```js
Object.defineProperty(Component.prototype, 'nextBase', {
  get() { return this._nb && this._nb.get('base'); },
  set(base) {
    if (!this._nb) this._nb = new WeakMap();
    this._nb.set('base', base);
  }
});
```

As for changes to Preact itself, recycling needs to be removed entirely.  We did this for elements earlier in the year and changed the diff to account for it, we just need to do the same for components.  I'm working on something to this effect right now and will be publishing my findings shortly.

**Comment by MaxPower15** [comment]
Thanks for the reply! Glad I asked first. I'll try out your first suggestion and look for those updates.

**Comment by MaxPower15** [comment]
Minor update here. I tested the provided suggestions but wasn't able to see any difference in GC in the Memory tab.

First suggestion: https://jsfiddle.net/n5ngymr7/10/
Second suggestion: https://jsfiddle.net/n5ngymr7/11/

If I set that up incorrectly, let me know.

**Comment by Scarysize** [comment]
Sorry to chime in: How would the `nextBase.null` "hack" work for stateless components? They don't provide a hook for when they are unmounted.

**Comment by developit** [comment]
Ah but they do @Scarysize! You can use a ref or use the backing instance for a functional component - they're really just full components under-the-hood:

```js
function Foo(props) {
  let root;
  let ref = node => {
    if (root && !node) {
      // we had a root, but now it's going away: that's an unmount!
      this.nextBase = null;
    }
    root = node;
  };
  return <div ref={ref} />
}
```

Option 2 is to use lifecycle methods on a pure functional component, which has been supported since Preact 8 and we plan to support indefinitely:

```js
function preventCaching() {
  setTimeout( () => {
    this.nextBase = null;
  })
}
function Foo(props) {
  // `this` in a PFC is actually a real component. It even has setState().
  this.componentWillUnmount = preventCaching;
  return <div />
}
```

**Comment by Scarysize** [comment]
> Just a note: the future of Preact doesn't include component recycling/caching, so this nuisance will be going away very shortly!

That sounds great! Thanks for the quick response :)

**Comment by marvinhagemeister** [comment]
We just merged the code for our next version of Preact into `master`. The recycler is no more :tada:
