### ISSUE TITLE
IE 11 sometimes re-renders unexpectedly

### ISSUE THREAD

**Issue by mrMetalWood** [developit/preact#960]
Preact version: 8.2.7

I have a component that returns `null` from `render` and `shouldComponentUpdate` always returns `false`.  All component logic is handled by `componentWillReceiveProps`. Whether or not this is best practice is another story.

I'm now seeing some weird behaviour on IE 11 on Windows 7 as well as Windows 10.
I would expect that the components render function is only called once in the very beginning since `shouldComponentUpdate` is always false.

However, it seems IE 11 ignores it sometimes when new props come in for the first time and re-renders the component anyway. Sometimes not on the first time but second or third time when new props arrive. 

Because the `componentWillReceiveProps` method is not called on the initial render (or what IE 11 thinks is the initial render), this caused a nasty bug in my app when an important update for the component was "missed".

I created basic test case to demonstrate the issue:
https://codepen.io/mrMetalWood/pen/dJXLjq

Just click the button an watch the console. Here is the debug view: https://s.codepen.io/mrMetalWood/debug/dJXLjq/mVMbGEjaBndr

In modern browsers all is fine:
<img width="1646" alt="bildschirmfoto 2017-12-21 um 12 36 16" src="https://user-images.githubusercontent.com/2902795/34254954-b7c3b83a-e64e-11e7-8181-e811e4d1050e.png">

On IE 11 on Windows 7 it looks like this:
<img width="819" alt="bildschirmfoto 2017-12-21 um 12 34 16" src="https://user-images.githubusercontent.com/2902795/34254970-c91e624c-e64e-11e7-9598-ded3e0da3b31.png">

Same on IE 11 on Windows 10:
<img width="1421" alt="bildschirmfoto 2017-12-21 um 12 35 27" src="https://user-images.githubusercontent.com/2902795/34254987-d5826bfa-e64e-11e7-9051-f853bdcca0c8.png">

The (initial?) render method is called twice and thus causing the `componentWillReceiveProps` to be skipped because it thinks it is the initial render.

For know I worked around this by returning an empty `<div />` instead of `null` which now works as expected. But I still wanted to report the issues I had with this.

I don't know if this is even a preact bug or just the IE doing its weird thing it sometimes tends to do ;)

**Comment by mkxml** [comment]
I'm trying to figure this out.

This is what I have so far:

IE seems to have a flakey behavior when setting custom properties to text nodes, like preact does with `__preactattr_` and `_component`.

It is wiping custom properties like `_component` sometime after page load, thus confusing preact renderer.

The issue only affects pure text nodes, that's why empty divs and other elements work.

Looks like the wiping process is async, difficult to debug in IE.

Hope there is a way to prevent this.

**Comment by developit** [comment]
One thing I hadn't tried: using `Object.defineProperty(Text.prototype, '__preactattr_', ...etc)`

**Comment by mkxml** [comment]
@developit I tried that, it has the same behavior.

Also, on topic: Does preact 9 or later aim to remove some state (like `_component`) from the DOM? That would prevent this kind of issue from happening too.

**Comment by marvinhagemeister** [comment]
Good news: With Preact X we are not adding any new non-standard properties to the DOM anymore. The only exception is the topmost one which is treated as the root of a tree and containsa reference to the previous one via `_prevVNode` 👍
