### ISSUE TITLE
How to extract preact code from the bundle

### ISSUE THREAD

**Issue by 1rosehip** [developit/preact#964]
Hello,
I'm using preact in CMS and sometimes I need 2 different preact bundles on the same page. In this case I have preact code twice. How is it possible to remove preact and preact-compat code from the bundle and handle it separately?
Thank you very much!

**Comment by AbdulrahmanEng** [comment]
Try server-side rendering for one bundle and client-side rendering for the other. This repo might help: https://github.com/developit/preact-render-to-string

**Comment by 1rosehip** [comment]
Thanks, I'll try this.
