### ISSUE TITLE
[docs] Add description how to switch `h` JSX in TypeScript

### ISSUE THREAD

**Issue by alexeypetrushin** [developit/preact#966]
Currently it's not easy to find how to do it, it could be done by adding following option to `tsconfig.js`

```
{
  "compilerOptions": {
    ...
    "jsxFactory": "h"
    ...
  }
}
```

This docs needs to be updated https://preactjs.com/guide/switching-to-preact

**Comment by developit** [comment]
Might be better to recommend people use createElement since that's exported now.

**Comment by marvinhagemeister** [comment]
We have a section about TypeScript in our Readme now 🎉💯
