### ISSUE TITLE
React Portal

### ISSUE THREAD

**Issue by bsurai** [developit/preact#969]
Hi. 
Does Preact have a feature like React Portals (react 16)? 

It is described like :
> Portals provide a first-class way to render children into a DOM node that exists outside the DOM hierarchy of the parent component.

Perhaps Preact has some another possibility to render a children component into a DOM node that exists outside the DOM hierarchy of the parent component?

Here is reference to react portals doc.
https://reactjs.org/docs/portals.html

Thank you.

**Comment by hassanbazzi** [comment]
We've had this for a while: https://github.com/developit/preact-portal

Let me know if this does what you're looking for. :)

**Comment by bsurai** [comment]
@hassanbazzi Yep. Thank you :)

**Comment by hassanbazzi** [comment]
@bsurai Feel free to close the issue if you're good to go. If anything, we're here to help ;)
