### ISSUE TITLE
Class attribute not cleared when re-using elements from cache pool

### ISSUE THREAD

**Issue by steelbrain** [developit/preact#97]
I am hitting a very weird and difficult to reproduce bug. It would be nice to have a Slack, Gitter or IRC channel for preact where I can collaborate with the community to repro it.

The bug I'm hitting is with [`Message` Component of linter-ui-default](https://github.com/AtomLinter/linter-ui-default/blob/77e67f45ede96b097a0dc83f0203a6bc7a4a5122/lib/elements/message.js).
It should, according to the code produce messages like this, and it does

<img width="577" alt="screen shot 2016-03-16 at 7 22 46 pm" src="https://cloud.githubusercontent.com/assets/4278113/13834464/8b194474-ebac-11e5-8b94-f449d90916e8.png">

but after a few dozen `render` triggers, it becomes this

<img width="490" alt="screen shot 2016-03-16 at 7 22 34 pm" src="https://cloud.githubusercontent.com/assets/4278113/13834482/a7189256-ebac-11e5-8ea5-4d8bf03848ce.png">

Nothing on our component side changes, I believe the bug to be on preact's side

## Update
After an hour trying to repro, I found out that it's using the `span` elements from `linter-eslint` that it had recycled, and it's passing the same **without clearing their class attribute**

**Comment by developit** [comment]
Hi @steelbrain - there is a gitter room, gitter.im/developit/preact

I suspect this may be related to the manual Element insertion via appendChild - this ends up getting recollected by preact's recycled, but it does not have any props associated because it was not created by preact. I can look into supporting that though, otherwise preact really shouldn't be recollecting an Element it didn't create.

**Comment by steelbrain** [comment]
Please note that the examples demonstrated don't use `appendChild`, it's support exists but it isn't used

**Comment by developit** [comment]
Fix released in [4.4](https://github.com/developit/preact/releases/tag/4.4.0).

**Comment by steelbrain** [comment]
Beautiful, thanks again! :+1:

**Comment by StoneCypher** [comment]
@developit - gitter.im/developit/preact doesn't seem to exist.  is there a replacement?

**Comment by StoneCypher** [comment]
nevermind, found it

the new chat is at preact.slack.com

you must sign up from https://preact-slack.now.sh instead
