### ISSUE TITLE
SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by mehmetkose** [developit/preact#970]
Hi, 

Sometimes I'm getting this log with the blank page after page refresh
```sh
SyntaxError: expected expression, got '<'
```
Where I'm doing something wrong? Any idea?

![screen shot 2018-01-03 at 14 26 48](https://user-images.githubusercontent.com/706678/34518958-e54b08f0-f092-11e7-864f-ac1e35e0cb5e.png)

**Comment by mehmetkose** [comment]
I couldn't understand from the compressed js file.
However I have not seen this message in the last couple hours.

I've done 3 things;
added **defer** attribute to all js files. 
cleared **service worker pwa** caches from the browser. 
cleared all **browser** caches.

I keep on testing

**Comment by developit** [comment]
You're missing a JSX transformation (such as Babel's), resulting in the browser attempting to parse JSX (which is not supported).

**Comment by arockia-probytes** [comment]
I got same error in my React project. It fixed while I put my external jQuery files and CSS files to puplic folder and Images in src folder

**Comment by arockia-probytes** [comment]
> Hi,
> 
> Sometimes I'm getting this log with the blank page after page refresh
> 
> ```shell
> SyntaxError: expected expression, got '<'
> ```
> 
> Where I'm doing something wrong? Any idea?
> 
> ![screen shot 2018-01-03 at 14 26 48](https://user-images.githubusercontent.com/706678/34518958-e54b08f0-f092-11e7-864f-ac1e35e0cb5e.png)

**

> **I got same error in my React project. It fixed while I put my external jQuery files and CSS files to puplic folder and Images in src folder**

**
