### ISSUE TITLE
[question/bug?] this.base arbitrary being null in favor of this. "nextBase"

### ISSUE THREAD

**Issue by k1r0s** [developit/preact#976]
I need to setup a listener on scroll to translate table headers .. 

But sometimes I found that this.base is null while this.nextBase has the element reference. Why?

Thanks!

https://github.com/developit/preact/blob/14f54565616d4f7e8c8feca243ad5bca000381cc/src/preact.d.ts#L64

![image](https://user-images.githubusercontent.com/6052309/34820322-6d560078-f6c0-11e7-871b-3f1d22cd93e2.png)

**Comment by k1r0s** [comment]
related https://github.com/developit/preact/issues/239

**Comment by k1r0s** [comment]
Guess my problem is removeEventListener is still calling the event handler o_O

I just added a condition to avoid processing if this.base is null or so

```javascript
  setHeaderPosition() {
    if(!this.base) return;
    const translate = `translate(0, ${this.base.scrollTop}px)`;
    this.base.querySelector("thead").style.transform = translate;
  }
```

But this is still very weird xD

**Comment by k1r0s** [comment]
thanks @kurtextrem , as you can see on my first message I'm using arrow function as a callback wrapping the listener so `this` is completely bounded to the component instance.

**Comment by kurtextrem** [comment]
@k1r0s doesnt seem like it? You are using the arrow fn in the listener, not in the class. That also means the listener won't get removed (by that call), as `fn => this.fn()` !== `fn => this.fn()`, V8 creates a new Function each time and if they're not equal, it won't get removed.

**Comment by k1r0s** [comment]
agree. Those functions are just annonymous ones. Its pretty clear, Thanks!
