### ISSUE TITLE
Question: `on*` props callbacks

### ISSUE THREAD

**Issue by donifer** [developit/preact#980]
Is there a way to pass a prop called with the prefix `on` without it being registered as an event handler?

I might been doing it wrong all this time but I normally pass functions as props and call them `onSomethingHappened`.

**Comment by Kanaye** [comment]
On components and functional components props starting with `on` are passed as normal props. 
No need to change anything.
[Here](https://preactjs.com/repl?code=import%20%7B%20h%2C%20render%2C%20Component%20%7D%20from%20%27preact%27%3B%0A%0Aclass%20ExampleComponent%20extends%20Component%20%7B%0A%09render()%20%7B%0A%09%09return%20(%0A%09%09%09%3Cdiv%20onClick%3D%7Bthis.props.onSomething%7D%3E%0A%09%09%09%09ExampleComponent%3A%20onSomething%20is%20%7Btypeof%20this.props.onSomething%7D.%20%0A%09%09%20%20%3C%2Fdiv%3E%0A%09%09)%3B%0A%09%7D%0A%7D%0A%0Aconst%20FunctionalExample%20%3D%20(%7BonSomething%7D)%20%3D%3E%20(%0A%09%3Cdiv%20onClick%3D%7BonSomething%7D%3EFunctionalExample%3A%20onSomething%20is%20%7Btypeof%20onSomething%7D%3C%2Fdiv%3E%0A)%3B%0A%0Aconst%20onSomething%20%3D%20()%20%3D%3E%20%7B%0A%09window.alert(%27onSomething()%27)%3B%0A%7D%3B%0A%0Aconst%20App%20%3D%20()%20%3D%3E%20(%0A%09%3Cdiv%3E%0A%09%09%3CExampleComponent%20onSomething%3D%7BonSomething%7D%20%2F%3E%0A%09%09%3CFunctionalExample%20onSomething%3D%7BonSomething%7D%20%2F%3E%0A%09%3C%2Fdiv%3E%0A)%0A%0Arender(%20%3CApp%20%2F%3E%2C%20document.body)%3B) an example showing preacts behavior.

**Comment by donifer** [comment]
Thanks @Kanaye! That example was just what I needed.

I guess I don't understand this part of the code then https://github.com/developit/preact/blob/66d74c5d210ee72e41732e6aa5efb0e23d0c09ba/src/dom/index.js#L65 not sure when this is running.

**Comment by Kanaye** [comment]
`setAccessor` is called by `diffAttributes` https://github.com/developit/preact/blob/66d74c5d210ee72e41732e6aa5efb0e23d0c09ba/src/vdom/diff.js#L307 which is called by `idiff` https://github.com/developit/preact/blob/66d74c5d210ee72e41732e6aa5efb0e23d0c09ba/src/vdom/diff.js#L148. 
But in case of components `idiff` returns early https://github.com/developit/preact/blob/66d74c5d210ee72e41732e6aa5efb0e23d0c09ba/src/vdom/diff.js#L100 bevor any dom diffing code is executed. 
So setAccessor is only executed for vdom nodes that represent a real dom node and not for components.

**Comment by donifer** [comment]
❤️  It finally makes sense (to me)! Thank you so much @Kanaye
