### ISSUE TITLE
Reference to component is set in wrong order

### ISSUE THREAD

**Issue by rosenfeld** [developit/preact#981]
Hi, take a look at this example app: https://codesandbox.io/s/0x1xj6m60p

You'll notice that while both React, Inferno and NervJS set the reference to component in the right order while clicking on the "Second" button (null is logged before the new reference), both Dio.js and Preact seem to process them in the wrong order (new reference, then null).

When implementing a client-side routing while willing to keep a reference to the current app, it's very important that this order should work like React, Inferno and NervJS. Would you mind fixing this, please?

P.S.: I've created the same issue in Dio.js: https://github.com/thysultan/dio.js/issues/47

**Comment by marvinhagemeister** [comment]
This is fixed in Preact X. The alpha is already available on npm :tada:
