### ISSUE TITLE
error, redirectLocation, renderProps all are undefined

### ISSUE THREAD

**Issue by Arun1048576** [developit/preact#984]
I am using Preact along with React Router 3.2. I am getting all the parameters undefined in the callback function. Tried same thing with React and thing are working as desired. Please help.

```
function renderApp (req, res, next) {
  match({ 
    routes: routes, 
    location: req.url
  }, (error, redirectLocation, renderProps) => {

    console.log (error, redirectLocation, renderProps)

    if (renderProps) {
      const  content = renderToString(
        <Provider store={store}>
          <RouterContext {...renderProps}/>
        </Provider>
      )

      res.render('index', { content })
      res.end()
    }
  })
}
```

**Comment by developit** [comment]
Hmm - that part of your code doesn't seem to even have anything to do with Preact. Are you sure this is related?

**Comment by ztoben** [comment]
Surprisingly I have ran into the same issue when trying to upgrade an older project to preact that is still on react-router 3.2. I'm guessing the key will be upgrading that package first, but it's interesting that it doesn't seem to be fixed by preact/compat alone.
