### ISSUE TITLE
Can't listen error by custom error logger

### ISSUE THREAD

**Issue by cestrensem** [developit/preact#989]
Hello, Preact uses the enqueueRender function to render components asynchronously.
But there is no error handling, and there is no way to listen this type of error by custom error loggers, such as muscula or centry. You can see any error in developer console but can't see any updates in error logger

**Comment by Kanaye** [comment]
Hi @cestrensem.

You can override `preact.options.debounceRendering ` to achive custom error logging.

[Here](https://preactjs.com/repl?code=import%20%7B%20h%2C%20render%2C%20Component%20%7D%20from%20%27preact%27%3B%0A%0Aclass%20MayThrowComponent%20extends%20Component%20%7B%0A%09constructor()%20%7B%0A%09%09super()%3B%0A%09%20%20this.state%20%3D%20%7Berr%3A%20false%7D%3B%0A%09%09setTimeout(()%20%3D>%20%7B%20this.setState(%7Berr%3A%20true%7D)%20%7D%2C%201000)%3B%0A%09%7D%0A%20%20render%20()%20%7B%0A%09%20%20if%20(this.state.err)%20throw%20new%20Error(%27Some%20error!%27)%3B%0A%09%20%20return%20(<div>Rendered!<%2Fdiv>)%3B%0A%09%7D%0A%7D%0A%0Aconst%20customLogger%20%3D%20(error)%20%3D>%20%7B%0A%20%20alert(%60TODO%3A%20log%20%3A%20%24%7Berror.stack%7D%60)%3B%0A%7D%3B%0A%0Apreact.options.debounceRendering%20%3D%20(rerender)%20%3D>%20%7B%0A%09Promise.resolve().then(rerender).catch(customLogger)%3B%0A%7D%3B%0Arender(%20<MayThrowComponent%20%2F>%2C%20document.body)%3B) a short example of how this could be done. For the example I'm just `alert()`-ing the errors stack.

**Comment by cestrensem** [comment]
Thanks, @Kanaye !!!
