### ISSUE TITLE
placeholder prop reused incorrectly when rerendering text input with cloneElement wrapper - MS Edge only

### ISSUE THREAD

**Issue by billneff79** [developit/preact#993]
Discovered this while creating some form dialog boxes using `preact-portal`.  See reproduction here: https://jsfiddle.net/billneff79/bcphq0zr/

I believe this represents the minimum amount needed to reproduce the issue, which includes:
1. A text input with a placeholder attribute and no value
2. A component that wraps the input and uses `cloneElement` to render its child, the text input
3. render the wrapped text input with placeholder text "foo" -> render null in place of the wrapped element -> render the wrapped text input with placeholder text "bar"

Only occurs in Edge (tested using Microsoft Edge 40.15063.674.0)

*Expected Outcome*
text input with placeholder text of "bar"

*Actual Outcome in Edge*
text input with placeholder text of "foo"

![screenshot](https://i.gyazo.com/f6cc4d629bf7ad5377876926c86b686c.png)

*Other Notes*
I created a similar setup using React and did not encounter the same problem on Edge: https://jsfiddle.net/billneff79/6b2eu3wy/4/

The `cloneElement` with a wrapping parent seems important.  If there is no wrapping element, (e.g. if you just clone inline) the issue does not occur.

I have not seen this issue on any other browsers.

**Comment by billneff79** [comment]
In case anything happens to the fiddle link, the repro code looks like this:

```
const { h, Component, render, cloneElement } = preact;

/** @jsx h */


function Cloner() {
	return cloneElement(this.props.children[0]);
 }

//second render
const removeInput = () => 
	this.remote = render(
  <div>
    <button onClick={addBarInput}>click to add</button>
  </div>, document.getElementById('container'), this.remote);
  
//third render
const addBarInput = () => 
	this.remote = render(
  <div>
    <button onClick={removeInput}>click to remove</button>
    <Cloner>
      <input type="text" placeholder="bar" />
    </Cloner>
  </div>, document.getElementById('container'), this.remote);

//First render
this.remote = render(
	<div>
    <button onClick={removeInput}>click to remove</button>
    <Cloner>
      <input type="text" placeholder="foo"/>
    </Cloner>
  </div>, document.getElementById('container'));
```

**Comment by developit** [comment]
Quick Q: does adding `value=""` address the issue? (I'm about to check in Edge)

**Comment by billneff79** [comment]
No, adding an empty `value=""` attribute does not change the behavior.  Fun fact, adding a value on the second render has the side effect of showing the new value _and_ the old placeholder:

![value and placeholder](https://i.gyazo.com/51af58820f9e1e258cbf2b181aed259d.png)

**Comment by k1r0s** [comment]
You don't need cloneElement to reproduce this issue

**Comment by marvinhagemeister** [comment]
Good news: We completely removed the recycler from Preact. Bugs like this where the wrong components are reused are now a thing of the past 👍 An alpha is already available on npm and a final version should follow sometime soon 💯
