### ISSUE TITLE
TypeScript: `render`'s first arg needs to be nullable

### ISSUE THREAD

**Issue by dcporter** [developit/preact#996]
In order to remove an element, I need to be able to do `render(null, parentEl, elToRemove)`. In the [typings file](https://github.com/developit/preact/blob/master/src/preact.d.ts#L79), `render`’s first argument is typed `Element`, which is non-nullable, precluding passing in `null`. This is preventing me from removing elements from a TypeScript project. The [source](https://github.com/developit/preact/blob/master/src/vdom/diff.js#L69) suggests that this argument can be null, undefined, a boolean (?), a string or a number.

~~(I haven't gotten this far yet, but I assume that if `render` returns the rendered element, and I'm removing things, it an also return `null`, which means the function’s return type also needs to be nullable.)~~ (Sounds like no problem on the return type.)

**Comment by developit** [comment]
Rendering null will return an empty text node.

**Comment by dcporter** [comment]
Cool, probably no problem on the return type side then. I updated the issue to reflect.

**Comment by developit** [comment]
Want to PR the nullable arg bit?

**Comment by wuweiweiwu** [comment]
@developit Can I pick this up? :)
